### ISSUE TITLE
Isofox Integration with GRIDSS

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#104]
Could it take as input a GRIDSS somatic VCF file for the same patient to increase the specificity of fusion detection? A bit like internal consistency and PURPLE.

**Comment by p-priestley** [comment]
Hi Dario,

Thanks for the suggestion.     Isofox considers all locations with chimeric reads as potential fusions and  produce both a filtered and unfiltered fusion prediction file.   The filters are specified here:  (https://github.com/hartwigmedical/hmftools/tree/master/isofox#c-filtering).  

A downstream analysis could use both ISOFOX and GRIDSS / LINX output, but our comparison suggests quite high sensitivity already for both DNA and RNA predictions (~95% for pathogenic fusions).  We are not currently planning to make a combined tool as we do not have a specific use case or example we have seen where this would have made a differnece.      The fusion RNA caller Arriba offer such functionality  in a limited way where the read filters are lowered if a structural variant is found within a range of 100k bases  (https://arriba.readthedocs.io/en/latest/input-files/#structural-variant-calls-from-wgs).
