### ISSUE TITLE
Resources Website Displays Security Warning

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#105]
Also, I'm not sure if GRIPSS will have hg38 known fusion pairs BEDPE hosted there soon.

![image](https://user-images.githubusercontent.com/631218/88143410-82a14d00-cc3a-11ea-85b9-5b3678b093e4.png)

**Comment by p-priestley** [comment]
The resources page is back up.   Will get back to you on the known fusions bedpe.

**Comment by DarioS** [comment]
I notice that it became available for download a couple of days ago.
