### ISSUE TITLE
LINX Plotting Lines Underneath Derivative Chromosome Track Background Region

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#108]
I marked two places with a red asterisk. Because of the transparency of the bottom left one, you can seen that LINX appears to be drawing the line faintly underneath the pale blue track background rather than on top of it unlike the other similar lines to the left and right of it. The red asterisk at top-right of plot might be the same problem. Viewing the image at original size makes the bottom-left faint line visible. The blue line going diagonally across the centre white circle also appears pale grey. But the two curved blue lines retain their blue colour.

![TCGA-BA-5149-T cluster108 LINE sv3 003 annotated](https://user-images.githubusercontent.com/631218/89968603-8d7a5b00-dc97-11ea-8678-0e4c1d70b793.png)

**Comment by p-priestley** [comment]
We will take a look to see if we can fix the visualisation issue.    For the record, this looks like  a LINE insertion with inversion (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC311219/)   and 15 bases target site duplication.

**Comment by DarioS** [comment]
Has this "underplotting" problem been reproduced and might there be a resolution soon?

**Comment by p-priestley** [comment]
Hi Dario, I don't think we found a case of this ourselves.  I am closing, but feel free to comment again if it is still a problem and you have a current example you can share.
