### ISSUE TITLE
LINX support for reference genomes

### ISSUE THREAD

**Issue by alvinwt** [hartwigmedical/hmftools#109]
Hi, I am wondering if there is a way around the annotation for the gene disruption and fusion events to suit other reference genomes. Specifically, I am using hs37d5 with additional scaffolds and chr added to each chromosome. The gridss-linx framework works well except for the two features of gene disruptions and fusions. I edited the reference and dbs files but it seems like gene disruptions and features rely on additional annotations within LINX. 

 Thanks for the great piece of software!

**Comment by p-priestley** [comment]
Hi Alvin,   I think we have users already who are use that ref genome.    What is the error that you see exactly?

**Comment by alvinwt** [comment]
Hi @p-priestley, there's no error but no output in the fusion and disruption files.

**Comment by charlesshale** [comment]
Hi Alvin,

Are you running with fusion-calling enabled? To do this ensure that:
- 'check_fusions' is enabled
- the Ensembl data cache is included (ie gene_transcripts_dir=/path_to_ensembl_files/
- typically pass in the HMF known-pair and promiscuous gene files

thanks,

Charles

**Comment by p-priestley** [comment]
Closing due to lack of response

**Comment by TnakaNY** [comment]
I am also using hs37d5 reference for my WGS data (human cancer sample, not interested in virus.).
I am thinking of using GRIDSS-PURPLE-LINX pipeline for my SV analysis.

Did anybody remake reference dbs files like here:
dbs/ensembl_data_cache/ensembl_gene_data.csv
dbs/gc/GC_profile.1000bp.cnp
dbs/germline_het_pon_hg19/GermlineHetPon.hg19.bed
dbs/germline_het_pon_hg19/GermlineHetPon.hg19.vcf.gz
dbs/sv/fragile_sites_hmf.csv
dbs/sv/line_elements.csv
