### ISSUE TITLE
PURPLE support for hg38 assembly

### ISSUE THREAD

**Issue by pdiakumis** [hartwigmedical/hmftools#11]
Hi,

Would there be any issues with using PURPLE with hg38-aligned BAM files? I assume that the `CytoScanHD_hg19_SNPs_sorted.bed` would need to be lifted over for the amber/sambamba pileup step (paired with the hg38 fasta), whereas I'm not too sure about the `GC_profile.1000bp.cnp` file. I'm also guessing the circos chromosome coordinates would need a bit of tweaking, although I could probably handle the plotting separately.

Many thanks - Peter

**Comment by jonbaber** [comment]
Hi Peter, 

I spent some time this morning going through the code and unfortunately there are a couple of built in assumptions that may not play nicely with hg38. We do intend to support the hg38 assembly down the track but I would't recommend trying to use it until we have tested it properly.

Regards, Jonathan

**Comment by ohofmann** [comment]
Thanks Jonathan, appreciate the feedback. Let us know if we can help with any testing; we were about to roll Purple into bcbio but might hold off until you feel it's ready.

**Comment by chapmanb** [comment]
Jonathan;
I've started working on integrating PURPLE and COBALT into bcbio and wanted to follow up on this discussion. Having support for hg38 and also hg19 chr style chromosomes for build 37 would really help with making it widely available. I'm excited about the recent work on generalizing this (https://github.com/hartwigmedical/hmftools/commit/4aace9c9d05801407a83c733cc447c57429b40dd) and would like to coordinate with you. As a starting point, I put together a hg38 GC_profile using gccount which I believe is equivalent to the one you distribute for build 37 now:

https://s3.amazonaws.com/biodata/coverage/GC_profile.hg38.1000bp.cnp.gz

Please let me know how else we can test/work with hg38 and help move this forward. Thanks again for all your great work on these tools.

**Comment by jonbaber** [comment]
Thanks very much Brad. 

Work is solidly underway so it shouldn't be too long before its ready, hopefully within the week barring any unexpected issues. I'll let you know as soon as it is ready and AMBER, COBALT and PURPLE are released. 

Cheers, Jon

**Comment by chapmanb** [comment]
Jonathan;
Wow, brilliant. I appreciate all the work and will be standing by to test out when it's all ready. Please feel free to use the hg38 GC_profile if it's useful and you don't already have one in place. Thank you again.

**Comment by jonbaber** [comment]
Hi Brad,

Thanks for the GC profile, was just what we needed.

The apps should all be ready to go now, but do please note that we not
using this in production so there might be some corner cases I have missed.
If so, I am more than happy to work with you to resolve them.

Cheers, Jon

Amber 1.7:
https://github.com/hartwigmedical/hmftools/releases/tag/amber-v1-7
Cobalt 1.5:
https://github.com/hartwigmedical/hmftools/releases/tag/cobalt-v1-5
Purple 2.16:
https://github.com/hartwigmedical/hmftools/releases/tag/purple-v2-16
BPI: https://github.com/hartwigmedical/hmftools/releases/tag/bpi-v1-7

**Comment by chapmanb** [comment]
Jon;
Thanks so much for this work. bcbio now has initial PURPLE integration with COBALT and PURPLE, using pre-called variants from the pipeline in place of AMBER. I've run this through on several samples with hg38 and am getting results, so appreciate you making it so smooth. This has all been TCGA exome samples so far and I understand PURPLE is primarily targeted for WGS, so I'll work on testing on some WGS samples where we have better expectations for getting good outputs. I appreciate all the help making this happen and looking forward to having this tuned and ready to go in bcbio.

**Comment by jonbaber** [comment]
Great to hear, that's very exciting! Although I have never tried to run
PURPLE on exome samples before so have no idea what kind of results you
will be getting :)

Unfortunately I missed one part of the HG38 support. Our gene copy number
output is still using hg19 gene definitions. Standard copy number output is
fine but obviously the gene copy number output will be incorrect. I will
try to correct this in the next few days.

Finally, in case you do decide to try AMBER at some point in the future, I
have uploaded to our pipeline resources file share (
https://resources.hartwigmedicalfoundation.nl/) a GermlineHetPon bed file
that we intend to start using to generate our baf points. Currently we are
using a bed file that generates around 180k points. The new one generate
more in the order of 400-500k data points.

Jon

**Comment by ohofmann** [comment]
The exomes we tried didn't quite work, but we'll be running both versions in parallel for all WGS tumor/normal pairs going forward to capture metrics ;)

--
@fiamh
Skype: ohofmann
+61 466 366 501

**Comment by chapmanb** [comment]
Jon;
Thanks again for this. I gave PURPLE a try on TCGA exomes with CNVkit, PureCN and TitanCNA as comparison points. It seems to prefer zero copy solutions in the final copy calls:

https://github.com/bcbio/bcbio_validations/tree/master/TCGA-heterogeneity

It does recover some of the same amplications as the other approaches, but prefers to center the calls around 0 copy number so we won't see the sample LOH/deletion regions. I'm guessing this is due to the lack of coverage in non-exome regions.

As Oliver mentioned, we're working on WGS comparisons where you actually actively support PURPLE application, but I wanted to share what we're seeing with exomes in case you start to work on those cases as well. Thanks again for all this work and support.

**Comment by pdiakumis** [comment]
Hi Jonathan,

Sorry for digging up this old discussion. We were just looking through these old issues and were wondering what you meant with the below:

> Unfortunately I missed one part of the HG38 support. Our gene copy number output is still using hg19 gene definitions. Standard copy number output is fine but obviously the gene copy number output will be incorrect. I will try to correct this in the next few days.

Was this corrected? Just trying to make sure we're not missing out on anything with hg38 support.

Cheers - Peter

**Comment by jonbaber** [comment]
Hi Peter, 

No problem. That issue was fixed in 2.17. 

Cheers, Jon

**Comment by jonbaber** [comment]
Hi All, 

We have recently discovered an issue with our COBALT/PURPLE GCProfile in HG38. It was originally generated with an alt enabled ref genome which set the mappability of some regions to zero, including the full HLA region and the region surrounding ERBB2. We have regenerated the file using a "no alt analysis set" version of the hg38 assembly without alt configs. This file is available to download from [HMF-Pipeline-Resources](https://resources.hartwigmedicalfoundation.nl). 

Please let me know if you have any questions regarding this change.

Regards, Jon
