### ISSUE TITLE
SAGE 2 command line arguments

### ISSUE THREAD

**Issue by vladsaveliev** [hartwigmedical/hmftools#112]
Hey,

I'm trying out the new SAGE 2 jar (downloaded from wget https://github.com/hartwigmedical/hmftools/releases/download/sage-v2.2/sage-2.2.jar), and the command line options seems to mismatch the new documentation. There are no options `-threads`, `-assembly` and `-high_confidence_bed`; `-hotspots` is called `-known_hotspots` and `-panel_bed` is called `-coding_regions`. Is this jar still the old SAGE and I probably need a newer one?

Vlad

**Comment by vladsaveliev** [comment]
Figured it out :) I was trying the conda SAGE, which defaulted to`SageHotspotApplication`. The jar defaults to `SageHotspotApplication` as well, unless the class path to `com.hartwig.hmftools.sage.SageApplication` is specified explicitly. All good now!

**Comment by jonbaber** [comment]
Thanks for the heads up. I will change  the default application to
SageApplication.
