### ISSUE TITLE
Bioconda hmftools-cobalt recipe missing copynumber dependency

### ISSUE THREAD

**Issue by lkhilton** [hartwigmedical/hmftools#113]
I'm running the hmftools-cobalt v1.8 Bioconda recipe. Cobalt consistently errors out: 

```
11:02:20 - Executing R script via command: Rscript /tmp/script2775884026055629006.R results/gambl/hmftools-1.0/03-cobalt/genome--grch37/05-25788T--05-25788N--matched/05-25788T.cobalt.ratio.tsv tumorGCRatio results/gambl/hmftools-1.0/03-cobalt/genome--grch37/05-25788T--05-25788N--matched/05-25788T.cobalt.ratio.pcf
11:02:20 - Executing R script via command: Rscript /tmp/script5739863832526138460.R results/gambl/hmftools-1.0/03-cobalt/genome--grch37/05-25788T--05-25788N--matched/05-25788T.cobalt.ratio.tsv referenceGCDiploidRatio results/gambl/hmftools-1.0/03-cobalt/genome--grch37/05-25788T--05-25788N--matched/05-25788N.cobalt.ratio.pcf
11:02:20 - Error executing R script. Examine error file /tmp/ratioSegmentation.R15793150358994711410.error for details.
11:02:20 - Error executing R script. Examine error file /tmp/ratioSegmentation.R830331258552063160.error for details.
11:02:20 - Complete
Exception in thread "main" java.util.concurrent.ExecutionException: java.io.IOException: R execution failed. Unable to complete segmentation.
...
```

The  error files say: 
```
Error in library(copynumber) : there is no package called ‘copynumber’
Execution halted
```

Adding the copynumber package to the environment solves the problem. Letting you know in case you want to update the recipe.

**Comment by alexiswl** [comment]
Thanks Peter, from https://github.com/hartwigmedical/hmftools/blob/master/count-bam-lines/src/main/resources/r/ratioSegmentation.R it is reassuring to see it is likely just that dependency.

**Comment by pdiakumis** [comment]
@lkhilton this should be resolved now via https://github.com/bioconda/bioconda-recipes/commit/c01290396c84f0e52688b69216decfdd8eaf9ea1

```
# in case you're unaware, mamba can install conda packages much faster than conda
# conda install -c conda-forge mamba

$ (base) mamba create -n my_cobalt_env -c conda-forge -c bioconda hmftools-cobalt
$ (base) conda activate my_cobalt_env
$ (my_cobalt_env) Rscript -e "require(copynumber)"
Loading required package: copynumber
Loading required package: BiocGenerics
Loading required package: parallel
```

**Comment by lkhilton** [comment]
Thanks for the Mamba tip - it's great! Can confirm the new Conda build installs all the dependencies.

**Comment by alexiswl** [comment]
@pdiakumis I have the same error for purple.

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/hmftools-purple/meta.yaml

For output chart generation the following R packages are required:

From the Readme: https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator
```
library(BiocManager)
install("VariantAnnotation")
install("dplyr")
install("ggplot2")
```

Also in the README:
```
To generate the CIRCOS output, CIRCOS must be downloaded and installed. Unlike the charts above, CIRCOS charts are not generated by default but only if the circos argument is provided.
```

**Comment by alexiswl** [comment]
I think I can get away with this using the `-no_charts` option for now.

**Comment by pdiakumis** [comment]
@alexiswl Updated via https://github.com/bioconda/bioconda-recipes/pull/24336.
Use `docker pull quay.io/biocontainers/hmftools-purple:2.47--1`.
