### ISSUE TITLE
PURPLE circos BAF filter

### ISSUE THREAD

**Issue by pdiakumis** [hartwigmedical/hmftools#12]
Hi,

May I ask what filters are used from the AMBER BAF file to the BAF values displayed in the PURPLE circos plot? Comparing the two for a COLO829 sample, we have:

```
wc -l baf_*
  192516 baf_amber.igv
   24066 baf_circos.igv
```

And here's their display in IGV (pretty similar, albeit a bit more of a separation for the filtered values):

<img width="839" alt="screen shot 2018-09-05 at 17 38 44" src="https://user-images.githubusercontent.com/29562861/45078326-17782b80-b133-11e8-9115-92b68f63ad6a.png">

Many thanks - Peter

**Comment by jonbaber** [comment]
Hi Peter, 

All circos tracks are downsampled by selecting every nth sample such that there is never more than 25000 data points. 

Cheers, Jonathan
