### ISSUE TITLE
output from linx - some of the chromosomes don't have plots

### ISSUE THREAD

**Issue by LibbyLi667** [hartwigmedical/hmftools#120]
Hi all, 

I ran the gridss/purple/linx pipeline (docker image) for my tumor/normal pairs, but for linx's result, I found not all chromosomes' plots are inside the 'linx/plot' directory, does linx just not put out a plot if there's nothing to be found? The pipeline/docker image I used shows Linx's version is 1.7.
Could anyone advise on this?

Thanks,
Libby

**Comment by charlesshale** [comment]
Hi Libby,

That's right - the Linx visualiser will only create plots for chromosomes which have SVs.

thanks,

Charles
