### ISSUE TITLE
Confusing Plotting of Disruptions

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#121]
Disruptions don't have a cluster ID, so it's confusing how to plot them. I thought I could do it by simply specifying the chromosome, but none of the plots created have the gene in the disruptions table illustrated. For example, if a disruptions file looks like

```
$ cat CSCC_0001-M1.linx.disruptions.tsv
svId    chromosome      orientation     strand  chrBand gene    type    junctionCopyNumber      exonUp  exonDown        undisruptedCopyNumber
458     chr5    -1      -1      p14.1-p14.2     CDH10   SGL     2.0000  5       6       2.7944
459     chr5    1       -1      p14.1-p14.2     CDH10   SGL     2.0800  5       6       2.8345
818     chr8    -1      -1      q22.3   UBR5    SGL     1.7000  44      45      4.1100
1289    chr14   -1      1       q24.1   RAD51B  DUP     1.8100  10      11      5.7800
```

and I open CSCC_0001-M1.chr5.035.png or CSCC_0001-M1.chr8.065.png or CSCC_0001-M1.chr14.029.png each created by specifying `-chromosome`  based on the second column of the table above, I see some structural variant but no genes in the gene track.

**Comment by charlesshale** [comment]
Hi Dario,

These Linx output files match our database schema, so they need to be linked by foreign & primary keys. In this case the disruptions file has svId, and then the linx.svs.tsv file links the svId to the clusterId. The use the 'clusterId' config option in the Visualiser to plot the relevant cluster.

There are also now 2 other applicable config options for the Visualiser:
- plot_cluster_genes - for a given cluster, show any gene linked to a SV breakend
-  plot_reportable - plot any cluster with a reportable fusion, driver or disruption
