### ISSUE TITLE
Allow linx `-output_dir` parameter to not exist

### ISSUE THREAD

**Issue by alexiswl** [hartwigmedical/hmftools#123]
Hello,

Would it be possible for the linx output directory parameter to not exist before running the command, this would make it consistent with cobalt, amber and purple, which also all have `-output_dir` parameters that don't need to exist.

Furthermore, writing a pre command for workflow languages makes the whole thing look a little ugly.

Kind regards,
Alexis.

**Comment by charlesshale** [comment]
I will add this in Linx 1.12. Thanks for the suggestion.
