### ISSUE TITLE
Purple bucket weight ? character

### ISSUE THREAD

**Issue by cboursnell** [hartwigmedical/hmftools#126]
I am running gridss-2.7.3, amber 3.5, cobalt 1.9 and purple 2.48. I have run gridss and the somatic filter Rscript, then run amber and cobalt and then purple. Purple gives an error when trying to plot with circos, and in the `sample.purple.somatic.clonality.tsv` output file the `bucketWeight` column contains a unicode ? in every row.

```
peak    bucket  bucketWeight    peakAvgWeight   isValid isSubclonal
0.0000  0.0000  �       1.0000  false   true
```

I don't get this issue when running purple 2.36 on the same input data.

**Comment by jonbaber** [comment]
Hi Chris, 

What somatic variant caller are you using? Are you allowed to share any of your data with me to help diagnose?

Thanks, Jon

**Comment by cboursnell** [comment]
I'm using GATK 4.1.8.1 Mutect2. I can't share patient data but maybe if I can reproduce with a minimal set of variants then I could share.
Would you suggest trying without the SNV vcf as an input to see if that changes anything?

**Comment by cboursnell** [comment]
Ok I found that by running without any SNV vcf specified then the bucket weights column contains numbers and not symbols. 
What about the vcf do you think could be causing that to happen? I'll try to reproduce with a minimal SNV vcf

**Comment by cboursnell** [comment]
I have reproduced this with a SNV vcf that contains just 3 variants. I think this would be safe to share. Let me know how you'd like me to get the file to you.

**Comment by jonbaber** [comment]
Thanks Chris, 

You can email me on J.Baber@hartwigmedicalfoundation.nl

Jon

**Comment by jonbaber** [comment]
Thank you for your patience. Could you please try again with version [2.50](https://github.com/hartwigmedical/hmftools/releases/tag/purple-v2.50).

**Comment by nvolkovaGEL** [comment]
Hi, I am having the same issue, but with `sample.purple.segment.tsv` for PURPLE version 2.50, it has these symbols scattered across all columns starting from `minorAlleleCopyNumber`:

`minorAlleleCopyNumber   minorAlleleCopyNumberDeviation  observedTumorRatio      observedNormalRatio     unnormalisedObservedNormalRatio majorAlleleCopyNumber   majorAlleleCopyNumberDeviationdeviationPenalty tumorCopyNumber fittedTumorCopyNumber   fittedBAF       refNormalisedCopyNumber ratioSupport    support depthWindowCount        tumorBAF        gcContent       svCluster       eventPenalty    minStart        maxStart
0.0000  �       0.0000  0.0000  0.0000  0.0000  �       �       0.0000  0.0000  0.0000  0.0000  true    TELOMERE        0       1.0000  0.4909  false   1.8000  1       1
 �       �       0.2123  1.1067  1.1067  �       �       �       �       0.0000  0.0000  0.0000  true    CENTROMERE      1       �       0.4505  false   �       123605523       123605523`

**Comment by jonbaber** [comment]
Hi Nadeza, 

Can you please show me the contents of your SAMPLE.purple.purity.tsv file.

Thanks, Jonathan

**Comment by nvolkovaGEL** [comment]
Hi Jonathan,

This is what I am seeing in the purity file:

```
user@host:~/test_purple$ head sample1.purple.purity.tsv

purity  normFactor      score   diploidProportion       ploidy  gender  status  polyclonalProportion    minPurity       maxPurity       minPloidy       maxPloidy       minDiploidProportion    maxDiploidProportion    version somaticPenalty  wholeGenomeDuplication  msIndelsPerMb  msStatus        tml     tmlStatus       tmbPerMb        tmbStatus       svTumorMutationalBurden
0.0800  �       0.0000  0.0000  0.0000  FEMALE  NORMAL  0.0000  0.0800  1.0000  0.0000  0.0000  0.0000  0.0000  2.50    0.0000  false   0.0     UNKNOWN 0       UNKNOWN 0.0     UNKNOWN 21
```

This purity looks quite misestimated (should be around 70%), not sure though how good this estimate should be for a targeted BAM. Can it be due to an error in some upstream component?

**Comment by jonbaber** [comment]
That NaN normFactor certainly looks like the culprit. I haven't been able to reproduce yet but I have put in a quick check to ensure the normFactor must be an actual number. 

Could you please try with this [beta version](https://nextcloud.hartwigmedicalfoundation.nl/s/wNtXjYWWBbmEWtT) and see if it fixes the problem.

**Comment by nvolkovaGEL** [comment]
Thanks for sharing a new version! Unfortunately, it did not help, now it just throws an error on the samples where it previously reported very low purity:

```
11:11:27 - Fitting purity
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.hartwig.hmftools.common.purple.purity.BestFitFactory.bestFit(BestFitFactory.java:69)
        at com.hartwig.hmftools.common.purple.purity.BestFitFactory.<init>(BestFitFactory.java:63)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.fitPurity(PurityPloidyEstimateApplication.java:346)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:161)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:103)
```

With purple-2.47, the purity was still very understimated but normFactor calculation worked fine. Still led to a error being thrown by LINX though:

sample.purple.purity.tsv
```
purity  normFactor      score   diploidProportion       ploidy  gender  status  polyclonalProportion    minPurity       maxPurity       minPloidy       maxPloidy       minDiploidProportion    maxDiploidProportion    version somaticPenalty  wholeGenomeDuplication  msIndelsPerMb  msStatus        tml     tmlStatus       tmbPerMb        tmbStatus
0.0800  0.5900  0.0000  0.0000  0.0000  FEMALE  NORMAL  0.0000  0.0800  1.0000  0.0000  0.0000  0.0000  0.0000  2.47    0.0000  false   0.0     UNKNOWN 0       UNKNOWN 0.0     UNKNOWN
```

sv-linx-v.1.11
```
[ERROR] - SV(274) missing start copy number data or unlined SV data
```
