### ISSUE TITLE
? Character in purity.tsv file

### ISSUE THREAD

**Issue by ellchua** [hartwigmedical/hmftools#127]
Hi, 

I've run GRIDSS 2.10.0, AMBER 3.5, COBALT 1.9 and currently trying to run PURPLE 2.48. 

I'm getting a question mark character in my `.purity.tsv` file - in the normFactor column - that is subsequently causing problems for when I try to run LINX.
```
purity	normFactor	score	diploidProportion	ploidy	gender	status	polyclonalProportion	minPurity	maxPurityminPloidy	maxPloidy	minDiploidProportion	maxDiploidProportion	version	somaticPenalty	wholeGenomeDuplication	msIndelsPerMb	msStatus	tml	tmlStatus	tmbPerMb	tmbStatus	svTumorMutationalBurden
0.0800	�	0.0000	0.0000	0.0000	FEMALE	NORMAL	0.0000	0.0800	1.0000	0.0000	0.0000	0.0000	0.0000	2.48	0.0000	false	0.22805176635187127	MSS	0	LOW	2.2808674361664916	LOW	9
```

I also get an error when trying to plot with circos:
`Fatal error creating circos plot. Examine error file purple/circos/CX_1200134_Tumor.circos.png.error for details.`

Similar to a previous issue, I don't get this problem when running purple 2.36 on the same input data. 

This is the command I've run:
```
java -jar purple-2.48.jar \
-reference CX_1200134_Blood \
-tumor CX_1200134_Tumor \
-output_dir purple \
-amber ./amber \
-cobalt ./cobalt \
-gc_profile ./hg38/GC_profile.hg38.1000bp.cnp \
-ref_genome ./reference_fasta/hg38_analysisSet.fa \
-somatic_vcf ./strelka_filtered_by_pass/CX_1200134.merged.annotated.vcf.gz \
-structural_vcf /home/ellora/projects/astrocytoma/gridss/CX_1200134.gridss.somatic.vcf.bgz \
-sv_recovery_vcf /home/ellora/projects/astrocytoma/gridss/CX_1200134.gridss.full.somatic.vcf.bgz \
-circos /home/shared/software/circos-0.69-9/bin/circos \
-threads 20
```

The somatic variant caller that I used was Strelka and I processed them according to [this](https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#preparing-strelka-output-for-purple) with the below tweaks as I'm currently using gatk 4.1.3.0 which no longer has the CombineVariants tool:
```
gatk MergeVcfs \
-I pass_CX_1200134_somatic.indels.recode.vcf \
-I pass_CX_1200134_somatic.snvs.recode.vcf \
-R /home/ellora/projects/astrocytoma/hmftools/reference_fasta/hg38_analysisSet.fa \
-O CX_1200134.merged.vcf

sed -i 's/NORMAL/CX_1200134_Blood/g' CX_1200134.merged.vcf
sed -i 's/TUMOR/CX_1200134_Tumor/g' CX_1200134.merged.vcf

java -Xmx4G -cp purple-2.48.jar com.hartwig.hmftools.purple.tools.AnnotateStrelkaWithAllelicDepth \
-in CX_1200134.merged.vcf \
-out CX_1200134.merged.annotated.vcf.gz
```

**Comment by ellchua** [comment]
I tried running the command again without the `-somatic_vcf` argument but still get the same results, so currently I'm not sure if it has to do with my vcf file...

**Comment by jonbaber** [comment]
It’s a regression bug I introduced into 2.48 and onwards.

I will release a new version tomorrow with a fix.

Thanks, Jon

**Comment by jonbaber** [comment]
Thank you for your patience. Could you please try again with version [2.50](https://github.com/hartwigmedical/hmftools/releases/tag/purple-v2.50)

**Comment by ellchua** [comment]
It works now! Thanks, Jon.
