### ISSUE TITLE
COBALT 1.9 segmentation issues

### ISSUE THREAD

**Issue by nvolkovaGEL** [hartwigmedical/hmftools#129]
Hello,
I am running cobalt 1.9 as a part of GRIDSS-PURPLE-LINX pipeline on BAM files generated from WGS CRAMs by selecting the regions of interest (so some chromosomes will have no reads by design). On the very same input, cobalt 1.8 runs fine and produces outputs needed for downstream pipeline component, but v.1.9 throws the following error:

> Warning: pcf is not run for sample 1 on chromosome arm  because all observations are missing. NA is returned.
> Error in data.frame(rep(sampleid[i], nSeg), seg.chrom, seg.arm, pos.start,  :
>  arguments imply differing number of rows: 1, 0
> Calls: pcf -> data.frame

I did not yet try to build cobalt v.1.10, but could you please let me know whether this is to be extected with v.1.10 as well, or provide a pre-built JAR to test it? Thanks a lot in advance!

**Comment by jonbaber** [comment]
There is a good chance that 1.10 will fix this as it fixed an issue with our test cancer panel which is small and targeted.

We normally provide pre built JARs for each version that we release. Links are available in the [version history](https://github.com/hartwigmedical/hmftools/tree/master/count-bam-lines#version-history-and-download-links).

Looks like I made a mistake and forgot to release 1.10. My apologies. This i is fixed now and available [here](https://github.com/hartwigmedical/hmftools/releases/tag/cobalt-v1.10).
