### ISSUE TITLE
GRIPSS tumor, reference specification

### ISSUE THREAD

**Issue by TnakaNY** [hartwigmedical/hmftools#131]
I am not sure how I specify tumor, reference sample name for GRIPSS.jar after GRIDSS running. 
Please tell us how to specify the names for tumor, reference.

I used this command for GRIDSS running: 
docker run --ulimit nofile=100000:100000 -v D:/GRIDSStest/refdata:/refdata -v D:/GRIDSStest/test13:/data/ gridss/gridss:2.9.4 -b /refdata/dbs/gridss/ENCFF001TDO.bed -r /refdata/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta -o /data/outputs/gridss/CPCT12345678T.gridss.vcf.gz -a /data/outputs/gridss/CPCT12345678T.assembly.bam -w /data/outputs/gridss -j /opt/gridss/gridss-2.9.4-gridss-jar-with-dependencies.jar -t 8 --jvmheap 30g --labels CPCT12345678,CPCT12345678 --steps all /data/CPCT12345678R.bam /data/CPCT12345678T.bam

Then, 
java -cp gripss-1.8.jar com.hartwig.hmftools.gripss.GripssApplicationKt -tumor CPCT12345678T -reference CPCT12345678R -ref_genome D:\GRIDSStest\refdata\refgenomes\Homo_sapiens.GRCh37.GATK.illumina\Homo_sapiens.GRCh37.GATK.illumina.fasta -breakend_pon D:\GRIDSStest\refdata\dbs\gridss\pon3792v1\gridss_pon_single_breakend.bed -breakpoint_pon D:\GRIDSStest\refdata\dbs\gridss\pon3792v1\gridss_pon_breakpoint.bedpe -breakpoint_hotspot D:\GRIDSStest\refdata\dbs\knowledgebases\output\KnownFusionPairs.hg19.bedpe -input_vcf D:\GRIDSStest\test13\outputs\gridss\CPCT12345678T.gridss.vcf.gz -output_vcf D:\GRIDSStest\test13\outputs\gridss\CPCT12345678T.gridss.somatic.vcf.gz

Error:
Unable to locate sample CPCT12345678T in supplied VCF

**Comment by jonbaber** [comment]
Hi, 

Can you please verify what the sample names are in the CPCT12345678T.gridss.vcf.gz file? If they do not match CPCT12345678R and CPCT12345678T then gripss will not be able to find them.

In your gridss command you have used the same label for both normal and tumor which I am guessing is the problem.

You can try running gridss again with `--labels CPCT12345678R,CPCT12345678T` or just manually change the labels in the VCF file.

Jon

**Comment by TnakaNY** [comment]
In my vcf, I see CPCT12345678.
These input files for GRIDSS are normal and tumor file from same patient.
That's why I used same name for '--label'.

**Comment by jonbaber** [comment]
That confirms the problem then. While they are both from the patient, they are still 2 seperate samples and must have distinct labels, eg CPCT12345678R and CPCT12345678T.

**Comment by TnakaNY** [comment]
I see. Thank you for your help!
