### ISSUE TITLE
GRIPSS output for PURPLE  structural variant recovery vcf

### ISSUE THREAD

**Issue by TnakaNY** [hartwigmedical/hmftools#132]
In the PURPLE and GRIPSS documentation, it is not clear, so let me ask here.

Input files for PURPLE, there are two sv input option.
structural_vcf
sv_recovery_vcf

SAMPLE_T.gridss.somatic.vcf.gz can be used for "sv_recovery_vcf" as a low confidence.
SAMPLE_T.gridss.somatic.filtered.vcf.gz can be used for "structural_vcf" as a high confidence.

Is this specification correct?

**Comment by p-priestley** [comment]
Correct.    The SV recovery is described here:

https://github.com/hartwigmedical/hmftools/blob/master/purity-ploidy-estimator/README.md#7-structural-variant-recovery

**Comment by TnakaNY** [comment]
Thank you!

**Comment by jamesdalg** [comment]
Question: can you use the fulloutput described below (high and low confidence, shown below) as a recovery VCF file?
from https://github.com/PapenfussLab/gridss/blob/a6b230a78179869c0210dc878490811be813d2fb/QuickStart.md:
gridss_somatic_filter \
  --pondir refdata/hg19/dbs/gridss/pon3792v1/ \
  --input all_calls.vcf \
  --output high_confidence_somatic.vcf.gz \
  --fulloutput high_and_low_confidence_somatic.vcf.gz \
  --scriptdir $(dirname $(which gridss_somatic_filter)) \
  -n 1 \
  -t 2

> Correct. The SV recovery is described here:
> 
> https://github.com/hartwigmedical/hmftools/blob/master/purity-ploidy-estimator/README.md#7-structural-variant-recovery

**Comment by p-priestley** [comment]
We use this program to do the filtering:  https://github.com/hartwigmedical/hmftools/tree/master/gripss

This writes 2 files:
• SAMPLE_T.gridss.somatic.vcf.gz - all non-hard-filtered SVs  => used for SV recovery
• SAMPLE_T.gridss.somatic.filtered.vcf.gz - filtered for PASS and PON only   => used as primary SV input

I think gridss_somatic_filter does something similar and I think the high_and_low_confidence_somatic.vcf.gz should be the recovery file.
