### ISSUE TITLE
PURPLE failure in final step for making plot by R

### ISSUE THREAD

**Issue by TnakaNY** [hartwigmedical/hmftools#133]
I am trying to run PURPLE in HPC.
I installed circos by conda. 
For R, "module load R3.6.0" was used.
dependent R package was locally installed.

Most steps of PURPLE ran well, but final steps for making purple plot failed.
Console output, error file are attached.

Could anyone give me suggestions? 

[copyNumberPlots.R8677610706250992212.error.txt](https://github.com/hartwigmedical/hmftools/files/5484333/copyNumberPlots.R8677610706250992212.error.txt)
[somaticVariantPlots.R82776327360657982.error.txt](https://github.com/hartwigmedical/hmftools/files/5484334/somaticVariantPlots.R82776327360657982.error.txt)
[PURPLE_console_output.txt](https://github.com/hartwigmedical/hmftools/files/5484362/PURPLE_console_output.txt)

**Comment by jonbaber** [comment]
Not familiar with that error. A quick google of the error message produced a number of hits so you might want to try some of the suggestions from there. 

The other option is to run PURPLE with the `-no_charts` option.

**Comment by pdiakumis** [comment]
Hi @TnakaNY,
My guess would be that the R HPC installation is missing a PNG device (or something related). If you want to try a full-conda installation of PURPLE/AMBER/COBALT with R, we use the below in our group (you can ignore linx/gridss/sage if you're not using them):

`conda env create -f environment.yml` where the YAML file is:


```
# environment.yml
name: hmf_conda_env

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bwa
  - r-base
  - python ==3.7.3
  - hmftools-amber ==3.5
  - hmftools-cobalt ==1.10
  - hmftools-linx ==1.12
  - hmftools-purple ==2.51
  - hmftools-sage ==1.0
  - gridss
  - r-argparser
  - r-assertthat
  - r-devtools
  - r-magick
  - r-nmf
  - r-r.cache
  - r-stringdist
  - r-testthat
  - r-tidyverse
  - bioconductor-bsgenome
  - bioconductor-org.hs.eg.db
  - bioconductor-rtracklayer
  - bioconductor-structuralvariantannotation
  - bioconductor-variantannotation
```

Hope that helps.

**Comment by DarioS** [comment]
Easiest way to find out more would be to log a support request with your HPC systems administrator. I had the same error on University of Sydney's HPC a while ago and I ended up editing the R files within PURPLE's JAR and commenting out the plotting code and replacing it by a save of the data onto disk, then copying files and doing the circular plotting on another server.

**Comment by TnakaNY** [comment]
Hi All,
Thank you for prompt reply. Please let me try to make new conda env shown above and check PNG setting in our HPC.
