### ISSUE TITLE
PURPLE final circos plot failure

### ISSUE THREAD

**Issue by TnakaNY** [hartwigmedical/hmftools#134]
I am trying to run PURPLE in HPC.
I installed circos by conda. 
For R, "module load R3.6.0" was used.
dependent R package was locally installed.

Most steps of PURPLE ran well, but final steps for making purple plot failed.
Console output, error file are attached.

Could anyone give me suggestions? 

[copyNumberPlots.R8677610706250992212.error.txt](https://github.com/hartwigmedical/hmftools/files/5484333/copyNumberPlots.R8677610706250992212.error.txt)
[somaticVariantPlots.R82776327360657982.error.txt](https://github.com/hartwigmedical/hmftools/files/5484334/somaticVariantPlots.R82776327360657982.error.txt)
[PURPLE_console_output.txt](https://github.com/hartwigmedical/hmftools/files/5484362/PURPLE_console_output.txt)

**Comment by p-priestley** [comment]
appears to be fixed in linked issue
