### ISSUE TITLE
Comparing PURPLE results with GATK CNV according to ploidy value

### ISSUE THREAD

**Issue by Jelisaveta** [hartwigmedical/hmftools#136]
Hi, 

I am working on comparison between several callers. I have an output from PURPLE (tumor.purple.purity.tsv file) which states that ploidy is 3. For other callers, example: GATK, ploidy is not set and we assume it is 2. 

How to compare those results? Should we adjust results from PURPLE (tumor.purple.cnv.somatic.tsv file) to 3, meaning that result >3 would be gain, ==3 would be neutral, and <3 would be loss, or in which way to compare those results to other callers, for example GATK or FREEC?

Thank you in advance

**Comment by p-priestley** [comment]
Many callers indeed calculate a relative copy number only.

For a tumor with ploidy 3, copy number of 3 should be considered neutral.   We have used CN>1.4x ploidy and CN<0.6x ploidy to represent gain or loss,  with CN >3x ploidy as high level gain and CN < 0.5 (absolute) as homozygous deletion.   See for example figure 2a in this publicaiton: https://www.nature.com/articles/s41586-019-1689-y#Fig2

**Comment by Jelisaveta** [comment]
Thank you!

So just to make it clear once again, itis correct to put it like this (with ploidy = 3.23): 
`   if cn_value < 0.5:
        status = 'homozygous_deletion'
    elif 0.5 <= cn_value < (0.6 * ploidy):
        status = 'heterozygous_deletion'
    elif (0.6 * ploidy) <= cn_value < (1.4 * ploidy):
        status = 'neutral'
    elif (1.4 * ploidy) <= cn_value < (3 * ploidy):
        status = 'gain'
    else:
        status = 'gain_high'
    return status`

**Comment by p-priestley** [comment]
yes this is the logic we applied.

**Comment by Jelisaveta** [comment]
Thank you once again!
