### ISSUE TITLE
median normal depth is 0 reads

### ISSUE THREAD

**Issue by MaXXinee** [hartwigmedical/hmftools#139]
Dear PURPLE team,

thank you for building such a great tool for calling tumor purity and ploidy. When I was running amber to prepare one of my tumor/normal bam files, I got the following error: Median normal depth is 0 reads: filtering reads outside of 0 and 0. At the end there were 0 BAF, and the segmentation had failed. Could you please give me some suggestions on what might went wrong?

**Comment by jonbaber** [comment]
Hi, 

This means that no BAF points were found in the BAM. Is it a WGS bam you are using? We do not support panel at the moment. Also, you might want to double check that you are using the correct loci file for your assembly and pay particular attention to the contig naming scheme as the bam contigs must match the loci contigs exactly. 

Jon

**Comment by MaXXinee** [comment]
Thank you for your help! I am using a WES bam. The contig naming scheme is exactly the same as the other bams that I am using and I had no problems with those files.

**Comment by jonbaber** [comment]
That explains the problem then. There are no BAF points that match our criteria within your panel. 

Unfortunately PURPLE is not designed for WES so I can't offer you much support. 

If you still wish to persist then you need to create a new loci VCF specifically designed for your panel.
