### ISSUE TITLE
GC adjusted coverage file from COBALT

### ISSUE THREAD

**Issue by alhafidzhamdan** [hartwigmedical/hmftools#142]
Hi there,

I'm trying to figure out the best way to get a file containing GC content adjusted copy number for tumour sample WGS.
Looking at cobalt.ratio.tsv output, what would you say the best way to obtain this?

`Chromosome | Position | ReferenceReadCount | TumorReadCount | ReferenceGCRatio | TumorGCRatio | ReferenceGCDiploidRatio`

Is it simply (TumorReadCount X TumorGCRatio)/(ReferenceReadCount X ReferenceGCDiploidRatio).
I might be totally out of mark here but appreciate any input.
A

**Comment by DarioS** [comment]
That's the main purpose of PURPLE. See [Copy Number File](https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#copy-number-file) section, particularly CopyNumber column definition.

**Comment by alhafidzhamdan** [comment]
Hi @DarioS thanks for that. 
I need a gc content only adjusted copy number and not purity adjusted.

**Comment by p-priestley** [comment]
The "tumorGCRatio" is already the binned copy number adjusted for GC.      The ratio is the copy number relative to the ploidy of the sample.

**Comment by alhafidzhamdan** [comment]
Cheers @p-priestley, that will do.
