### ISSUE TITLE
Difficult Plotting of Reportable Fusion Genes

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#144]
It is unclear how to always plot both genes of a gene fusion in one plot. For example, if the summary file looks like:
```
$ cat CSCC_0009-M1.linx.reported_fusion.tsv
geneStart       geneContextStart        geneTranscriptStart     geneEnd geneContextEnd  geneTranscriptEnd       junctionCopyNumber
STRN    Exon 1  ENST00000263918 DLG2    Exon 7  ENST00000376104 0.5750
```

I find that STRN is on chromosome 2. By specifying `-sample CSCC_0009-M1` and `-chromosome chr2` I see a plot that includes STRN on chromosome 2, as well as parts on chromosomes 1, 3 and 20. But, nothing on chromosome 11 which is what DLG2 is on. By specifying `-sample CSCC_0009-M1` and `-chromosome chr11` I see a plot with DLG2 on it and no other chromosomes apart from 11.

**Comment by p-priestley** [comment]
Hi Dario,    You can plot by chromosome or cluster id.    We always use the cluster id to plot fusions.     I think both genes will definitely show in this case.

**Comment by DarioS** [comment]
Neither the fusion nor reported fusion tables have a clusterId column. How should it be done?

**Comment by DarioS** [comment]
The `-plot_reportable` option in version 1.16 makes it easy to plot reportable fusions.
