### ISSUE TITLE
How do I get integer segment copy number from PURPLEoutput?

### ISSUE THREAD

**Issue by TnakaNY** [hartwigmedical/hmftools#147]
I ran GRIDSS, cobalt, amber, purple, linx, seperately.
Then, for further analysis, I needed integer segment copy number.
But, ".tumor.purple.cnv.somatic.tsv" has  non-integer "copyNumber".

What is the best process to get integer segment copy number?
Any suggestion is great help for me.

Thanks.

**Comment by p-priestley** [comment]
The numbers are intentionally left as non integer to not obscure any features which may be subclonal.  You should just round to the nearest positive integer or 0.
