### ISSUE TITLE
unusual paths?

### ISSUE THREAD

**Issue by RichardCorbett** [hartwigmedical/hmftools#15]
Hi folks, 
Here's the command I'm trying:
`
/linux-x86_64/jre1.8.0_66/bin/java -jar bin/cobalt/cobalt-1.5.jar -reference /references/GRCh37-lite.fa -reference_bam /rcorbettprj2/purple/normal.bam -reference normal -tumor tumour -tumor_bam /rcorbettprj2/purple/tumour.bam -gc_profile /rcorbettprj2/purple/GC_profile.hg19.1000bp.cnp -output_dir /rcorbettprj2/purple/ -threads 24`

This runs smoothly for a few minutes and then fails with the following output.  It looks as though it is mashing together two parts of the path to look for a file.

> 08:18:52 - COBALT version: 1.5
> 08:18:52 - Thread Count: 24, Window Size: 1000, Min Quality 10
> 08:18:52 - Reading GC Profile
> 08:18:56 - Calculating Read Count from /rcorbettprj2/purple/tumour.bam
> 08:18:56 - Generating windows on chromosome 1
> 08:18:56 - Generating windows on chromosome 2
> 08:18:56 - Generating windows on chromosome 3
> 08:18:56 - Generating windows on chromosome 4
> 08:18:56 - Generating windows on chromosome 7
> 08:18:56 - Generating windows on chromosome 6
> 08:18:56 - Generating windows on chromosome 5
> 08:18:56 - Generating windows on chromosome 8
> 08:18:56 - Generating windows on chromosome 15
> 08:18:56 - Generating windows on chromosome 14
> 08:18:56 - Generating windows on chromosome 12
> 08:18:56 - Generating windows on chromosome 18
> 08:18:56 - Generating windows on chromosome 16
> 08:18:56 - Generating windows on chromosome 22
> 08:18:56 - Generating windows on chromosome 21
> 08:18:56 - Generating windows on chromosome 20
> 08:18:56 - Generating windows on chromosome 19
> 08:18:56 - Generating windows on chromosome 9
> 08:18:56 - Calculating Read Count from /rcorbettprj2/purple/normal.bam
> 08:18:56 - Generating windows on chromosome X
> 08:18:56 - Generating windows on chromosome Y
> 08:18:56 - Generating windows on chromosome 10
> 08:18:56 - Generating windows on chromosome 11
> 08:18:56 - Generating windows on chromosome 13
> 08:18:56 - Generating windows on chromosome 17
> 08:21:14 - Generating windows on chromosome 1
> 08:25:53 - Generating windows on chromosome 2
> 08:26:26 - Generating windows on chromosome 3
> 08:26:54 - Generating windows on chromosome 4
> 08:29:24 - Generating windows on chromosome 5
> 08:29:36 - Generating windows on chromosome 6
> 08:30:13 - Generating windows on chromosome 7
> 08:31:54 - Generating windows on chromosome 8
> 08:32:10 - Generating windows on chromosome 9
> 08:32:41 - Generating windows on chromosome 10
> 08:32:47 - Generating windows on chromosome 11
> 08:33:46 - Generating windows on chromosome 12
> 08:34:11 - Generating windows on chromosome 13
> 08:35:43 - Generating windows on chromosome 14
> 08:36:44 - Generating windows on chromosome 15
> 08:36:49 - Generating windows on chromosome 16
> 08:36:53 - Generating windows on chromosome 17
> 08:36:57 - Generating windows on chromosome 18
> 08:39:16 - Generating windows on chromosome 19
> 08:39:19 - Generating windows on chromosome 20
> 08:40:50 - Generating windows on chromosome 21
> 08:41:31 - Generating windows on chromosome 22
> 08:41:36 - Generating windows on chromosome X
> 08:41:48 - Generating windows on chromosome Y
> 09:10:59 - Read Count Complete
> 09:11:00 - Applying ratio gc normalization
> 09:11:04 - Applying ratio diploid normalization
> 09:11:16 - Persisting gc read count medians to /rcorbettprj2/purple/
> Exception in thread "main" java.nio.file.NoSuchFileException: /rcorbettprj2/purple/rcorbettprj2/GATK4VariantCall/GRCh37-lite.fa.cobalt.gc.median
> 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
> 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
> 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
> 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
> 	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
> 	at java.nio.file.Files.newOutputStream(Files.java:216)
> 	at java.nio.file.Files.write(Files.java:3351)
> 	at java.nio.file.Files.write(Files.java:3397)
> 	at com.hartwig.hmftools.common.gc.GCMedianReadCountFile.write(GCMedianReadCountFile.java:31)
> 	at com.hartwig.hmftools.cobalt.ratio.RatioSupplier.generateRatios(RatioSupplier.java:48)
> 	at com.hartwig.hmftools.cobalt.CountBamLinesApplication.<init>(CountBamLinesApplication.java:122)
> 	at com.hartwig.hmftools.cobalt.CountBamLinesApplication.main(CountBamLinesApplication.java:51)
>

**Comment by jonbaber** [comment]
Hi Richard,

The -reference parameter should just be the name of the reference sample.
You have included it twice, in the first instance you have used a path to a
ref genome.

Removing the first usage should fix it:

/linux-x86_64/jre1.8.0_66/bin/java -jar bin/cobalt/cobalt-1.5.jar
-reference_bam /rcorbettprj2/purple/normal.bam -reference normal -tumor
tumour -tumor_bam /rcorbettprj2/purple/tumour.bam -gc_profile
/rcorbettprj2/purple/GC_profile.hg19.1000bp.cnp -output_dir
/rcorbettprj2/purple/ -threads 24


Cheers, Jon

**Comment by RichardCorbett** [comment]
Yikes! How did I miss that.  Thanks @jonbaber

**Comment by jonbaber** [comment]
Always the way isn't it :)
