### ISSUE TITLE
jar for health-checker

### ISSUE THREAD

**Issue by DavyCats** [hartwigmedical/hmftools#150]
Hi,

I was wondering if it would be possible for a jar file of the latest version (3.2) of health-checker to be made available. I would like to add it to a docker image, so we can use it in our [reimplementation](https://github.com/biowdl/WGSinCancerDiagnostics) of [pipeline5](https://github.com/hartwigmedical/pipeline5).

**Comment by kduyvesteyn** [comment]
Hi Davy,

Have added the jar to https://github.com/hartwigmedical/hmftools/releases/tag/health-checker-v3.2

**Comment by DavyCats** [comment]
Thanks! 👍
