### ISSUE TITLE
reciprocal inversion annotation

### ISSUE THREAD

**Issue by hastj7373** [hartwigmedical/hmftools#151]
Hello

I have a question regarding reciprocal inversion. 
The following shows GRIDSS VCF (1) and its annotation by LINX (2; see below)
LINX seems to annotate these events as INV (type column), but the resolved type is PAIR_OTHER.
I suspect these events might have been annotated as reciprocal inversion. 
Could you please correct me if I misunderstand something?

1. GRIDSS VCF

chr13	103922321	gridss218ff_3579o	A	ATTG]chr13:103925352]	772.92	PASS	AS=1;ASC=241M1X;ASQ=298.13;ASRP=15;ASSR=15;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm218-18011,asm218-18027,asm218-65873;BEIDH=71,0,193;BEIDL=0,303,0;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=51.54;BSC=3;BSCQ=51.54;BUM=0;BUMQ=0.00;BVF=0;CAS=1;CASQ=35.19;CQ=698.14;EVENT=gridss218ff_3579;IC=0;IHOMPOS=0,0;IQ=0.00;MATEID=gridss218ff_3579h;MQ=57.43;MQN=21.00;MQX=60.00;RAS=1;RASQ=229.42;REF=37;REFPAIR=10;RP=5;RPQ=87.98;SB=0.5833333;SC=241M1X;SR=6;SRQ=122.19;SVTYPE=BND;VF=13	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0.00:0:0:0:0.00:0:0.00:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:0.00:0.00:23:6:0:0.00:0:0.00:0	.:298.13:15:15:0:0.00:0:0.00:0.00:0:0:51.54:3:51.54:0:0.00:0:35.19:0:0.00:772.92:229.42:14:4:5:87.98:6:122.19:13
chr13	103925352	gridss218ff_3579h	C	CCAA]chr13:103922321]	772.92	PASS	AS=1;ASC=312M1X;ASQ=229.42;ASRP=15;ASSR=15;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm218-18011,asm218-18027,asm218-65873;BEIDH=0,303,0;BEIDL=71,0,193;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=19.25;BSC=1;BSCQ=19.25;BUM=0;BUMQ=0.00;BVF=0;CAS=1;CASQ=35.19;CQ=698.14;EVENT=gridss218ff_3579;IC=0;IHOMPOS=0,0;IQ=0.00;MATEID=gridss218ff_3579o;MQ=57.43;MQN=21.00;MQX=60.00;RAS=1;RASQ=298.13;REF=51;REFPAIR=10;RP=5;RPQ=87.98;SB=0.36363637;SC=312M1X;SR=6;SRQ=122.19;SVTYPE=BND;VF=13	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0.00:0:0:0:0.00:0:0.00:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:0.00:0.00:26:4:0:0.00:0:0.00:0	.:229.42:15:15:0:0.00:0:0.00:0.00:0:0:19.25:1:19.25:0:0.00:0:35.19:0:0.00:772.92:298.13:25:6:5:87.98:6:122.19:13
chr13	103923392	gridss218bb_3562o	T	[chr13:103925041[T	794	PASS	AS=2;ASC=1X1N1X216M;ASQ=263.64;ASRP=11;ASSR=18;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm218-18011,asm218-65863,asm218-65864,asm218-65873;BEIDH=71,0,202,193;BEIDL=384,206,0,301;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=33.65;BSC=2;BSCQ=33.65;BUM=0;BUMQ=0.00;BVF=0;CAS=1;CASQ=70.39;CIPOS=-1,1;CIRPOS=-1,1;CQ=794.00;EVENT=gridss218bb_3562;HOMLEN=2;HOMSEQ=TT;IC=0;IHOMPOS=-1,1;IQ=0.00;MATEID=gridss218bb_3562h;MQ=60.00;MQN=60.00;MQX=60.00;RAS=1;RASQ=212.39;REF=31;REFPAIR=16;RP=5;RPQ=87.98;SB=0.4722222;SC=1X1N1X216M4D151M;SR=8;SRQ=159.60;SVTYPE=BND;VF=13	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0.00:0:0:0:0.00:0:0.00:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:0.00:0.00:23:12:0:0.00:0:0.00:0	.:263.64:11:18:0:0.00:0:0.00:0.00:0:0:33.65:2:33.65:0:0.00:0:70.39:0:0.00:794.00:212.39:8:4:5:87.98:8:159.60:13
chr13	103925041	gridss218bb_3562h	A	[chr13:103923392[A	794	PASS	AS=1;ASC=1X312M;ASQ=212.39;ASRP=11;ASSR=18;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm218-18011,asm218-65863,asm218-65864,asm218-65873;BEIDH=384,206,0,301;BEIDL=71,0,202,193;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=33.51;BSC=2;BSCQ=33.51;BUM=0;BUMQ=0.00;BVF=1;CAS=1;CASQ=70.39;CIPOS=-1,1;CIRPOS=-1,1;CQ=794.00;EVENT=gridss218bb_3562;HOMLEN=2;HOMSEQ=AA;IC=0;IHOMPOS=-1,1;IQ=0.00;MATEID=gridss218bb_3562o;MQ=60.00;MQN=60.00;MQX=60.00;RAS=2;RASQ=263.64;REF=59;REFPAIR=8;RP=5;RPQ=87.98;SB=0.5555556;SC=1X312M;SR=8;SRQ=159.60;SVTYPE=BND;VF=13	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:0.00:0:0:0:0.00:0:0.00:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:0.00:0.00:30:7:0:0.00:0:0.00:0	.:212.39:11:18:0:0.00:0:0.00:0.00:0:0:33.51:2:33.51:0:0.00:1:70.39:0:0.00:794.00:263.64:29:1:5:87.98:8:159.60:13

2. LINX annotation
A       4       1       2       INV     PAIR_OTHER      false   chr13   chr13   103922321       103925352       1       1       NORMAL  NORMAL  0.0000  false
A       4       2       3       INV     PAIR_OTHER      false   chr13   chr13   103923392       103925041       -1      -1      FOLDBACK        FOLDBACK        0.0000  false

**Comment by p-priestley** [comment]
From the GRIDSS vcf it appears the 2 higher breakends at 103925352 and  103925041 may be linked by assembly.   Could you confirm that you run GRIPSS to filter somatic, and if so could you also include the GRIPSS vcf output for those 2 variants so that we can see whether GRIPSS has found the linkage?

If the higher breakends are infact linked as I expect, then I would expect this to be classified as a DELETION with a small templated insertion (so not a RECIP_INVERSION), so I still cannot explain why it is classified PAIR_OTHER.  If you could also attach the relevant lines from the svs.tsv, links.tsv and clusters.tsv then I can probably diagnose.

**Comment by hastj7373** [comment]
Hello

I appreciate your prompt and kind answer. !

I just ran GRIPSS according to your suggestion and then ran LINX again. 
However, I found the same results. 
I looked into the log (see below), these events appeared to be skipped because of low JCN. 
Is there any way to turn off this filter? (I am playing with LINX without input from PURPLE).

02:24:45 - [INFO ] - LINX version: 1.12
02:24:45 - [INFO ] - running SV analysis for test
02:24:45 - [INFO ] - loaded 20 known fragile sites from file: ./Linx/fragile_sites_hmf.hg38.csv
02:24:45 - [INFO ] - loaded 124 known line elements from file: ./Linx/line_elements.hg38.csv
02:24:45 - [DEBUG] - loaded 1613 viral host data
02:24:45 - [INFO ] - loaded 2 SV data records from VCF file: ./somatic.vcf.gz
02:24:45 - [ERROR] - failed to load purity context: java.nio.file.NoSuchFileException: ./purple/test.purple.cnv
02:24:45 - [DEBUG] - sample(test) LOH sections(0) fullMatched(0)
02:24:45 - [DEBUG] - loaded 2 SVs
02:24:45 - [DEBUG] - sample(test) analysing 2 variants
02:24:45 - [DEBUG] - simple dels count(0) cutoff-length(100000), dups count(0) cutoff-length(100000) simpleArms(1) trimCount(0)
02:24:45 - [DEBUG] - cluster(0) adding assembly linked pair(0 chr13:103925041:end & 1 chr13:103925352:end) length(311)
02:24:45 - [DEBUG] - cluster(0) skipping SV(1) with low JCN(0.00 min=0.00 max=0.00)
02:24:45 - [DEBUG] - cluster(0) skipping SV(0) with low JCN(0.00 min=0.00 max=0.00)
02:24:45 - [DEBUG] - cluster(0) skipping assembled link(pair(0 chr13:103925041:end & 1 chr13:103925352:end) rule(ASSEMBLY) jcn(0.00) match(None) length(311) priority(1)) with low JCN
02:24:45 - [DEBUG] - cluster(0) chaining finished: chains(0 links=0) SVs(0) unlinked SVs(0) breakends(0)
02:24:45 - [DEBUG] - cluster(0) complex SVs(2) desc(INV=2 res=NONE) arms(1) consis(0) chains(0 perc=0.00) replic(false) inv=2
02:24:45 - [DEBUG] - cluster(0) skipping SV(1) with low JCN(0.00 min=0.00 max=0.00)
02:24:45 - [DEBUG] - cluster(0) skipping SV(0) with low JCN(0.00 min=0.00 max=0.00)
02:24:45 - [DEBUG] - cluster(0) skipping assembled link(pair(0 chr13:103925041:end & 1 chr13:103925352:end) rule(ASSEMBLY) jcn(0.00) match(None) length(311) priority(1)) with low JCN
02:24:45 - [DEBUG] - cluster(0) chaining finished: chains(0 links=0) SVs(0) unlinked SVs(0) breakends(0)
02:24:45 - [DEBUG] - cluster(0) complex SVs(2) desc(INV=2 res=PAIR_OTHER) arms(1) consis(0) chains(0 perc=0.00) replic(false) inv=2
02:24:45 - [INFO ] - PerfStats: name(Total) intervals(1) total(0.224)
02:24:45 - [INFO ] - PerfStats: name(Preparation) intervals(1) total(0.006)
02:24:45 - [INFO ] - PerfStats: name(ClusterAndAnalyse) intervals(1) total(0.032)
02:24:45 - [INFO ] - PerfStats: name(Clustering) intervals(1) total(0.007)
02:24:45 - [INFO ] - PerfStats: name(Chaining) intervals(1) total(0.018)
02:24:45 - [INFO ] - PerfStats: name(Annotation) intervals(1) total(0.001)
02:24:45 - [INFO ] - PerfStats: name(WriteCSV) intervals(1) total(0.027)
02:24:45 - [INFO ] - SV analysis complete for test

**Comment by p-priestley** [comment]
JCN=0 looks like there is a problem upstream with your output from PURPLE.   

Could you provide the input sv.vcf.gz that you have used for LINX so I can see the JCN and other details please?

**Comment by hastj7373** [comment]
Hello

Thanks to you, I figured it out. (There was a mistake when I ran PURPLE).
What I got,

clusterId       category        synthetic       resolvedType    clusterCount
  clusterDesc

16      SIMPLE  true    DEL     2       INV=2


The resolved type is DEL as you expected.

This event is associated with DEL, followed by insertion? (so probably copy
a neutral event?)


I hugely appreciate your help.!

Best wishes,

**Comment by p-priestley** [comment]
This is most like a small deletion with a 'shard' inserted.

For some background please read the section on shards in our preprint:

https://www.biorxiv.org/content/10.1101/2020.12.03.410860v1.full

We also describe this kind of event on our github documentation,here:

https://github.com/hartwigmedical/hmftools/tree/master/sv-linx#shards-and-synthetic-events
