### ISSUE TITLE
Command for filtering with PoN

### ISSUE THREAD

**Issue by maingoc303** [hartwigmedical/hmftools#153]
Hi, I running your command as reference for filtering output from GRIDSS:
java -Xms4G -Xmx16G -cp gripss.jar com.hartwig.hmftools.gripss.GripssApplicationKt \
   -tumor SAMPLE_T \
   -reference SAMPLE_N \
   -ref_genome /path/to/Homo_sapiens_assembly.fasta \
   -breakend_pon /path/to/gridss_pon_single_breakend.bed \
   -breakpoint_pon /path/to/gridss_pon_breakpoint.bedpe \
   -breakpoint_hotspot /path/to/KnownFusionPairs.bedpe \
   -input_vcf /path/to/SAMPLE_T.gridss.unfiltered.vcf.gz \
   -output_vcf /path/to/SAMPLE_T.gridss.somatic.vcf.gz 

I provided name of list of tumor samples (with multiple -tumor [name]) and reference sample in the vcf file. However, the error message returned as below. I saw that it just processes for 1 tumor sample only rather multiple tumor samples. Can you please help to check what is the issue? And how I can handle it? I created PoN as instruction from GRIDSS.

10:22:25 - Config GripssFilterConfig(hardMinTumorQual=100, hardMaxNormalAbsoluteSupport=3, hardMaxNormalRelativeSupport=0.06, softMaxNormalRelativeSupport=0.03, minNormalCoverage=8, minTumorAF=0.005, maxShortStrandBias=0.95, minQualBreakEnd=1000, minQualBreakPoint=400, minQualRescueMobileElementInsertion=1000, maxHomLengthShortInversion=6, maxInexactHomLengthShortDel=5, minLength=32, polyGCRegion=2:32916190-32916630	+	.)
10:22:25 - Using H033_BDNA3684 as reference sample
10:22:25 - Using H033_pOvaR_DNA1 as tumor sample
10:22:25 - Reading hotspot file: /mnt/storageBig8/work/nguyenma/SV/PoN/known_fusion_data.hg38.csv
10:22:25 - Finished in 0 seconds
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:4817)
	at com.hartwig.hmftools.bedpe.Breakpoint$Companion.fromBedpe(Location.kt:60)
	at com.hartwig.hmftools.bedpe.Breakpoint$Companion.fromBedpeFile(Location.kt:56)
	at com.hartwig.hmftools.gripss.GripssApplication.run(GripssApplication.kt:90)
	at com.hartwig.hmftools.gripss.GripssApplicationKt.main(GripssApplication.kt:42)

**Comment by jonbaber** [comment]
Can you please double check your hotspot file is in the exact same format as the expected KnownFusionPairs.bedpe.

The filename that you have provided ends with csv but we are expecting a bedpe file.

**Comment by maingoc303** [comment]
Thanks so much for your reply. I downloaded KnownFusionGene.csv from your resource, I have just tried to separate that csv file to tab delimiter then save as bedpe format. Do you have the instruction for how column in that hotpot should be? As error message still returned. I also tried remove the header of the file then run again but similar error message.

09:48:44 - Config GripssFilterConfig(hardMinTumorQual=100, hardMaxNormalAbsoluteSupport=3, hardMaxNormalRelativeSupport=0.06, softMaxNormalRelativeSupport=0.03, minNormalCoverage=8, minTumorAF=0.005, maxShortStrandBias=0.95, minQualBreakEnd=1000, minQualBreakPoint=400, minQualRescueMobileElementInsertion=1000, maxHomLengthShortInversion=6, maxInexactHomLengthShortDel=5, minLength=32, polyGCRegion=2:32916190-32916630	+	.)
09:48:44 - Using H033_BDNA3684 as reference sample
09:48:44 - Using H033_pOvaR_DNA1 as tumor sample
09:48:44 - Reading hotspot file: /mnt/storageBig8/work/nguyenma/SV/PoN/known_fusion_data.hg38.bedpe
09:48:44 - Finished in 0 seconds
Exception in thread "main" java.lang.NumberFormatException: For input string: "FiveGene"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.hartwig.hmftools.bedpe.Breakpoint$Companion.fromBedpe(Location.kt:61)
	at com.hartwig.hmftools.bedpe.Breakpoint$Companion.fromBedpeFile(Location.kt:56)
	at com.hartwig.hmftools.gripss.GripssApplication.run(GripssApplication.kt:90)
	at com.hartwig.hmftools.gripss.GripssApplicationKt.main(GripssApplication.kt:42)

**Comment by jonbaber** [comment]
Perhaps you have downloaded the wrong file. If you go to our [resources page](https://resources.hartwigmedicalfoundation.nl/) then click on HMFTools-Resources > GRIDSS you should be able to download the bedpe file.

![image](https://user-images.githubusercontent.com/27909546/106716748-87fc3d00-664a-11eb-9960-2de7b44561a3.png)

**Comment by maingoc303** [comment]
Thank you so much. It works now. I would like to ask one more question. As in output from GRIDSS, there are multiple tumor samples, in the command, I put multiple "-tumor [tumor names]" but it seems that command just use the 1st tumor provided. How can I process for all tumor samples simultaneously?

**Comment by jonbaber** [comment]
GRIPSS is designed to run on a single tumor only. There are no current plans to support running multiple tumors simultaneously. You will need to run GRIPSS on each tumor individually and then merge the results.

**Comment by DarioS** [comment]
Are your patients Dutch people? It might not be particularly useful to use that panel of normals if your samples are all of a different ancestry. If you're filtering somatic variants, you could make your own panel of normals. If you want to filter germline variants, then you would need a large set of samples of matching ancestry proportions, which are not part of your project. Something like gnomAD-SV but also processed by GRIDSS in the same way. Gene fusions have nothing to do with a panel of normals, which is why the file looks nothing like what is expected for a panel of normals.

**Comment by maingoc303** [comment]
Hi, I do not run for Dutch samples, I created my own PoN already (as instructed in GRIDSS).

**Comment by maingoc303** [comment]
> GRIPSS is designed to run on a single tumor only. There are no current plans to support running multiple tumors simultaneously. You will need to run GRIPSS on each tumor individually and then merge the results.

Thank you so much. I am going to do this.
