### ISSUE TITLE
Run multiple bam files in SAGE

### ISSUE THREAD

**Issue by maingoc303** [hartwigmedical/hmftools#154]
Dear Hartwig Medical,
I am running SAGE for mutation calling, as instructed, SAGE allows to run multiple bam files at a time, but when I provide multiple bam files (comma separated), result shows only first sample. No error or message.
Can you please check this?

**Comment by jonbaber** [comment]
Did you also provide multiple (comma seperated) tumor names?

**Comment by maingoc303** [comment]
Yes, I put a comma between sample names as well as bam files. I also tried to run just 2 samples but the result shows the 1st sample only.

**Comment by jonbaber** [comment]
Could you please provide the exact arguments you are using as well as a copy of the log output. Thanks.

**Comment by maingoc303** [comment]
Hi, my command is below. The command successfully processed and the output returned but only 1st sample.

java -Xms4G -Xmx32G -cp sage-2.6.jar com.hartwig.hmftools.sage.SageApplication -tumor H122_pOme, H122_pAsc -tumor_bam H122_pOme1.bam, H122_pAsc.bam -assembly hg38 -ref_genome GRCh38.d1.vd1.fa -panel_bed Targets.bed.gz -out H122_sage.vcf.gz

**Comment by jonbaber** [comment]
Try without any spaces in the argument, ie

<code>
 -tumor H122_pOme,H122_pAsc -tumor_bam H122_pOme1.bam,H122_pAsc.bam
</code>

**Comment by maingoc303** [comment]
Thank you so much, it works now.
