### ISSUE TITLE
Annotating Structural Variants by RNA-seq Evidence

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#156]
LINX's Version History has mention of "RNA fusion matching" but the user guide does not contain instructions about it. Is it possible to annotate some categories of structural variants with their split read and discordant pair RNA-seq support using LINX?

**Comment by p-priestley** [comment]
HI Dario,

This is a function we have used for our internal analysis of RNA called fusions vs LINX, not something we intend to support, sorry.   

LINX also does not talk to BAMS sat all, so cannot annotated SR and DP support.
