### ISSUE TITLE
<ID=TAF> description is missing in GRIPSS somatic filtered VCF 

### ISSUE THREAD

**Issue by hansolo-bioinfo** [hartwigmedical/hmftools#158]
Seems like this INFO is missing in terms of the description. Could you provide the exact definition of this tag?

##INFO=<ID=TAF,Number=1,Type=Float,Description="Description">

Thank you.

Han

**Comment by jonbaber** [comment]
Thanks for pointing out this oversight. 

Have changed to:

```
##INFO=<ID=TAF,Number=1,Type=Float,Description="Tumor allelic frequency (fragment support / total support)">
```
