### ISSUE TITLE
PURPLE circos: SNPs/Indels not shown genome-wide

### ISSUE THREAD

**Issue by pdiakumis** [hartwigmedical/hmftools#16]
Hi folks, 
I bumped PURPLE from 2.14 to 2.17 last week, so not sure if something's changed in the CircosSNP/IndelWriter scripts or somewhere else. We only get SNPs + Indels plotted for a single chromosome (see example below). I can only see that the transformPosition function's been refactored a bit, but my Java is very rusty. Both 2.15 and 2.17 give the same output.

```
$ grep -v "^#" purple_2.17/circos/tumor.snp.circos | cut -f1 | uniq -c
     28 hs21
$ grep -v "^#" purple_2.17/circos/tumor.indel.circos | cut -f1 | uniq -c
     4 hs21
```

Cheers - Peter

![screen shot 2018-11-12 at 11 45 09](https://user-images.githubusercontent.com/29562861/48320788-6bdae280-e671-11e8-98fe-cd2c5b37aace.png)

**Comment by pdiakumis** [comment]
Hmm, I'm puzzled now because it happens with v2.14 as well. But I just noticed that both VCFs that had issues were somewhat unsorted:

```
zcat P055-ensemble-annotated.vcf.gz | grep -v "^#" | cut -f1 | uniq -c
    127 21
      1 Y
    633 1
    734 2
    543 3
    724 4
    606 5
    505 6
    517 7
    492 8
    327 9
    246 10
    403 11
    382 12
    347 13
    261 14
    217 15
    233 16
    176 17
    261 18
    159 19
    170 20
     75 22
    784 X
```  

So it might be on our side.

**Comment by jonbaber** [comment]
Just did a quick check of the code and while we have always used sorted
VCFs I can't see where it really matters for the somatics. Maybe do a
similar command on the circos data files, ie
purple/circos/SAMPLE.snp.circos and see what comes out there.

If you get reasonable counts per chromosome but just out of order it might
actually be an issues for circos. Easy to fix if this is the case as I can
sort before writing.

**Comment by pdiakumis** [comment]
Thanks Jonathan, I wouldn't think sorting would matter either. I've included a summary of the contents from `circos/sample.snp.circos` in my first comment (I edited it soon after), and as you can see only 28 points are included, and those are from chr21. Weird. I can email you the VCF if you want to have a play, but I'm guessing it would reproduce with any unsorted VCF.

**Comment by jonbaber** [comment]
Took a more thorough look through PURPLE, and yes, there is an implicit dependency on sorted VCFs. Relatively easy to add support for the chromosomes to be unsorted if you like so long as within a chromosome it is sorted, but in the mean time I suggest you try sorting the VCFs first.

**Comment by pdiakumis** [comment]
Ah that's great that you got to the bottom of it then. No need to change requirements, VCFs _should_ be sorted anyhow, this one is on us.
Thanks again!

**Comment by jonbaber** [comment]
No worries :)
