### ISSUE TITLE
StructuralVariantFactory does not write VCF headers

### ISSUE THREAD

**Issue by d-cameron** [hartwigmedical/hmftools#160]
No headers are written for hmftools-specific VCF headers (it relies on implict header creation by htsjdk). This means users lack documentation/descriptions of PURPLE/LINX headers.

VCF headers should be explicitly defined, similarly to how they are defined in GRIDSS and htsjdk, and the relevant headers written to the VCF:

https://github.com/PapenfussLab/gridss/blob/master/src/main/java/au/edu/wehi/idsv/vcf/GridssVcfConstants.java

**Comment by p-priestley** [comment]
TAF description was fixed in GRIPSS v1.11

All PURPLE descriptions are already written correctly.
