### ISSUE TITLE
Arm Highlighting Appears to be Incorrect

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#163]
Looking at the plot below, and counting up the segments, they add up to about 59 million bases. That's the length of the short arm of chromsome 7. However, the ideogram track has a coloured border around both the p and q arms of chromosome 7.

![image](https://user-images.githubusercontent.com/631218/110722343-30af4500-8266-11eb-98ea-d9dce77826dd.png)

Should only the p arm be highlighted in the ideogram or should there be more numbers around the circle? Is 13.9 m extending to the end of the circle or only to the end of the p arm? Should I upgrade from version 1.11?

**Comment by p-priestley** [comment]
Looks like a bug.   will take a look

**Comment by jonbaber** [comment]
Hi Dario, 

Could you please email me the Linx file and the command used to generate this plot.

Thanks, Jonathan

**Comment by DarioS** [comment]
Command is

```
java -cp sv-linx_v1.11.jar com.hartwig.hmftools.linx.visualiser.SvVisualiser -sample OSCC_22-P -chromosome chr7 -gene_transcripts_dir . -plot_out ../EGFRs/ -data_out ../EGFRs/ -vis_file_dir . -circos /usr/bin/circos
```

[Files for testing](https://github.com/hartwigmedical/hmftools/files/6120322/test.gz)

**Comment by DarioS** [comment]
Now providing [input files](https://github.com/hartwigmedical/hmftools/files/6120390/test2.tar.gz)

**Comment by jonbaber** [comment]
Hi Dario, 

Quick update for you, the arm highlighting is actually correct. The problem is the missing copy number distance text (showed in the image below) and no position text along the outside. At 59M there is a (tiny) copy number change that is not visible on the plot. We do not put a position marker here because it does not have a corresponding SV. 

I am working on improving the distance text now. 

![OSCC_22-P chr7 001](https://user-images.githubusercontent.com/27909546/111411138-c2ff8f00-8725-11eb-949c-53756ec2a73b.png)

**Comment by DarioS** [comment]
Now that I look at more plots, I notice that the chromosome track is sometimes not plotted at all. Executing another plot for the matched primary sample of this cell line from the same folder automatically shows the ideogram.

```
java -cp sv-linx_v1.11.jar com.hartwig.hmftools.linx.visualiser.SvVisualiser -sample OSCC_16-CC_P -clusterId 117 gene_transcripts_dir . -plot_out ../EGFRs/ -data_out ../EGFRs/ -vis_file_dir . -circos /usr/bin/circos
```

Testing data in [missingIdeogram.tar.gz](https://github.com/hartwigmedical/hmftools/files/6175327/missingIdeogram.tar.gz)

![image](https://user-images.githubusercontent.com/631218/111867201-a2099900-89c6-11eb-8f60-f55427e5508b.png)

Why is it plotted for one plot but not the other?

**Comment by charlesshale** [comment]
I ran a similar visualiser call to the one above but for clusterId 117 and it shows the chromosomal graphic. What was then difference between these two plots above? Do they both use that same sample data you've attached? I'm trying to reproduce the issue.

**Comment by DarioS** [comment]
Yes, `-sample OSCC_16-CC_P` refers to the plot on right side missing the ideogram. Data for the left panel wasn't included. Today, the right plot has the ideogram shown, but there are black rectangles in the corners. Perhaps some recent server software upgrade.
![OSCC_16-CC_P cluster117 COMPLEX sv46 089](https://user-images.githubusercontent.com/631218/122657929-0b0dd200-d1ab-11eb-92e2-4c566c3b461b.png)

I will upgrade to LINX 1.16 next week.
