### ISSUE TITLE
Purple QC metrics with Illumina 1.5 chemistry

### ISSUE THREAD

**Issue by ohofmann** [hartwigmedical/hmftools#167]
We've done a few side-by-side comparisons of the Illumina 1.0 and 1.5 chemistry and found overall very little difference between the variant and SC call sets, but I've noticed QC flags (deleted_genes, among others) and purity / clonality estimates to differ on the Purple side. 

Is there anything in the Purple thresholds that might be more tailored towards the 1.0 chemistry? At a first glance I am seeing a slight shift in GC content of the reads (41% -> 40%) but I am not sure that's enough to explain. Just checking if this is something you've noticed / looked at, if not we'll generate more data.

**Comment by p-priestley** [comment]
We have not seen this and I don't think that PURPLE would be tailored.   I am just checking with our lab about the chemistry of our own samples and if and when that has changed.

I would be happy to comment on individual results if you would like to post here or mail to me directly.
