### ISSUE TITLE
BAF value and cellular fraction

### ISSUE THREAD

**Issue by lisemangiante** [hartwigmedical/hmftools#168]
Hi Hartwig Medical,
First, thank you for this very impressive tool! We are analysing the .purple.cnv.somatic.tsv and .purple.cnv.gene.tsv outputs and we were wondering if the BAF variable can be used and interpreted as the fraction of the tumour cells with the given copy number change?
Thank you in advance for your help.
Best,
Lise

**Comment by p-priestley** [comment]
Hi Lise,

the somatic TSV file has both the raw observed BAF in the sample and an adjusted BAF corrected for the purity of the sample.       The corrected number can be interpreted as the major allele copy number / total copy number for the tumor as a whole.    So for exmaple a BAF of 100% will indicate a LOH.  The minor and major allele copy number are also calculated explicitly for you in the same tsv output.   

The BAF is therefore NOT the fraction of tumor cells with the copy number change.   Most detectable copy number changes are clonal and will be present in every tumor cell but this won't give a 100% BAF unless an LOH has occurred.

Peter

**Comment by lisemangiante** [comment]
Hi Peter,
Thank you for these explanations! 
Best,
Lise
