### ISSUE TITLE
Question of the requirement of the vcf for GRIPSS

### ISSUE THREAD

**Issue by hsiaoyi0504** [hartwigmedical/hmftools#170]
In the GRIPSS page, it says
> Repeat masker and viral annotations must be included in the GRIDSS output before running GRIPSS. Details on how to include these are available on the GRIDSS readme here and here.

However, it seems to me that without annotating them, GRIPSS still could be run and finish. Does it mean that it's not the requirement anymore? Also, what will be the expected result without these two annotations? For example, what kinds of the filters will be omitted given the annotations are not available.

**Comment by jonbaber** [comment]
GRIPSS will run so long as BEALN, INSRMRC and INSRMRT are defined in the VCF header. They are still required but have little impact in GRIPSS. We have them as a requirement for our downstream analysis (eg LINX).
