### ISSUE TITLE
Preprocessing with Repeatmasker and VirusBreakEnd

### ISSUE THREAD

**Issue by orsolyasipos** [hartwigmedical/hmftools#172]
Hi, 

I was wondering if there is a recommended way to preprocess the input vcf for GRIPSS. The input for RepeatMasker is the GRIDSS vcf output file. The annotated vcf output of RepeatMasker is a straightforward input for GRIPSS, however, VirusBreakEnd input is the BAM file and the output is another vcf. 

Does this mean that the two output vcfs, one from RepeatMasker and one from VirusBreakEnd, need to be merged before applying GRIPSS?

Many thanks!

**Comment by DarioS** [comment]
It's confusing. There is another approach to annotate viruses using `gridss_annotate_vcf_kraken2.sh` which uses a VCF file as input. VIRUSBreakend is designed as a standalone tool to be used independently of structural variant calling.

**Comment by orsolyasipos** [comment]
Thanks very much for the clarification!
