### ISSUE TITLE
wholeGenomeDuplication from FALSE in PURPLE v2.36 to TRUE in v2.50?

### ISSUE THREAD

**Issue by ellchua** [hartwigmedical/hmftools#173]
Hi, 

I used PURPLE v2.36 a while back and for a particular sample got these results in the `purity.tsv` file:
```r
purity	normFactor	score	diploidProportion	ploidy	gender	status	polyclonalProportion	minPurity	maxPurity	minPloidy	maxPloidy	minDiploidProportion	maxDiploidProportion	version	somaticPenalty	wholeGenomeDuplication	msIndelsPerMb	msStatus	tml	tmlStatus	tmbPerMb	tmbStatus
0.3800	1.0000	0.4059	0.6242	1.9400	FEMALE	NORMAL	0.1029	0.3300	0.6800	1.8940	3.9395	0.0000	0.6343	2.39	0.0000	false	0.0	UNKNOWN	0.0	UNKNOWN	0.0	UNKNOWN
```

However, when I used PURPLE v2.50 more recently for the same sample, these were the results:
```r
purity	normFactor	score	diploidProportion	ploidy	gender	status	polyclonalProportion	minPurity	maxPurity	minPloidy	maxPloidy	minDiploidProportion	maxDiploidProportion	version	somaticPenalty	wholeGenomeDuplication	msIndelsPerMb	msStatus	tml	tmlStatus	tmbPerMb	tmbStatus	svTumorMutationalBurden
0.6200	0.6204	0.3716	0.0000	3.9000	FEMALE	NORMAL	0.1450	0.5300	1.0000	1.9200	3.9500	0.0000	0.6954	2.52	0.0004	true	0.2137110877929346	MSS	0	LOW	2.639734172787688	LOW	759
```

Specifically, note `wholeGenomeDuplication` going from FALSE to TRUE. 

This is a pretty substantial change, so I'm trying to understand what has changed in PURPLE that would affect these results so drastically?

**Comment by p-priestley** [comment]
It is difficult to distinguish between solutions which have WGD versus samples which may have subclonal copy number events with 50% cellular fraction, so this sample is likely borderline between these cases.   In both versions above, I see that PURPLE
give the minPloidy of 1.9 and max ploidy of 3.9, indicating the WGD may be uncertain, but in the end PURPLE chooses what it deems to be the best solution.

Small changes to the fitting algorithm were made in v2.41 and v2.48.   we have tested these on our full cohort and found these to give small improvements overall, but it is difficult to gaurentee on every sample.    The QC plots may give insight into which fit is better.

**Comment by ellchua** [comment]
By QC plots, do you mean the `purity.range.png` file? The documentation for this plot indicates that "Other viable solutions are shown in blue", so for this specific sample, how do you tell which fit is better?
![FR_14_010_Tumor purity range](https://user-images.githubusercontent.com/18107708/113828616-2fb2fa00-97b7-11eb-82f5-2b435190b76e.png)

**Comment by p-priestley** [comment]
Hi Ellora,   This is showing that there are indeed 2 good solutions.   It is difficult to say much from this figure alone.  If you could also attach the somatic.png, map.png and copynumber.png then I could give some insight.

**Comment by ellchua** [comment]
Hello, here are the plots: 

![FR_14_010_Tumor somatic](https://user-images.githubusercontent.com/18107708/113960134-920f0780-9856-11eb-8656-62ff20c71098.png)
![FR_14_010_Tumor map](https://user-images.githubusercontent.com/18107708/113960142-94716180-9856-11eb-99b7-2c7d15d4a344.png)
![FR_14_010_Tumor copynumber](https://user-images.githubusercontent.com/18107708/113960147-96d3bb80-9856-11eb-94af-d33b0a09dee9.png)

**Comment by p-priestley** [comment]
It looks quite likely to me that  WGD may have occurred.   Some indications:
* The minor allele copy number of 1 & major allele 3 are very close to integer values
* There appears to be a peak in the somatic copy number at variant copy number = 1.  

An alternative explanation still could be that there is a subclone  of ~50% is present, but on the basis of these charts alone I think WGD is more likely.

**Comment by ellchua** [comment]
May I ask what are the significance of those two indications? What are they saying?

**Comment by p-priestley** [comment]
Sorry I am not sure I understand the question.  Could you be more precise?

**Comment by ellchua** [comment]
What does it mean/why does it matter that the minor allele copy number & major allele are very close to integer values? Same for the second indication, what does it mean/why does it matter that there is a peak in the somatic copy number at variant copy number = 1? How to interpret those indications biologically in deciding that WGD has (more likely) occurred?

**Comment by p-priestley** [comment]
Clonal mutations should have integer counts.    Hence if a WGD hypothesis leads to an integer peak in somatic variant copy number (which was otherwise a subclonal peak in the non WGD hypothesis)   then that makes the WGD hypothesis more plausible.
