### ISSUE TITLE
FAIL_SEGMENT Downgrade to Copy Number Noise Warning Not Documented

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#174]
We have been excluding samples from all analyses in our project based on FAIL_SEGMENT but that appears to have been converted to a warning in a recent version of PURPLE. I am using version 2.47. Could important changes like this appear with certainty in the news list? I only noticed this by chance and am wondering about returning the samples which have FAIL_SEGMENT into the project. It's unclear how much effect this issue has on PURPLE_VCN estimates and copy number segmentation in general.

**Comment by p-priestley** [comment]
Hi Dario,

Thanks for the feedback.   This change occurred in v2.48, and was mentioned in the release notes but only as "QC Status improvements" which is obviously not meaningful.   We made this change to professionalise further the QC STATUS as we found in the majority of FAIL cases, that despite DNA damage, we were still able to report a meaningful result.

The documentation was updated concurrently to the change, and the current rules can be seen here.

https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#9-determine-a-qc-status-for-the-tumor

The QC status does not affect PURPLE_VCN or copy number segmentation.   It does have an impact on amplifications and deletions reported in the driver catalog as documented here.

https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#12-driver-catalog

We will try to be more verbose with changes in the future.

Peter
