### ISSUE TITLE
known_fusions.38_v3.bedpe file for GRIPSS includes chrNA and NA for start and end positions

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#175]
Just tried running GRIPSS 1.11 with updated "38" resource files.
The known_fusions.38_v3.bedpe has a number of rows with chrNA and also NA for position values, which probably are not the expected values.

**Comment by charlesshale** [comment]
Fixed. Some of the gene names changed between 37 and 38 and were not looking up their coordinates correctly.

Will update HMF resources shortly. In the meantime I've attached the new 38 BEDPE file
[known_fusions.38_v3.bedpe.txt](https://github.com/hartwigmedical/hmftools/files/6332403/known_fusions.38_v3.bedpe.txt)

(remove the .txt extension to use it)
