### ISSUE TITLE
coverage bed in provided resources is not a subset of actionable coding panel

### ISSUE THREAD

**Issue by DavyCats** [hartwigmedical/hmftools#176]
When running SAGE (2.6 or 2.7) in panel only mode using the CoverageCodingPanel.germline.37.bed.gz and ActionableCodingPanel.germline.37.bed.gz files (provided through https://nextcloud.hartwigmedicalfoundation.nl), I get an error saying: "Coverage bed must be a subset of panel bed when running in panel only mode". The coverage bed file does indeed appear to contain more regions that the panel bed. Are these the same files as used by pipeline5?

In case it might help, here is the full command I'm using (based on [this class from pipeline5](https://github.com/hartwigmedical/pipeline5/blob/master/cluster/src/main/java/com/hartwig/pipeline/calling/sage/SageGermlineCaller.java)):
```
SAGE -Xmx50G -XX:ParallelGCThreads=1 \
-tumor COLO829v003R \
-tumor_bam COLO829v003R.markdup.bam \
-reference COLO829v003T \
-reference_bam COLO829v003T.markdup.bam \
-ref_genome Homo_sapiens.GRCh37.GATK.illumina.fasta \
-hotspots KnownHotspots.germline.37.vcf.gz \
-panel_bed ActionableCodingPanel.germline.37.bed.gz \
-high_confidence_bed NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed.gz \
-assembly hg19 \
-hotspot_min_tumor_qual 50 \
-panel_min_tumor_qual 75 \
-hotspot_max_germline_vaf 100 \
-hotspot_max_germline_rel_raw_base_qual 100 \
-panel_max_germline_vaf 100 \
-panel_max_germline_rel_raw_base_qual 100 \
-mnv_filter_enabled false \
-coverage_bed CoverageCodingPanel.germline.37.bed.gz \
-panel_only \
-threads 2 \
-out germlineSage.vcf.gz
```

**Comment by kduyvesteyn** [comment]
Apologies, the actionable panel on https://resources.hartwigmedicalfoundation.nl was indeed out-of-date. I've simply refreshed all SAGE files (in separate 37/38 folders) and also added our copy of clinvar db. If this still doesn't work let me know!

**Comment by DavyCats** [comment]
Thanks! It's working now
