### ISSUE TITLE
PURPLE's Circos Plots Different Appearance if SVG Format

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#177]
The SVG files have a much darker track background than PNG files. Could it be the same transparency level by default? SVG format is also entirely missing the structural variants inside the white circle.

![image](https://user-images.githubusercontent.com/631218/115490172-e2e41e80-a2a0-11eb-8df5-e48bcebeb2ef.png)

**Comment by p-priestley** [comment]
Hi Dario - we only support PNG format for now sorry.
