### ISSUE TITLE
Create PoN with SAGE

### ISSUE THREAD

**Issue by maingoc303** [hartwigmedical/hmftools#178]
Dear Hartwigmedical,
I would like to ask you how can I create PoN with Sage, as from the README file, I created PoN by running SAGE with all normal samples, however, I don't see the parameter PON_COUNT/PON_MAX in the output.
Can you please help to check with this function?
Thank you and best regards,

**Comment by p-priestley** [comment]
Hello.

We provide PON resources files based on our own cohort:  https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC

We have an application we use internally to build this (but have not released externally), bur it requires Sage to be first run in a highly sensitive PON mode.  

The PON annotation is a post process so you can do this with your own PON in any way you like.   The following part of the readme describes how to annotate Sage output with our PON file:  
 https://github.com/hartwigmedical/hmftools/tree/master/sage#pon-filtering
