### ISSUE TITLE
classes com.hartwig.hmftools.strelka.mnv.ImmutableMNVMerger; com.hartwig.hmftools.strelka.mnv.ImmutableMNVValidator are not in the source codes

### ISSUE THREAD

**Issue by LeaveYeah** [hartwigmedical/hmftools#18]
Hi, I am trying to use strelka-post-process in my pipeline. But I find the two classes imported in StrelkaPostProcessApplication.java, 
com.hartwig.hmftools.strelka.mnv.ImmutableMNVMerger;
com.hartwig.hmftools.strelka.mnv.ImmutableMNVValidator;
can not be found. Could you help resolve this problem? Thank you very much.

**Comment by kduyvesteyn** [comment]
These classes are auto-generated when you build using maven, so should be there.

You could also grab our latest official release from https://resources.hartwigmedicalfoundation.nl (folder HMFTools-Jars).

**Comment by LeaveYeah** [comment]
Many thanks. But it seems the file hmftools_pipeline_v4_3.zip exceeds the download limit of the website. I am not able to download it. Would you mind releasing the limit of size?

**Comment by kduyvesteyn** [comment]
This must be a limitation on your end. This works fine for me, plus we use the same system to transfer files up to 100s of GBs

**Comment by LeaveYeah** [comment]
Thank you very much!
One more question, according to the methodology part of the paper _Pan-cancer whole genome analyses of metastatic solid tumors_ ,  known pathogenic
variants and PON data are used to preserve and filter the variants. But I see the package strelka-post-process jar file do not require input of these files. So are these steps included in the package? 
Thank you very much

**Comment by kduyvesteyn** [comment]
Most of the annotation steps (hotspots, mappability, PON) are fairly generic so assume they'd work on any VCF. 

StrelkaPostProcess has some dependencies on the VCF itself, it expects the following fields:
 - QCC_NT
 - QSI_NT
 - TQSS_NT
 - TQSI_NT
 - TIR
 - TAR

If strelka2 has these fields, with the same meaning as strelka1, then it may work.

We never tested though!

**Comment by LeaveYeah** [comment]
Great! Thank you very much!
