### ISSUE TITLE
GRIPSS input without viral annotation

### ISSUE THREAD

**Issue by orsolyasipos** [hartwigmedical/hmftools#180]
Hi, 

I was wondering if it is possible to run GRIPSS without repeat masker and viral annotations?

Many thanks,
Orsolya

**Comment by p-priestley** [comment]
Please see:

https://github.com/hartwigmedical/hmftools/issues/170

**Comment by orsolyasipos** [comment]
I am really sorry for the redundant question, thank you very much!
