### ISSUE TITLE
Linx: gene plotting?

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#181]
When are genes supposed to appear on a circos plot?  Even for genes that appear in the linx 1.15 **.linx.driver.catalog.tsv file, and which fall completely within the genome coordinates shown in the plot, they are not appearing.  Also, should genes be expected to appear if they fall within an event labelled by Purple as a driver, but that do not appear in the **.linx.driver.catalog.tsv file?  Also, I was able to force a gene to plot using the "gene" argument, but then the gene name labels did not appear, and while the exons did appear, the overlap of exons with the breakpoints of the structural variant did not seem to agree with those in the linx tabular output.

**Comment by charlesshale** [comment]
Genes appear on the Circos plots if they identified as being impacted by a driver AMP or DEL, matching a pseudogene, or in a fusion. Their transcript & exon data is then written to the file *linx.vis_gene_exon.tsv and used in the Circos plot.

I've attached an example of a PTEN deletion from COLO829.

![COLO829T cluster67 DEL sv1 debug 003](https://user-images.githubusercontent.com/10849511/117075953-01eeb000-ad79-11eb-9f6c-816efb2addbe.png)

**Comment by charlesshale** [comment]
Our pre-print of Linx has the COLO829 output files. Github doesn't allow TSVs to be uploaded from what I can tell. The command used to plot this cluster is:

java -cp sv-linx.jar com.hartwig.hmftools.linx.visualiser.SvVisualiser -sample COLO8329T -plot_out ./vis/ -data_out ./plot_data/ -vis_file_dir /path_to_linx_files/ -circos /path_to_circos_bin/ -clusterId 67

**Comment by toddajohnson** [comment]
Hi Charles,
Thank you for the response and sorry for the late reply since I was on vacation last week.

If I understand above and the README, LINX only labels genes reported as AMP (GAIN) or DEL if a breakend lies within an exon or an intron, or if the end of the gene is within 100kb of the breakend.  What about SVs that completely encompass a driver gene (reported by PURPLE) but are farther from the SV breakend than 100kb? For our data, PURPLE reported a number of driver genes and SV events that fall into that situation, but It seems no visualization from PURPLE or LINX would label them in a figure.

To note, I first ran GRIDSS-2.11.1, GRIPSS-1.11, AMBER 3.5, COBALT 1.11, PURPLE 2.54, and LINX 1.15 and then created plots against the LINX directory using:
`java -cp ${linx_jar} com.hartwig.hmftools.linx.visualiser.SvVisualiser \
	-sample ${tumour_sample} \
	-gene_transcripts_dir ${ensembl_data_dir} \
	-plot_out $run_dir/linx/$tumour_sample/plot/ \
	-data_out $run_dir/linx/$tumour_sample/circos/ \
	-vis_file_dir $run_dir/linx/$tumour_sample \
	-circos circos \
	-threads $threads`

For subsequent manual creation I ran either per clusterId:
`java -cp $LINX_JAR com.hartwig.hmftools.linx.visualiser.SvVisualiser \
		-sample $tumour_sample \
		-gene_transcripts_dir ${ensembl_data_dir} \
		-plot_out $plot_out \
		-data_out $data_out \
		-vis_file_dir $run_dir/linx/$tumour_sample \
		-clusterId ${clusterID} \
		-gene ${genelist} \
		-circos circos \
		-threads $threads`

or per chromosome:
`	java -cp $LINX_JAR com.hartwig.hmftools.linx.visualiser.SvVisualiser \
		-sample $tumour_sample \
		-gene_transcripts_dir ${ensembl_data_dir} \
		-plot_out $plot_out \
		-data_out $data_out \
		-vis_file_dir $run_dir/linx/$tumour_sample \
		-chromosome ${chromosome} \
		-gene ${genelist} \
		-circos circos \
		-threads $threads`

 In the following chromosome plot, passing -gene CDKN2A created a plot, but with no gene model (empty gene.circos file); CDKN2A should be in the region with LOH and highest CN loss between 21.2m-22.3M.   I may have missed it, but is it not possible to place a gene on a -chromosome created plot?.  I imagine the gene model would have to be tiny, but perhaps just showing a bar and a label?
![Example1 chr9 007](https://user-images.githubusercontent.com/17885404/117641245-e6dccf80-b1c0-11eb-9a9f-c33ace5ad010.png)

The corresponding per clusterId plot had a fatal error starting with "Circos::Error::fatal_error("data", "repeated_chr_in_karyotype", "hs9")", which appeared to be because two rows of coordinates for chr9 were present in the the karyotype.circos file.  Assuming the row with higher value range was correct, I deleted the other one and reran the commands from the png.error file. The gene model was included in the plot, but the chr9 position labels do not seem to agree with exon positions (21.2m should not be between any exons in CDKN2A gene models), and no gene label was included; I am guessing because the end of exon4 is placed right at the boundary of the SV.  I assume deleting the line in karyotype.circos was not the most error-proof way of solving this issue....
![Example1 cluster3 DEL sv1 003](https://user-images.githubusercontent.com/17885404/117641264-eb08ed00-b1c0-11eb-8f43-a69a76859a2d.png)

Thank you for your kind help!
Todd

**Comment by charlesshale** [comment]
Hi Todd,

Just to reply on the first point, need more time to look over the Circos issues.

Linx will look for any SV which may have caused a Purple driver DEL or AMP, not matter how far away it is. I wonder if you're looking at this section of the readme for the 100K limit you've referred to:

Annotation of breakends with potential gene impact

For each breakend we search for genes that could be potentially disrupted or fused by the structural variant. To do this we find and annotate the breakend for any transcript that either:

Has an exon or intron overlapping the breakend
Has its 5’ end downstream of and facing the breakend and less than 100k bases where no other splice acceptor exists closer to the breakend.

- it only relates to upstream upstream fusion breakends.

Are you able to send me the SV VCF and purple files you're running with, and the command you've used? Then I can debug the driver-annotation and plotting more easily. 
***@***.***

thanks,

Charles

**Comment by toddajohnson** [comment]
Hi Charles,
I will talk with my team leader tomorrow and check that sending an SV vcf and purple files is OK.
I think replies to this post will be public and Github anonymized your real e-mail address, so I just sent a connect request and my e-mail address on LinkedIn so we can set up a file exchange more privately.

Best wishes,
Todd

From: charlesshale ***@***.***>
Reply-To: hartwigmedical/hmftools ***@***.***>
Date: Tuesday, May 11, 2021 at 6:53 PM
To: hartwigmedical/hmftools ***@***.***>
Cc: "Todd A. Johnson" ***@***.***>, Author ***@***.***>
Subject: Re: [hartwigmedical/hmftools] Linx: gene plotting? (#181)

Hi Todd,

Just to reply on the first point, need more time to look over the Circos issues.

Linx will look for any SV which may have caused a Purple driver DEL or AMP, not matter how far away it is. I wonder if you're looking at this section of the readme for the 100K limit you've referred to:

Annotation of breakends with potential gene impact

For each breakend we search for genes that could be potentially disrupted or fused by the structural variant. To do this we find and annotate the breakend for any transcript that either:

Has an exon or intron overlapping the breakend
Has its 5’ end downstream of and facing the breakend and less than 100k bases where no other splice acceptor exists closer to the breakend.

- it only relates to upstream upstream fusion breakends.

Are you able to send me the SV VCF and purple files you're running with, and the command you've used? Then I can debug the driver-annotation and plotting more easily.
***@***.***

thanks,

Charles

**Comment by toddajohnson** [comment]
Hi Charles,
I have a tar gzipped file of data from a couple of our tumors that I can share once we connect

privately.

Also, I ran linx with log_verbose and log_debug against your COLO829v003T sample from biorxiv as well as the two samples that I prepared.  For COLO829v003T, linx reports drivers in driver.tsv that have clusterIds, but for my two samples, the clusterId is set to -1.  In looking through the verbose/debug logs, near the end it reports for those AMP events that “AMP gain no event found”, although in looking at the plots, gene coordinates, and link.vis_sv_data.tsv files, it seems like they overlap an SV event or cluster of events.

Also, I noticed in comparing the top of the logs that while linx for the HG37 mapped COLO829v003T reports “loaded 2882843 replication origins”, that for my HG38 mapped files it reports “loaded 0 replication origins” since the heli_rep_origins.bed file for HG38 on the HMF file server is empty.  As that input appears to be involved in breakend annotation by linx, could that be a problem?

Best wishes,
Todd

From: charlesshale ***@***.***>
Reply-To: hartwigmedical/hmftools ***@***.***>
Date: Tuesday, May 11, 2021 at 6:53 PM
To: hartwigmedical/hmftools ***@***.***>
Cc: "Todd A. Johnson" ***@***.***>, Author ***@***.***>
Subject: Re: [hartwigmedical/hmftools] Linx: gene plotting? (#181)

Hi Todd,

Just to reply on the first point, need more time to look over the Circos issues.

Linx will look for any SV which may have caused a Purple driver DEL or AMP, not matter how far away it is. I wonder if you're looking at this section of the readme for the 100K limit you've referred to:

Annotation of breakends with potential gene impact

For each breakend we search for genes that could be potentially disrupted or fused by the structural variant. To do this we find and annotate the breakend for any transcript that either:

Has an exon or intron overlapping the breakend
Has its 5’ end downstream of and facing the breakend and less than 100k bases where no other splice acceptor exists closer to the breakend.

- it only relates to upstream upstream fusion breakends.

Are you able to send me the SV VCF and purple files you're running with, and the command you've used? Then I can debug the driver-annotation and plotting more easily.
***@***.***

thanks,

Charles

**Comment by lkhilton** [comment]
I'd like to chime in here and suggest a simple fix to this problem that I think would help a lot. 

The file `tumour.linx.svs.tsv` already has a column with a comma-separated list of genes that are near the events shown in a cluster. I've written my own hacky bash for loop to parse that column and ask Linx to re-plot each cluster while specifying the genes with the `-genes` argument. Would it be possible to add an option to the SvVisualizer tool to plot all genes identified within a cluster regardless of driver status? 

We work in B-cell lymphomas and we're interested in structural variants that place oncogenes near enhancers, and since these don't create in-frame fusions these never get annotated as drivers using the hmftools logic. In addition the hmftools pipeline does a really nice job of identifying structural variants on the immunoglobulin loci where they get rearranged and we would really love it if the Linx plots annotated the IG genes in those clusters. Here's a good example from one of our tumours: 
```
gridss230fb_598o        316     356     PROXIMITY-315   false   false   false   NONE    NONE    0.8436  1.3502  IGHJ5;IGHJ4     IGHD3-10;IGHD3-9;IGHD2-8;IGHD1-7;IGHD6-6;IGHD5-5;IGHD4-4;IGHD3-3;FAM30A    0.0000  0.0000  0       1       SAME_ORIENT     ISOLATED_BE     4       0
```

**Comment by charlesshale** [comment]
Yes I will add that in the next version, 1.16 due out soon. I'm looking into a couple of related issues at the same time.

thanks,

Charles

**Comment by toddajohnson** [comment]
Hi Charles,
I just found the problem that caused this issue for me.

At some point around the linx-1.14 update, -ref_genome argument was causing linx to crash, and I inadvertenly removed both -ref_genome and -ref_genome_version arguments from my scripts; since linx ran without warning, I did not realize that the final output was incorrect.  As a result, PURPLE driver genes were not getting labelled with an SV cluster, probably due to different chromosome labels in the reference genome (chrN labels) and the ensembl cache (no chr prefix), and then, no genes were getting plotted.

This was fixed by putting back -ref_genome_version HG38 as an argument during the main linx run.
Perhaps adding an explicit "HG38" example or statement about the necessity of passing it in the README would help avoid future mistakes.

**Comment by charlesshale** [comment]
Ok understood. I've added ref_genome_version to the Linx readme example command so it's clearer, thanks for the suggestion.

**Comment by charlesshale** [comment]
I have made a Linx 1.16 beta release:

https://github.com/hartwigmedical/hmftools/releases/tag/sv-linx-v1.16_beta <https://github.com/hartwigmedical/hmftools/releases/tag/sv-linx-v1.16_beta>

with which there is now the option of plotting the set of genes which the breakends in a cluster impact. Use the config option:

-plot_cluster_genes

in addition to usual Visualiser config. It requires the sample's data directory to be specified to find all Linx output files:

-vis_file_dir

as well as the specific cluster (by -clusterId).

**Comment by lkhilton** [comment]
Thank you, Charles!

**Comment by toddajohnson** [comment]
Thank you for making this addition.  It could be useful in certain
circumstances.
I reran sv-linx-v.16_beta against the HG38 based purple output for one
sample that had a couple of SV clusters that looked like plotting
additional genes might be informative, and then ran SvVisualizer for those
clusterIds either with or without -plot_cluster_genes.
Without -plot_cluster_genes, the Circos plot was produced (with the couple
of Linx identified driver genes), but with -plot_cluster_genes, the figure
was not made and *.png.error file had::

 at /yshare2/ZETTAI_path_WA_slash_home_KARA/home/tjohnson/tools/circos
-0.69-9/bin/../lib/Circos/Error.pm line 425, <F> line 2.

Circos::Error::fatal_error("data", "repeated_chr_in_karyotype", "hs1")
called at /yshare2/ZETTAI_path_WA_slash_home_KARA/home/tjohnson/tools/circos
-0.69-9/bin/../lib/Circos/Karyotype.pm line 165

Circos::Karyotype::read_karyotype_file("RK359_T.cluster100.COMPLEX.sv31.karyotype.circos",
HASH(0x4aae390)) called at /yshare2/ZETTAI_path_WA_slash_home_KARA/home/
tjohnson/tools/circos-0.69-9/bin/../lib/Circos/Karyotype.pm line 92

Circos::Karyotype::read_karyotype("file",
"RK359_T.cluster100.COMPLEX.sv31.karyotype.circos") called at
/yshare2/ZETTAI_path_WA_slash_home_KARA/home/tjohnson/tools/circos
-0.69-9/bin/../lib/Circos.pm line 218

Circos::run("Circos", "_argv", "-nosvg -conf /home/tjohnson
/workspace/scripts/check_linx/resu"..., "configfile",
"/home/tjohnson/workspace/scripts/check_linx/result/GRIDSS-2.1"...,
"_cwd", "/yshare2/ZETTAI_path_WA_slash_home_KARA/home/tjohnson/workspa"...,
"outputdir", ...) called at /home/tjohnson/tools/circos-0.69-9/bin/circos
line 536

The karyotype.circos file had multiple entries for each chromosome:

chr - hs1 1 1 398 chr1

chr - hs1 1 1 497 chr1

chr - hs4 4 1 398 chr4

chr - hs4 4 1 1464 chr4

chr - hs6 6 1 398 chr6

chr - hs6 6 1 1130 chr6

chr - hs10 10 1 1138 chr10

chr - hs10 10 1 2890 chr10

chr - hs13 13 1 398 chr13

chr - hs16 16 1 398 chr16

chr - hs16 16 1 942 chr16

chr - hs17 17 1 8778 chr17

chr - hs17 17 1 22459 chr17


Could this be related to what happens when running the main linx program
without -ref_genome_version HG38? I tried passing that, but it is not an
allowed argument for SvVisualizer.


Todd

**Comment by DarioS** [comment]
The Line Event section of the user guide shows a problem I previously reported. The segments are not joined and I have drawn a blue line to represent what I think is missing. Perhaps the lines are wrongly being drawn in the layer underneath the track background.

![image](https://user-images.githubusercontent.com/631218/120058051-3bba8a00-c08b-11eb-8e3e-f35c671c0899.png)

Also, where is the LINE1 retrotransposon? It is not clear from the graph how this relates to a LINE1 insertion.

**Comment by p-priestley** [comment]
Dario - I see this example is taken from here:  https://github.com/hartwigmedical/hmftools/blob/master/sv-linx/README_VIS.md#line-event

Here is a complete description of this picture from our LINX preprint:  "Complex LINE cluster in HMF002232B, a colorectal cancer. Overlapping segments from the LINE source element from chr 14:59.2M has been inserted in at least 20 independent locations scattered throughout the genome."

The features at 99.8M  and 56.2M are 2 insertion sites from separate insertions from the same source element in 14:59.2M.    There are special rules for chaining LINE clusters in LINX (https://github.com/hartwigmedical/hmftools/tree/master/sv-linx#special-considerations-for-line-clusters) and they are only chained at the source element site.

**Comment by charlesshale** [comment]
Todd you were correct - the Linx Visualiser needed to have the ref genome version specified when it was looking up gene information beyond what Linx had written out in the vis files. So when using the 'gene' or 'plot_cluster_genes' config options, the ref_genome_version V37 or V38 must also be supplied (although V37 is the default for now).

Will be part of the 1.16 release.
