### ISSUE TITLE
hg38 not handled in AMBER's bafSegmentation.R and COBALT's ratioSegmentation.R

### ISSUE THREAD

**Issue by nalcala** [hartwigmedical/hmftools#183]
Hi! First of all, thanks for the great tool, we are having a lot of fun analyzing the results. 

Upon looking into the code, I noticed that you are using the pcf function from the copynumber R package (for segmentation in amber at https://github.com/hartwigmedical/hmftools/blob/93ba2fac0ff249aefdb0dcb62f1e6499f321ce31/amber/src/main/resources/r/bafSegmentation.R#L16 and in cobalt at https://github.com/hartwigmedical/hmftools/blob/c2b94116ccb08605f8dcdaa95bb5721fd8f5fa7f/cobalt/src/main/resources/r/ratioSegmentation.R#L24); nevertheless, note that the assembly is assumed to be hg19 (there is an "assembly" argument to the function but you are not changing its value according to the database used, and they do not support hg38 anyway it seems). 

This probably has a limited effect but because the assembly is used for the pcf segmentation to get chromosome lengths and annotate arms, I think it could have a minor effect near telomeres/centromeres (e.g., force segment breaks at the position of centromeres in the wrong assembly), and preferably you would do your own annotation of arms depending on the assembly provided by the user, and provide a vector to pcf's "arms" argument.

Best,

Nicolas

**Comment by p-priestley** [comment]
Hi Nicolas,  

This is certainly something we were unaware of that this package has an assembly parameter so thanks very much for pointing it out.   

I am unsure at this stage what the assembly parameter affects in the copynumber package.    I just briefly inspected the output for 1 file and I noticed that the 'p' and 'q' arm annotations can be incorrect around the centromere.   We don't use this annotations at all in our downstream tools.   I also see checked a few q telomeres locations that differ significantly between hg19 and hg38 and it appears to behaving sensibly.     

In practice we have not noticed an issue in hg38 ourselves so I suspect it may be ok.    We will definitely get to the bottom of this. 

Thanks again.

**Comment by nalcala** [comment]
Great! Thanks for the quick answer. 

On our side, we noticed that copy number calls tend to be more variable (many small segments with large variations in estimated CN) around centromeres but this is probably a general feature of these regions (we have observed this with other callers) that have nothing to do with the pcf function.

Maybe you can even just shut down the whole usage of the assembly by considering everything as "p", since you do other annotations for centromeric regions and additional segmentation downstream.

Best

**Comment by charlesshale** [comment]
The assembly argument in that R pcf function is used to set the chomosomal arm, but this field is not then used downstream in Purple. So it is safe to continue using the library as-is.

**Comment by nalcala** [comment]
Thanks @charlesshale , but doesn't it also force the pcf function to have a breakpoint at the end of the chromosome arm, which breakpoint is then used downstream by Purple?
