### ISSUE TITLE
Resolved type is "LOW_VAF" by LINX.

### ISSUE THREAD

**Issue by hastj7373** [hartwigmedical/hmftools#185]
Dear Staff.

LINX annotated the event below as "LOW_VAF".
Could you please let me know why LINX annotated this event as "LOW_VAF"?
(I have been trying to rescue this event because this event seems like a real one)

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  PD37237
8       82781124        gridss147bb_3404o       G       [16:54341684[G  296     PASS    AS=1;ASC=1X7N1X31M;ASQ=108.71;ASRP=3;ASSR=8;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm147-66693,asm245-81989;BEIDH=0,32;BEIDL=119,0;BQ=0.00;BSC=0;BSCQ=0.00;BUM=0;BUMQ=0.00;BVF=0;CAS=0;CASQ=0.00;CIPOS=-4,4;CIRPOS=-4,4;CQ=296.00;EVENT=gridss147bb_3404;EVENTTYPE=BND;HOMLEN=8;HOMSEQ=GCATGGAG;IC=0;IHOMPOS=-4,4;IQ=0.00;LOCAL_LINKED_BY=.;MATEID=gridss147bb_3404h;MQ=59.70;MQN=54.00;MQX=60.00;PURPLE_AF=0.346,0.342;PURPLE_CN=1.99,2.03;PURPLE_CN_CHANGE=1,1;PURPLE_JCN=0.693;RAS=1;RASQ=63.52;REF=51;REFG=AGCTGGGCATGGAGGCACACG;REFPAIR=30;REMOTE_LINKED_BY=.;RP=4;RPQ=60.25;SB=0.6666667;SC=1X7N1X31M39D59M5D93M;SR=4;SRQ=63.52;SVTYPE=BND;TAF=0.5;VF=5      GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF   .:108.71:3:8:0:0.00:0:0.00:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:296.00:63.52:22:6:4:60.25:4:63.52:5
16      54341684        gridss147bb_3404h       A       [8:82781124[A   311.06  PASS    AS=1;ASC=1X118M;ASQ=63.52;ASRP=3;ASSR=8;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm147-66693,asm245-81989;BEIDH=119,0;BEIDL=0,32;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=16.03;BSC=1;BSCQ=16.03;BUM=0;BUMQ=0.00;BVF=0;CAS=0;CASQ=0.00;CIPOS=-4,4;CIRPOS=-4,4;CQ=296.00;EVENT=gridss147bb_3404;EVENTTYPE=BND;HOMLEN=8;HOMSEQ=CTCCATGC;IC=0;IHOMPOS=-4,4;IQ=0.00;LOCAL_LINKED_BY=.;MATEID=gridss147bb_3404o;MQ=59.73;MQN=54.00;MQX=60.00;PURPLE_AF=0.342,0.346;PURPLE_CN=2.03,1.99;PURPLE_CN_CHANGE=1,1;PURPLE_JCN=0.693;RAS=1;RASQ=108.71;REF=60;REFG=CCCTGTCTCCATGCTCCAAAG;REFPAIR=28;REMOTE_LINKED_BY=.;RP=5;RPQ=75.31;SB=0.30769232;SC=1X118M;SR=4;SRQ=63.52;SVTYPE=BND;TAF=0.5;VF=5    GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF   .:63.52:3:8:0:0.00:0:0.00:0.00:0:0:16.03:1:16.03:0:0.00:0:0.00:0:0.00:311.06:108.71:24:4:5:75.31:4:63.52:5

**Comment by p-priestley** [comment]
Filtering is described here:  https://github.com/hartwigmedical/hmftools/tree/master/sv-linx#artefact-filtering

The LOW_VAF filter applies in the following situation:

Isolated translocations and single breakends unsupported by copy number change at both breakends - These also common artefacts and similar to foldback inversions, we find an elevated rate of low junction copy number variant calls unsupported by copy number change indicating likely artefacts. We filter if both breakends of a translocation are > 5000 bases from another variant AND both breakends have copy number change <0.5 AND the insert sequence neither has a poly-A tail nor insertSequenceRepeatClass = ‘LINE/L1’ (which may indicate a Line insertion).
