### ISSUE TITLE
Smoothed Copy Number Segments File Availability

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#188]
I am aiming to plot the copy number profiles of pairs of samples in linear plots to compare how similar a cell line derived from a patient's tumour is to the tumour genome itself. I tried two different output files and both of them produce jagged segmentations. How do I obtain the coordinates and copy numbers of the segments shown in PURPLE's smooth Circos plots?

![image](https://user-images.githubusercontent.com/631218/121463599-b1144c00-c9f5-11eb-93b1-684adf0306e9.png)

[CopyNumberPlots](http://bioconductor.org/packages/release/bioc/html/CopyNumberPlots.html) doesn't produce nice plots like I thought it might.

**Comment by p-priestley** [comment]
Hi Dario,   

The PURPLE circos should identically match the purple.cnv.somatic.tsv file.    Do you have an example where your plotting does not match?   

The segment.tsv file is the raw unsmoothed output and is very noisy (as you can see from the top plot).   This is outputted simply to show the original segmentation used by PURPLE.

I haven't used CopyNumberPlots sorry

Peter

**Comment by DarioS** [comment]
Yes, you can see how jumpy 2p is in the above plot. It seems like that in the Somatic CNV file. But the Circos plot looks smooth.
 [test.zip](https://github.com/hartwigmedical/hmftools/files/6629023/test.zip)

**Comment by p-priestley** [comment]
I just replotted this myself and I do see the same issue.  I think most of it is just a resolution issue (the CIRCOS necessarily has to bucket the copy number regions), but I do see an issue in the CIRCOS plot at position ~137M where the copy number on circos spikes up but this is not in the raw data.    I think this is an actual bug with the plotting and will look into it tomorrow.    

I am not sure if this will address the resolution issue you are seeing though. The CIRCOS is meant to give a global perspective and the resolution is limited.   There is no more smoothing that can be be done on your data as from the somatic.tsv all the breakends are genuine and are supported by structural variants.     I am unclear why these structural variants are not displayed on your CIRCOS though.   Are you filtering these out somehow?

Here is my plot of chr2 which appears to match yours

![image](https://user-images.githubusercontent.com/18154939/121482088-2260f880-ca10-11eb-82bd-6dd2a9ef55dc.png)

**Comment by DarioS** [comment]
I do not do any smoothing of my own and I understand much of the difference would be due to resolution. Also, I notice that there are some copy segments 5 copies or more, but, in Circos plot, nothing above 4 copies is shown. Is it also squashing the copy number towards diploid somehow? I look forward to what you or Jon can find out today. It would be good to know if this also happens to the Hartwig Medical samples.

**Comment by p-priestley** [comment]
I spot checked about 25 samples and could not find a problem with the plotting.   The segments above 5 copies are all short so they may not survive the resolution, but the spike up in CN at 137M is definitely.   We still need to try and run it on our side with your tsv file to get to the bottom of it.

**Comment by DarioS** [comment]
It's hard to interpret the plot if every copy number change is plotted, shown below. I wonder what additional smoothing the Circos plots use. I'm trying to recreate the copy number track so I can compare between tumours, cell cultures and PDX models.

![OSCC_16](https://user-images.githubusercontent.com/631218/122007150-fde39280-cdfa-11eb-8447-a3cd10f44172.png)

**Comment by charlesshale** [comment]
HI Dario,

Could you provide all the files for this sample so I can run them through Purple to fix this issue.

thanks,

Charles

**Comment by p-priestley** [comment]
Another comment Dario:  I just compared the copy number for one of our samples between PURPLE output: [SampleId].purple.cnv.somatic.tsv  and the circos input:  [Sampleid].cnv.circos   I found the regions and copy numbers in them to be identical to 4 digit accuracy except for an offset of 2 (the convention we use in the plot).    

Perhaps you could do that also for your sample output?    If they are identical, then the problem is likely to be in CIRCOS.

**Comment by DarioS** [comment]
Sorry, I got confused about different versions of files with and without GRIDSS structural variants. Thanks for hint about checking PURPLE somatic CNV and Circos CNV files. I show the updated plot with lots of focal amplification and 2p chromothripsis.
![OSCC_16-CC_P circos](https://user-images.githubusercontent.com/631218/122322670-31442f80-cf69-11eb-823b-41d8323ffdd4.png)
