### ISSUE TITLE
Linx 1.16 plot_cluster_genes

### ISSUE THREAD

**Issue by lkhilton** [hartwigmedical/hmftools#189]
Hi @charlesshale, 

I've been testing out the latest release of Linx 1.16 (build date 2021-06-21) and I'm not finding that the `-plot_cluster_genes` functionality is working. For example, I have these events clustered together according to `linx.svs.tsv`, but the plot doesn't show any of the genes annotated for the cluster. 

```
vcfId	svId	clusterId	clusterReason	fragileSiteStart	fragileSiteEnd	isFoldback	lineTypeStart	lineTypeEnd	junctionCopyNumberMin	junctionCopyNumberMax	geneStart	geneEnd	replicationTimingStart	replicationTimingEnd	localTopologyIdStart	localTopologyIdEnd	localTopologyStart	localTopologyEnd	localTICountStart	localTICountEnd
gridss230fb_6162o	13	8	PROXIMITY-15	false	false	false	NONE	NONE	-0.2582	1.3710	IGHG3	IGHG3	0.0000	0.0000	0	0	ISOLATED_BE	ISOLATED_BE	1	1
gridss230fb_6228o	14	8	PROXIMITY-15	false	false	false	NONE	NONE	-0.0833	1.5246	AL122127.4	IGHM;hsa-mir-4539;AL122127.5;AL122127.2;hsa-mir-4538;AL122127.1;AL122127.4;hsa-mir-4537;AL122127.3	0.0000	0.0000	1	1	ISOLATED_BE	ISOLATED_BE	2	2
gridss230fb_6164o	15	8	PROXIMITY-13	false	false	false	NONE	NONE	-0.0169	1.6297	IGHG3	IGHM;hsa-mir-4539;AL122127.5;AL122127.2;hsa-mir-4538;AL122127.1;AL122127.4;hsa-mir-4537;AL122127.3	0.0000	0.0000	0	1	ISOLATED_BE	ISOLATED_BE	1	2
gridss230fb_6254o	16	8	PROXIMITY-17	false	false	false	NONE	NONE	0.2183	0.7215	IGHJ5;IGHJ4	IGHD5-18;IGHD4-17;IGHD3-16;IGHD2-15;IGHD1-14;IGHD6-13;IGHD5-12	0.0000	0.0000	1	2	ISOLATED_BE	ISOLATED_BE	2	0
gridss230fb_6253o	17	8	PROXIMITY-15	false	false	false	NONE	NONE	0.8510	1.3044	IGHJ5;IGHJ4	IGHV3-73	0.0000	0.0000	1	3	ISOLATED_BE	ISOLATED_BE	2	0
```

![image](https://user-images.githubusercontent.com/36017879/122987673-b3f83080-d355-11eb-83e0-f3252d204f54.png)

My Linx-Viz command is as follows: 
```
java -Xmx{params.jvmheap}m -cp {params.linx_jar} com.hartwig.hmftools.linx.visualiser.SvVisualiser 
            -sample {wildcards.tumour_id} 
            -gene_transcripts_dir {params.cache_subdir} 
            -plot_out {output.plots} 
            -data_out {output.data} 
            -segment `dirname {input.clusters}`/{wildcards.tumour_id}.linx.vis_segments.tsv 
            -link `dirname {input.clusters}`/{wildcards.tumour_id}.linx.vis_sv_data.tsv 
            -exon `dirname {input.clusters}`/{wildcards.tumour_id}.linx.vis_gene_exon.tsv 
            -cna `dirname {input.clusters}`/{wildcards.tumour_id}.linx.vis_copy_number.tsv 
            -protein_domain `dirname {input.clusters}`/{wildcards.tumour_id}.linx.vis_protein_domain.tsv 
            -fusion `dirname {input.clusters}`/{wildcards.tumour_id}.linx.fusions.tsv 
            -circos {params.circos} 
            -threads {threads} 
            -plot_cluster_genes
            {params.options}
            2>&1 | tee -a {log}
```

I can get the genes to appear when I plot only cluster 8 with the comma-separated list of genes specified. 

I would really appreciate any help you have to offer. 

Laura

**Comment by charlesshale** [comment]
Hi Laura,

Could you try using the 'vis_file_dir' parameter as the path to all Linx files, instead of specifying them one by one. This is required for the Visualiser to find the SvAnnotation file from which it can get clusterId and breakend gene data. With this parameter specified, you no longer need to include 'segment', 'link', 'exon', 'cna', 'protein_domain' or 'fusion' since it will pick those up automatically.

**Comment by lkhilton** [comment]
Thanks, Charles, I gave that a try but there are still no genes on my plots. I poked around in the source code for the SvVisualizer and I don't see any code related to -plot_cluster_genes, though I do see code for -plot_reportable there. (Not a Java expert so I may have mis-read this).

**Comment by charlesshale** [comment]
Hi Laura,

The code is in:

com.hartwig.hmftools.linx.visualiser/SampleData.java

From these COLO files:



Here is an example of usage and the plot for a cluster being produced:

-sample COLO829T -vis_file_dir ~/colo829_linx/ -circos /bin/circos-0.69-6/bin/circos -plot_out ~/vis/ -data_out ~/plot/ -gene_transcripts_dir ~/ensembl_hg37/-plot_cluster_genes -clusterId 67

Did you provide the config to the Ensembl data cache files? Sorry if that was missed from the example. It needs that to look at each gene's definitions.

thanks,

Charles

**Comment by charlesshale** [comment]
![COLO829T cluster67 DEL sv1 debug 003](https://user-images.githubusercontent.com/10849511/123181236-43295380-d4d0-11eb-9658-73ee50fe5d00.png)

**Comment by charlesshale** [comment]
Just realised I can't upload the COLO829 TSV files from Linx but email me directly if you'd like to try them out: 
c.shale@hartwigmedicalfoundation.nl

**Comment by lkhilton** [comment]
Hi Charles, I think I've misunderstood how that flag was meant to be used. It works to plot the genes in the linx.svs.tsv file when I specify a single cluster. It doesn't work however when I run it without specifying a cluster. Was that intended?

**Comment by charlesshale** [comment]
Yes that's how it is intended to work. Did you expect to plot any gene impacted by a breakend?

**Comment by lkhilton** [comment]
I thought I'd be able to run the SV Visualizer once per sample and have all genes annotated in the linx.svs.tsv file for each cluster that gets plotted, yes.

**Comment by DarioS** [comment]
I interpreted it the same as Laura.

**Comment by p-priestley** [comment]
Plan to leave this functionality as is for now
