### ISSUE TITLE
Issue with bafSegmentation.R

### ISSUE THREAD

**Issue by anitagh** [hartwigmedical/hmftools#191]
This is my first attempt at running girdss-purple-linux pipeline on a targeted dataset (instead of WGS). Amber generates an exception when the tumor-only vcf file is empty. I believe the issue is with bafSeqmentation.R. There is no check if the table is empty or not. 

Best

**Comment by p-priestley** [comment]
Hello.   

Sorry, our toolset only supports WGS at this time.
