### ISSUE TITLE
Potential correction for SAGE README

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#195]
In the SAGE README under "5. SoftFilters", shouldn't the cell in the Field column for the max_germline_vaf row
have Normal RC_CNT[0+1+2+3+4] / RC_CNT[6] rather than Normal RC_CNT[1+2+3+4] / RC_CNT[6]?  As written, it seems to be missing the FULL matches in the Normal sample.

**Comment by p-priestley** [comment]
fixed.  Thanks
