### ISSUE TITLE
Nonhuman species

### ISSUE THREAD

**Issue by xiaoyunguo** [hartwigmedical/hmftools#196]
Hi, 

I am using the somatic filtering function to filtering gridss output and working with non-human species. How do I generate the breakpoint_hotspot file?

Thanks

Xiaoyun

**Comment by p-priestley** [comment]
Hi Xiaoyun.

This is not something we have tried.   The hotspot file is just a list of paired breakend regions of known pathogenic fusions which we want to call with higher sensitivity.

I would recommend an empty file if you are looking at non-human data.

Peter
