### ISSUE TITLE
GRIPSS killed without a reason

### ISSUE THREAD

**Issue by pmcdil** [hartwigmedical/hmftools#197]
Hi, I am running this: 

`java -Xmx35G -cp gripss.jar com.hartwig.hmftools.gripss.GripssApplicationKt \
   -tumor SAMPLE_T \
   -ref_genome /path/to/Homo_sapiens_assembly.fasta \
   -breakend_pon /path/to/gridss_pon_single_breakend.bed \
   -breakpoint_pon /path/to/gridss_pon_breakpoint.bedpe \
   -breakpoint_hotspot /path/to/KnownFusionPairs.bedpe \
   -input_vcf /path/to/SAMPLE_T.gridss.unfiltered.vcf.gz \
   -output_vcf /path/to/SAMPLE_T.gridss.somatic.vcf.gz `

and my process is being killed in  "Reading VCF file" step without an error message. Could you help me to understand why?

Thanks!

**Comment by p-priestley** [comment]
Sorry that this issue has been missed.   Can you please confirm whether you still have an issue here?

**Comment by charlesshale** [comment]
Can I suggest upgraded to the latest Gripss here:

https://github.com/hartwigmedical/hmftools/blob/master/gripss/README.md

and

https://github.com/hartwigmedical/hmftools/releases/tag/gripss-v2.0_beta

It has clearer error handling.

**Comment by pmcdil** [comment]
Thank you very much for response. By that time, it didn't work and I stopped using it. Now I am planning another WGS analysis and I will try this tool again with upgraded version of Gripps. Thank you!
