### ISSUE TITLE
Binary/JAR releases?

### ISSUE THREAD

**Issue by brainstorm** [hartwigmedical/hmftools#2]
Thanks for producing BPI-inspector, we are using it actively @UMCCR.

To ease deployment of BPI in our pipelines, have you considered shipping the pre-compiled (with dependencies) JAR in your release process?

That would be very helpful to automate shipping and usage of new releases in our pipes.

/cc @pdiakumis, @vladsaveliev

**Comment by binaryminary** [comment]
Hi @brainstorm, while internally all these tools are used in our production analysis and reporting pipeline, it is clear that we do need to spend a little bit of time on "productising" them for wider use outside of HMF. Certainly, providing JAR's would be a good first step in this regard.

**Comment by binaryminary** [comment]
I'll upload JAR's to github manually for now till we have CI/CD set up.
[BPI 1.5](https://github.com/hartwigmedical/hmftools/releases/tag/bpi-v1-5)

**Comment by brainstorm** [comment]
Great @binaryminary! We just saw the BPI release you just pushed, thanks for that! 👍 

Perhaps the next step for productionalizing this would be to write a TravisCI yml definition? Sth like:

```
language: java
sudo: false
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
```

But I'm no java expert and I bet you guys had this in mind already ;)

Thanks a lot, much appreciated!

**Comment by binaryminary** [comment]
@kduyvesteyn I'll leave this with you to follow up :)

**Comment by kduyvesteyn** [comment]
Thanks! 

We do have the jars used in the pipeline repo publicly available, added the link to the readme of HMFtools. BPI v1.5 is not available though yet. 

At some point we will make these jars available more structurally, but for now if you need any made just  let us know!
