### ISSUE TITLE
Isofox: Fusion filtering and problem in isofox.combined_fusions.csv header generated by FusionCohort.java

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#203]
The README states that "Isofox generates 2 fusion output files - one for passing fusions and one for all fusions", but running isofox with -functions "TRANSCRIPT_COUNTS;NOVEL_LOCATIONS;FUSIONS" produced output for me that includes only one fusions related file for each sample (file ending ".isf.fusions.csv").

Searching through the Isofox code for filtering methods led me to FusionCohort and the calling calls CohortAnalyser.
Using below, I get a file ending in isf.pass_fusions.csv for each sample in -sample_data_file and an isofox.combined_fusions.csv file that merges all of the samples' fusions along with a leading SampleId column.

`java -Xmx${jvm_mem} -cp ${ISOFOX_JAR} com.hartwig.hmftools.isofox.cohort.CohortAnalyser \
	-root_data_dir ${output_root_path} \
	-sample_data_file ${sample_list} \
	-use_sample_dir \
	-analyses "FUSION" \
	-fusion_write_filtered -fusion_write_combined \
	-known_fusion_file "${ref_dir}/dbs/knowledgebases/known_fusion_data.38_v3.csv" \
	-threads ${threads} \
	-output_dir ${output_root_path}`

However, the header on that combined fusions table did not include the columns that were in the single sample files, but rather just "SampleId,null,Filter,CohortCount,KnownFusionType".
In FusionCohort.java line 136 is supposed to add mFilteredFusionHeader as `mWriter.write(String.format("SampleId,%s", mFilteredFusionHeader));`, but it was created on line 53 as mFilteredFusionHeader = null; so just adds null to the header row.

**Comment by charlesshale** [comment]
Yes I can reproduce this - it is supposed to add all the columns from a sample fusion input file after 'SampleId'. Will fix shortly.

thanks

**Comment by charlesshale** [comment]
https://github.com/hartwigmedical/hmftools/releases/tag/isofox-v1.3_beta

**Comment by toddajohnson** [comment]
Hi Charles,
I ran the new isofox-v1.3_beta.jar against my data, but it failed with the following exception:
`Picked up JAVA_TOOL_OPTIONS: -XX:+UseSerialGC -Xmx64m -Xms32m
Picked up _JAVA_OPTIONS: -Xmx25g
14:09:04 - [INFO ] - Isofox version: 1.3
14:09:04 - [INFO ] - running function(s): TRANSCRIPT_COUNTS
14:09:04 - [INFO ] - running function(s): NOVEL_LOCATIONS
14:09:04 - [INFO ] - running function(s): FUSIONS
14:09:04 - [DEBUG] - loading indexed fasta reference file
14:09:04 - [INFO ] - loaded known fusion data: PROMISCUOUS_5(31), EXON_DEL_DUP(12), IG_KNOWN_PAIR(18), PROMISCUOUS_3(32), KNOWN_PAIR(402), IG_PROMISCUOUS(1)
Exception in thread "main" java.lang.NullPointerException
	at com.hartwig.hmftools.common.utils.FileWriterUtils.checkAddDirSeparator(FileWriterUtils.java:47)
	at com.hartwig.hmftools.common.ensemblcache.EnsemblDataCache.<init>(EnsemblDataCache.java:67)
	at com.hartwig.hmftools.isofox.Isofox.<init>(Isofox.java:84)
	at com.hartwig.hmftools.isofox.Isofox.main(Isofox.java:486)`

Just to check, I ran the immediately previous 1.3.beta, and it completed successfully against the same input file.

**Comment by charlesshale** [comment]
Could you change the config option 'gene_transcripts_dir' to 'ensembl_data_dir'. I've updated Isofox's read-me to reflect this in the examples.

thanks.
