### ISSUE TITLE
PURPLE Unusually Large Ploidy Estimate

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#207]
I have a cancer sample for which the estimated ploidy is 5.30. I am wondering about that because I've only seen ones around 2 and 3 and rarely 4 before. Purity is 0.19 with minPurity being 0.19 and maxPurity being 0.26. Why isn't the solution at 4 chosen?

![image](https://user-images.githubusercontent.com/631218/132625952-29aebaab-661b-4c2f-82af-83c4af79081b.png)

I used PURPLE version 3.1.

**Comment by p-priestley** [comment]
Hi Dario,   
It is difficult to say much from just that picture alone, but the purity range between 19-26% means that those solutions score within 10% of the best score,  but PURPLE still prefers the ploidy 5.3 solution.    I would recommend to look at the other QC plots particularly the copy number and minor allele copy number plots to see how well the copy numbers align with integers.   

5.3 is high but not impossible.   see eg.  https://www.nature.com/articles/ng.2760#Fig1

**Comment by DarioS** [comment]
Ah, I see why. Two doublings seems plausible.

![image](https://user-images.githubusercontent.com/631218/132758748-aa1213d3-68ea-417f-9bf5-270065a96c53.png)
