### ISSUE TITLE
Recommendations for DE with isofox counts

### ISSUE THREAD

**Issue by nayfous** [hartwigmedical/hmftools#208]
Dear HMF team,

I would like to know how to best use the estimated transcripts generated by ISOFOX for differential expression analysis (DE). In the README file from section 5. Fit abundance estimate per transcript, I understand that the estimated transcripts count is estimated similarly to other tools such as RSEM, Salmon, Kallisto, etc. For the output of these tools to be used in DE, tximport can be used. However, ISOFOX is not supported by this package. What is your recommendation to use the ISOFOX output for DE analysis?

Thank you very much in advance for the advice.

Best,
Nayfous

**Comment by p-priestley** [comment]
Sorry about the late reply.   There is no single defined format for outputting expression data and ISOFOX does have some unique annotations.   I just looked at tximport and it appears to do a fairly trivial transformation on the data in R.   I would recommend to simply import the ISOFOX output into R and make the transformation yourself to the appropriate data format.
