### ISSUE TITLE
PURPLE adds LOW_TUMOR_VCN to VCF FILTER but not to VCF header

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#214]
Using PURPLE 3.1, the *purple.germline.vcf.gz file does not have LOW_TUMOR_VCN in the vcf header, so produces an error when bcftools is used with those files.

Looking at current .../purple/germline/GermlineVariantEnrichment.java on GitHub, lines 94 and 95 perform  mLowVafRescueEnrichment.flush() and mLowTumorVCNEnrichment.flush();, respectively, but in lines 106-113, there is no line for adding a header to the vcf for mLowTumorVCNEnrichment.

**Comment by charlesshale** [comment]
Added the missing VCN header entry. Will be part of the 3.2 release.
