### ISSUE TITLE
Chromothripsis Event Identification with LINX

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#215]
We subjectively described the Circos plot below as being illustrative of chromothripsis but the reviewer isn't buying it.

> The authors purport to observe chromothripsis and chromoplexy but do not use any of the proposed methods todetect such event computationally or at least describe definitions that were followed. For one, I do not see either of those events in the presented images.

Is there any classification of events in terms of chromothripsis coming to LINX? I realise that someone else asked last year.

![CSCC_0005-M1 cluster37 COMPLEX sv35 073](https://user-images.githubusercontent.com/631218/136131952-99a9f860-fa13-412f-ab10-5f9726d1119b.png)

**Comment by p-priestley** [comment]
Hi Dario, 

We don't try to predict chromothripsis or chromoplexy sorry, but I think you can easily compare the results to one of the published definitions.   One reason why we have not done so is that those definitions don't really allow for a diversity of repair paths which may include replication before repair and potentially breakage fusion bridge leading to multiple different copy number regimes.  In that sense this event pictured may not meet a classic definition of chromothripsis (I would not call this chromoplexy)

I find your example quite interesting though and definitely representative of recurrent patterns I have seen before.   It appears to vary between 3 copy number regimes:  CN=2,5 & 8  (with an additional likely independent focal duplication of MYC).    The minor allele copy number is 1 throughout, indicating only 1 parental allele has been impacted and has regions of 1,4 & 7.   There is no regions of LOH though which to me suggests that the rearrangement took place on an additional copy of the chromosome, perhaps during or after S phase.   The interspersed regions with no gain strongly suggest that the initial trigger was as chromothriptic like event (perhaps a failure of replication in a micronucleus?).    The interesting question to me is why some regions have double the amplification of others.  Could it be that replication has in fact been attempted and failed multiple times prior to repair creating 2 copies of some regions, 1 copy of others and other missing segments that either weren't replicated or were not repaired into a surviving chromosome?      After repair did occur the rearranged chromosome must have been replicated twice over to explain the copy number jumps from 1 to 4 and 4 to 7.    The foldback inversion at 15.9M looks like a potential cause of this later amplification as it is one of the only variants with a lower junction copy number, and may suggest that breakage fusion bridge has occured.  

Hope this is helpful.
