### ISSUE TITLE
CN Amplifications of 1bp? 

### ISSUE THREAD

**Issue by ellchua** [hartwigmedical/hmftools#225]
Hi, 

I'm currently looking at the results from PURPLE, specifically the `purple.cnv.somatic.tsv` file to look at CN amplifications, and I noticed that the width for some entries is only 1bp long. What does this mean/why does PURPLE return these results considering the lower limit for CNV length is ~50 bps? 

PURPLE version: 2.52 

```{r}
GRanges object with 118 ranges and 14 metadata columns:
        seqnames    ranges strand | copyNumber  bafCount observedBAF       baf segmentStartSupport segmentEndSupport
           <Rle> <IRanges>  <Rle> |  <numeric> <integer>   <numeric> <numeric>         <character>       <character>
    [1]     chr1  37029637      * |     3.0787         0           0    0.7074                 SGL               DUP
    [2]     chr2  27199348      * |     3.2968         0           0    0.7022                 SGL               INF
    [3]     chr2  48599384      * |     2.8171         0           0    0.6523                 SGL               DUP
    [4]     chr5  53732495      * |     2.6669         0           0    0.6256                 DUP               INV
    [5]     chr7   4083693      * |     3.0689         0           0    0.6739                 SGL               INF
```

**Comment by p-priestley** [comment]
Hi Ellora,

PURPLE will determine a copy number for every base of the genome. 
 The normal resolution is 1kb, but where there are SV breakpoints within 1kb of each other, PURPLE will use the SV and the surrounding segment copy numbers to infer the copy number in the smaller ranges (see https://github.com/hartwigmedical/hmftools/tree/master/purple#5-inferring-copy-number-for-regions-without-read-depth-information for full details).  The copyNumberMethod is set to "STRUCTURAL_VARIANT".   

Additionally if the copy number change is inconsistent with the junctionCopyNumber of the SV at the breakpoint, then PURPLE will create an inferred SV ("INF") by convention at the same precise breakpoint (see https://github.com/hartwigmedical/hmftools/tree/master/purple#7-structural-variant-recovery for details).  This may result in copy number regions of 1 base only.

Peter

**Comment by ellchua** [comment]
Hi Peter, 

Should we be reporting these regions as amplified? 

Ellora

**Comment by p-priestley** [comment]
I cannot really comment on your use case without context sorry.

At Hartwig we report amplifications of cancer genes where exonic regions are fully or partially amplified as candidate oncogenic events.   Normally, we would expect a gene to be fully amplified, but in some cases, notably EGFRvII and EGFRvIII exon deletions, we get high amplification for a subset of amplifications.    It is difficult to imagine that a 1 base amplification can be very interesting but again, I am not sure of your exact casse.

**Comment by ellchua** [comment]
Alright. Thanks a lot for your insight, Peter!
