### ISSUE TITLE
obtaining clonality of CNVs from purple

### ISSUE THREAD

**Issue by NathanHarmston** [hartwigmedical/hmftools#227]
Hi, 

I am trying to get hold of the clonality of copy number calls generated by PURPLE - is this possible to do? There appears to be a file *.purple.somatic.clonality.tsv that is generated by the software (with a isSubclonal column), but this doesn't appear to link to CNVs / coordinates in the rest of the output. 

Maybe I"m missing obvious something here, 

thanks, 

nathan

**Comment by NathanHarmston** [comment]
actually, i've just realised from the supp methods that this is referring to clusters of SNVS .... but my overall question regarding extracting clonality of CNVs from purple output still remains

**Comment by p-priestley** [comment]
Hi Nathan,  

So fare we have focused only on SNVs for estimating subclonality and don't estimate this for copy number (although we don't round copy numbers so it is possible to do this downstream).     

As far as I am aware, a novel subclonal SNV could occur 2 ways:   it could be a novel SNV on a subclone which only makes up a portion of the tumor (in which case it would likely not be associated with subclonal copy number) or that a set of clustered SNVs is lost in a copy number deletion that is present on a subclone.  

Peter

**Comment by NathanHarmston** [comment]
thanks for your quick response
