### ISSUE TITLE
PURPLE allele-specific copy number/ploidy

### ISSUE THREAD

**Issue by pdiakumis** [hartwigmedical/hmftools#23]
Hello again.
What is the best way to get the allele-specific copy number from PURPLE? The `circos.png` plot contains the total CN changes in the green/red tracks, but it also includes the minor allele CNs in the internal blue + orange tracks from my understanding (correct me if I'm wrong). So e.g. we can have an LOH region that has a total CN = 2, and a minor allele with CN = 0, so the major allele would have 2 copies.
The `purple.cnv` and `purple.gene.cnv` have the `copyNumber` and `min/maxCopyNumber` columns, respectively, which I assume refer to total copies. Where can I find the minor allele copy number? Are the `purple.fitted` values recommended? From memory in the past I found the fitted CNs to be a bit noisy.
Thanks in advance!

Cheers - Peter

**Comment by p-priestley** [comment]
The minorAllelePloidy can be calculated for any region from the purple.cnv output file as  (1-actualBaf) * CopyNumber.   

By convention in our analyses we say there is a LOH if minorAlllelePloidy < 0.5.   The bafCount column gives you the number of observations used to calculate the actualBaf, so can be used as a measure of confidence.

In the purple.gene.cnv file we also calculate the minimum minor alllele ploidy per gene which is the minMinorAlllePloidy

In recent versions (last 2 months), we have greatly improved inferring of minorAlllelePloidy for small regions where we have no BAF coverage.     We are updating our algorithm documentation presently and will release soon, but in the meantime here is an overview of the inferring algorithm:

**5. Minor allele ploidy inferring**

Once region smoothing is complete, it is possible there will be regions without BAF points which will result in an unknown minor allele ploidy.

We infer the minor allele ploidy of unknown regions by first targeting the ploidy of a neighbouring allele and applying it to all consecutive unknown regions. Whenever possible, only one allele changes between unknown regions.

Which allele ploidy to target from the neighbouring region depends on a number of rules including on whether there is BAF information on both sides of the unknown region or only one one side.

If only one side of the unknown region is available then we must target either the major or minor allele of that neighbour with the following logic:

- If the unknown region is tiny (<= 30 bases) and is greater in copy number than the neighbour, then target the neighbour minor allele.
- If the minor allele has changed by more than 0.5 leading up to the unknown region then target the neighbour major allele.
- Failing everything else, target the neighbour minor allele. 

If there is neighbouring information on both sides of the unknown region, the following logic applies:

- If both the major and minor allele of the neighbours are significantly different (> 0.5) but the minor allele of one matches the major allele of the other ( < 0.5) then the matching ploidy as the target ploidy.
- If the major allele of the neighbours is significantly different target the minor allele.
- If the minor allele of the neighbours is significantly different target the major allele.
- If the unknown region is tiny (<= 30 bases) and is greater in copy number than the neighbour with the highest baf count, then target that neighbours minor allele.
- If the unknown region is not a small region (< 1000 bases) flanked by large ( > 1,000,000) LOH regions then look back on either side (without crossing the centromere) for a change in minor or major allele. If found, re-apply logic from the first three steps. 
- Failing everything else, target the minor allele of the neighbour with the largest number of BAF points.

At this stage we have determined a copy number and minor allele ploidy for every base in the genome
