### ISSUE TITLE
Mismatch in GRIPSS 1.12 and 2.0 README with expected parameters and output

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#237]
Just tried out the newly released gripss-kt_v1.12.jar.  It seems like from the README (web and ones inside the source code) that it is supposed to have been modified from the previous two-step usage (which now appears described in the gripss-kt README; run GRIPSS then run hard-filtering) so that one call to gripss would output into an output_dir both the soft filtered and hard filtered vcf files.
I tried running it with replacing the original parameters used with those now described on the GRIPSS README (sample, pon_sgl_file, pon_sv_file, vcf, output_dir), but it crashes with:
Picked up JAVA_TOOL_OPTIONS: -XX:+UseSerialGC -Xmx64m -Xms32m
13:51:28 - org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -pon_sgl_file
Followed by expected parameter list that looks like the previous parameter list.

Charles, I just noticed that you uploaded GRIPSS 2.0, but it is labelled Beta.
Is v2 good enough to use, and if not, how does one use the gripss-kt_v1.12.jar
It does not seem like either the README description matching v2 or the previous "java -Xms4G -Xmx16G -cp gripss.jar com.hartwig.hmftools.gripss.GripssApplicationKt" work, as the latter returns an error java.lang.ClassNotFoundException.

Also, I just tried the run with changed parameters using 2.0.
The release comments say "The unfiltered output VCF is named SAMPLE_ID.gripss.vcf.gz, and the filtered one is named SAMPLE_ID.gripss.filtered.vcf.gz" but the current README states 
SAMPLE_T.gridss.somatic.vcf.gz - all non-hard-filtered SVs
SAMPLE_T.gridss.somatic.filtered.vcf.gz - filtered for PASS and PON only

Best wishes,
Todd

**Comment by charlesshale** [comment]
Hi Todd,

The Gripss v1.12 is still the 'old' version and needs to be run twice as described here:
https://github.com/hartwigmedical/hmftools/tree/master/gripss-kt

The refactored Gripss is the v2.0 beta release and yes is ready for use. It is functionally identical to v1.12.  I've just updated its READ-ME to show the correctly output filenames as per the release notes.

The PON files now need to be order by start chromosome (column 1) and then start breakend start position (column 2). This is to aid in the efficient application of the PON and otherwise it will generate a lot of warning messages as you saw.

**Comment by toddajohnson** [comment]
Hi Charles,
I Gripss 1.11, there was just a root gripss directory, but for 1.12 there are both gripss and gripss-kt directories.
Based on some playing around, I think the README for Gripss v1.12 needs to be changed a little to:
java -Xms4G -Xmx16G -cp gripss.jar com.hartwig.hmftools.gripsskt.GripssApplicationKt


Also, with v2, does an unproperly sorted PON just create efficiency issues and warnings or is their any potential (unseen) problem that could occur?  I ask because I already started a run and would rather not stop them or rerun them unless the output may be faulty.

Thanks,
Todd

**Comment by charlesshale** [comment]
Thanks, I've changed the old Gripss' READ-ME.

If the PON is unsorted it will likely miss applying some of the entries since it assumes it can move sequentially through as it reads the SVs (also sequentially) per chromosome.

**Comment by toddajohnson** [comment]
Thanks...I will delete the output and rerun it...
