### ISSUE TITLE
GRIPSS 2.0 warnings about unordered PON

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#238]
Just to let you know, when I ran GRIPSS 2.0 beta, there were a large number of warnings such as:
"[WARN ] SV PON not ordered: last(84000-84000) vs this(83991-84010)"

Those were not errors, but still, basically filled up a log file with lots of records and those warnings did not show up in the previous version using that same PONs that I created using gridss.GeneratePonBedpe with our Japanese data.

**Comment by keiranmraine** [comment]
Not ideal but recommend
```
sort -k1V -k2,3n -k4V -k5,6n old.bedpe > new.bedpe
```

**Comment by charlesshale** [comment]
Gripss 2.0 requires the PON to be sorted by ChromosomeStart then PositionStart. This makes the PON annotation more efficient.

**Comment by jamesdalg** [comment]
> Not ideal but recommend
> 
> ```
> sort -k1V -k2,3n -k4V -k5,6n old.bedpe > new.bedpe
> ```
```
20:34:27.382 [WARN ] SV PON not ordered: last(34514-34514) vs this(34513-34515)
20:34:27.382 [WARN ] SV PON not ordered: last(34514-34515) vs this(34486-34518)
20:34:27.382 [WARN ] SV PON not ordered: last(34763-34763) vs this(34762-34764)
20:34:27.382 [WARN ] SV PON not ordered: last(34764-34764) vs this(34741-34765)
20:34:27.382 [WARN ] SV PON not ordered: last(44271-44272) vs this(44263-44275)
20:34:27.382 [WARN ] SV PON not ordered: last(46429-46442) vs this(46427-46451)
20:34:27.382 [WARN ] SV PON not ordered: last(47570-47570) vs this(47548-47574)
20:34:27.382 [WARN ] SV PON not ordered: last(47746-47746) vs this(47728-47750)
20:34:27.382 [WARN ] SV PON not ordered: last(51208-51208) vs this(51194-51217)
20:34:27.382 [WARN ] SV PON not ordered: last(51796-51796) vs this(51778-51797)
20:34:27.382 [WARN ] SV PON not ordered: last(52246-52247) vs this(52245-52248)
20:34:27.382 [WARN ] SV PON not ordered: last(58528-58528) vs this(58507-58530)
20:34:27.382 [WARN ] SV PON not ordered: last(59266-59266) vs this(59264-59269)
20:34:27.382 [WARN ] SV PON not ordered: last(60819-60819) vs this(60790-60828)
20:34:27.382 [WARN ] SV PON not ordered: last(60790-60828) vs this(60789-60832)
20:34:27.382 [WARN ] SV PON not ordered: last(63625-63625) vs this(63624-63640)
20:34:27.382 [WARN ] SV PON not ordered: last(63624-63640) vs this(63619-63645)
20:34:27.383 [WARN ] SV PON not ordered: last(112257-112257) vs this(112256-112258)
20:34:27.383 [WARN ] SV PON not ordered: last(112260-112260) vs this(112258-112261)
20:34:27.383 [WARN ] SV PON not ordered: last(112381-112381) vs this(112377-112382)
20:34:27.383 [WARN ] SV PON not ordered: last(153957-153957) vs this(153938-153959)
20:34:27.383 [WARN ] SV PON not ordered: last(157419-157419) vs this(157394-157424)
20:34:27.383 [WARN ] SV PON not ordered: last(165331-165331) vs this(165306-165346)
20:34:27.383 [INFO ] loaded 3103381 germline SV PON records from file(/data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/ponhg38/gridss_pon_breakpoint.38.bedpe)
20:34:28.416 [INFO ] loaded 1520513 germline SGL PON records from file(/data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/ponhg38/gridss_pon_single_breakend.38.bed)
20:34:28.418 [INFO ] loaded 446 known hotspot records from file
20:34:28.501 [INFO ] sample(TINYPATUXZ_T) processing VCF(/data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/TINYPATUXZ_T_N_gridss_paired_hg38/TINYPATUXZ_T.gripss.vcf.gz)
20:34:28.505 [INFO ] genetype info: ref(0: TINYPATUXZ_N) tumor(1: TINYPATUXZ_T)
20:34:28.509 [INFO ] read VCF: breakends(0) unmatched(0) complete(0) hardFiltered(0)
20:34:28.509 [INFO ] writing output VCF files to /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/TINYPATUXZ_T_N_gridss_paired_hg38/
20:34:28.716 [INFO ] writing empty VCF
20:34:28.726 [INFO ] Gripss run complete

```
This doesn't work for me. I did this and still get the warnings. What is the official recommendation on how to properly sort a bedpe at this point? I downloaded the hg38 pons directly from the gridss folder: https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources%2FGRIDSS%2F38

Is it sorted as in chr1 chr2 chr3 or is it chr1 chr10.... and so on? Is it identical to the way these are sorted? https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources%2FGripss
I'm currently using the files downloaded from here for hg38:
 https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources%2FGRIDSS%2F38

**Comment by charlesshale** [comment]
Not sure about sorting for use other than for Gripss, but Gripss requires the BED and BEDPE files to be sorted by Chromosome then PositionStart. The PON files on the HMF Resources page are sorted this way.

**Comment by toddajohnson** [comment]
Hi Charles,
Since my warning that started this issue, I have not run on this problem personally, because I use PONs made from our Japanese samples, but I checked the HMF GRIDSS PONs in my local files and then redownloaded from HMF's resource site (GRIDSS/38/gridss_pon_breakpoint.38.resorted.bedpe') and checked some positions that threw the warnings up above::
`library(data.table)
gridss_pon_bp <- fread('gridss_pon_breakpoint.38.bedpe')
gridss_pon_bp[,idx:=as.integer(1:nrow(gridss_pon_bp))]
gridss_pon_bp[V1=='chrUn_GL000216v2' & V3%in%c(51208, 51194, 51217),]
                                             V1    V2    V3               V4    V5    V6 V7 V8 V9 V10     idx
1: chrUn_GL000216v2 51207 51208 chrUn_GL000216v2 51226 51227  .  1  +   - 3101994
2: chrUn_GL000216v2 51193 51217 chrUn_GL000216v2 51647 51671  .  1  +   - 3101995
`
It seems like the bed GRIDSS PONs (or at least the breakpoint PON) are not sorted correctly as 51193 should be above 51207. 
I wonder if this is because under GRIDSS directory, there are PONs under 37 and 38 updated a year or 2 years ago, and then under Gripss directory there are PONs for just 37 updated 6 months ago?  The former are probably before GRIPSS 2.0.
That still does not  answer why James has warnings after running `sort -k1V -k2,3n -k4V -k5,6n old.bedpe > new.bedpe`, since that returns the above positions in (what looks to me) the correct order.

**Comment by charlesshale** [comment]
Ok thanks for pointing that out. 

I have now removed the old files under /GRIDSS/ and added the latest files to the Gripss/38/ directory.

**Comment by jamesdalg** [comment]
That fixed it for me. Thanks!
