### ISSUE TITLE
2.0_beta - NullPointer parseVcfSampleIds

### ISSUE THREAD

**Issue by keiranmraine** [hartwigmedical/hmftools#239]
Output files from `##gridssVersion=2.11.1-gridss` do not have an aux header item for `##SAMPLE`.  Still waiting for a functional GRIDSS docker for later versions (https://github.com/PapenfussLab/gridss/issues/549)

The column headers include the expected sample name:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  PD13371b
```

Executed as:

```
java -jar /opt/wtsi-cgp/java/gripss.jar \
-sample PD13371b \
-ref_genome /ref/genome.fa \
-pon_sgl_file /ref/gridss/gridss_pon_single_breakend.37.bed \
-pon_sv_file /ref/gridss/gridss_pon_breakpoint.37.bedpe \
-known_hotspot_file /ref/gridss/known_fusions.37_v3.bedpe \
-vcf /input/PD13371b.gridss.vcf.gz \
-output_dir /output
```

**Comment by keiranmraine** [comment]
Sorry forgot the actual error:

```
10:19:23.698 [INFO ] loading reference data
10:19:31.414 [INFO ] loaded 8508749 germline SV PON records from file(/ref/gridss/gridss_pon_breakpoint.37.bedpe)
10:19:33.028 [INFO ] loaded 2546492 germline SGL PON records from file
10:19:33.030 [INFO ] loaded 446 known hotspot records from file
10:19:33.077 [INFO ] sample(PD13371b) processing VCF(/input/PD13371b.gridss.vcf.gz)
Exception in thread "main" java.lang.NullPointerException
	at com.hartwig.hmftools.gripss.common.VcfUtils.parseVcfSampleIds(VcfUtils.java:113)
	at com.hartwig.hmftools.gripss.GripssApplication.processVcf(GripssApplication.java:108)
	at com.hartwig.hmftools.gripss.GripssApplication.run(GripssApplication.java:96)
	at com.hartwig.hmftools.gripss.GripssApplication.main(GripssApplication.java:320)
```

**Comment by charlesshale** [comment]
I've re-added support for tumor-only mode (ie where -reference config is not provided).

Could you try again with the JAR here:

https://github.com/hartwigmedical/hmftools/releases/tag/gripss-v2.0_beta

**Comment by keiranmraine** [comment]
Thanks for the quick response, our large-scale (i.e. real data) internal CI now runs to completion.

...however the results are significantly different to gripss v1.11 (both use the same input data from gridss 2.11.1):


## grips v 1.11

![Screenshot 2021-12-16 at 09 01 46](https://user-images.githubusercontent.com/3740323/146340666-9999dc84-de2f-48da-9938-fd571e78661a.png)

## gripss v2.0_beta

![Screenshot 2021-12-16 at 08 58 54](https://user-images.githubusercontent.com/3740323/146340309-e1d34626-302d-4da3-8db0-f3dd45a494ce.png)

**Comment by charlesshale** [comment]
Gripss v2.0 is functionally identical to v1.12, however note that v1.12 has quite a few filtering changes from v1.11 as described here:

https://github.com/hartwigmedical/hmftools/releases/tag/gripss-v1.12

Do any of these explain the differences you're seeing?

**Comment by charlesshale** [comment]
Gripss v2.0 has a routine to compare 2 VCFs and report the differences - you may want to try this to see what is causing them:

java -cp com.hartwig.hmftools.gripss.GripssCompareVcfs -sample SAMPLE_ID -original_vcf SAMPLE_ID.gripss.old.vcf.gz -new_vcf SAMPLE_ID.gripss.new_full.vcf.gz -output_dir ./ -log_debug

**Comment by keiranmraine** [comment]
Thanks, that's useful.  We didn't get round to evaluating 1.12 due to the issue on gridss itself.  I'll try that script and get back to you.  It's certainly an issue with changing of the actual vcf coordinates as just comparing these shows the change in commonality.

**Comment by keiranmraine** [comment]
Sadly the comparison script gives:

```
$ java -cp /opt/wtsi-cgp/java/gripss.jar com.hartwig.hmftools.gripss.GripssCompareVcfs -sample PD13371b -original_vcf /data/newS_1.11.vcf.gz -new_vcf /data/newS_2.0.vcf.gz -output_dir ./ -log_debug
09:36:19.724 [INFO ] writing comparison file: ./PD13371b.compare.csv
09:36:19.726 [INFO ] loading original VCF(/data/newS_1.11.vcf.gz)
Exception in thread "main" java.lang.NullPointerException
	at com.hartwig.hmftools.gripss.common.VcfUtils.getGenotypeAttributeAsInt(VcfUtils.java:125)
	at com.hartwig.hmftools.gripss.common.VcfUtils.sglFragmentCount(VcfUtils.java:146)
	at com.hartwig.hmftools.gripss.common.Breakend.<init>(Breakend.java:94)
	at com.hartwig.hmftools.gripss.common.Breakend.from(Breakend.java:145)
	at com.hartwig.hmftools.gripss.common.SvData.<init>(SvData.java:63)
	at com.hartwig.hmftools.gripss.VariantBuilder.checkCreateVariant(VariantBuilder.java:69)
	at com.hartwig.hmftools.gripss.GripssCompareVcfs.loadOriginalVariants(GripssCompareVcfs.java:112)
	at com.hartwig.hmftools.gripss.GripssCompareVcfs.run(GripssCompareVcfs.java:91)
	at com.hartwig.hmftools.gripss.GripssCompareVcfs.main(GripssCompareVcfs.java:323)
```

**Comment by charlesshale** [comment]
The compare routine did not handle tumor-only VCFs but it does now. The beta JAR has been updated.

thanks.

**Comment by keiranmraine** [comment]
Can you clarify, do I compare 2 versions of gri***p***ss output or gri***d***ss vs gri***p***ss

**Comment by charlesshale** [comment]
It compares 2 versions of Gripss VCF files. So you might want to compare
v1.11 vs v1.12 or v2.0
