### ISSUE TITLE
Benchmark Against Competing Software

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#24]
Is there a peer-reviewed journal article available for hmftools? I'm interested in the mathematical details of the algorithm and how PURPLE performs in comparison to [Accurity](https://academic.oup.com/bioinformatics/article/34/12/2004/4827681). I have no experience with either method but I am choosing one to apply to a biologist's data set.

**Comment by p-priestley** [comment]
The original version of the algorithm which we used for the first 2500 tumor samples in our cohort is described in some detail in the methods of our preprint which is currently under review:   

https://www.biorxiv.org/content/10.1101/415133v2

Section 8 of the methods describes the algorithm and section 9 shows our validation on benchmarks and on ~70 real samples vs ASCAT.

In the latest version there are quite some changes to the algorithm, although the basic principles are the same.   We have nearly finalised our documentation for the revised version and will make it available shortly on github.  

I am not familiar with accurity so cannot comment on the differences.
