### ISSUE TITLE
minPurity greater than purity

### ISSUE THREAD

**Issue by SebastianHollizeck** [hartwigmedical/hmftools#242]
Hi,

I finished running PURPLE and the results look very nice, apart from one specific sample, which has a bit of a weird result to me, where the called purity is lower than the minPurity result

purity: 0.2400
minPurity: 0.4300
maxPuirty: 1.0000

is that because of local vs global optimsation or any other issue that i might have overseen?

Thank you for your help,
Sebastian

**Comment by p-priestley** [comment]
Hi Sebastian.

I agree this is confusing.   The minPurity and maxPurity are the minimum purity and maximum purity solutions found within 10% of the best scoring solution based on the copy number inputs.   However, if the sample is found to be highly diploid the fit uses a somatic mode instead and instead uses the SNV profile to fit.   This can lead to a purity outside the original range.   
Do you see fit_method = SOMATIC in the purity.tsv file?

**Comment by SebastianHollizeck** [comment]
Hey,

yes, the "status" column is "SOMATIC" where in the other samples it is "NORMAL"

So i assume the actually assigned purity is the one to believe in more?

**Comment by p-priestley** [comment]
Yes.   The final purity is the one you want to look at.  

You can check the plots directory to evaluate whether it looks plausible.

**Comment by SebastianHollizeck** [comment]
I have done that already, I just wanted to confirm that I dont do anything wrong.

Thank you very much for your quick help.

in case I would believe an alternative solution after looking at the plots, I would just rerun purple with a preselected purity and ploidy input range right?

**Comment by p-priestley** [comment]
correct
