### ISSUE TITLE
CN ticks on linx plots

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#246]
I've generated a plot with linx and I'm wondering if the ticks shown in the diagram (https://github.com/hartwigmedical/hmftools/blob/master/linx/README_VIS.md) can be created in the plots. Thusfar, I haven't been able to generate them and it would help interpretability to know if there was 0,1,2, or 3 copies at a given locus:
![PAPXWB_T cluster273 SGL sv2 003](https://user-images.githubusercontent.com/26911077/150415353-732ecad7-246b-4025-a7f6-b8d28b2e36c8.png)

**Comment by jamesdalg** [comment]
To make it clear, I'm talking about this:
![image](https://user-images.githubusercontent.com/26911077/150418306-854c51bd-2bc0-44ac-9847-a9cb9a3a2ead.png)

**Comment by p-priestley** [comment]
I am sorry - we have never supported this feature (except for the guide) as the design was intended to be relative minimalist.  I agree it could help interpretation,  so will leave this issue open and add it at some time in the future, but I am not sure if we will get a chance to look at it in the very short term.  

Note the scale of the CN plot can vary enormously  as we have to support anything from CN 2 to 200+, but can always be judged by the spacing of the concentric lines (which are spaced by CN=1 for CN up to 10 and then by 10 thereafter).     In your example the CN alternates between 6 and 4.
