### ISSUE TITLE
Minor addition for Linx visualiser documentation

### ISSUE THREAD

**Issue by scwatts** [hartwigmedical/hmftools#248]
Hello, we've been using the GRIDSS/PURPLE/Linx toolkit regularly for several months in a developmental Nextflow [pipeline](https://github.com/umccr/gridss-purple-linx-nf) and have found it to be exceedingly useful.

We had recently encountered an issue with Linx related to the usage of reference genome version, which we have now resolved on our side. To possibly save others from the same fate, could we suggest that information regarding `-ref_genome_version` be added to the Linx visualiser documentation? This argument is already well noted in the Linx annotator [documentation](https://github.com/hartwigmedical/hmftools/tree/master/linx#core-configuration).

In our case it wasn't immediately clear that `-ref_genome_version 38` is required to be specified for both the Linx annotator and Linx visualiser given it wasn't listed in the Linx visualiser [documentation](https://github.com/hartwigmedical/hmftools/blob/master/linx/README_VIS.md#other-arguments).

**Comment by charlesshale** [comment]
Thanks for picking this up and I will update the visualiser config now.
