### ISSUE TITLE
Computing Resource Requirements in Software Documentation

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#25]
Amber contains some comparisons for different numbers of threads and the number of minutes required to process a particular pair of samples with particular read deptth. This would be useful information to also provide for COBALT and PURPLE. Also, peak RAM usage would be valuable to know for all three software. I will use Portable Batch System scheduler to analyse my data set.

**Comment by p-priestley** [comment]
Thanks for the feedback.  We will post some numbers shortly equivalent to what is there for AMBER.

Roughly - Cobalt takes several hours to run on a single core but can be reduced to <15 mins by running with up to 48 cores (ie. 1 per chromosome per sample) .   

Purple will not take more than a few minutes as it does not need to access BAMs.

**Comment by jonbaber** [comment]
I have included performance characteristics for COBALT and PURPLE and have updated AMBER to include the peak memory usage. 

I will update the single threaded values for COBALT and AMBER when they become available.
