### ISSUE TITLE
signature definition file for sigs

### ISSUE THREAD

**Issue by drna** [hartwigmedical/hmftools#250]
We were trying to run sigs but cannot locate the signatures definition file that is mentioned in the documentation to be located here:  https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources

Could you please point me into the right direction?

**Comment by charlesshale** [comment]
[snv_cosmic_sigs.csv](https://github.com/hartwigmedical/hmftools/files/8035253/snv_cosmic_sigs.csv)

Here are the COSMIC 30 signature definitions.
