### ISSUE TITLE
SAGE Prefixes Resource Directory to Reference Genome Path

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#252]
I am specifying `-resource_dir /verona/nobackup/biostat/databases/SAGE/` and specifying reference genome by `-ref_genome /verona/nobackup/biostat/sequence/hg38/hs38DH.fasta`. Although the documentation seems to suggest `-ref_genome` should be an absolute path (e.g. `/path/to/refGenome.fasta`), it seems to be treated as a relative path to the resource directory.

```
19:52:40 - [INFO ] - Sage version: 3.0
19:52:41 - [ERROR] - failed to load ref genome: java.io.FileNotFoundException: /verona/nobackup/biostat/databases/SAGE/verona/nobackup/biostat/sequence/hg38/hs38DH.fasta.fai not found.
```

Could it work as documented by accepting absolute paths for both parameters?

**Comment by charlesshale** [comment]
The purpose of specifying a resource directory is that it will contain all the reference files required by Sage without having to repeat the paths for each of them. The alternative is that you leave out "resource_dir" and provide a path for each resource/reference file, so in your case where they aren't in the same directory that seems like the better option.

thanks.
