### ISSUE TITLE
Making a teal blacklist for hg38

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#254]
Question-- I saw the teal release just today and that package looks really exciting. Teal will reveal exact breakpoint locations and that's exactly one of our key study questions and it might be able to shed light on ALT too. How was the teal blacklist created? I want to do the footwork to make it work for hg38. Perhaps its not so simple and that's fine if so.

**Comment by p-priestley** [comment]
The blacklist is only 28 regions and 56k bases.   The aim is to eliminate regions of high telomeric content to both avoid FP rearrangement calls and to improve performance.      I think you can likely just liftover to hg38 but I have not tested this.  We will get to this at some point soon when we migrate to hg38.

**Comment by p-priestley** [comment]
We are also looking at ALT rearrangements and others in our cohort

**Comment by jamesdalg** [comment]
Sounds great. I'll just use the hg19 to hg38 chain. They're large regions where exact base precision isn't mission critical, so liftOver seems like a great solution. Neat to hear that you're interested in ALT as well. It seems like your group does almost exactly what we do, just on a different cancer.
