### ISSUE TITLE
PURPLE 3.3 java.lang.NullPointerException (missing transcript handling)

### ISSUE THREAD

**Issue by scwatts** [hartwigmedical/hmftools#259]
Hi, I'm trying out PURPLE 3.3 on a downsampled dataset and hit an error:
```bash
java.lang.NullPointerException
	at com.hartwig.hmftools.purple.gene.GeneCopyNumberFactory.geneCopyNumbers(GeneCopyNumberFactory.java:27)
	at com.hartwig.hmftools.purple.PurpleApplication.performFit(PurpleApplication.java:309)
	at com.hartwig.hmftools.purple.PurpleApplication.processSample(PurpleApplication.java:233)
	at com.hartwig.hmftools.purple.PurpleApplication.run(PurpleApplication.java:167)
	at com.hartwig.hmftools.purple.PurpleApplication.main(PurpleApplication.java:581)
```

The command used was:
```bash
java \
  -Xmx4G \
  -jar /opt/hmftools/purple.jar \
  -reference SEQC-II_Normal \
  -tumor SEQC-II_Tumor_50pc \
  -sv_recovery_vcf SEQC-II_Tumor_50pc.gripss.vcf.gz \
  -structural_vcf SEQC-II_Tumor_50pc.gripss.filtered.vcf.gz \
  -amber amber/ \
  -cobalt cobalt/ \
  -output_dir purple/ \
  -gc_profile GC_profile.1000bp.38.cnp \
  -run_drivers \
  -driver_gene_panel DriverGenePanel.38.tsv \
  -ensembl_data_dir 38/ \
  -somatic_hotspots KnownHotspots.somatic.38.vcf.gz \
  -ref_genome umccrise_hg38/hg38.fa \
  -threads 4 \
  -circos circos \
  -ref_genome_version 38
```

At a glance the error seems to be related to the process used to [retrieve transcripts](https://github.com/hartwigmedical/hmftools/blob/master/hmf-common/src/main/java/com/hartwig/hmftools/common/ensemblcache/EnsemblDataCache.java#L197) from the Ensembl data cache. Specifically, it may be the `mTranscriptDataMap` Map object returning a `null` value for missing transcripts. Another cause could be use of downsampled data, though this data was working okay with PURPLE 3.2.

**Comment by charlesshale** [comment]
That error suggests an inconsistency in the Ensembl data cache. There should be at least one transcript entry in the ensembl_trans_exon_data.csv file for every gene in the ensembl_gene_data.csv file. Can you check this? 

I have just verified that this is the case for our 37 and 38 caches, which are available on the HMF Resources page.

eg in R:

ensemblGeneDataHg38 = read.csv('~/data/ensembl_db/ensembl_38_104/ensembl_gene_data.csv')
ensemblTransExonData38 = read.csv('~/data/ensembl_db/ensembl_38_104/ensembl_trans_exon_data.csv')

View(ensemblGeneDataHg38 %>% filter(!(GeneId %in% ensemblTransExonData38$GeneId))) # no entries
nrow(ensemblGeneDataHg38 %>% filter(GeneId %in% ensemblTransExonData38$GeneId)) # 39226

**Comment by scwatts** [comment]
Hi Charles, thanks for taking a look into this. Your hunch was correct - the `ensembl_trans_exon_data.csv` file from HMF's Nextcloud instance appears to be missing entries for the `ENSG00000258414` transcript. All other genes in `ensembl_gene_data.csv` have at least one transcript entry (totaling 39225).

<details><summary>Comparison details (click to expand)</summary>


Input files ([attached](https://github.com/hartwigmedical/hmftools/files/8122042/ensembl_data_cache_hg38_partial.tar.gz) to this issue comment)):
```bash
# Downloaded from HMF Nextcloud instance and placed into a compressed tarball today (20220223).
# URL: https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources%2FEnsembl-Data-Cache%2F38
tar -zxvf ensembl_data_cache_hg38_partial.tar.gz
```

Comparison:
```Rscript
library(dplyr)
d.ensemblGeneDataHg38 <- read.csv('./data/ensembl_gene_data.csv')
d.ensemblTransExonData38 <- read.csv('./data/ensembl_trans_exon_data.csv')

d.ensemblGeneDataHg38 %>% filter(!(GeneId %in% d.ensemblTransExonData38$GeneId))
nrow(d.ensemblGeneDataHg38 %>% filter(GeneId %in% d.ensemblTransExonData38$GeneId))
```

Results:
```text
# Transcripts missing from `ensembl_trans_exon_data.csv`
           GeneId   GeneName Chromosome Strand GeneStart  GeneEnd KaryotypeBand
1 ENSG00000258414 AL121790.1         14      1  37564047 37579125         q21.1
  Synonyms

# Count of transcripts present in both `ensembl_gene_data.csv` and `ensembl_trans_exon_data.csv`
39225
```

</details>

**Comment by charlesshale** [comment]
I've re-uploaded the GRCh38 Ensembl files to our HMF Resources page. It has 2 entries for that gene: ENSG00000258414

thanks.

**Comment by scwatts** [comment]
Thanks for updating the Ensembl data cache - PURPLE 3.3 is now running without error on the downsampled test dataset. I noticed a tarball of the old files on the Nextcloud instance but assume this is intentional.

Lastly, a couple of minor suggestions for the documentation:

- add `-ensembl_data_dir` as a [mandatory argument](https://github.com/hartwigmedical/hmftools/tree/master/purple#mandatory-arguments), and
- replace the depreciated `-driver_catalog` with `-run_drivers` in the [driver section](https://github.com/hartwigmedical/hmftools/tree/master/purple#optional-driver-catalog-arguments)

**Comment by charlesshale** [comment]
I've removed the old TAR file and updated the read-me with those changes, thanks.
