### ISSUE TITLE
R Package Installation Instructions Outdated

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#26]
Some software, like Amber, has instructions like `source("https://bioconductor.org/biocLite.R")` but this generates a warning because the method of installing Bioconductor packages has recently changed and the script sourcing approach will not work from the end of this year.

The newly required approach is like

```r
library(BiocManager) # Get it from CRAN
install("copynumber")
```

**Comment by jonbaber** [comment]
Thanks for letting us know. I have updated the readme files.
