### ISSUE TITLE
LINX Visualisation for LOH_CHR Events

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#261]
I am using the options `-plot_reportable -plot_cluster_genes` and my colleague @amarinderthind noticed that the resulting plots were not created for any of the LOH_CHR events listed in the linx.driver.catalog.tsv files, such as:

```
chrX    p22.33  PPP2R3B DEL     TSG     DEL     1.0000  0       0       0       0       0       0       true    -0.0040 -0.0040
chrX    p22.31  PUDP    DEL     TSG     DEL     1.0000  0       0       0       0       0       0       true    -0.0040 -0.0040
chrX    p22.31  STS     DEL     TSG     DEL     1.0000  0       0       0       0       0       0       true    -0.0040 -0.0040
chrX    p22.2   WWC3    DEL     TSG     DEL     1.0000  0       0       0       0       0       0       true    -0.0040 -0.0040
```

`-plot_reportable` is described as "Plot any cluster with reported fusion, disruption, or driver", so we're confused by skipping.

**Comment by p-priestley** [comment]
If the whole chromosome is deleted then there are no SV events by definition.
