### ISSUE TITLE
Where to find virus_reporting_db_tsv for virus-interpreter?

### ISSUE THREAD

**Issue by DavyCats** [hartwigmedical/hmftools#263]
I can't find the file to pass to the `-virus_reporting_db_tsv` option in virus-interpreter amongst the provided HMFTools-Resources. Could this file be made available?

**Comment by kduyvesteyn** [comment]
Apologies, this file was missing indeed. Has been added to Virus-Interpreter folder on the HMFTools-Resources page (https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources%2FVirus-Interpreter)
