### ISSUE TITLE
Negative telomere length with teal on tumor only, lower telomere lengths in all samples tested.

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#264]
TEAL is a very needed program and highly useful. I've found that teal is producing some odd results in hg38, specifically all telomere lengths are less in the tumor than in the normal tissue. Cancer cells, to become immortal, lengthen their telomeres. Generally this is the pattern to which I am familiar, although there might be rare exceptions. The negative telomere length is also a bit odd. Is this right? Should I expect these smaller tumor reads? If not, what should I be doing to troubleshoot this issue?

Here are my results:
![image](https://user-images.githubusercontent.com/26911077/156475460-6723ee63-11fb-4714-810a-1ecbff180153.png)

Here is the call that generated my output:
```
 module load java/17.0.1; java -Xmx30G -cp /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/hmftools/teal/teal-1.0_beta_hg38_blacklist.jar com.hartwig.hmftools.teal.TealApplication        -reference NAAHDI_N -reference_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/NAAHDI_N.bam        -tumor NAAHDI_T -tumor_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/NAAHDI_T.bam        -purple /data/CCRBioinfo/dalgleishjl/sv_mapping/NAAHDI_purple        -cobalt /data/CCRBioinfo/dalgleishjl/sv_mapping/NAAHDI_cobalt        -reference_wgs_metrics /data/CCRBioinfo/dalgleishjl/sv_mapping/NAAHDI_wgsmetrics/NAAHDI_N_wgs_metrics.txt        -tumor_wgs_metrics  /data/CCRBioinfo/dalgleishjl/sv_mapping/NAAHDI_wgsmetrics/NAAHDI_T_wgs_metrics.txt        -output_dir /data/CCRBioinfo/dalgleishjl/sv_mapping/NAAHDI_teal/        -threads 32;
```

Here is my hg38 blacklist (created using liftOver with an hg38tohg19 chain from UCSC):
```
1	121741202	121743636
1	125169944	125170022
1	248943801	248946422
2	242182006	242183529
3	198173129	198175129
4	10001	11000
4	190117845	190123121
5	10001	13000
7	10001	11000
7	106100554	106102554
8	43236857	43242857
9	10001	11000
10	41709209	41713209
10	41839209	41863209
10	41878209	41884209
10	42097572	42097641
10	42101501	42105552
10	133785675	133787422
12	10001	13740
12	133264414	133265309
15	101979797	101981189
18	10001	12000
19	27240875	27248092
19	58606633	58607616
20	64285647	64287647
21	8815167	8817167
21	46699088	46699983
X	156029335	156030895
MT	10999	11718
MT	11723	13999

Here is my wgs metrics for the top sample tumor/ref pair:
[NAAHDI_N_wgs_metrics.txt](https://github.com/hartwigmedical/hmftools/files/8174032/NAAHDI_N_wgs_metrics.txt)
[NAAHDI_T_wgs_metrics.txt](https://github.com/hartwigmedical/hmftools/files/8174033/NAAHDI_T_wgs_metrics.txt)

**Comment by p-priestley** [comment]
James,

Thanks for giving TEAL a try.       I don't see the result  being super strange.  Generally telomeres are shorter in tumor samples.  See for example: https://www.nature.com/articles/s41467-019-13824-9#Fig1

Also FYI - Here is a cdf of telomere length for samples in our cohort (~6k samples) - both germlne and somatic:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/18154939/156504359-af3ef925-9871-4ec6-8ca7-f856bcb10b6d.png">

The formulas for calculating telomere length are very straight forward.  Please see here:

https://github.com/hartwigmedical/hmftools/tree/master/teal#3-estimate-total-telomeric-content-and-length

I would say as long as all the inputs are estimated correctly, then hopefully the formula  itself should not be too controversial.  

Negative estimates is obviously not great.  This arises from the combination of the tumor having low purity (33% in your case) and  the tumor mix telomere length being much lower than the germline estimate.     I would say what has happened here is the germline estimate from the blood cells may not be fully reflective of the impure part of the tumor mix.    Different cell types in the body may have systematically different telomere lengths and so assuming the non tumor part of the mix to have the same length as the measure blood sample may not be a good assumption.   Nevertheless in this case the telomere length is likely to be very short indeed.    Only a tiny proportion of our cohort (~0.2% ) give a negative telomere estimate, and even then it is within noise of 0 telomere length.

Hope this helps

Peter

**Comment by jamesdalg** [comment]
Wow, that's a very comprehensive answer. Thanks so much again.
