### ISSUE TITLE
strelka-post-process.jar

### ISSUE THREAD

**Issue by tlesluyes** [hartwigmedical/hmftools#265]
Hi,

Related to [issue 18](https://github.com/hartwigmedical/hmftools/issues/18), I'm interested in aggregating SNV calls from Strelka into MNV. It seems like a particular strategy was used in HMF ([sup info, section 3, subsection 'MNV Correction'](https://www.nature.com/articles/s41586-019-1689-y#Sec25)) and I'd like to apply that to my Strelka calls. However, such a process is done by `strelka-post-process.jar` (as part of [this script](https://github.com/hartwigmedical/pipeline/blob/master/templates/StrelkaPostProcess.sh.tt)), but I wasn't able to find such a JAR file at https://resources.hartwigmedicalfoundation.nl, was subfolder HMFTools-Jars removed?

Thank you in advance for your help.

**Comment by charlesshale** [comment]
We don't run Strelka any more and the tools/script you're referring to has been dropped from our pipeline. 

We now use Sage (https://github.com/hartwigmedical/hmftools/tree/master/sage) for somatic variant calling, and this includes calling, filtering and de-duplication of MNVs.

We then run Pave (https://github.com/hartwigmedical/hmftools/tree/master/pave) for gene impact and PON annotation.

The only other step in our post-variant calling is to annotate variants with their mappability (see https://resources.hartwigmedicalfoundation.nl/ -> Mappability).

thanks
