### ISSUE TITLE
How are isofox neoepitiope files created?

### ISSUE THREAD

**Issue by joe-usset** [hartwigmedical/hmftools#270]
I am trying to find how the neoepitope files (*.isf.neoepitope.csv) from isofox are created. In particular, I want to understand the method used to predict neoepitope counts.

I have looked through ~/master/isofox/README.md but can't find a description. Where can I find more information?

Thank you for any help!

**Comment by p-priestley** [comment]
This is experimental functionality right now.    We will likely release our full neoepitope toolset somewhere in the coming months

**Comment by joe-usset** [comment]
Ok, thank you.

**Comment by p-priestley** [comment]
Sorry.   Still on the to do list, but have been focusing on other priorities.   We hope later this quarter.
