### ISSUE TITLE
Joint calling

### ISSUE THREAD

**Issue by micoli98** [hartwigmedical/hmftools#274]
In the current implementation it seems that the joint calling is not possible. In fact, when specifying the -sample names, if they are separated by a comma, the error got is: [ERROR] missing sample names in VCF.
While if the names are provided separated from a space or each one preceded by "-sample", only the first name is analysed. 

What is the correct syntax?

**Comment by p-priestley** [comment]
GIRDSS can be indeed be run as a joint caller, but GRIPSS only supports a single tumor at a time.   You can either run samples one a time or else you may need to implement your own filters sorry.   The filters are all documented on the readme.

**Comment by micoli98** [comment]
No problem, thank you so much for your help.

On 5. Apr 2022, at 14.07, p-priestley ***@***.******@***.***>> wrote:



GIRDSS can be indeed be run as a joint caller, but GRIPSS only supports a single tumor at a time. You can either run samples one a time or else you may need to implement your own filters sorry. The filters are all documented on the readme.
