### ISSUE TITLE
LogR

### ISSUE THREAD

**Issue by micoli98** [hartwigmedical/hmftools#275]
Since I'm performing a comparison between different tools, I'm trying to extract from the tumor read counts the logR. Nevertheless, I don't understand how to do it since I don't understand how to combine the ratio results provided. Some hints?

**Comment by p-priestley** [comment]
The main copynumber output is in the *.purple.cnv.somatic.tsv.   Please see the column 'copynumber'.   you will need to convert to log space.

COBALT (the raw input to PURPLE) also presents raw Log2R (without smoothing) in the pcf file in the 'mean' field.
