### ISSUE TITLE
Question about GRIPSS filtered VCF

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#278]
This late in the game, I should not be asking this simple question, but should the filtered VCF file output by GRIPSS still have entries with FILTER=PON?

**Comment by charlesshale** [comment]
Yes we keep PASS and PON in the Gripss filtered VCF, and they are subsequently annotated by Purple and loaded into our HMF database. However they are ignored by Linx (ie for clustering, chaining, fusion calling and other analysis) and other downstream processes.
