### ISSUE TITLE
Clinvar 38 missing chr

### ISSUE THREAD

**Issue by jaesvi** [hartwigmedical/hmftools#279]
Hi,
I just discovered that the Clinvar 38 version provided in `HMFTools-Resources/Sage/38/clinvar.38.vcf.gz` is missing the chr prefix, while all the other files there do have it. This causes the germline variants to not be properly annotated with clinvar while following the SAGE readme for filtering those. Easy to fix, I just though you might want to know.

**Comment by charlesshale** [comment]
I agree it is inconsistent, thanks for point that out. I will get that file updated shortly.

**Comment by charlesshale** [comment]
The Clinvar VCF for v38 has been updated
