### ISSUE TITLE
Some updated tools without complied jar files in the releases page

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#283]
Some updated tools without complied jar files in the releases page, https://github.com/hartwigmedical/hmftools/releases .
Would it be possible for jar files to be added?

**Comment by jamesdalg** [comment]
Yes, specifically PAVE 1.2 is missing. [pave v1.2](https://github.com/hartwigmedical/hmftools/releases/tag/pave-v1.2)

**Comment by charlesshale** [comment]
I've just added the Pave 1.2 JAR.

**Comment by charlesshale** [comment]
I've added the Pave 1.2 JAR.
