### ISSUE TITLE
Error: Could not find or load main class com.hartwig.hmftools.sage.SageApplication

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#284]
Command:
`          if [[ -d "/lscratch/$SLURM_JOB_ID" ]] ; then
           tmp="/lscratch/$SLURM_JOB_ID/tmp";
           mkdir -p "$tmp";
           export TMPDIR="$tmp";
           fi
           mkdir -p  /data/CCRBioinfo/dalgleishjl/sv_mapping/sage/PALHRL_sage/;
           module load gridss samtools R java/17.0.2;
           java -Djava.io.tmpdir=/lscratch/$SLURM_JOB_ID -Xms4G -Xmx32G -cp /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/external_resources/HMFTools-Resources/Sage/sage_v3.0.1.jar com.hartwig.hmftools.sage.SageApplication            -threads 64            -reference PALHRL_N -reference_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/PALHRL_N.bam            -tumor PALHRL_T -tumor_bam /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_pipeline/bam_hg38/PALHRL_T.bam            -ref_genome /data/CCRBioinfo/dalgleishjl/sv_mapping/hg38_ref/hg38.fa            -hotspots /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/external_resources/HMFTools-Resources/Sage/38/KnownHotspots.somatic.38.vcf.gz            -panel_bed /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/external_resources/HMFTools-Resources/Sage/38/ActionableCodingPanel.somatic.38.bed.gz            -ref_genome_version 38            -ensembl_data_dir  /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss/external_resources/HMFTools-Resources/Ensembl-Data-Cache/38/            -out /data/CCRBioinfo/dalgleishjl/sv_mapping/sage/PALHRL_sage/PALHRL.sage.vcf.gz -min_map_quality 30 -hard_filter_enabled true;
`

Error:
```
[-] Unloading gridss  2.13.2 on cn0908
[+] Loading gridss  2.13.2  on cn0908
[-] Unloading singularity  3.8.5-1  on cn0908
[+] Loading singularity  3.8.5-1  on cn0908
[-] Unloading samtools 1.15  ...
[+] Loading samtools 1.15  ...
[-] Unloading gcc  9.2.0  ...
[-] Unloading GSL 2.6 for GCC 9.2.0 ...
[-] Unloading openmpi 4.0.5  for GCC 9.2.0
[-] Unloading ImageMagick  7.0.8  on cn0908
[-] Unloading HDF5  1.10.4
[-] Unloading NetCDF 4.7.4_gcc9.2.0
[-] Unloading pandoc  2.17.1.1  on cn0908
[-] Unloading pcre2 10.21  ...
[-] Unloading R 4.1.3
[+] Loading gcc  9.2.0  ...
[+] Loading GSL 2.6 for GCC 9.2.0 ...
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading openmpi 4.0.5  for GCC 9.2.0
[+] Loading ImageMagick  7.0.8  on cn0908
[+] Loading HDF5  1.10.4
[-] Unloading gcc  9.2.0  ...
[+] Loading gcc  9.2.0  ...
[+] Loading NetCDF 4.7.4_gcc9.2.0
[+] Loading pandoc  2.17.1.1  on cn0908
[+] Loading pcre2 10.21  ...
[+] Loading R 4.1.3
[-] Unloading java 17.0.1  ...
[+] Loading java 17.0.2  ...

The following have been reloaded with a version change:
  1) java/17.0.1 => java/17.0.2

Error: Could not find or load main class com.hartwig.hmftools.sage.SageApplication
Caused by: java.lang.ClassNotFoundException: com.hartwig.hmftools.sage.SageApplication

```

I'm not quite sure how to remedy this. Sage worked fine until I updated it to 3.0.1 from 3.0 beta. Is there a different syntax now? I've looked at documentation and it seems this is in line with documentation, but I could be wrong.

**Comment by charlesshale** [comment]
I can't explain that sorry - I just tried running both 3.0 and 3.0.1 with and without the class-path and it worked correctly each time:

java -cp ~/hmf/tags/sage_v3.0.1.jar com.hartwig.hmftools.sage.SageApplication
05:06:22.314 [INFO ] Sage version: 3.0.1

java -cp ~/hmf/tags/sage_v3.0.jar com.hartwig.hmftools.sage.SageApplication
05:06:31.517 [INFO ] Sage version: 3.0

Without specifying classpath:

java -jar ~/hmf/tags/sage_v3.0.1.jar
05:07:53.407 [INFO ] Sage version: 3.0.1

java -jar ~/hmf/tags/sage_v3.0.jar
05:07:57.251 [INFO ] Sage version: 3.0


That error can occur when the path to the JAR is invalid.

**Comment by jamesdalg** [comment]
That's precisely it. Thanks!
