### ISSUE TITLE
Purple Mandatory Arguments Seem Unnecessary

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#29]
Why is specifying `-amber` and `-cobalt` mandatory if the optional argument `-run_dir` can provide enough information for both folder locations to be inferred, if it's specified? It seems that `-amber` and `-cobalt` should be **conditionally** mandatory (only if `-run_dir` is not specified).

**Comment by jonbaber** [comment]
You are correct that they are conditionally mandatory if `-run_dir` is specified and the amber and cobalt directories are already in the expected locations, i.e, `<run_dir>/amber` and `<run_dir>/cobalt`. The same is also true for the `-output_dir` directory. If you have included `-run-dir` but omitted `-output_dir` PURPLE will write to `<run_dir>/purple` by default. 

This is just a very small optimisation for our pipeline and I don't typically expect other uses to use it. I was a little weary of even including a description of this parameter as I think it is more confusing than helpful. 

To resolve this I have de-emphasised this parameter by removing its example usage. I have also explicitly mentioned that using this parameter makes the other 3 non-mandatory.  I will keep the 3 parameters in the mandatory section as I believe this will be the least confusing for users.
