### ISSUE TITLE
teal: read groups could not be completed

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#290]
Hi,

29 of my teal runnings failed with 'java.lang.IllegalStateException: XX read groups could not be completed':

10:24:31.992 ReadGroup | main | WARN | isComplete | DP8400027238TLL1C041R02401039977 1/2 100b aligned to chr8:205717-205769. Missing supplementary read: aligned to chr8:205582
10:24:31.992 BamRecordWriter | main | WARN | finish | incomplete read group: id=DP8400027238TLL1C041R02401039977, is complete=false
10:24:31.992 BamRecordWriter | main | WARN | finish | record(DP8400027238TLL1C041R02401039977 1/2 100b aligned to chr8:205717-205769.) cigar(47S53M) neg strand(false) suppl flag(false) suppl attr(chr8,205582,+,64M36S,14,3;)
10:24:31.993 BamRecordWriter | main | WARN | finish | record(DP8400027238TLL1C041R02401039977 2/2 100b aligned to chr8:205899-205998.) cigar(100M) neg strand(true) suppl flag(false) suppl attr(null)
10:24:31.993 BamRecordWriter | main | WARN | finish | supplementary(DP8400027238TLL1C041R02401039977 1/2 100b aligned to chr8:205575-205645.) cigar(7M7D57M36S) neg strand(false) suppl flag(true) suppl attr(chr8,205717,+,47S53M,14,0;)
10:24:33.701 TealApplication | main | ERROR | run | java.lang.IllegalStateException: 1 read groups could not be completed

**Comment by hongwingl** [comment]
Would you be able to run 
```
samtools view <bam file> | grep DP8400027238TLL1C041R02401039977
```
And paste the result here?
It seems to be missing one supplementary read.

Regards,

Hong

**Comment by YingYa** [comment]
DP8400027238TLL1C041R02401039977        2147    chr8    205575  24      7M7D57M36S      =       205899  417     CCCTAAACCCTAACCCTAACCCTACCCCTAGCCCAAACCCGAACCCGAACCCTCACCCTAACCCTAAACCACATGAGCAATGTGGGTATTATATTTTGGG     ???>@AAACC??@@@AB?A?BBBA@BBAA@=ACAC@B@CC(/B@CA7ABACCDCB@CBBABBCCDBCB>DE7ECDBBCEABDAABA@BCBBCB@C??8>>     MC:Z:100M       AS:i:49 XS:i:0  RG:Z:DP8400027238TL_L01_358     SA:Z:chr8,205717,+,47S53M,14,0; OC:Z:64M36S     OP:i:205582      NM:i:9
the alignment result of  DP8400027238TLL1C041R02401039977:

DP8400027238TLL1C041R02401039977        99      chr8    205717  14      47S53M  =       205899  282     CCCTAAACCCTAACCCTAACCCTACCCCTAGCCCAAACCCGAACCCGAACCCTCACCCTAACCCTAAACCACATGAGCAATGTGGGTATTATATTTTGGG     ???>@AAACC??@@@AB?A?BBBA@BBAA@=ACAC@B@CC(/B@CA7ABACCDCB@CBBABBCCDBCB>DE7ECDBBCEABDAABA@BCBBCB@C??8>>     NM:i:0  MD:Z:53 AS:i:53 XS:i:48 RG:Z:DP8400027238TL_L01_358     SA:Z:chr8,205582,+,64M36S,14,3; XA:Z:chr19,+245983,47S53M,1;     MC:Z:100M       MQ:i:38
DP8400027238TLL1C041R02401039977        147     chr8    205899  38      100M    =       205717  -282    TTCCACACTGAACCGTTCTAACTGGTCTCTGACCTTGATTATTAACGGCTGCAACCGGGAAAGATTTTATTCACCGTCGATGCGGCCCCGAGTTGTCCCA     ?@?A@DADDCCAD8ACDCBB@DDDACDBDCCACDCDCBCBBCBCB8CBEDCDBBC8CDBAABBACCCAABBC@C6@C7A@BB6BAACC6AB@BA?B@>@?     NM:i:0  MD:Z:100        AS:i:100        XS:i:85 RG:Z:DP8400027238TL_L01_358     XA:Z:chr19,-246165,100M,3;      MC:Z:47S53M      MQ:i:14

**Comment by hongwingl** [comment]
From one of the read, the SA tag shows: `SA:Z:chr8,205582,+,64M36S,14,3;`
Which means there should be a supplementary alignment that aligns to chr8,205582. That one seems to be missing. I can make Teal complete even if some read group cannot be completed I supposed. It is not really a show stopper.

**Comment by hongwingl** [comment]
I have made a new release of Teal that addresses this issue and also the number format parsing problem you raised in the other ticket.

**Comment by YingYa** [comment]
The number format parsing problem seems not not solved:
Exception in thread "main" java.lang.IllegalArgumentException: Column meanReadsPerKb is of type INTEGER and cannot be cast to DOUBLE. Use the method for INTEGER.
        at tech.tablesaw.api.Row$ColumnMap.throwWrongTypeError(Row.java:65)
        at tech.tablesaw.api.Row$ColumnMap.get(Row.java:45)
        at tech.tablesaw.api.Row.setDouble(Row.java:641)
        at com.hartwig.hmftools.teal.tellength.TelomereLengthCalc.writeTelLengthTsv(TelomereLengthCalc.kt:208)
        at com.hartwig.hmftools.teal.tellength.TelLengthApp.calcTelomereLength(TelLengthApp.kt:84)
        at com.hartwig.hmftools.teal.TealApplication$StandaloneMode.run(TealApplication.kt:93)
        at com.hartwig.hmftools.teal.TealApplication$PipelineMode.run(TealApplication.kt:191)
        at com.hartwig.hmftools.teal.TealApplication$Companion.main(TealApplication.kt:286)
        at com.hartwig.hmftools.teal.TealApplication.main(TealApplication.kt)

**Comment by hongwingl** [comment]
Thanks for reporting this. I made a new release (Teal v1.0.1) to fix this bug.

**Comment by YingYa** [comment]
Thanks, the issues have been solved,
