### ISSUE TITLE
Release, git tag, and assets for compar v1.0

### ISSUE THREAD

**Issue by scwatts** [hartwigmedical/hmftools#294]
Hi, I've found that the GitHub release and git tag for compar v1.0 seem to be missing. Out of curiosity, are you using any other tooling internally for regression testing? We're building a framework to generate reports to serve that purpose and others, and would like to incorporate compar or similar in some capacity.

**Comment by p-priestley** [comment]
The aim of compar is cohort wide regression testing when we upgrade our pipleine and rerun tools. We have just been testing this internally.   A tagged release and readme will be available soon.

**Comment by charlesshale** [comment]
https://github.com/hartwigmedical/hmftools/releases/tag/compar-v1.0
