### ISSUE TITLE
PURPLE - Empty gene copy number file 

### ISSUE THREAD

**Issue by PFonseca21** [hartwigmedical/hmftools#295]
Hi! I have run purple in order to generate a CNV file required as input for Lilac. It has not shown any error message, but the copy number file (sample.purple.cnv.gene.tsv) comes out empty.

I have used the set of arguments showed below:

`java -jar purple.jar  -reference LINFOM9  -tumor FFPEM9 \
 -no_charts \
 -output_dir /mnt/netapp1/posadalab/Pembro/HLA/purple/Purple_out/M9_2 \
 -amber /mnt/netapp1/posadalab/Pembro/HLA/amber/OutputM9  \
 -cobalt /mnt/netapp1/posadalab/Pembro/HLA/cobalt/OutputM9 \
 -gc_profile /mnt/netapp1/posadalab/Pembro/HLA/purple/GC_profile.1000bp.37.cnp  \
 -ref_genome /mnt/netapp1/posadalab/phylocancer/RESOURCES/hs37d5.fa    \
 -somatic_vcf /mnt/netapp1/posadalab/Pembro/HLA/sage/OutputM9/M9.sage.vcf.gz \
 -ensembl_data_dir /mnt/netapp1/posadalab/Pembro/HLA/sage/ensembl-vepa`

I believe I may have to specify the location of the HMF gene panel, but I did not find the corresponding argument for that purpose. 
Thank you in advance

**Comment by p-priestley** [comment]
I guess it is probably the ensembl_data_dir since that defines the genes that will end up in that tsv file.  

What version of purple are you running?

**Comment by PFonseca21** [comment]
I am running purple version 3.3. As for the ensemble_data_dir, I downloaded the repository from https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html

**Comment by charlesshale** [comment]
Purple requires the Ensembl data cache from the HMF Resources page:

https://resources.hartwigmedicalfoundation.nl/

**Comment by PFonseca21** [comment]
Thannk you, I hadn't noticed. I proceeded to replace the Ensembl data cache with the one from the HMF Resources page and I can confirm it worked. 

Sorry for the inconvenience and thank you for your help.
