### ISSUE TITLE
Does variant calling using SAGE 3.0 necessitate creating new PONs?

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#296]
Do you use your previous PONs created using SAGE 2.X for annotating and filtering variants called using SAGE 3?

**Comment by p-priestley** [comment]
Yes.  That is correct

It is possible that there may be some new artefacts that are specific to Sage 3, so we will probably regenerate at some stage, but I think it should suffice for 99% of the filtering
