### ISSUE TITLE
GRIPSS changing variant coordinates

### ISSUE THREAD

**Issue by stsergbg** [hartwigmedical/hmftools#299]
Hi!

I have run GRIPSS over a small test GRIDSS output file and noticed that some of the variants (judged by variant ID) changed their coordinates. Is this the intended behaviour? I was expecting that GRIPSS only filters all-sv file retaining only somatic variants. This complicates vcf merging and comparison a little (e.g. for germline variant selection).

GRIDSS output file
`11      94975791        gridss24ff_1o   G       G]11:94987896]  761.10  PASS    ANRP=20;ANRPQ=400.58;ANSR=0;ANSRQ=0.00;AS=1;ASC=195M65D1X70N1X;ASQ=120.17;ASRP=12;ASSR=0;BA=0;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm24-19,asm24-8;BEIDH=0,2;BEIDL=2,0;BQ=0.00;BSC=0;BSCQ=0.00;BUM=0;BUMQ=0.00;BVF=0;CAS=0;CASQ=0.00;CIPOS=-35,36;CIRPOS=-34,35;CQ=761.10;EVENT=gridss24ff_1;IC=0;IMPRECISE;IQ=0.00;MATEID=gridss24ff_1h;MQ=37.36;MQN=25.00;MQX=60.00;RAS=1;RASQ=120.17;REF=279;REFPAIR=176;RP=26;RPQ=520.75;SC=260M1X70N1X;SR=0;SRQ=0.00;SVTYPE=BND;VF=26    GT:AF:ANRP:ANRPQ:ANSR:ANSRQ:ASQ:ASRP:ASSR:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF    .:0.00:0:0.00:0:0.00:0.00:0:0:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:0.00:0.00:21:14:0:0.00:0:0.00:0 .:0.058:10:200.29:0:0.00:60.09:6:0:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:380.55:60.09:129:81:13:260.38:0:0.00:13    .:0.058:10:200.29:0:0.00:60.09:6:0:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:380.55:60.09:129:81:13:260.38:0:0.00:13`

GRIPSS output
`11      94975756        gridss24ff_1o   T       T]11:94987862]  380.55  imprecise;minQual       ANRP=20;ANRPQ=400.58;ANSR=0;ANSRQ=0.00;AS=1;ASC=195M65D1X70N1X;ASQ=120.17;ASRP=12;ASSR=0;BA=0;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm24-19,asm24-8;BEIDH=0,2;BEIDL=2,0;BQ=0.00;BSC=0;BSCQ=0.00;BUM=0;BUMQ=0.00;BVF=0;CAS=0;CASQ=0.00;CIPOS=0,71;CIRPOS=0,69;CQ=761.10;EVENT=gridss24ff_1;EVENTTYPE=INV;IC=0;IMPRECISE;IQ=0.00;LOCAL_LINKED_BY;MATEID=gridss24ff_1h;MQ=37.36;MQN=25.00;MQX=60.00;RAS=1;RASQ=120.17;REALIGN;REF=279;REFPAIR=176;REMOTE_LINKED_BY;RP=26;RPQ=520.75;SC=260M1X70N1X;SR=0;SRQ=0.00;SVTYPE=BND;TAF=0.0583;VF=26      GT:AF:ANRP:ANRPQ:ANSR:ANSRQ:ASQ:ASRP:ASSR:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF    .:0.00:0:0.00:0:0.00:0.00:0:0:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:0.00:0.00:21:14:0:0.00:0:0.00:0 .:0.058:10:200.29:0:0.00:60.09:6:0:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:380.55:60.09:129:81:13:260.38:0:0.00:13    .`

Sergey

**Comment by p-priestley** [comment]
Hello,

This is intended behaviour.   For details of why, please see this part of the readme: https://github.com/hartwigmedical/hmftools/tree/master/gripss#2-realignment

You can match by id column to the original.   

Peter
