### ISSUE TITLE
90 Percent of Genes Not Diploid

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#30]
I imported the Gene CNV file into R and rounded the MinCopyNumber column to one decimal place. The distribution of copy numbers is weird.

```r
-0.1    0  0.1  1.2  1.9    2  2.1  2.8  2.9    3  3.1  3.3  3.7  3.8  3.9    4  4.2  4.6  4.7  4.8  4.9    5  5.3  5.4  5.9    6    7    8 
   1    4    1    2  131 1116  989  857 1308 2439 3723    1  838  344 3310 3399  758  110   13  836    1 3688    1    3  319  939  211   75 
```

A copy number of two is quite rare and a copy number of 5 is most common. If we consider, 1.9, 2, and 2.1 as being diploid, I find that 91.2 percent of genes are not diploid.

```r
> table(round(CNV$MinCopyNumber, 1) < 1.9 | round(CNV$MinCopyNumber, 1) > 2.1)
FALSE  TRUE 
 2236 23181 
> 23181 / (23181 + 2236)
[1] 0.912
```

This seems implausible. I ran PURPLE version 2.21 using default parameters.

**Comment by p-priestley** [comment]
This is not atypical in metastatic cancer and likely reflects a whole genome duplication (WGD).   We found that 56% of tumors in our metastatic cohort have a WGD (https://www.biorxiv.org/content/10.1101/415133v2).    

I cannot judge from the information you have given if the fit looks good or not.   However, Purple produces several plots in the plot directory which allow you to view characteristics of the fit.  Perhaps interesting to look at these, particularly the circos pictures.   If you want assistance with interpretation of your input and output circos, you can share with me privately at p.priestley@hartwigmedicalfoundation.nl

**Comment by p-priestley** [comment]
For further diagnosis it would be helpful to get the purity output:

cat *.purple.purity

**Comment by DarioS** [comment]
Thanks for your generous offer to provide diagnosis. The purity summary is

```
#Purity	NormFactor	Score	DiploidProportion	Ploidy	Gender	Status	PolyclonalProportion	MinPurity	MaxPurity	MinPloidy	MaxPloidy	MinDiploidProportion	MaxDiploidProportion	Version	SomaticDeviation
0.3300	0.7600		0.4437	0.0153			3.8884	MALE	NORMAL	0.0679			0.3100		0.3600		3.8804		3.9474		0.0103			0.0153			2.21	0.0000
```

and the plots I found are 

![image](https://user-images.githubusercontent.com/631218/54735357-d55b9680-4bf9-11e9-824e-28b0ed4d6798.png)

![image](https://user-images.githubusercontent.com/631218/54735366-e4424900-4bf9-11e9-8f66-8a4fda8dab60.png)

![image](https://user-images.githubusercontent.com/631218/54735370-edcbb100-4bf9-11e9-8a5e-0e2b1fc161b6.png)

The Circos files are in [circFiles.zip](https://github.com/hartwigmedical/hmftools/files/2990974/circFiles.zip)

> 56% of tumors in our metastatic cohort have a WGD

I overlooked it. It's a very interesting result but it's worth mentioning that this sample is a primary tumour.

**Comment by jonbaber** [comment]
I have generated the output circos for you...
![SP15-022713cancer circos](https://user-images.githubusercontent.com/27909546/54735859-16e94300-4bf4-11e9-9e71-d854e65fe1df.png)

**Comment by p-priestley** [comment]
Dario, this fit looks good to me.    

• You can see integer peaks in the copy number at ploidy 2,3,4,5,6,7& 8 (as well as some evidence of subclonality).   The next most plausible solution would be to assume a higher purity and halve the ploidy, but this would require the large peaks at 3,5 and 7 to all be subclonal at a 50% cellular fraction which is unlikely since they exist across many chromosomes.
• Major allele ploidy also has integer peaks
* PURPLE reports a tight min-max purity and ploidy range which means that it is confident about the solution.

If you wanted to improve confidence further you could supply a somatic SNV vcf to PURPLE.   We use Strelka for this, but it should work as long as your vcf contains the AD field which most do.   If the fit is correct, you should be able to see clear peaks in somatic ploidies (top chart above) at ploidy 1 and likely ploidy 2 (for variants which occurred before the genome duplication).     

Using a somatic vcf will also improve the circos output and the fit itself (particularly if there is little aneuploidy).

**Comment by p-priestley** [comment]
A description of the circos output can be found here:

https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#output

**Comment by DarioS** [comment]
That sounds good to me. I will relabel all of the somatic VCFs produced by Strelka2 using `sed` because Strelka2 doesn't have a command-line parameter for the user to specify the sample identifier, so the sample name is always SAMPLE1 by default and then I will input it to PURPLE.

I wonder if the Whole Genome Duplication rule could be added as output into any one of PURPLE's text files, such as the QC file, which already has some similar details. The new statistic could look like `WholeGenomeDuplicated true`. I guess that I could get close to the same answer using a rule based on DiploidProportion and Ploidy from the QC file, but not the same.

Also, for Figure 2D of your journal article, could you add percentage integers next to each dark blue bar for each Cancer Type? The 55.9% (overall statistic) in the Mesothelioma row would need to be moved out of the plot to the top plot margin. For example

![image](https://user-images.githubusercontent.com/631218/54736617-1fe01180-4c00-11e9-841b-7ebea06edf81.png)

**Comment by p-priestley** [comment]
We will at some point add WGD=T/F to our output.  An approximate rule of thumb is that if sample ploidy > 2.7 then it is likely that a WGD has occurred.    

We will consider your suggestion for the charts.   Will close this for now.
