### ISSUE TITLE
hotspot fusions not annotated

### ISSUE THREAD

**Issue by abelhj** [hartwigmedical/hmftools#304]
Hi,
I have several cases with known hotspot fusion variants, that are contained in the KnownFusionPairs.bedpe but are not being annotated in my output (gripssv2.1).  

e.g., 

`chr9	130773120	gridss667bf_2384o	A	]chr22:23291512]A	2352.92	PASS	AS=1;ASC=1X347M;ASQ=832.40;ASRP=56;ASSR=44;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm1140-27954,asm667-65973;BEIDH=0,0;BEIDL=348,377;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=118.52;BSC=7;BSCQ=118.52;BUM=0;BUMQ=0.00;BVF=0;CAS=0;CASQ=0.00;CQ=2483.64;EVENT=gridss667bf_2384;EVENTTYPE=BND;IC=0;IHOMPOS=0,0;IQ=0.00;LOCAL_LINKED_BY=dsb23800;MATEID=gridss667bf_2384h;MQ=57.12;MQN=28.00;MQX=60.00;RAS=1;RASQ=957.31;REF=103;REFPAIR=12;REMOTE_LINKED_BY=dsb23801;RP=28;RPQ=473.97;SB=0.71428573;SC=1X347M;SR=12;SRQ=239.90;SVTYPE=BND;TAF=0.3628;VF=44	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:45.93:4:3:0:0.00:0:0.00:0.00:0:0:0.00:0:0.00:0:0.00:0:0.00:0:0.00:150.67:58.82:42:1:2:28.18:1:17.74:3	.:786.47:52:41:0:0.00:0:0.00:0.00:0:0:118.52:7:118.52:0:0.00:0:0.00:0:0.00:2352.92:898.50:61:11:26:445.79:11:222.16:41
chr9	130773123	gridss667fb_3401o	C	C[chr22:23291519[	2377.95	PASS	AS=1;ASC=381M1X;ASQ=786.06;ASRP=63;ASSR=36;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm1140-57080,asm667-25850;BEIDH=382,382;BEIDL=0,0;BMQ=58.40;BMQN=44.00;BMQX=60.00;BQ=198.55;BSC=8;BSCQ=138.21;BUM=2;BUMQ=60.34;BVF=2;CAS=0;CASQ=0.00;CQ=2437.96;EVENT=gridss667fb_3401;EVENTTYPE=BND;IC=0;IHOMPOS=0,0;IQ=0.00;LOCAL_LINKED_BY=dsb23800;MATEID=gridss667fb_3401h;MQ=58.05;MQN=29.00;MQX=60.00;RAS=1;RASQ=1004.06;REF=112;REFPAIR=12;REMOTE_LINKED_BY=dsb23801;RP=30;RPQ=511.32;SB=0.47058824;SC=381M1X;SR=7;SRQ=136.53;SVTYPE=BND;TAF=0.3445;VF=42	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:14.09:2:1:0:0.00:0:0.00:0.00:0:0:29.81:0:0.00:1:29.81:1:0.00:0:0.00:60.02:31.83:45:1:1:14.09:0:0.00:1	.:771.96:61:35:0:0.00:0:0.00:0.00:0:0:168.75:8:138.21:1:30.53:1:0.00:0:0.00:2377.95:972.23:67:11:29:497.22:7:136.53:41
chr22	23291512	gridss667bf_2384h	C	C[chr9:130773120[	2352.92	PASS	AS=1;ASC=376M1X;ASQ=957.31;ASRP=56;ASSR=44;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm1140-27954,asm667-65973;BEIDH=348,377;BEIDL=0,0;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=243.44;BSC=13;BSCQ=243.44;BUM=0;BUMQ=0.00;BVF=0;CAS=0;CASQ=0.00;CQ=2483.64;EVENT=gridss667bf_2384;EVENTTYPE=BND;IC=0;IHOMPOS=0,0;IQ=0.00;LOCAL_LINKED_BY=dsb23801;MATEID=gridss667bf_2384o;MQ=57.12;MQN=28.00;MQX=60.00;RAS=1;RASQ=832.40;REF=83;REFPAIR=15;REMOTE_LINKED_BY=dsb23800;RP=28;RPQ=473.97;SB=0.73913044;SC=376M1X;SR=12;SRQ=239.90;SVTYPE=BND;TAF=0.4505;VF=44	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:58.82:4:3:0:0.00:0:0.00:0.00:0:0:12.89:1:12.89:0:0.00:0:0.00:0:0.00:150.67:45.93:43:5:2:28.18:1:17.74:3	.:898.50:52:41:0:0.00:0:0.00:0.00:0:0:230.55:12:230.55:0:0.00:0:0.00:0:0.00:2352.92:786.47:40:10:26:445.79:11:222.16:41
chr22	23291519	gridss667fb_3401h	G	]chr9:130773123]G	2377.95	PASS	AS=1;ASC=1X417M;ASQ=1004.06;ASRP=63;ASSR=36;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm1140-57080,asm667-25850;BEIDH=0,0;BEIDL=382,382;BMQ=59.06;BMQN=43.00;BMQX=60.00;BQ=375.91;BSC=15;BSCQ=284.31;BUM=3;BUMQ=91.60;BVF=0;CAS=0;CASQ=0.00;CQ=2437.96;EVENT=gridss667fb_3401;EVENTTYPE=BND;IC=0;IHOMPOS=0,0;IQ=0.00;LOCAL_LINKED_BY=dsb23801;MATEID=gridss667fb_3401o;MQ=58.05;MQN=29.00;MQX=60.00;RAS=1;RASQ=786.06;REF=78;REFPAIR=16;REMOTE_LINKED_BY=dsb23800;RP=30;RPQ=511.32;SB=0.36206895;SC=1X417M;SR=7;SRQ=136.53;SVTYPE=BND;TAF=0.4659;VF=42	GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF	.:31.83:2:1:0:0.00:0:0.00:0.00:0:0:17.74:1:17.74:0:0.00:0:0.00:0:0.00:60.02:14.09:42:5:1:14.09:0:0.00:1	.:972.23:61:35:0:0.00:0:0.00:0.00:0:0:358.17:14:266.57:3:91.60:0:0.00:0:0.00:2377.95:771.96:36:11:29:497.22:7:136.53:41`

Where the bedpe entry is:
`chr22	23169703	23318037	chr9	130703945	130887675	BCR-ABL1	0	+	-	chr22	chr9`

Some of the known fusions in my samples are being annotated as HOTSPOT (only for 1 fusion, though, the others are being missed).  Thanks

**Comment by p-priestley** [comment]
This looks problematic.   Let us try this and get back to you.

**Comment by abelhj** [comment]
I tried sorting the existing file (sort -k1,1V -k2,2n ) and that did not appear to fix the issue.

**Comment by charlesshale** [comment]
I've just uploaded a fixed v38 BEDPE file to HMF Tool-Resources -> Known-Fusions -> 38.

I've checked those breakends included in the ticket above and it is now correctly marking the 2384 variant as 'HOTSPOT'.

chr9    130773120       gridss667bf_2384o       A       ]chr22:23291512]A       2352.92 PASS    AS=1;ASC=1X347M;ASQ=832.40;ASRP=56;ASSR=44;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm1140-27954,asm667-65973;BEIDH=0,0;BEIDL=348,377;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=118.52;BSC=7;BSCQ=118.52;BUM=0;BUMQ=0.00;BVF=0;CAS=0;CASQ=0.00;CQ=2483.64;EVENT=gridss667bf_2384;EVENTTYPE=BND;HOTSPOT;IC=0;IHOMPOS=0,0;IQ=0.00;LOCAL_LINKED_BY=dsb1;MATEID=gridss667bf_2384h;MQ=57.12;MQN=28.00;MQX=60.00;RAS=1;RASQ=957.31;REF=103;REFPAIR=12;REMOTE_LINKED_BY=dsb2;RP=28;RPQ=473.97;SB=0.71428573;SC=1X347M;SR=12;SRQ=239.90;SVTYPE=BND;TAF=0.3628;VF=44 GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF   .       .:786.47:52:41:0:0.00:0:0.00:0.00:0:0:118.52:7:118.52:0:0.00:0:0.00:0:0.00:2352.92:898.50:61:11:26:445.79:11:222.16:41

chr22   23291512        gridss667bf_2384h       C       C[chr9:130773120[       2352.92 PASS    AS=1;ASC=376M1X;ASQ=957.31;ASRP=56;ASSR=44;BA=0;BANRP=0;BANRPQ=0.00;BANSR=0;BANSRQ=0.00;BAQ=0.00;BASRP=0;BASSR=0;BEID=asm1140-27954,asm667-65973;BEIDH=348,377;BEIDL=0,0;BMQ=60.00;BMQN=60.00;BMQX=60.00;BQ=243.44;BSC=13;BSCQ=243.44;BUM=0;BUMQ=0.00;BVF=0;CAS=0;CASQ=0.00;CQ=2483.64;EVENT=gridss667bf_2384;EVENTTYPE=BND;HOTSPOT;IC=0;IHOMPOS=0,0;IQ=0.00;LOCAL_LINKED_BY=dsb2;MATEID=gridss667bf_2384o;MQ=57.12;MQN=28.00;MQX=60.00;RAS=1;RASQ=832.40;REF=83;REFPAIR=15;REMOTE_LINKED_BY=dsb1;RP=28;RPQ=473.97;SB=0.73913044;SC=376M1X;SR=12;SRQ=239.90;SVTYPE=BND;TAF=0.4505;VF=44 GT:ASQ:ASRP:ASSR:BANRP:BANRPQ:BANSR:BANSRQ:BAQ:BASRP:BASSR:BQ:BSC:BSCQ:BUM:BUMQ:BVF:CASQ:IC:IQ:QUAL:RASQ:REF:REFPAIR:RP:RPQ:SR:SRQ:VF   .       .:898.50:52:41:0:0.00:0:0.00:0.00:0:0:230.55:12:230.55:0:0.00:0:0.00:0:0.00:2352.92:786.47:40:10:26:445.79:11:222.16:41

The release of Gripss (v2.2) will automatically sort these entries to avoid issues in the file.

**Comment by scwatts** [comment]
Apologies for the unintended commit reference to this issue.
