### ISSUE TITLE
PAVE and mappability_bed argument

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#309]
I used PAVE with the -mappability_bed argument and the mappability bed (out_150.mappability.38.bed.gz) from the HMF Resources page, but besides an entry in the headers, no variants were annotated for MAPPABILITY.

Looking at the Mappability.java code under PAVE, it seems to be expecting a four column non-standard bed rather than the one in the resources, which has five columns (chromosome, start, end, entry name, value). It looks like it probably fails to annotate silently rather than give any warning about the column number in the "bed" not matching.

**Comment by charlesshale** [comment]
Apologies for that - the HMF Tools-Resources mappability files have just now been updated (named mappability_150.37.bed.gz and mappability_150.38.bed.gz).

Pave will fail to run on an invalid file in the next release.
