### ISSUE TITLE
File format TUMOR.purple.cnv.somatic.tsv

### ISSUE THREAD

**Issue by hylkedonker** [hartwigmedical/hmftools#312]
Hi,

I was wondering what copy number file format PURPLE is currently producing for `TUMOR.purple.cnv.somatic.tsv`. The README file indicates that PURPLE produces fields such as `MinorAllelePloidy`. But in the copy number files of my Hartwig data request I have columns such as `minorAlleleCopyNumber`. Are the fields in my data request outdated, or is the readme?

I am asking since I plan to integrate support for the PURPLE CNV format in an other package.

Thanks,

Hylke

**Comment by charlesshale** [comment]
I've been through each Purple output file and updated the READ-ME. Thanks for picking up these differences.
