### ISSUE TITLE
Cannot find somatic SNV/INDEL PON

### ISSUE THREAD

**Issue by DarraghNimmo1** [hartwigmedical/hmftools#314]
Hi,

I cannot find the Hartwig panel of normals for somatic SNV/INDEL variant calling.

I have searched through the external resources repository https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources however I do not see it in there?

Thanks in advance,
Darragh

**Comment by p-priestley** [comment]
Please look in the directory  Sage/37/    or Sage/38/  for the SageGermlinePon file
