### ISSUE TITLE
germline vs somatic LiLac HLAtyping

### ISSUE THREAD

**Issue by Biojenifer** [hartwigmedical/hmftools#317]
Hi!

I am running LiLaC specifying both the reference and the tumour bam. If I understood well, as I am running it I am getting germline alleles. Is this correct? Then, in case of not indicating a copy number or a somatic mutation file, would LiLac extract some information from the tumour bam?

My commands are those, but I am wondering if I should first run lilac indicating the reference bam and, then, not indicating it, in order to check if the tumour has different alleles.

```
java -jar lilac.jar \
-sample A \
-ref_genome hs37d5.fa \
-resource_dir /mnt/lustre/lilac1/ \
-reference_bam /mnt/lustre/linfoA/aligned.sorted.marked_duplicates.bam \
-tumor_bam /mnt/lustre/tumA/aligned.sorted.marked_duplicates.bam \
-somatic_variants_file /mnt/lustre/tumA.mutect2.vcf \
-gene_copy_number_file /mnt/lustre/tumA.purple.cnv.gene.tsv \
-log_debug \
-output_dir ../tumA
```

Thanks!

**Comment by p-priestley** [comment]
Yes.   As per the readme (https://github.com/hartwigmedical/hmftools/tree/master/lilac)  Lilac will predict alleles based off the reference bam but also report the assignment in the tumor bam using the purple gene data to assign to allelic copy numbers.

If you provide somatic variants then Lilac will also determine whether these are supported in each allele in the tumor.

You can also run with just the tumor.   We have done this on our full cohort and LIlac nearly always predicts the same alleles as if running off the reference (>99.5% concordance).    In this case any somatic variants will just be reported as 'UNMATCHED_HAPLOTYPE'.   In rare cases the somatic variant may cause the allele to look like a different germline allele.
