### ISSUE TITLE
Copy Number Illustration on Sex Chromosomes

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#32]
Looking at the gene CNV output file of PURPLE for a test patient I am analysing, I view the copy number of the sex chromosomes. The genes on the X chromosome have a copy number like 1.9653 and on the Y chromosome like 1.9595 This makes sense because the ploidy of the sample is 3.8884, so the cancer sample is tetraploid, so the ploidy of the sex chromosomes is about double compared to a normal sample. However, in the CIRCOS plot, there is no green rectangle or orange rectangle shown. I would expect to see a green rectangle of height 1 to indicate there's one more X and Y chromosome than usual. This probably also applies to the example CIRCOS plot in the Readme.md file for PURPLE. It seems that the plot is incorrectly using a baseline of 2 copies for the sex chromosomes. The patient is inferred to be male, so the baseline should be 1 for the X and the Y chromosome.

**Comment by p-priestley** [comment]
Dario - we are aware for MALE samples that this is the case.  The numbers are all accurately presented though and we think this is less confusing then changing the chart specifically for these chromosomes in  MALE samples only.

I am closing this as WONT FIX.
