### ISSUE TITLE
HMF demo pipeline Sage error

### ISSUE THREAD

**Issue by gbnci** [hartwigmedical/hmftools#320]
Good afternoon:
I am trying to run the pipeline with your COLO829T testing data set, but just could not get it work. I am kind of sure I have downloaded all files and put everything in their right directories, but still could not generate any result. one error I saw is like this (between two lines of "###")
############################################
[wangyong@cn0847 HMF]$ /data/wangyong/HMF/scripts/run_pipeline /data/wangyong/HMF/scripts /data/wangyong/HMF/data /data/wangyong/HMF/DNA-Resources  /data/wangyong/HMF/tools "COLO829T,COLO829R"  V37 5 
Environment:
  scripts dir: /data/wangyong/HMF/scripts
  samples dir: /data/wangyong/HMF/data
  resources dir: /data/wangyong/HMF/DNA-Resources
  tools dir: /data/wangyong/HMF/tools
  tumorId: COLO829T
  referenceId: COLO829R
  ref genome version: V37
  threads: 5
Sample output dir: /data/wangyong/HMF/data/COLO829T
Reference genome version GRCh37
Running Sage somatic for COLO829T, output dir /data/wangyong/HMF/data/COLO829T/sage_somatic
14:40:59.636 [INFO ] Sage version: 3.0
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "geneDataList" is null
	at com.hartwig.hmftools.common.hla.HlaCommon.populateGeneData(HlaCommon.java:29)
	at com.hartwig.hmftools.sage.ReferenceData.<init>(ReferenceData.java:64)
	at com.hartwig.hmftools.sage.SageApplication.<init>(SageApplication.java:62)
	at com.hartwig.hmftools.sage.SageApplication.main(SageApplication.java:167)
..............
#############################
I am not sure what caused the "geneDataList" is null (maybe I missed some files). Another question I have is why I can't find ref-genome for Hg38 (only found "ref_genome_37.tar.gz"), which I will use it eventually for my data. Just for your information, I use java/15.0.2 today. I also tried java/17.0.2, I got the same error.
Just want to make sure. I downloaded all jar files and put in "tools" directory, but not sure how to handle "glidss", but I also downloaded them all and put them in the "tools" directory too.  HMFTools-resources was downloaded but only unzip the DNA resources files (is it necessary?), not sure whether I also need to upzip all zipped files inside HMFTools-resources folder. All scripts were downloaded and placed in the "scripts" folder.
Any suggestions about my problems?
Thanks

**Comment by charlesshale** [comment]
That error is occurring because the 3 HLA genes (HLA-A, HLA-B, HLA-C) are not being found in the Ensembl data cache. That will be due to one of 2 reasons:

- the Ensembl files are not being found in /data/wangyong/HMF/DNA-Resources/common/ensembl_data/
- the ref genome version is inconsistent with the reference files in /data/wangyong/HMF/DNA-Resources/ - ie they should be the GRCh37 files given you've passed in V37 into the pipeline command above

Could you check those 2 things and see if that error persists?

**Comment by gbnci** [comment]
Hello, Charles:
Thank you very much for your suggestions. I am assuming I should use “HMFTools-Resources” instead of using “DNA_Resources”. Even though, after I changed to “HMFTools-Resources” in the command line, I still got the same error. The contents inside ““HMFTools-Resources” are downloaded from github, which includes many sub-folders like:
Amber
DNA-Resources
GIAB-High-Conf 
Isofox        
Linx           
Orange     
Repeatmasker 
Virus-Interpreter 
Cobalt 
Ensembl-Data-Cache 
GRIDSS         
Known-Fusions 
Mappability    
Peach      
Sage 
Cuppa  
Gene Panel         
Gripss         
Lilac         
Older-Versions 
ref_genome 
Serve
 
There is nowhere that I can find “common/ensembl_data” as suggested in your email except that I did find “Ensembl-Data-Cache” inside “HMFTools-Resources”. If this is the correct data directory, how can I implement this into the command line? As for the V37 referance genome, within the “HMFTools-Resources”, there is a folder “ref_genome” which contains the reference information for V37.
 
Another question is regarding to the “hmftools-master” folder I downloaded from your github. I am not sure whether I should also implement the contents from this “hmftools-master” folder in order to make this work?
Here is the command line I used:
 
/data/wangyong/HMF/scripts/run_pipeline /data/wangyong/HMF/scripts /data/wangyong/HMF/data /data/wangyong/HMF/HMFTools-Resources  /data/wangyong/HMF/tools "COLO829T,COLO829R"  V37 5
 
All the jar files downloaded are in the tools directory (/data/wangyong/HMF/tools), all scripts including “run_pipeline” are in the scripts directory (/data/wangyong/HMF/scripts).
 
Very appreciated for your help

**Comment by gbnci** [comment]
I checked the code of "run-pipeline", seems many of the files required are not in the resource file directory required by the code. I am wondering whether or where can I download all the standard files so that I can put them in the resources file directory?
Thanks

**Comment by charlesshale** [comment]
Yes you can download the files for v37 and v38 as a single TAR file here:

https://resources.hartwigmedicalfoundation.nl/
then see DNA-Resources

**Comment by gbnci** [comment]
Hello, Charles:
Thank you very much for your suggestions. I am assuming I should use “HMFTools-Resources” instead of using “DNA_Resources”. Even though, after I changed to “HMFTools-Resources” in the command line, I still got the same error. The contents inside ““HMFTools-Resources” are downloaded from github, which includes sub-folders like:
Amber
DNA-Resources
GIAB-High-Conf
Isofox
Linx
Orange
Repeatmasker
Virus-Interpreter
Cobalt
Ensembl-Data-Cache
GRIDSS
Known-Fusions
Mappability
Peach
Sage
Cuppa
Gene Panel
Gripss
Lilac
Older-Versions
ref_genome
Serve

There is nowhere that I can find “common/ensembl_data” as suggested in your email except that I did find “Ensembl-Data-Cache” inside “HMFTools-Resources”. If this is the correct data directory, how can I implement this into the command line? As for the V37 referance genome, within the “HMFTools-Resources”, there is a folder “ref_genome” which contains the reference information for V37.

Another question is regarding to the “hmftools-master” folder I downloaded from your github. I am not sure whether I should also implement the contents from this “hmftools-master” folder in order to make this work?
Here is the command line I used:

/data/wangyong/HMF/scripts/run_pipeline /data/wangyong/HMF/scripts /data/wangyong/HMF/data /data/wangyong/HMF/HMFTools-Resources  /data/wangyong/HMF/tools "COLO829T,COLO829R"  V37 5

All the jar files downloaded are in the tools directory (/data/wangyong/HMF/tools), all scripts including “run_pipeline” are in the scripts directory (/data/wangyong/HMF/scripts).

Very appreciated for your help


From: charlesshale ***@***.***>
Reply-To: hartwigmedical/hmftools ***@***.***>
Date: Monday, August 8, 2022 at 11:39 PM
To: hartwigmedical/hmftools ***@***.***>
Cc: "Wang, Yonghong (NIH/NCI) [E]" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [hartwigmedical/hmftools] testing run (Issue #320)


That error is occurring because the 3 HLA genes (HLA-A, HLA-B, HLA-C) are not being found in the Ensembl data cache. That will be due to one of 2 reasons:

  *   the Ensembl files are not being found in /data/wangyong/HMF/DNA-Resources/common/ensembl_data/
  *   the ref genome version is inconsistent with the reference files in /data/wangyong/HMF/DNA-Resources/ - ie they should be the GRCh37 files given you've passed in V37 into the pipeline command above

Could you check those 2 things and see if that error persists?

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhartwigmedical%2Fhmftools%2Fissues%2F320%23issuecomment-1208873860&data=05%7C01%7Cwangyong%40mail.nih.gov%7C9eb639dfa9cc4b8faa0a08da79b8c6ab%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637956131770802128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=udjqXrB5NjVxoZ7uqw79IFgT%2FTkPxidjGoZPFrM7Ntc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI62R6HWO7BOTUZ7CFRIDBLVYHHHJANCNFSM55BVYKPA&data=05%7C01%7Cwangyong%40mail.nih.gov%7C9eb639dfa9cc4b8faa0a08da79b8c6ab%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637956131770802128%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9x7uLUrPzE8SEG7osSaCkFk1Nk%2BDh7JQhwF5mKCBi9s%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by charlesshale** [comment]
The resource files for our pipeline are all zipped up in a single TAR file now, not in separate directories. 

To find these, go to website: https://resources.hartwigmedicalfoundation.nl/
Then click on HMFTools-Resources, then click on DNA-Resources

If you unzip this, there will be a directory called 'common' and within that one with the Ensembl data files.

The reference genome is not included in that zipped TAR file (due to its size) and needs to be manually added to a  ref_genome directory at the same level as the other resource directories.

There is no need to download or clone our git repo to get the tools, only the pipeline script files. Links to the latest JARs for the tools can be found on our landing page for hmftools (ie https://github.com/hartwigmedical/hmftools).

Hope that's clearer.
