### ISSUE TITLE
Data Access Issue

### ISSUE THREAD

**Issue by felixbeaudry** [hartwigmedical/hmftools#322]
Hi there,

Really love the packages, very cool work! 

I've been able to run GRIDSS and PURPLE on my local machine, and I went to work on getting LINX to run but it seems I've lost access to the files (eg fragile sites, LINE source regions and replication origins) hosted on https://resources.hartwigmedicalfoundation.nl/ , I instead now land on a login page requesting user sign in. Can I make an account, will this page be available again in the future or do you have recommendations on how to create our own data files?

Thank you for your help!
Felix

**Comment by charlesshale** [comment]
Read-only access to this website should be possible without creating an account. We're investigating what has changed.

thanks

**Comment by charlesshale** [comment]
You should have access again now.

I just release new resource files for our demo pipeline yesterday - see DNA-Resources - hmf_pipeline_resources.37_v5.30.gz and hmf_pipeline_resources.38_v5.30.gz.
