### ISSUE TITLE
GRIPSS on GRIDSS svtypes

### ISSUE THREAD

**Issue by stsergbg** [hartwigmedical/hmftools#324]
Hi!

I have a question regarding GRIDSS output processing with GRIPSS. As far as I get it, GRIPSS was designed specifically for handling GRIDSS output. But in README and in source code of GRIPSS I found parts that refer to DEL, DUP, INS, INV and SGL SVTYPEs. But GRIDSS only produces BND structural variant types. I successfully ran GRIPSS on BND calls but if you have methods of transforming GRIDSS output to have other SVTYPEs I would very much like to know how (not only for GRIPSS filtering purposes but for SV annotation by VEP/nirvana as well). Can you please help me with transforming GRIDSS output in broader SVTYPE format that can be understood by GRIPSS?

Sergey

**Comment by charlesshale** [comment]
The translation is performed the class StructuralVariantFactory:
https://github.com/hartwigmedical/hmftools/blob/master/hmf-common/src/main/java/com/hartwig/hmftools/common/sv/StructuralVariantFactory.java

and the method:
public static StructuralVariant create(@NotNull VariantContext first, @NotNull VariantContext second)

**Comment by stsergbg** [comment]
Thank you! I see, so GRIPSS does the SVTYPE inference inside. Is this information retained on disk in any temporary GRIPSS files?

**Comment by charlesshale** [comment]
Not in any Gripss files, no. It is written to the structuralVariant table in our MySQL hmf_patients DB.
