### ISSUE TITLE
pave pon Artefact file for 37

### ISSUE THREAD

**Issue by DavyCats** [hartwigmedical/hmftools#325]
In pipeline5 (5.29) a [panel artefact file is mentioned](https://github.com/hartwigmedical/pipeline5/blob/v5.29/cluster/src/main/java/com/hartwig/pipeline/resource/RefGenome37ResourceFiles.java#L118), which is getting [used by pave ](https://github.com/hartwigmedical/pipeline5/blob/v5.29/cluster/src/main/java/com/hartwig/pipeline/tertiary/pave/PaveArguments.java#L21). Based on the code it seems to be getting used regardless of the reference genome version. I can't seem to locate this "PanelArtefacts.37.tsv" amongst the resource files you provide for download and in the pave README it is mentioned this is only used for GRCh38. Is there such a panel artefact file available for GRCh37?

**Comment by p-priestley** [comment]
This is intended for our targeted sequencing implementation only which includes a range of functionalities    We are only offering support on 38 for this

**Comment by DavyCats** [comment]
I see, thanks for the quick response!
