### ISSUE TITLE
How can we identify LOH on some HLA allele in Lilac's output?

### ISSUE THREAD

**Issue by Biojenifer** [hartwigmedical/hmftools#327]
Hi!

I was wondering how can we identify LOH in some HLA allele in Lilac's output. Should we look at TumorCopyNumber column?

For example:

I get a TumorCopyNumber of 0.64 for B*51:01 allele in one of my samples. Does this mean LOH for this allele?

Thanks!

**Comment by p-priestley** [comment]
LILAC leverages PURPLE copy number fitting and assigns to the alleles based on the relative support for each allele.

We normally use a  rule of alleleCopyNumber (ie TumorCopyNumber column) < 0.5  as LOH.    Generally fitted copy number is close to integer, but 0.64 is unclear and could indicate noise, a poor fit or subclonal loss of the allele so in this case it may not be super clear.
