### ISSUE TITLE
typo in COBALT run command in documentation 

### ISSUE THREAD

**Issue by georgiesamaha** [hartwigmedical/hmftools#328]
Hi, 

Just making a note that the example run command in the COBALT README.md has a typo and doesn't currently run: 

https://github.com/hartwigmedical/hmftools/blob/ba93b64b3dc366dcac9634ca90cb5207accd20f3/cobalt/README.md?plain=1#L51-L58

With java/jdk-13.33, gives:
```
Error: -cp requires class path specification
```

Example run command should be:
```
java -Xmx8G -cp cobalt.jar com.hartwig.hmftools.cobalt.CobaltApplication \
    -reference COLO829R -reference_bam /run_dir/COLO829R.bam \ 
    -tumor COLO829T -tumor_bam /run_dir/COLO829T.bam \ 
    -output_dir /run_dir/cobalt \ 
    -threads 16 \ 
    -gc_profile /path/to/GC_profile.1000bp.37.cnp
```

Cheers

**Comment by charlesshale** [comment]
Fixed in the read-me, thanks.
