### ISSUE TITLE
Linx 1.21 com.hartwig.hmftools.linx.visualiser.SvVisualiser [FATAL] error

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#329]
Running Linx 1.21 with:
`	java -cp ${linx_jar} com.hartwig.hmftools.linx.visualiser.SvVisualiser \
		-sample ${tumour_sample} \
		-ensembl_data_dir ${ensembl_data_dir} \
		-plot_out ${linx_dir}/plot/ \
		-data_out ${linx_dir}/circos/ \
		-ref_genome_version ${ref_genome_version} \
		-vis_file_dir ${linx_dir} \
		-circos circos \
		-plot_reportable \
		-threads $threads \
		2>&1 | tee $log_prefix.linx_plot.log`

Previously, Linx 1.19 produced plots with fusions shown, but Linx 1.21 produced plots that appear truncated at the bottom, and the log file contains [FATAL] error lines in each cluster plotting step:
15:44:37 - [FATAL] - Error executing R script. Examine error file /tmp/fusionPlot.R3203441871073751138.error for details.

The error output contains the line:
 `Error in if (is.na(pLegend)) { : the condition has length > 1
Execution halted`

That comes from fusionPlot.R, but that file does not seem to have been modified recently.
As these are now running with R 4.2.1 and recently updated packages, maybe something has changed to produce that error?  Here are the attached packages and versions when I ran fusionPlot.R to try to track down what was happening:

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magick_2.7.3  cowplot_1.1.1 dplyr_1.0.10  tidyr_1.2.1   ggplot2_3.3.6

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9       magrittr_2.0.3   tidyselect_1.1.2 munsell_0.5.0    colorspace_2.0-3 R6_2.5.1         rlang_1.0.5      fansi_1.0.3      grid_4.2.1       gtable_0.3.1     utf8_1.2.2       cli_3.4.0       
[13] DBI_1.1.3        withr_2.5.0      ellipsis_0.3.2   digest_0.6.29    assertthat_0.2.1 tibble_3.1.8     lifecycle_1.0.1  farver_2.1.1     purrr_0.3.4      vctrs_0.4.1      glue_1.6.2       labeling_0.4.2  
[25] compiler_4.2.1   pillar_1.8.1     generics_0.1.3   scales_1.2.1     pkgconfig_2.0.3 `

**Comment by charlesshale** [comment]
The fusionPlot.R script has not been changed for more than a year so I'm wondering the source of the issue lies in the data being passed to the SvVisualiser call. Would you be able to email some sample Linx files that show this error and I can try to reproduce and debug it?

thanks.

**Comment by toddajohnson** [comment]
Hi Charles,

I have done some bug hunting today, and the error that I was seeing seems to come from two problems.

First, in comparing running Linx visualization for 91 reportable SV clusters in one sample that had lots of SVs and fusions, there was a FATAL error in executing fusion plotting in R 4.0.2 in 7/91 clusters versus 85/91 for R 4.2.1.  That huge increase can be traced to the testing and logic for what fusionPlot.R does when nrow(nonUTRProteinDomain) > 0 or not.  When there are no nonUTRProteinDomains, then `pLegend=NA` on line 120 and tested as  `if (is.na(pLegend)) {` on line 135. is.na(pLegend) returns:
grobs	layout	widths	heights	respect	rownames	colnames	name	gp	vp	children	childrenOrder	
FALSE	FALSE	FALSE	FALSE	FALSE	FALSE	FALSE	FALSE	FALSE	FALSE	FALSE	FALSE

The expectation would be that the if statement would just look at the first value and the program keep running, but I checked CRAN, and as of R 4.2.0, testing `if` against an object with length > 1 changed from being a warning to being an error.  Therefore, plots of SV clusters for which the genes have no protein domains should work in R 4.2.0, but those with protein domains (that need the protein domain legend) will throw an error and just the circos sub-panel and not the fusion sub-panel will be plotted.

I tested a change by substituting a modified r/fusionPlot.R file into the jar. Change line 20 from `pLegend = NA` to `pLegend = NULL` and the test on line 135 from `if (is.na(pLegend)) {` to `if (is.null(pLegend)) {`.  Testing the table with is.null just returns a single FALSE.

The second problem related to why 7/91 SV clusters had a FATAL error plotting the fusion sub-panel even in R 4.0.2.  I looked at files with or without the fatal error, and narrowed it down to genes with fusions with breaks within exons.  In those cases, the fusedExons table only contains upGene=TRUE across all rows, while when single genes have exon-exon fusions, with the breaks occurring within introns, those before the break have upGene=TRUE and those after the break have upGene=FALSE.

For instance, one with two exons and  portions of surrounding introns removed:
![cluster-1249 DEL sv1 003](https://user-images.githubusercontent.com/17885404/190084779-426145f5-f60c-441c-a48d-7a629b610ddb.png)

and the fusedExons table:
[cluster_1249_TTYH1_fusion.xlsx](https://github.com/hartwigmedical/hmftools/files/9563621/cluster_1249_TTYH1_fusion.xlsx)

versus one with parts of two exons and the intervening intron removed:
![cluster-1158 DEL sv1 003](https://user-images.githubusercontent.com/17885404/190085285-c4b9aa67-6d9b-48f6-98aa-9b8348954b7a.png)

[cluster_1158_CAMTA2_fusion.xlsx](https://github.com/hartwigmedical/hmftools/files/9563639/cluster_1158_CAMTA2_fusion.xlsx)

 It is possible that there are more complicated situations than what I found that also don't work as expected...

It looks to me like the logic for upGene setting needs to be modified between fusionPlot.R lines 103-107, but that probably also depends on the clusterFusedExons table which comes from *.fusions.tsv and involves calculations from other parts of SVVisualizer.

**Comment by toddajohnson** [comment]
Short version of above:

1. R changed as of R 4.2.0 so that an error is thrown if "if" is tested against an object with length>1.

- `a <- c(1,2,3,4);if(a>0){print("positive")}` throws "Error in if (a > 0) { : the condition has length > 1".  So, the test on line 135 for  `if( is.na(pLegend) )` of r/fusionPlot.R will throw an error since pLegend has length>1.  This still should have thrown a warning previously.

3. Fusion sub-panels are not plotted if the breakpoints occur within exons.

**Comment by charlesshale** [comment]
Thanks for the detailed bug investigation - I will try to address those issues in the next release.

**Comment by charlesshale** [comment]
Fixed those two issues:
- missing protein domain info in some transcripts
- same-gene fusions fixed the split in R plotter between up and downstream genes

v1.24 due for release shortly

**Comment by charlesshale** [comment]
https://github.com/hartwigmedical/hmftools/releases/tag/linx-v1.24
