### ISSUE TITLE
Purple CRAM support

### ISSUE THREAD

**Issue by vladsaveliev** [hartwigmedical/hmftools#33]
Working with CRAM requires a reference fasta on input. Currently Amber has `-ref_genome` option, however Cobalt doesn't seem to have it. Would be awesome to have full CRAM support in Purple.

UPD: with `-ref_genome` set, Amber still errors: 
```
A valid CRAM reference was not supplied and one cannot be acquired via the property settings reference_fasta or use_cram_ref_download
```

**Comment by jonbaber** [comment]
Hi Vlad, 

Looks like it is fairly simple to add. I should be able to get around to that tomorrow for you.

Cheers, Jon

**Comment by jonbaber** [comment]
I have released new versions of [AMBER](https://github.com/hartwigmedical/hmftools/releases/tag/amber-v2-3) and [COBALT](https://github.com/hartwigmedical/hmftools/releases/tag/cobalt-v1-6) with CRAM support for you. 

I tested against a single chromosome with both AMBER and COBALT and they gave identical results but please be aware we don't use CRAM ourselves so let me know if you encounter any unexpected issues. 

I also noted that AMBER performed significantly faster while COBALT was similar but slightly slower. 

Cheers, Jon

**Comment by vladsaveliev** [comment]
Fantastic, thanks a lot for implementing this so quickly!

**Comment by jonbaber** [comment]
No worries :)
