### ISSUE TITLE
SVVisualizer and cytoBands.txt file (only for hg19...?)

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#330]
It looks to me like for producing the Linx SVVisualizer Circos plots that use of r/cytoBands.txt is hardcoded into ChromosomeRangeExecution.java.  Comparing that file to one I made for GRCh38 looks like there are differences for band coordinates.  Isn't that file just for hg19?  Maybe this should be produced along with Ensembl_data_cache for specific genome builds?

**Comment by charlesshale** [comment]
I will address this in Linv v1.23 which is due for release early next year. 

I have also added hg38 ref files for fragile sites and mobile LINE elements so the visualiser will use them when required.

**Comment by charlesshale** [comment]
Fixed in:
https://github.com/hartwigmedical/hmftools/releases/tag/linx-v1.23.1
