### ISSUE TITLE
Linx SV driver suggestion

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#334]
I am now working with HCC sample data, and I have a sample that has 687 bp of HBV integrated into the TERT promoter (GRCh38 chr5:1295052) based on the ALT allele of the GRIDSS VCF and VIRUSBreakend analysis.  I somewhat expected Linx to identify this as an SV driver but it does not (probably as it falls outside of the coding region within the 5'-UTR).  I understand this should up in Virus Interpreter from the VIRUSBreakend analysis, but it seems like it would be useful for these known driver insertions into the TERT promoter to be identified in the Linx output.

**Comment by p-priestley** [comment]
FYI - Both TERT and C19MC are now called as fusions in Linx 1.23
