### ISSUE TITLE
Cuppa 

### ISSUE THREAD

**Issue by senzhaocode** [hartwigmedical/hmftools#337]
Hi hmftools developer, 

I was running Cuppa (v1.6) for predicting a tissue origin of tumor, however an error occurred during running (see attached figure). BTW, purple and linx output files needed for Cuppa are OK. Could you help me for troubleshooting. Thanks in advances

<img width="1425" alt="Screenshot 2022-11-02 at 22 34 59" src="https://user-images.githubusercontent.com/26706345/199607832-bef5db24-40fb-48a4-805a-bcb1cd30f22e.png">

**Comment by charlesshale** [comment]
Cuppa v1.7 is required to work with this version of Linx and the resource files for pipeline v5.31.

thanks
