### ISSUE TITLE
Enhancement: Tumour-only Sample Purity and Ploidy Estimation

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#34]
I don't know about the feasibility of it, but if a data set contains patients with both a tumour sample and normal sample and other patients with just a tumour sample, could a panel-of-normal style approach be used as the baseline for the patients with only a tumour sample, to enable estimating purity and copy numbers for their tumour?

**Comment by p-priestley** [comment]
This is not supported right now as it is not a use case we have had internally, and would require some development work.      

The main issue is for AMBER - we need to add an algorithm to determine which SNV locations were heterozygous in the germline whereas right now we just inspect the reference sample directly.    

Logical to have this functionality.  Let me get back to you on whether we will pick this up shortly

**Comment by p-priestley** [comment]
Dario - we won't pick this up immediately, but will likely do it at some stage over the next quarter.   

I will leave open for now.

**Comment by jonbaber** [comment]
Instructions for running PURPLE in tumor-only mode can be found [here](https://github.com/hartwigmedical/hmftools/blob/master/purity-ploidy-estimator/README.md#tumor-only-mode).
