### ISSUE TITLE
gnomad variant file for Pave step in pipeline

### ISSUE THREAD

**Issue by FedericaBrando** [hartwigmedical/hmftools#341]
Hi, I'm currently running HMFTpipeline locally and when it comes to pave somatic step it asks for this file: `ref_data_dir/37/variants/gnomad_variants_v37.csv.gz`. 

this is the output that I get:
```js
Running Pave somatic with args: -sample COLO829T   -ensembl_data_dir ref_data_dir/37/common/ensembl_data/   \
-driver_gene_panel ref_data_dir/37/common/DriverGenePanel.37.tsv   -ref_genome_version V37   \ 
-ref_genome ref_data_dir/37/ref_genome/Homo_sapiens.GRCh37.GATK.illumina.fasta   \ 
-pon_file ref_data_dir/37/variants/SageGermlinePon.1000x.37.tsv.gz   \ 
-pon_filters HOTSPOT:10:5;PANEL:6:5;UNKNOWN:6:0   \ 
-mappability_bed ref_data_dir/37/variants/mappability_150.37.bed.gz  \
-vcf_file test_data/COLO829T/sage_somatic/COLO829T.sage.somatic.vcf.gz  \ 
-read_pass_only   -output_vcf_file test_data/COLO829T/pave_somatic/COLO829T.sage.somatic.pave.vcf.gz \ 
-gnomad_freq_file ref_data_dir/37/variants/gnomad_variants_v37.csv.gz
10:03:32 - [ERROR] - failed to load gnoamd frequency file(ref_data_dir/37/variants/gnomad_variants_v37.csv.gz):
java.io.FileNotFoundException: ref_data_dir/37/variants/gnomad_variants_v37.csv.gz (No such file or directory)
```
I thought the file was included in [hmftools directory](https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/dna_pipeline/v5_31/37/variants?pageState=("StorageObjectListTable":("f":"%255B%255D"))&prefix=&forceOnObjectsSortingFiltering=false), but in fact , for `dna_pipeline/37` it is not there (while in the [directory](https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/dna_pipeline/v5_31/38/variants?pageState=("StorageObjectListTable":("f":"%255B%255D"))&prefix=&forceOnObjectsSortingFiltering=false) for 38, there is). Do you know, by chance, where can I get it?

**Comment by charlesshale** [comment]
Yes this file was only recently added to our v37 pipeline - I will update the TAR resources file to include this within a few days.

**Comment by charlesshale** [comment]
The Gnomad variants file is now included in the WGS and TSO-500 resource files for v37 - see:

https://github.com/hartwigmedical/hmftools/releases/tag/pipeline-scripts-v5.31

which also has includes some minor updates to the scripts and tools.

**Comment by FedericaBrando** [comment]
Thank you, just wanted to note that the link that points to the [GRCh38 for WGS](https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/dna_pipeline/v5_31/38/hmf_dna_pipeline_resources.38_v5.31.gz) is pointing to something that it's not downloadable from the folder. 

In the folder there is only [hmf_pipeline_resources.38_v5.31.gz](https://console.cloud.google.com/storage/browser/_details/hmf-public/HMFtools-Resources/dna_pipeline/v5_31/38/hmf_pipeline_resources.38_v5.31.gz?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))) not **hmf_dna_pipeline_resources.38_v5.31.gz**.

**Comment by charlesshale** [comment]
Thanks for picking that up - the file name has now been corrected
