### ISSUE TITLE
A failure to run PROTECT

### ISSUE THREAD

**Issue by senzhaocode** [hartwigmedical/hmftools#342]
Hi hmftools developer, 

I experienced a failure when running PROTECT(v2.3) to assign the clinical evidence/info to variant calls by the pipeline (SAGE, PAVE, PURPLE, LINX, CHORD, LILAC and CUPPA were all run successfully). From the error report (see an attachment), it is related to SERVE actionability files - I downloaded them from [HMFTools-Resources](https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources%2FServe%2F38), which includes four tsv files **ActionableCharacteristics.38.tsv**,   **ActionableFusions.38.tsv**,  **ActionableGenes.38.tsv**,  **ActionableHotspots.38.tsv** and  **ActionableRanges.38.tsv**.  Not sure whether the format of these file fits to PROTECT?

<img width="1467" alt="Screenshot 2022-11-16 at 10 09 02" src="https://user-images.githubusercontent.com/26706345/202172034-dd10954d-8ed0-4d73-b810-cbd6ecb919e6.png">

BWT, I also attached the running command line (_-serve_actionability_dir_ is the path of folder that contains the four dowloaded Actionable* files)

<img width="1393" alt="Screenshot 2022-11-16 at 12 50 41" src="https://user-images.githubusercontent.com/26706345/202173750-dd7cf9bd-4e64-4c61-8901-4fcbc6fca715.png">

Could you help me a troubleshooting. Thanks in advance. 

Sen

**Comment by kduyvesteyn** [comment]
Hi Sen,

The SERVE actionability files on HMFTools-Resources were not up-to-date yet. I have updated both 37 and 38 to work with PROTECT v2.3, could you try again? Sorry for the inconvenience. 

Also note that the SERVE actionability files that are publicly available are based off VICC and are a few years old by now (VICC has not published an update for a while...). So while they should technically work, you will miss all the recent evidence.

**Comment by senzhaocode** [comment]
Great! The updated SERVE actionability files works well : ) Thank you again and please close this ticket
