### ISSUE TITLE
More questions about Cuppa

### ISSUE THREAD

**Issue by senzhaocode** [hartwigmedical/hmftools#344]
Dear hmftools developer, 

1. I only got one csv file (i.e. XXX.cup.data.csv) for the output of Cuppa (v1.7). There are no "Cuppa report feature plot" and "Cuppa report feature plot" available. It seems these two png files are a prerequisite for running of Orange (v1.10.2) tool (e.g. args of Orange: _-cuppa_ feature_plot_ and _-cuppa_summary_plot_). Could give me some help of how to create plot files for Cuppa run.

2. The reference resource data set for Cuppa is only available for genome **37** at [HMFtools-Resources](https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/cuppa_ref_data/37/cuppa_ref_data.v16.gz;tab=objects?prefix=&forceOnObjectsSortingFiltering=false) download site. Not quite sure whether it can work for genome **38** properly as my variant calls from Sage, Purple and Linx are based on **38**. I saw many warnings popped up during Cuppa run (e.g. chr1 position 1706608 cannot map to genomic position, see attachment), although the whole process went through well without any errors. 

<img width="1239" alt="Screenshot 2022-11-17 at 12 54 20" src="https://user-images.githubusercontent.com/26706345/202439798-ebea095f-140a-4aca-96a0-99741ee9407e.png">

Thanks in advance!

Sen ZHAO

**Comment by charlesshale** [comment]
1. The Cuppa PNG files are created by a call to the Python script in hmftools/cuppa/src/main/resources/cuppa-chart/

python cuppa-chart.py -sample COLO829T -sample_data COLO829T.cup.data.csv -output_dir ./


2. We are planning on making Cuppa ref data for GRCh38 available in Jan/Feb next year. Cuppa will not produce meaningful results if v38 input files are used.

**Comment by charlesshale** [comment]
There are options to get v38 sample data working with Cuppa - if you'd like to discuss this further then feel free to email me directly: c.shale@hartwigmedicalfoundation.nl
