### ISSUE TITLE
PROMISCUOUS_ENHANCER_TARGET TERT fusions with intergenic regions can crash Linx visualizer

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#354]
I ran Linx 1.23 with the updated TERT PROMISCUOUS_ENHANCER_TARGET target region added to the known fusions file, and for my positive test example, Linx produced line.vis_fusion.tsv file that crashed Linx visualizer when run against the visualizer data directory.

In this example, fusion breakend coordinates in vis_sv_data were:
ChrStart PosStart OrientStart ChrEnd   PosEnd OrientEnd
  chr5  1309391           1  chr19 44744689         1

The calculated fusion was ZNF180_TERT, which seems like a strange choice: the ZNF180 transcript lies at chr19:44,474,443-44,500,522, so is 244kb away from the chr19 breakend, and is transcribed from the minus strand, which means that the fused exons or promoter regions would not be in the proper orientation when fused with TERT.

In any case, for fused enhancer regions, it seems like one cannot expect any functional gene fusion product, so perhaps for that event type, just marking the closest gene(s) might end up being more informative.  For instance, this chr19 breakpoint is just upstream of the BCL3 promoter, which seems conceptually like a better candidate for providing an impactful regulatory element. 

For the moment, I have modified my workflow to check the linx.vis_fusion.tsv and remove any TERT fusion rows before running Linx visualizer.

**Comment by charlesshale** [comment]
Could you test your sample with v1.23.1 and let me know if the issue is fixed. I came across a similar crash when the 5' gene had no exons overlapping with the fusion breakends.

https://github.com/hartwigmedical/hmftools/releases/tag/linx-v1.23.1

**Comment by toddajohnson** [comment]
I just ran that sample with the new linx-v1.23.1.jar, and the linx visualization did not crash for the TERT upstream fusion SV cluster, and it produced a .png file.  However, it does produce a "fatal" error when adding the fusion sub-panel and greyed out areas at the bottom and left corners.

12:31:21 - [FATAL] - Error executing R script. Examine error file /tmp/fusionPlot.R5269745488907342244.error for details.
12:31:21 - [WARN ] - Error adding fusion plots.

Here is the error output after fusionPlot.R loaded libraries:
[tmp_fusionPlot.R.error.txt](https://github.com/hartwigmedical/hmftools/files/10388867/tmp_fusionPlot.R.error.txt)

For reference, here is the ZNF180_TERT "fusion" SV:

![TERT_fusion_example](https://user-images.githubusercontent.com/17885404/211721403-dbe5d1ff-9cac-4709-9beb-4f005a73c7ec.jpg)

As I mentioned, ZNF180 seems a strange choice as a "fusion" partner that must be forced by the code expectations, since empty 5'-gene information would seem to be a better choice.  Note also that the fusion exon table only includes TERT exons (which could be expected given the orientation and distance of the 5'- gene), and the error appears related to the missing 5'-gene.

**Comment by charlesshale** [comment]
Thanks for the detailed log. I've got one of these non-genic to TERT enhancer fusions to test with now too, so will figure out how to handle it better.

**Comment by charlesshale** [comment]
We've changed the Visualiser to not attempt to plot the fusion gene component if either up or down exons are missing. This will be the case for most of the promotor enchancer fusions.

See https://github.com/hartwigmedical/hmftools/releases/tag/linx-v1.23.2_beta
