### ISSUE TITLE
PROMISCUOUS_ENHANCER_TARGET TERT fusions and known_fusions.38.bedpe

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#355]
With the added PROMISCUOUS_ENHANCER_TARGET fusion type for TERT and added rows to known_fusion_data.38.csv to represent TERT as a downstream fusion partner, is there any thought as to also adding data to known_fusions.38.bedpe to represent such promiscuous hotspots so that SVs involving TERT could be marked as HOTSPOT by GRIPSS and rescued?  Or, is it already possible to represent a single gene region partner in that file?

**Comment by p-priestley** [comment]
We only use that to rescue pairs which are known on each side (due to high prior likelihood).    GRIDSS is already quite sensitive without this, so we don't feel we need the extra sesnsitivity in this case.
