### ISSUE TITLE
complied jar file request: cider v0.5

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#356]
Hi developers,

If a complied jar file of cider v0.5 could be added to the releases page?

Thanks

**Comment by hongwingl** [comment]
Apologies, I did not realise the upload has failed. I have re uploaded it.

**Comment by hongwingl** [comment]
Thanks for using cider. Please do not hesitate to let me know if you run into any other issues, or have any feature improvements for suggestion. You can email me at h.lee@hartwigmedicalfoundation.nl
