### ISSUE TITLE
linx_v1.23.1.jar cytoBands.37.tsv and cytoBands.38.tsv files: Header problems

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#357]
There is no header in the cytoBands.38.tsv file embedded in the linx_v1.23.1.jar refgenome/ directory, so when linx visualizer runs chromosomeRangePlot.R, it crashes (no chrom object to be found by dplyr mutate, since there was no header).

Also, it may not create a problem, but the cytoBands.37.tsv header is delimited with spaces, while the the rest of the file is tab delimited.

**Comment by charlesshale** [comment]
Thanks for picking that up - I've fixed them both and re-uploaded the Linx v1.23.1 JAR.

**Comment by toddajohnson** [comment]
Thanks.  I've already updated those files in the linx jar, and it did not through errors related to that anymore.
