### ISSUE TITLE
Cancer Sample Identifier Appended to Germline CNV FIle

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#36]
One of the outputs of PURPLE is a file with name ending in purple.germline.cnv but it's prefixed with what was supplied to `-tumor` rather than `-reference`. If the copy number values are those from the reference sample, I would expect it to be prefixed with the reference sample identifier.

**Comment by jonbaber** [comment]
This file contains the homozygous deletes from the germline as well as any deletes that are heterozygous in the germline but homozygous in the tumor. The copy number values in this file still refer to the tumor. 

This is described in [section 8](https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#8-identify-germline-copy-number-alterations-that-are-homozygously-deleted-in-the-tumor) of the algorithm: 

During the smoothing process, regions that are homozygously or heterozygously deleted from the germline are smoothed over for the purposes of producing the somatic output. However, as some of these regions are of specific interest we include them in a separate germline copy number output that contains the homozygous deletes from the germline as well as any deletes that are heterozygous in the germline but homozygous in the tumor.
