### ISSUE TITLE
TSO500 different reference

### ISSUE THREAD

**Issue by davidvanzessen** [hartwigmedical/hmftools#360]
Hello,

We're trying to run the panel tumor pipeline described [here](https://github.com/hartwigmedical/hmftools/blob/master/pipeline/README_PANEL.md) on our Illumina TSO500 data.

But after setting everything up, Amber immediately starts throwing this error when trying to load the sample BAM:  
```
09:17:56.483 INFO  [main] - AMBER version: 3.9
09:17:56.485 INFO  [main] - Loading vcf file ./references//copy_number/GermlineHetPon.37.vcf.gz
09:17:59.351 INFO  [main] - loaded 1344545 baf loci
09:17:59.627 INFO  [main] - removed 0 blacklisted loci, 1344545 remaining
09:17:59.628 INFO  [main] - Processing 1344545 germline heterozygous loci in tumor bam ./sample_data/M22-3189T/M22-3189T.bam
09:17:59.628 INFO  [main] - Processing 0 germline homozygous loci in tumor bam ./sample_data/M22-3189T/M22-3189T.bam for contamination
09:18:00.869 INFO  [main] - 1344545 loci, 148821 genome regions, min gap = 4000
Exception in thread "worker-0" java.lang.IllegalArgumentException: Invalid reference index -1
	at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
	at com.hartwig.hmftools.amber.AsyncBamLociReader$BamReaderThread.run(AsyncBamLociReader.java:69)
```

Because the reference used in the official Illumina analysis pipeline is different than the one used in this pipeline, the names are different (which was easily fixed), but also the length of the chrM/MT contig is different.  

We thought of a couple of solutions to this, simply aligning to the new reference (slow), removing the mitochondrial reads and modifying the header (could be great), or replacing the reference files in this pipeline (not sure if the pipeline will accept this?).  
We've spent some time on trying out modifying the BAM file, but so far tools kept tripping over it and it's something that's usually not recommended...

Since the page specifically describes TSO500 as en example, we were wondering how this was done,  
Platinum is mentioned on the page so we assume the FastQ were used as a starting point, skipping the described problems, but double checking if there isn't an existing other solution.  

Thank you in advance, if you need any more info let us know.

**Comment by p-priestley** [comment]
We have run smoothly on TSO500 samples from FASTQ, after aligning to our own pipeline version of the  genome available from our resource page.

if you are starting from BAM, you should definitely use the same reference genome that you aligned with.   I believe that should work, but I can't guarantee all configurations.  If it does not work, I recommend just starting from FASTQ.   Mixing ref genomes is a bad idea and can lead to lots of different problems.

**Comment by davidvanzessen** [comment]
Thank you for the quick response, we will replace the reference genome with ours and try the pipeline again.
