### ISSUE TITLE
java.nio.file.NoSuchFileException: /workspace/purple/circos/COLO829T.circos.conf

### ISSUE THREAD

**Issue by bobrad98** [hartwigmedical/hmftools#364]
Hi, 

I'm trying to run PURPLE 3.7.2 with the test data that you provided:

```
java -jar purple_v3.7.2.jar 
-reference COLO829R 
-tumor COLO829T 
-output_dir /workspace/purple 
-amber /project-files/AMBER 
-cobalt /project-files/COBALT 
-gc_profile /project-files/ref_hg37/GC_profile.1000bp.37.cnp 
-ref_genome /project-files/ref_hg37/HMFtools-Resources_ref_genome_37_Homo_sapiens.GRCh37.GATK.illumina.fasta 
-ref_genome_version 37 
-ensembl_data_dir /project-files/ref_hg37/ensembl_37  
```

and I get this error:

> java.nio.file.NoSuchFileException: /workspace/purple/circos/COLO829T.circos.conf
>         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
>         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
>         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
>         at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
>         at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
>         at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
>         at java.base/java.nio.file.Files.write(Files.java:3425)
>         at com.hartwig.hmftools.purple.plot.CircosCharts.writeConfig(CircosCharts.java:172)
>         at com.hartwig.hmftools.purple.plot.CircosCharts.writeConfig(CircosCharts.java:151)
>         at com.hartwig.hmftools.purple.plot.CircosCharts.write(CircosCharts.java:75)
>         at com.hartwig.hmftools.purple.plot.Charts.write(Charts.java:54)
>         at com.hartwig.hmftools.purple.PurpleApplication.performFit(PurpleApplication.java:435)
>         at com.hartwig.hmftools.purple.PurpleApplication.processSample(PurpleApplication.java:236)
>         at com.hartwig.hmftools.purple.PurpleApplication.run(PurpleApplication.java:174)
>         at com.hartwig.hmftools.purple.PurpleApplication.main(PurpleApplication.java:654)

It seems to me that PURPLE didn't generate `/output_dir/circos` and Java gets confused. 
I tried to make that subdirectory manually, before running the tool, and the tool worked perfectly.

Can you help me figure out what I'm doing wrong?
Thanks!

**Comment by charlesshale** [comment]
Could you re-try this but set the circos in path, eg:
-circos /path_to_circos/

Purple creates the output directories it needs. In your example the plots should be created here:
/workspace/purple/COLO829T/plot/
