### ISSUE TITLE
Failed to run the gridss-purple-linx pipeline

### ISSUE THREAD

**Issue by Eric0627** [hartwigmedical/hmftools#365]
I tried to use `./scripts/run_pipeline ./scripts /sample_data/ /ref_data_dir/ /tools_dir/ "COLO829T,COLO829R" V37 WGS 10 16` to resolve the BFB event in COLO829. But there are a lot of errors with the highly dependent software. Could you please give me a suggestion for running LINX on COLO829 with the least required arguments?

Here is the full screenshot of the errors:
![1](https://user-images.githubusercontent.com/47047934/217211715-dce1b3dc-9eee-4771-aecc-155c89be9730.PNG)
![2](https://user-images.githubusercontent.com/47047934/217211767-ab168731-6deb-45cd-bc09-dca3b138c551.PNG)
![3](https://user-images.githubusercontent.com/47047934/217211774-e14bdc34-0fbe-4527-bcd8-90b435b98dec.PNG)
![4](https://user-images.githubusercontent.com/47047934/217211778-ed689e7c-08c8-47c6-acdd-f041949b1355.PNG)

**Comment by charlesshale** [comment]
That looks like Java needs to be upgraded to version 11.
