### ISSUE TITLE
Cannot find SageGermlinePon.98x.38.vcf.gz 

### ISSUE THREAD

**Issue by FedericaBrando** [hartwigmedical/hmftools#368]
Hi,
Unfortunately I cannot find the Hartwig panel of normals for somatic SNV/INDEL variant calling anymore:
`SageGermlinePon.98x.38.vcf.gz`.

I used to download it from  https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC/download?path=%2FHMFTools-Resources%2FSage%2F38&files=SageGermlinePon.98x.38.vcf.gz, but the link is not working anymore. 

Where could I find it? 
I onlt found the tsv one [`SageGermlinePon.98x.38.tsv.gz`] , not the vcf. 

Thanks in advance,
Federica

**Comment by charlesshale** [comment]
We not longer support the PON in this format. Pave uses the same contents but in a condensed TSV format.

Our public resource files are now stored in GCP:
https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/dna_pipeline/
