### ISSUE TITLE
jar for rose 1.3

### ISSUE THREAD

**Issue by DavyCats** [hartwigmedical/hmftools#370]
Would it be possible for the jar file to be added to the release for rose 1.3? I would like to add rose 1.3 to bioconda and having a download link for the jar file would make that a lot easier.

Thanks!

**Comment by kduyvesteyn** [comment]
ROSE will be removed from the genomic pipeline as per 5.32 (it will be moved to a separate oncoact pipeline). 

Will make sure though a jar will be available on https://github.com/hartwigmedical/hmftools/releases/tag/rose-v1.3, please check there tomorrow

**Comment by DavyCats** [comment]
Thanks, good to know.
