### ISSUE TITLE
circos issue

### ISSUE THREAD

**Issue by felixbeaudry** [hartwigmedical/hmftools#371]
Hi there,

Really enjoy purple and the whole hartwig suite, thank you! 

I'm getting an error with purple-v3.8.1: 
`[ERROR] charting error: java.nio.file.NoSuchFileException: purple_output/circos/OCT_011408_Co_P_OCT_011408-TS.circos.conf` I don't have circos enabled (and I don't have circos installed). The PURPLE documentation suggests issues with circos would only arise when the circos flag is used. The issue does not appear if I add the `-no_charts` flag. I can use the no-charts flag, but would prefer to have the R charts run .

Thank you!
Felix

**Comment by charlesshale** [comment]
Hi Felix,

From the next release of Purple (v3.8.)2 it will generate the R plots but skip the Circos plots if the path to the circos binary is not provided in config.
