### ISSUE TITLE
MSI Score

### ISSUE THREAD

**Issue by Luke-Tork** [hartwigmedical/hmftools#372]
Hi all, we are trying to document a few things as part of our curation report:

We are interested in a high level summary of how the MSI score is calculated from PURPLE. Has that calculation significantly changed from v2.51, released back in Oct 2020? ([Reference](https://www.nature.com/articles/s41586-019-1689-y) extract below):

> MSI status determination
> To determine the MSI status, we used the method described by the [MSIseq tool](https://www.nature.com/articles/srep13321) and counted the number of indels per million bases occurring in homopolymers of five or more bases or dinucleotide, trinucleotide and tetranucleotide sequences of repeat count four or more. MSIseq score of >4 were considered MSI.

Thanks for your help!

**Comment by p-priestley** [comment]
Hi Luke, 

This should not have changed in this time.

Regards,

Peter
