### ISSUE TITLE
linx 1.22.1

### ISSUE THREAD

**Issue by DavyCats** [hartwigmedical/hmftools#377]
I noticed that the pipeline5 5.31-hotfix branch (https://github.com/hartwigmedical/pipeline5/blob/5.31-hotfix/cluster/src/main/java/com/hartwig/pipeline/tools/Versions.java) uses linx 1.22.1, however I can't find this version in the releases. Would it be possible to add a release for this version?

**Comment by charlesshale** [comment]
Sorry the release was left as a draft rather than published, here you go:

https://github.com/hartwigmedical/hmftools/releases/tag/linx-v1.22.1
