### ISSUE TITLE
Cannot find citation

### ISSUE THREAD

**Issue by micoli98** [hartwigmedical/hmftools#380]
I have to cite some of the tools you developed in a couple of articles but I cannot find any paper to cite or DOI. Is there something similar yet? Or should I just insert the link to the repo with the versions of the tools?

**Comment by p-priestley** [comment]
I would say best to use the repo link.

A few of our tools can be referenced if you prefer to these publications:

For PURPLE, you can use: https://www.nature.com/articles/s41586-019-1689-y  (described in the supplementary methods)
For LINX, you can use: https://www.cell.com/cell-genomics/pdf/S2666-979X(22)00032-5.pdf
For LILAC, we currently have this preprint (soon to be published):  https://www.biorxiv.org/content/10.1101/2022.02.23.481444v3

**Comment by micoli98** [comment]
Ok thank you. I'll reference them as you suggested.

**Comment by p-priestley** [comment]
FYI - The best reference we have to cite for oncoanalyser at the moment are the Zenodo records (oncoanalyser 1.0.0 [https://zenodo.org/records/15194163] and oncoanalyser 2.0.0 [https://zenodo.org/records/15189387]).
