### ISSUE TITLE
Quick question-- compatibility with long read data?

### ISSUE THREAD

**Issue by jamesdalg** [hartwigmedical/hmftools#389]
I really liked using the HMF tools pipeline in the past. I'm moving to long read data (pacbio). Is there a part of the pipeline that will still work for this type of data, or are there some parts that implicitly expect Illumina reads?

**Comment by charlesshale** [comment]
Hi James, we haven't tried running any of our tools with long read data so their performance with it is unknown. If can you provide a public sample dataset I can take a look - email me directly.

thanks,

Charles

**Comment by eesiribloom** [comment]
has there been any update on using hmftools pipeline with long reads?

**Comment by p-priestley** [comment]
There are many implicit short read assumptions in our tools particularly in structural variant calling.   We don't intend to work on this in the near future, sorry.  

Some users have had decent results using COBALT, AMBER + PURPLE for copy number.

**Comment by eesiribloom** [comment]
Ah okay, thanks for the quick response! I would only be interested in results from purple (and cobalt and amber) anyway? None of our samples have high average read length (range from 1-10kb), would this make any difference or is it more an issue with implicit features of short vs long-reads e.g. paired ends, split reads etc.

**Comment by p-priestley** [comment]
PURPLE may work fine.  

The key issues in the remaining components would be assumptions around fragment length (we implicitly assume <~1kb) and around base quality (we implicitly assume a high proportion of bases will have quals > 30 phred score).  Long reads may also cause performance issues.   We have not tested it at all.
