### ISSUE TITLE
Purple MACN in SV VCF

### ISSUE THREAD

**Issue by jaesvi** [hartwigmedical/hmftools#391]
Hi,

Is there a particular reason why minorAlleleCopyNumber is not annotated in the SV VCF in the same way it's done for the SNV VCF (PURPLE_MACN field)?
It can be useful in downstream analysis. 
Thanks,
Jose

**Comment by charlesshale** [comment]
SNVs derive their copy number values (including MACN) from the applicable straddling Purple copy number segment. SV breakends are linked to a specific Purple copy number segment by chromosome and position, so their MACN can be derived precisely from the matched copy number record. We have populated the SV VCF with the adjusted copy number value, but have no plans at this stage to add in BAF, MACN or any of the the other values.

**Comment by jaesvi** [comment]
Clear, so I should get the CN segment based on the breakend position and orientation and can get it from there.
Thanks.
