### ISSUE TITLE
LINX visualization for select regions

### ISSUE THREAD

**Issue by lichennan123** [hartwigmedical/hmftools#395]
Hi LINX developers,

I would like to view a particular SV chain within a cluster that crosses three genomic locations. Here is the script that I used:

```shell
java -cp /data/lic27/tools/linx_v1.22.jar com.hartwig.hmftools.linx.visualiser.SvVisualiser \
    -sample SAMPLE \
    -ensembl_data_dir /data/lic27/tools/linx/ensembl_data/ \
    -ref_genome_version 38 \
    -plot_out /data/lic27/linx/linx_visual/plot \
    -data_out /data/lic27/linx/linx_visual/data \
    -vis_file_dir /data/lic27/linx/linx \
    -circos /data/lic27/tools/circos/circos-0.69-9/bin/circos \
    -clusterId 317 \
    -chromosome chr10,chr12,chr17 \
    -specific_regions chr10:9300000:9370000;chr12:45798000:45803000;chr17:3000000:8000000
``` 

I realized the script above was run without the last portion (chr12/chr17 regions) due to the semicolon which is specified in the [manual](https://github.com/hartwigmedical/hmftools/blob/master/linx/README_VIS.md) - the argument 'specific_regions'. I was able to view each of the three locations separately. Just wondered if there are any suggestions for viewing the entire chain (rather than the whole cluster) as a whole. Thank you for any thoughts and creating such a great tool! 

Sincerely,
Chennan

**Comment by lichennan123** [comment]
Any response? It is okay if this is not an option at all and I can try figuring out some other ways. Thanks!

**Comment by charlesshale** [comment]
This is possible in LInx 1.23.6 which will be released later this week.

**Comment by charlesshale** [comment]
See:
https://github.com/hartwigmedical/hmftools/releases/tag/linx-v1.23.6
