### ISSUE TITLE
realignment command for alt contigs

### ISSUE THREAD

**Issue by rod1Gene** [hartwigmedical/hmftools#397]
Do you have suggestions about the alignment program and arguments to use when realigning reads from alt contigs to chr6?

**Comment by rod1Gene** [comment]
For LILAC and its dependents.

**Comment by charlesshale** [comment]
The v38 alt-config ref genome is not currently supported. We recommend using the no-alt ref genome, especially for running Lilac. Lilac loads all known HLA alleles and internally considers all reads mapped to the HLA regions to these alleles.

**Comment by rod1Gene** [comment]
Thanks.
Do you have an opinion about which aligner and arguments to use?

**Comment by charlesshale** [comment]
We use BWA version 0.7.17.
The arguments are: mem -R SAMPLE_FLOWCELL_IDS -Y -t THREAD_COUNT REF_GENOME_FILE FASTQS

Our v38 ref genome is here:
https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/ref_genome/38/
