### ISSUE TITLE
location of required input files

### ISSUE THREAD

**Issue by rod1Gene** [hartwigmedical/hmftools#398]
Would you help me find the locations of the required input files for reference 38: hotspots, panel bed, high_confidence_bed, and ensembl_data_dir?

And also the exact 38 reference to which these files refer?

**Comment by charlesshale** [comment]
All our resources are available here:

https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/dna_pipeline/

The latest resources files are:
https://console.cloud.google.com/storage/browser/_details/hmf-public/HMFtools-Resources/dna_pipeline/v5_32/38/hmf_dna_pipeline_resources.38_v5.32.gz

Each tool gives the list of which specific files are required.

The ref genome is here:
https://console.cloud.google.com/storage/browser/_details/hmf-public/HMFtools-Resources/ref_genome/38/

**Comment by rod1Gene** [comment]
For SAGE's high_confidence_bed parameter, is it .../variants/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed.gz?
