### ISSUE TITLE
Binaries for other tools

### ISSUE THREAD

**Issue by ohofmann** [hartwigmedical/hmftools#4]
Dear all,

following up on https://github.com/hartwigmedical/hmftools/issues/2 we are now starting to explore Purple (and Amber/Cobalt). Would it be possible to also distribute the relevant JARs?

Best, Oliver

**Comment by jonbaber** [comment]
Hi Oliver, 

Thanks for the friendly reminder. I have updated the latest releases of [amber](https://github.com/hartwigmedical/hmftools/releases/tag/amber-v1-5) and [cobalt](https://github.com/hartwigmedical/hmftools/releases/tag/cobalt-v1-2) with JARs. 

I plan on releasing a new version of purple tomorrow that I suggest you hold out for. Will update this thread once I have done so.

Cheers, Jon

**Comment by ohofmann** [comment]
No rush at all, thanks for the support!

**Comment by jonbaber** [comment]
No problem. Latest version of [purple](https://github.com/hartwigmedical/hmftools/releases/tag/purple-v2-6) now available.
