### ISSUE TITLE
Evidence for Loss of Heterozygosity Detection and Definitions

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#40]
The README file explains that a minor allele copy number of less than 1 indicates LOH. Looking at some pairs of samples for various patients in a viewer like IGV, I can't see any heterozygous SNPs at anywhere close to half the reads in the normal sample. It would be convenient if there was an output file which listed the coordinates of SNPs being used to infer the minor allele copy number, a concept which isn't explicitly defined (is it a non-reference sequence allele?) I read [a definition of minor allele](https://www.biostars.org/p/310841/#310899), and it depends on the patient cohort and the frequencies of various alleles within it, so I don't know how PURPLE could determine the minor allele if it works on a pair of samples for each patient independently of each other patient and doesn't know about the frequency of different alleles in the whole data set.

**Comment by p-priestley** [comment]
Dario - our definition of LOH we use internally is minor allelle ploidy < 0.5 (the readme might be marginally misleading), although anything less than 1 represents loss from diploid heterozygous.

The SNPs used to infer BAF are all contained in the amber.baf file which also has read counts of that SNV in both normal and tumor sample.    The CNV output also reports the total count of baf points (bafCount) and average observed baf (observedBaf) as described on the readme.     You can also see a visualisation of this in the input circos.    It is non-trivial to see heterozygosity in input SNP points as the observed VAF depends on both the tumor allele imbalance and the purity and ploidy of the sample.

I looked at your link of minor allele definition.  The minor allele in somatic copy number terminology is not a reference to the population based frequency but simply the parental allele that has the least copies at each locus of the genome - detecting loss of heterozygosity is generally the most interesting application for tumor analysis.   We do not phase these in PURPLE at this stage.

**Comment by DarioS** [comment]
That explains how I can check it in a better way.
