### ISSUE TITLE
PURPLE ERROR

### ISSUE THREAD

**Issue by YuP9934** [hartwigmedical/hmftools#405]
I'm using PURPLE.I know I need to use amber and cobalt before I use them.
I make sure the reference samples I use are consistent.
But I received the following error message.
I don't know what's wrong. Could you help me?

15:34:59.630 [INFO ] Purple version: 3.8.1
15:34:59.640 [INFO ] output directory: /test/PURPLE/
15:34:59.643 [INFO ] reference(A375M2_gDNA) tumor(A375M2_Exos)
15:34:59.837 [INFO ] using ref genome: V38
15:35:00.512 [ERROR] invalid reference data, exiting

**Comment by charlesshale** [comment]
Could you paste the command you're running into the ticket? Does it match the one on Purple's read-me and use all HMF required resource files?

thanks.

From: YuP9934 ***@***.***>
Reply to: hartwigmedical/hmftools ***@***.***>
Date: Friday, 26 May 2023 at 5:50 pm
To: hartwigmedical/hmftools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hartwigmedical/hmftools] PURPLE ERROR (Issue #405)


I'm using PURPLE.I know I need to use amber and cobalt before I use them.
I make sure the reference samples I use are consistent.
But I received the following error message.
I don't know what's wrong. Could you help me?

15:34:59.630 [INFO ] Purple version: 3.8.1
15:34:59.640 [INFO ] output directory: /test/PURPLE/
15:34:59.643 [INFO ] reference(A375M2_gDNA) tumor(A375M2_Exos)
15:34:59.837 [INFO ] using ref genome: V38
15:35:00.512 [ERROR] invalid reference data, exiting

**Comment by YuP9934** [comment]
I used amber:
`java -Xmx32G  -cp amber-3.9.jar com.hartwig.hmftools.amber.AmberApplication 
	-reference normal 
	-reference_bam test/projectdir/normal.bam 
	-tumor TUMOR 
	-tumor_bam test/projectdir/TUMOR.bam 
	-output_dir test/amber 
	-ref_genome_version V38 
	-threads 16 
	-loci GermlineHetPon.38.vcf.gz
`
It executed successfully.
Then I used coblat:
`java -jar -Xmx8G cobalt_v1.14.jar 
	-reference normal 
	-reference_bam test/projectdir/normal.bam 
	-tumor TUMOR 
	-tumor_bam test/projectdir/TUMOR.bam 
	-output_dir test/cobalt 
	-threads 16 
	-gc_profile GC_profile.1000bp.38.cnp`
It executed successfully too.
I use the command PURPLE:
`java -jar purple_v3.8.1.jar 
   -reference normal 
   -tumor TUMOR 
   -amber test/amber 
   -cobalt test/cobalt 
   -gc_profile GC_profile.1000bp.38.cnp 
   -ref_genome_version 38 
   -ref_genome hg38.fa 
   -ensembl_data_dir test/PURPLE 
   -output_dir test/PURPLE`
At this time, there is an error. I don't know which step is wrong

**Comment by charlesshale** [comment]
That Purple command looks ok. Could you try the latest version of Purple (v3.8.4)? It should give more information about which reference file path is invalid.

**Comment by AlexanderKotyurgin** [comment]
I have exactly the same error while using v3.8.4, no change in logs.
