### ISSUE TITLE
Lilac on WES data

### ISSUE THREAD

**Issue by AAAapollo** [hartwigmedical/hmftools#415]
Dear developer,

I am running Lilac(v1.4.2) on >200x depth WES data, and some samples error are shown below.  

And the genome version that we used for alignment is hg19, and there are some ALTs of chr6 (like chr6_apd_hap1, chr6_cox_hap2, ...). The parameter is mostly the same with the parameter in HMFtools pipeline, but is added with "-fatal_low_coverage 10000". 
And many samples get different HLA typing with previous polysolver typing result. 

So my question is if Lilac can work on WES data, and how can I fixed the bugs as below and get consistent result with polysolver.

Looking forward to your reply, thanks!

[INFO ] Lilac version(1.4.2), key parameters:
[INFO ] sample(P68) inputs: tumorBam(false) somaticVCF(true) geneCopyNumber(true) rnaBam(false)
[INFO ] minBaseQual(30), minEvidence(2) minFragmentsPerAllele(7) minFragmentsToRemoveSingle(40) maxDistanceFromTopScore(0.005)
[INFO ] reading nucleotide file: hla_ref_nucleotide_sequences.csv
[INFO ] loaded 17542 sequences from file hla_ref_nucleotide_sequences.csv
[INFO ] reading protein file: hla_ref_aminoacid_sequences.csv
[INFO ] loaded 13198 sequences from file hla_ref_aminoacid_sequences.csv
[INFO ] loaded 128 common alleles
[INFO ] querying records from reference bam P68.bam
[INFO ] lowering min base quality(30) to median(28)
[INFO ] totalFrags(911) minEvidence(2.0) minHighQualEvidence(0.3)
[INFO ] gene(HLA-A) determining un-phased candidates from frags(896)
[WARN ]   no candidates after amino acid filtering - reverting to common allele gene candidates
[INFO ] gene(HLA-B) determining un-phased candidates from frags(853)
[WARN ]   no candidates after amino acid filtering - reverting to common allele gene candidates
[INFO ] gene(HLA-C) determining un-phased candidates from frags(787)
[WARN ]   no candidates after amino acid filtering - reverting to common allele gene candidates
[INFO ] gene(HLA-A) has 0 candidates after phasing:
[INFO ] gene(HLA-B) has 0 candidates after phasing:
[INFO ] gene(HLA-C) has 5 candidates after phasing: C*01:02, C*04:01, C*04:09N, C*04:82, C*14:02
[INFO ] recovering common alleles: A*01:01, A*01:02, A*02:01, A*02:02, A*02:03, A*02:05, A*02:06, A*02:07, A*02:20, A*03:01, A*03:02, A*11:01, A*23:01, A*24:02, A*24:03, A*24:07, A*25:01, A*26:01, A*26:08, A*29:01, A*29:02, A*30:01, A*30:02, A*30:04, A*31:01, A*32:01, A*33:01, A*33:03, A*34:01, A*34:02, A*66:01,A*68:01, A*68:02, A*69:01, A*74:01, B*07:02, B*07:05, B*07:06, B*08:01, B*13:01, B*13:02, B*14:01, B*14:02, B*15:01, B*15:02, B*15:03, B*15:07, B*15:13, B*15:17, B*15:18, B*15:21, B*18:01, B*27:02, B*27:05, B*27:06, B*27:07, B*35:01, B*35:02, B*35:03, B*35:05, B*35:08, B*37:01, B*38:01, B*38:02, B*39:01, B*39:06, B*40:01, B*40:02, B*40:06, B*41:01, B*41:02, B*42:01, B*44:02, B*44:03, B*44:04, B*44:05, B*44:27, B*45:01, B*46:01, B*47:01, B*48:01, B*49:01, B*50:01, B*50:02, B*51:01, B*51:07, B*51:08, B*52:01, B*53:01, B*55:01, B*56:01, B*57:01, B*57:03, B*58:01, B*73:01, B*81:01, C*02:02, C*02:10, C*03:02, C*03:03, C*03:04, C*04:03, C*05:01, C*06:02, C*07:01, C*07:02, C*07:04, C*07:06, C*07:18, C*08:01, C*08:02, C*12:02, C*12:03, C*12:143, C*15:02, C*15:05, C*15:06, C*16:01, C*16:02, C*16:04, C*17:01, C*17:03, C*18:01
[INFO ] building frag-alleles from aminoAcids(frags=911 candSeq=128) nucFrags(hetLoci=3 candSeq=3717 nucs=1101) knownIndels(0)
[INFO ] HLA-Y fragments(182 unique=76) shared=106) above threshold
[INFO ] filtering candidates from fragAlleles(527) candidates(128) recovered(123)
[INFO ]   confirmed 1 unique groups: C*01[103,72,31,0]
[INFO ]   found 1 insufficiently unique groups: A*33[18,3,15,0]
[INFO ]   keeping 2 recovered alleles from unique groups: A*33:01, A*33:03
[INFO ]   confirmed 1 unique proteins: C*01:02[152,126,26,0]
[INFO ]   found 2 insufficiently unique proteins: A*33:03[54,4,50,0], C*14:02[31,4,27,0]
[INFO ] building frag-alleles from aminoAcids(frags=911 candSeq=7) nucFrags(hetLoci=3 candSeq=304 nucs=1101) knownIndels(0)
[INFO ] calculating coverage for complexes(0) and ref alleles(392)
[FATAL] failed to calculate complex coverage

**Comment by p-priestley** [comment]
There is no fundamental problem with WES data.   The log above though suggests you have poor or very uneven coverage of the HLA-A/HLA-B/HLA-C genes.   Are you perhaps using a hg38_alt genome?    LILAC does not currently support gathering of  ALT alignments from the HLA ALT contigs.  Please note this comment on our readme:

_LILAC supports GRCH37, hg19 and hg38 (no alt) ref genomes. Note that if the genome has been aligned to an hg38 genome with HLA alt contigs, that fragments from these contigs will need to be extracted and realigned to the no alt genome prior to running LILAC._

If you are not using a reference with ALT contigs, then it would be good to visually check the coverage of each of the genes.

**Comment by AAAapollo** [comment]
> There is no fundamental problem with WES data. The log above though suggests you have poor or very uneven coverage of the HLA-A/HLA-B/HLA-C genes. Are you perhaps using a hg38_alt genome? LILAC does not currently support gathering of ALT alignments from the HLA ALT contigs. Please note this comment on our readme:
> 
> _LILAC supports GRCH37, hg19 and hg38 (no alt) ref genomes. Note that if the genome has been aligned to an hg38 genome with HLA alt contigs, that fragments from these contigs will need to be extracted and realigned to the no alt genome prior to running LILAC._
> 
> If you are not using a reference with ALT contigs, then it would be good to visually check the coverage of each of the genes.

Thanks. We used hg19 genome version, but with ALT contigs like chr6_apd_hap1, chr6_cox_hap2 and so on. Will this effect the coverage of HLA genes?

**Comment by p-priestley** [comment]
I don't know about that ref genome specifically, but only HLA related ALT contigs should cause problems, so it is unlikely

This line suggests that in total only 911 fragments were found overlapping the HLA gene exons which seems very low for exome data:

[INFO ] totalFrags(911) minEvidence(2.0) minHighQualEvidence(0.3)

Did you get a qc file produced.  If so, perhaps you could share that?

I think I would need to look at the data directly to comment more on the specific issue.    You can email me at p.priestley@hartwigmedicalfoundation.nl if you want to discuss sharing that for one patient to diagnose the problem

**Comment by AAAapollo** [comment]
> I don't know about that ref genome specifically, but only HLA related ALT contigs should cause problems, so it is unlikely
> 
> This line suggests that in total only 911 fragments were found overlapping the HLA gene exons which seems very low for exome data:
> 
> [INFO ] totalFrags(911) minEvidence(2.0) minHighQualEvidence(0.3)
> 
> Did you get a qc file produced. If so, perhaps you could share that?
> 
> I think I would need to look at the data directly to comment more on the specific issue. You can email me at [p.priestley@hartwigmedicalfoundation.nl](mailto:p.priestley@hartwigmedicalfoundation.nl) if you want to discuss sharing that for one patient to diagnose the problem

Actually, lilac failed on this patient, so there was no any file output. And is there any solution for lilac to deal with such genome within ALT contigs?

**Comment by p-priestley** [comment]
I am not sure the problem is the reference genome.   It might just be that certain exons have very poor coverage in your exome panel.  I cannot tell without looking at some example data
