### ISSUE TITLE
Change "gender" to "sex" in PURPLE outputs

### ISSUE THREAD

**Issue by nalcala** [hartwigmedical/hmftools#416]
Hi, 

thanks for the great tools, they have been very helpful to us in our studies. I just thought to bring your attention to a change of wording that I am myself manually changing systematically in the PURPLE output but that would actually be better incorporated from the beginning: the column reporting what kind of sex chromosomes were found should be called sex and not gender, because what is inferred is of course purely biological.

Cheers,

Nicolas

**Comment by charlesshale** [comment]
Thanks for this suggestion and it has been added to the list of future improvements.
