### ISSUE TITLE
ORANGE (v2.5.0) could not find features plots from CUPPA (v1.8)

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#428]
I am running ORANGE (v2.5.0) to summarize the key outputs from all algorithms in the Hartwig suite.

But some samples failed to run when '-cuppa_feature_plot' was specified, because of the lack of features plot (tumor-id.cup.report.features.png) from CUPPA. 

Base on the line 143 to line 191 of the source code [CupGenerateReport_pipeline](https://github.com/hartwigmedical/hmftools/blob/master/cuppa/src/main/resources/r/CupGenerateReport_pipeline.R): samples with features less than 15 will only get a merge summary plot with features; samples with features more than 15 will get separated features plot and summary plot, but summary plot without features.

Could ORANGE return warning but not error, when run with parameter '-cuppa_feature_plot' but lack of features plot?

**Comment by kduyvesteyn** [comment]
Suggestion makes sense but suggest to switch to ORANGE 2.6.0 instead (although I see there is no proper release linked yet). In this version you only have to provide individual dirs, so you can provide `cuppa_dir` and ORANGE will determine whether there is a feature plot to be used or not.
