### ISSUE TITLE
Linx neo-epitope file(tumor-id.linx.neoepitope.tsv) not found

### ISSUE THREAD

**Issue by YingYa** [hartwigmedical/hmftools#429]
I am running neo (v1.0.1), and get the following warning: Linx neo-epitope file(tumor-id.linx.neoepitope.tsv) not found.

The neo-epitope file generated from Linx (v1.23.6) is named tumor-id.linx.neo_epitope.tsv, and is CSV format not TSV format.

After following processing, the neo could run without warning:
csvtk csv2tab /path/to/linx/tumor-id.linx.neo_epitope.tsv > /path/to/linx/tumor-id.linx.neoepitope.tsv

**Comment by charlesshale** [comment]
Linx will write TSV output from v1.24 onwards, due for release shortly
