### ISSUE TITLE
Provide Focal Copy Number Identifications by PURPLE

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#43]
I thought about writing an R script that processes pairs of gene CNV and CNV segment files for each patient to identify genes that are focally amplified or deleted by identifying genes in copy number blocks which have a copy number that spans less than 5% of the chromosome the gene is located on. But, it might be a result that many users of PURPLE are interested in, so it would be nice to have such information computed by PURPLE in a standard way, so users don't come up with custom scripts which each do the calculation in a slightly different way.

**Comment by p-priestley** [comment]
For now, TUMOR.purple.cnv.gene.tsv contains the minimum exonic copy number for the gene and the bounds of that minimum.

More generally, we think of all copy number segments that are not full chromosome events as 'focal' and that the aim should be to link them to the SV events that cause them.   We are finalising a new prorgam called LINX which includes functionality to link every driver amplification, deletion and LOH directly to the structural variant clusters which contribute them

**Comment by p-priestley** [comment]
Closing as WONT_FIX
