### ISSUE TITLE
[ERROR]cobalt germline error

### ISSUE THREAD

**Issue by YuP9934** [hartwigmedical/hmftools#432]
hi,I only have a standard sample data of NA12878, and I want to run purple software to detect copy number variation.
So I've chosen the germline mode.But I had a problem executing it.Could you help me deal it?
When I use cobalt, the script I use is
'_java -jar cobalt_v1.14.jar -reference WGS -reference_bam WGS.bam -gc_profile GC_profile.1000bp.37.cnp_'
But there was a mistake,
ERROR:'_Warning: pcf is not run for sample 1 on chromosome arm  because all observations are missing. NA is returned._'
I don't know. Is there something missing in my input?
Without the pcf file, the purple behind it will not work properly

**Comment by p-priestley** [comment]
Just to be sure of your use case, PURPLE is not intended as a comprehensive germline CNV caller.  The germline mode is mainly to annotate germline SV and SNV with the correct copy number and to identify genes that are deleted in the germline.

**Comment by hongwingl** [comment]
Cobalt expect chromosome names for v37 to be 1, 2, 3.. X, Y etc. What is the chromosome names for NA12878 bam file? You can find that with `samtools view -H WGS.bam`
