### ISSUE TITLE
GC_profile profiles generation 

### ISSUE THREAD

**Issue by DanielNaro** [hartwigmedical/hmftools#435]
Hi,
Could you please share how the GC_profile files have been generated?
Regards,
Daniel

**Comment by p-priestley** [comment]
This file simply contains the GC proportion, % of N bases and average mappability of each 1kb window.   Details can be found here:

https://github.com/hartwigmedical/scripts/tree/b49ba4859025cedbbe48738e1ad6c0e5d8ef3b6e/mappability
