### ISSUE TITLE
GRIPSS: missing sample names error

### ISSUE THREAD

**Issue by diljotgrewal** [hartwigmedical/hmftools#441]
Hi, 
I'm trying to run gridss and am getting the following error

```
14:17:28.935 [INFO ] Gripss version: 2.3.4
14:17:28.938 [INFO ] loading reference data
14:17:39.427 [INFO ] loaded 8508747 germline SV PON records from file(reference/sv/sv_pon.37.bedpe.gz)
14:17:41.283 [INFO ] loaded 2546492 germline SGL PON records from file(reference/sv/sgl_pon.37.bed.gz)
14:17:41.292 [INFO ] loaded 458 known hotspot records from file
14:18:02.977 [INFO ] loaded 5295850 repeat-mask entries from file(reference/sv/repeat_mask_data.37.fa.gz)
14:18:03.102 [INFO ] sample(SAMPLE_T) processing VCF(gridss.vcf)
14:18:03.103 [ERROR] missing sample names(ref=SAMPLE_N tumor=SAMPLE_T) in VCF: [SAMPLE_T, SAMPLE_N]
```

Would appreciate any help figuring this out. Thank you so much
Diljot

**Comment by charlesshale** [comment]
Can you share the command you ran?

If you specify 'reference' and 'sample' config, then the  input VCF must contain both those genotype names in that order.

**Comment by diljotgrewal** [comment]
I'll try to provide a reproducible example with data soon.

In the mean time, I switched to v2.2 and that fixed the problem, without making any changes to vcf or arguments.

**Comment by Indianhedgehog** [comment]
Indeed Gripss throws the above error in the latest version when `--labels ` command is used during GRIDSS

For example: you get an error when the following command is used.
`gridss --jvmheap 32G --otherjvmheap 4G --reference /omics/odcf/analysis/hipo/hipo_021/RP_all_RNAseq/temp_files/reference/hs37d5_PhiX.fa --output /omics/odcf/analysis/hipo/hipo_018/rajesh_test/hmf/H021-B34NNL/gridss/sample_metastasis_H021-B34NNL.gridss.vcf.gz --assembly /omics/odcf/analysis/hipo/hipo_018/rajesh_test/hmf/H021-B34NNL/gridss/sample_metastasis_H021-B34NNL.assembly.gridss.bam --threads 16 --workingdir /omics/odcf/analysis/hipo/hipo_018/rajesh_test/hmf/H021-B34NNL/gridss/gridssTmp --labels sample_metastasis_H021-B34NNL,sample_blood_H021-B34NNL --blacklist /omics/odcf/analysis/hipo/hipo_021/RP_all_RNAseq/hmf/v5_34/ref/37/sv//gridss_blacklist.37.bed.gz  /omics/odcf/project/hipo/hipo_021/sequencing/whole_genome_sequencing/view-by-pid/H021-B34NNL/metastasis/paired/merged-alignment/.merging_0/metastasis_H021-B34NNL_merged.mdup.bam /omics/odcf/project/hipo/hipo_021/sequencing/whole_genome_sequencing/view-by-pid/H021-B34NNL/blood/paired/merged-alignment/.merging_0/blood_H021-B34NNL_merged.mdup.bam 
`
whereas if you remove the labels command , it works just fine
