### ISSUE TITLE
Hyper-segmented Samples Handling by Purple

### ISSUE THREAD

**Issue by asd1289** [hartwigmedical/hmftools#444]
Hi,

I was wondering if there are ways to deal with hyper-segmented samples in Purple. 

As far as I understand, in the absence of SV breakpoints, the segmentation from Cobalt and Amber are combined and breakpoints are accepted if they are a genomic window apart (eg 1kb). In noisy samples the total copy number signal (processed by cobalt) is often the source of hyper-segmentation. Methods like Battenberg try to use BAF only segmentation, but that leads to throwing out small events since BAF resolution is lower and non-uniform. The other solution for a rescue of such samples is to smooth the signal. 

Can we control the genomic window parameter in Purple so we can increase the accepted distances for breakpoint to be integrated? Or would running Cobalt at lower resolution the only way? A lot of FFPE samples will have this issue and rejecting these samples seem to be the less preferred solution. 

Any advice on how to deal with noisy samples will be great apart from the query of the window sizes.

**Comment by p-priestley** [comment]
Hi there,

Here is an overview of the smoothing PURPLE does already: https://github.com/hartwigmedical/hmftools/tree/master/purple#4-copy-number-smoothing

I am not sure from your description above what pattern of noise you are seeing.   In some samples we see many short FP segments and we do have a couple  smoothing parameters which are settable and can help here.  Please see.
https://github.com/hartwigmedical/hmftools/tree/master/purple#optional-smoothing-arguments

We don't support changing the 1kb window size sorry.  In COBALT there is one smoothing parameter in the pcf algorithm which you could try raising "-pcf_gamma".

If you are fine to post a snippet of the somatic CNV output (or share with me at p.priestley@hartwigmedicalfoundation.nl) then I could give more specific advice.

**Comment by asd1289** [comment]
I think this is a great starting point. I will close the issue and reach out on your email if there are specific noise patterns are problematic. 

Thank you.
