### ISSUE TITLE
from where can i create ensemble data direct file called ensembl_gene_data.csv, ensembl_protein_features.csv , ensembl_trans_exon_data.csv,  ensembl_trans_splice_data.csv how did u create all these files

### ISSUE THREAD

**Issue by gagank4911** [hartwigmedical/hmftools#452]
i would like you to know how did u create all the files and which columns of which file is been used for what purpose and list  the tools used to create the file it would be very helpful

**Comment by gagank4911** [comment]
my doubt has not been cleared can you please explain properly

**Comment by p-priestley** [comment]
The ensembl database can be downloaded from ensembl:  https://asia.ensembl.org/info/data/index.html

Could you please give more details on your use case is and why you want to recreate these derived files?
