### ISSUE TITLE
i would like to know the information inside a GC_profile.1000bp.38.cnp  file like what the column names are 

### ISSUE THREAD

**Issue by gagank4911** [hartwigmedical/hmftools#453]
GNU nano 6.2                                    GC_profile.1000bp.38.cnp                                              chr1    0       -1      0       0
chr1    1000    -1      0       0
chr1    2000    -1      0       0
chr1    3000    -1      0       0
chr1    4000    -1      0       0
chr1    5000    -1      0       0
chr1    6000    -1      0       0
chr1    7000    -1      0       0
chr1    8000    -1      0       0
chr1    9000    -1      0       0
chr1    10000   0.646   1       0.271
chr1    11000   0.543   1       0
chr1    12000   0.6     1       0
chr1    13000   0.575   1       0
chr1    14000   0.583   1       0
chr1    15000   0.62    1       0
chr1    16000   0.565   1       0
chr1    17000   0.622   1       0
chr1    18000   0.592   1       0
chr1    19000   0.577   1       0
chr1    20000   0.49    1       0
chr1    21000   0.591   1       0
chr1    22000   0.543   1       0
chr1    23000   0.507   1       0
chr1    24000   0.542   1       0
chr1    25000   0.503   1       0

**Comment by p-priestley** [comment]
FYI - I added a comment to the COBALT page which describes the file

This file contains 5 columns for each 1kb window of the genome {chromosome,position,GC Proportion,Non N Proportion,Average Mappability}.
