### ISSUE TITLE
sage error mRefContext

### ISSUE THREAD

**Issue by alhafidzhamdan** [hartwigmedical/hmftools#457]
Hi HMF team,

I'm running sage in an LSF cluster.
I keep getting this mRefContext is NULL error at the processALTRead stage.
Screenshots:

![Screenshot 2023-08-26 at 12 44 58](https://github.com/hartwigmedical/hmftools/assets/53702866/e5cad20e-c529-4397-ba8d-173700c24949)

In between these lines, there were endless lines of these:
![Screenshot 2023-08-26 at 12 45 47](https://github.com/hartwigmedical/hmftools/assets/53702866/f7ca343e-99ec-4a7c-a4aa-00c8ff9db65d)

![Screenshot 2023-08-26 at 12 46 07](https://github.com/hartwigmedical/hmftools/assets/53702866/330e7857-22b0-4acb-9dec-e918b7fc62e2)

My commands are:
![Screenshot 2023-08-26 at 12 50 18](https://github.com/hartwigmedical/hmftools/assets/53702866/f4208ac0-7320-4eb5-8b6f-47519fdbd265)

Using threads = 32

Any ideas? Thanks for looking into it

Al

**Comment by charlesshale** [comment]
Is your BAM definitely sorted?

**Comment by alhafidzhamdan** [comment]
I ran this  

`samtools sort -@ ${THREADS} -m 2G -T ${PATIENT_ID}T -O bam ${ALIGNED_BAM_FILE_NORMAL} -o ${ALIGNED_BAM_FILE_NORMAL_SORTED} `

for both tumour and normal bams and tried sage again and the same error occured.

**Comment by charlesshale** [comment]
Could you try a later version of Sage (eg v3.3) to see if it also hits this error?

Are you able to email me a small slice of the BAM so I can debug what is going on? c.shale@hartwigmedicalfoundation.nl

thanks.

**Comment by alhafidzhamdan** [comment]
Hi Charles, 
The original bam file was aligned using ISAAC.
I re-aligned my bam using BWA and it seemed to have worked.
