### ISSUE TITLE
PURPLE: alternate copy number solutions

### ISSUE THREAD

**Issue by felixbeaudry** [hartwigmedical/hmftools#459]
Hi,

Great software suite! Switching to PURPLE has made it much easier for us to call copy number variants.

I was wondering if it is possible to extract the copy number profiles for alternate purity/ploidy solutions, for when a secondary solution is close enough to the primary solution that it is worth considering/evaluating. I anticipate the segments themselves won't change, but the copy numbers might, and I'd like to have these for alternate solutions - is there a tool, command parameter or file I should look at?

Thank you,
Felix

**Comment by p-priestley** [comment]
Felix - please take a look here: https://github.com/hartwigmedical/hmftools/tree/master/purple#optional-fitting-arguments

You can set a minPurity/maxPurity and/or minPloidy/maxPloidy to force the fit to the one you want tocheck.

**Comment by felixbeaudry** [comment]
terrific, thank you!
