### ISSUE TITLE
SAGE issue ： INDEL 

### ISSUE THREAD

**Issue by xdgene** [hartwigmedical/hmftools#463]
Thank you very much for such excellent software development！ I am currently encountering an issue while using Sage to identify somatic mutations.I have noticed that Sage did not detect a deletion that is indeed present, whereas other software like Mutect2 and VarDict were able to detect it. I have also confirmed the deletion's existence using IGV.
![捕获](https://github.com/hartwigmedical/hmftools/assets/107597322/cf99066e-a9d1-450f-a10a-90ba0d37a448)

The arguments I used: 
`java -jar sage_v3.3.1.jar -threads 16 -reference 2022_N -reference_bam 2022_N_sorted.dedup.bam -tumor 2022_T -tumor_bam 2022_T_sorted.dedup.bam -ref_genome_version 37 -ref_genome hg19.fa -hotspots HMFtools-Resources/variants/KnownHotspots.somatic.37.vcf.gz -panel_bed 2022.bed -panel_only  -panel_min_tumor_vaf 0.01  -ensembl_data_dir HMFtools-Resources/common/ensembl_data  -out 2022.sage.vcf.gz`

How can I adjust the arguments to call this deletion?

**Comment by p-priestley** [comment]
Hello,  the first thing to do is to understand why it has been filtered.   Was this soft filtered by SAGE or hard filtered?   

If soft filtered, please provide the vcf output for the variant and we can assist.

If hard filtered then you need to try to understand why it is not being called.     There are only a handful of hard filters (https://github.com/hartwigmedical/hmftools/tree/master/sage#hard-filters) and none would appear to apply here, so hopefully this is unlikely.

**Comment by xdgene** [comment]
> Hello, the first thing to do is to understand why it has been filtered. Was this soft filtered by SAGE or hard filtered?
> 
> If soft filtered, please provide the vcf output for the variant and we can assist.
> 
> If hard filtered then you need to try to understand why it is not being called. There are only a handful of hard filters (https://github.com/hartwigmedical/hmftools/tree/master/sage#hard-filters) and none would appear to apply here, so hopefully this is unlikely.

I forgot to mention that I also used both '-disable_hard_filter' and '-disable_soft_filter' parameters to turn off the filters, but still not work.  Is it okay to use these two parameters together like this?
`java -jar sage_v3.3.1.jar -threads 16 -reference 2022_N -reference_bam 2022_N_sorted.dedup.bam -tumor 2022_T -tumor_bam 2022_T_sorted.dedup.bam -ref_genome_version 37 -ref_genome hg19.fa -hotspots HMFtools-Resources/variants/KnownHotspots.somatic.37.vcf.gz -panel_bed 2022.bed -panel_only  -panel_min_tumor_vaf 0.01  -ensembl_data_dir HMFtools-Resources/common/ensembl_data  -out 2022.sage.vcf.gz -disable_hard_filter -disable_soft_filter `

**Comment by charlesshale** [comment]
Yes those 2 parameters can be used together

**Comment by charlesshale** [comment]
If that KMT2B variant in the panel BED you've provided? With this argument '-panel_only', Sage will only call variants in that BED region file '2022.bed'.

We will need a slice of the BAM to be able to determine why the variant isn't called. I agree the evidence is clear.

**Comment by xdgene** [comment]
> If that KMT2B variant in the panel BED you've provided? With this argument '-panel_only', Sage will only call variants in that BED region file '2022.bed'.
> 
> We will need a slice of the BAM to be able to determine why the variant isn't called. I agree the evidence is clear.

Here' my test bam and bed.  [](https://github.com/xdgene/test)  I'm sorry for taking up your time. Thank you very much！

**Comment by xdgene** [comment]
> If that KMT2B variant in the panel BED you've provided? With this argument '-panel_only', Sage will only call variants in that BED region file '2022.bed'.
> 
> We will need a slice of the BAM to be able to determine why the variant isn't called. I agree the evidence is clear.

Here' my test bam and bed.
 `https://github.com/xdgene/test`
  I'm sorry for taking up your time. Thank you very much！

**Comment by charlesshale** [comment]
I can see that this BAM has 'chr' prefixes - it needs these prefixes stripped off to work with Sage.

**Comment by xdgene** [comment]
> I can see that this BAM has 'chr' prefixes - it needs these prefixes stripped off to work with Sage.

 It works fine even with the prefixes. Other mutations are called normally; it's just that this 'del' is missing
