### ISSUE TITLE
SAGE: multiallelic variants

### ISSUE THREAD

**Issue by andrianovam** [hartwigmedical/hmftools#468]
Could you please clarify how SAGE is dealing with multiallelic variants (positions with more then one alternative allele) and how such variants should be outputted (each alternative allele as a separate line/all alt alleles separated by coma in one line/etc)? I am sorry if I missed this but I was not able to find answer in the documentation..Thank you!

**Comment by charlesshale** [comment]
Sage will write these as separate lines in the VCF
