### ISSUE TITLE
PURPLE: structural_vcf and sv_recovery_vcf

### ISSUE THREAD

**Issue by vladsaveliev** [hartwigmedical/hmftools#47]
I'm wondering what's the difference between `structural_vcf` and `sv_recovery_vcf` arguments? In previous versions I used to feed my manta output using `structural_vcf`, which if I understand correctly was used both for guidance of CN breakpoint calling and for SV recovery. If I read the code correctly, these 2 purposes are now separated. Should I still feed the same VCF with both arguments, or there are some specific recommendations?

**Comment by p-priestley** [comment]
Please check readme.

https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#7-structural-variant-recovery

Note It is mainly designed with GRIDSS SV calling in mind.  GRIDSS produces a high confidence (similar to Manta + BPI) and low confidence call set.    It is optional, so I would probably not recommend using it if you don't use GRIDSS

**Comment by vladsaveliev** [comment]
Thanks for the explanation! I read that bit but wasn't sure about the difference between those 2 arguments. All clear now.

We are still using Manta+BPI in production, but switching to GRIDSS now. Thanks for your work on PURPLE and all recent improvements.
