### ISSUE TITLE
RData File of All Plots

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#48]
It would be convenient to be able to load the plots into an R session and edit aspects of them such as the axis titles. Currently, they are in PNG format. For example, I'd like to use `ggtitle` to add the sample ID to the tops of rainfall plots and perhaps change the x-axis data to chromosome names rather than mutation number and segment the plot by chromosomes using `geom_vline` to draw a vertical line between each chromosome.

**Comment by jonbaber** [comment]
Hi Dario, 

Good news is you already can make your own modifications! 

The plots are generated from the PURPLE output. You can re-run the R scripts at any time with any modifications as you see fit. 

You just need to supply the sample name, purple output dir and plot dir to the scripts as documented in the readme: https://github.com/hartwigmedical/hmftools/blob/master/purity-ploidy-estimator/README.md#charts

The copy number plots script is [here](https://github.com/hartwigmedical/hmftools/blob/master/purity-ploidy-estimator/src/main/resources/r/copyNumberPlots.R) and the somatic plots script is [here](https://github.com/hartwigmedical/hmftools/blob/master/purity-ploidy-estimator/src/main/resources/r/somaticVariantPlots.R)

Hope this helps.

Jon
