### ISSUE TITLE
Resource Download Failure

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#49]
I am trying to download the hg19 GC profile for Cobalt from the website, but I get a failure at somewhere between 8 MB to 11 MB out of 13.6 MB. The failure is at a different point for different repetitions. It happens at home and at university. I have tried three times at each location. At home, I used Microsoft Edge and Windows 10 yesterday. At university, I used CentOS 6.9 and Firefox earlier today. Is this problem reproducible by others? It would be convenient to make a URL available for use with `wget` instead of needing to download via a browser.

**Comment by jonbaber** [comment]
I tried it just now and it works for me.

**Comment by DarioS** [comment]
A colleague working elsewhere downloaded it and uploaded it to Slack, where I could download it from easily without truncation.
