### ISSUE TITLE
abundance estimate from cider

### ISSUE THREAD

**Issue by alhafidzhamdan** [hartwigmedical/hmftools#493]
Hi all, 
Testing CIDER with my tumour bams, and all went smoothly.
Quick question: Which file and what is the column output to use in estimating T-cell abundance in tumour cells? To put it in another way, how do i calculate abundance in this case using your output?

From you readme:

`For other tumors, the abundance estimate can be used to estimate immune infiltration and may give insight into diversity, and/or recurrent and cancer specific T-cell clones.
`

Cheers
A

**Comment by p-priestley** [comment]
You can use either 'minHighQualBaseReads' or 'assignedReads' to determine abundance of each passing sequence.

**Comment by hongwingl** [comment]
Those are inside the `<sampleId>.cider.vdj.tsv.gz` file
