### ISSUE TITLE
Out of memory when running isofox TRANSCRIPT_COUNTS

### ISSUE THREAD

**Issue by onebeingmay** [hartwigmedical/hmftools#494]
Hello Hartwig,
Thank you for presenting such as nice tool. I encountered "out of memory" error when trying to count reads in the RNASeq file downloaded. Here is my pipeline:
1. Convert the cram file downloaded from HMF bucket to bam file
```
samplename=`CPCT02010281T_dedup.realigned.cram`
samtools view -b -T reference/Homo_sapiens.GRCh37.GATK.illumina.fasta -o bam/$samplename.bam cram/$samplename.cram
```
This generated a bam file sized 198G: CPCT02010281T_dedup.realigned.bam
2. Run isofox to quantify reads

`isofox -sample $samplename -functions TRANSCRIPT_COUNTS -bam_file bam/$samplename.bam -ref_genome reference/Homo_sapiens.GRCh37.GATK.illumina.fasta -ensembl_data_dir reference/hmf_references/common/ensembl_data -read_length 151 -exp_counts_file reference/hmf_references/HMFtools-Resources_rna_pipeline_37_isofox_read_151_exp_counts.csv -exp_gc_ratios_file reference/hmf_references/HMFtools-Resources_rna_pipeline_37_isofox_read_100_exp_gc_ratios.csv -output_dir counts -threads 24`

Here is the output of the program

> 
> 16:07:18 - [INFO ] - Isofox version: 1.6.2
> 16:07:18 - [INFO ] - running function(s): TRANSCRIPT_COUNTS
> 16:07:23 - [INFO ] - fragment lengths(75, 100, 125, 150, 200, 250, 300, 400, 550) set from expected transcript counts file
> 16:07:48 - [INFO ] - loaded 26631 gene expected counts from file(reference/hmf_references/HMFtools-Resources_rna_pipeline_37_isofox_read_151_exp_counts.csv)
> 16:07:54 - [INFO ] - loaded 210180 transcript expected GC ratios from file(reference/hmf_references/HMFtools-Resources_rna_pipeline_37_isofox_read_100_exp_gc_ratios.csv)
> 16:07:54 - [INFO ] - sample(CPCT02010281T_dedup.realigned) running RNA analysis
> 16:35:31 - [INFO ] - max observed read length(0) set
> 16:35:31 - [INFO ] - fragmentLength(75) frequency(0)
> 16:35:31 - [INFO ] - fragmentLength(100) frequency(0)
> 16:35:31 - [INFO ] - fragmentLength(125) frequency(0)
> 16:35:31 - [INFO ] - fragmentLength(150) frequency(0)
> 16:35:31 - [INFO ] - fragmentLength(200) frequency(0)
> 16:35:31 - [INFO ] - fragmentLength(250) frequency(0)
> 16:35:31 - [INFO ] - fragmentLength(300) frequency(0)
> 16:35:31 - [INFO ] - fragmentLength(400) frequency(0)
> 16:35:31 - [INFO ] - fragmentLength(550) frequency(0)
> 16:35:31 - [INFO ] - PerfStat(FragLengthDist) intervals(19969) total(24297.981 avg=1.217 max=107.883)
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
> 	at com.hartwig.hmftools.isofox.common.BaseDepth.<init>(BaseDepth.java:33)
> 	at com.hartwig.hmftools.isofox.FragmentAllocator.<init>(FragmentAllocator.java:154)
> 	at com.hartwig.hmftools.isofox.ChromosomeTaskExecutor.<init>(ChromosomeTaskExecutor.java:105)
> 	at com.hartwig.hmftools.isofox.Isofox.allocateBamFragments(Isofox.java:198)
> 	at com.hartwig.hmftools.isofox.Isofox.runAnalysis(Isofox.java:150)
> 	at com.hartwig.hmftools.isofox.Isofox.main(Isofox.java:512)

I ran this on our HPC (big memory node) so memory shouldn't be an issue. I suspect my pipeline is wrong. Do you have any idea? Thanks!

**Comment by charlesshale** [comment]
Is Isofox being run on a DNA BAM/CRAM file? It is only designed to work on RNA. The CPCT sample ID suggests it is a DNA BAM.

Also Isofox will run directly on a CRAM, but still must be RNA and aligned with STAR not BWA.

**Comment by onebeingmay** [comment]
Thanks Charles. I indeed downloaded the DNA cram. Now I downloaded the RNASeq fastq, mapped with STAR and ran isofox. 
Here is my pipeline:

```
sample=CPCT02010276TII_AHTJKMBGX2_S2_L001

STAR --runThreadN 12 --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 --outSAMattributes All --outFilterMultimapNmax 10 \
--outFilterMismatchNmax 3 limitOutSJcollapsed 3000000 -chimSegmentMin 10 --chimOutType WithinBAM SoftClip \
--chimJunctionOverhangMin 10 --chimSegmentReadGapMax 3 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 \
--chimScoreSeparation 1 --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --outFilterMatchNmin 35 \
--alignSplicedMateMapLminOverLmate 0.33 --alignSplicedMateMapLmin 35 --alignSJstitchMismatchNmax 5 -1 5 5 --genomeDir reference/GRCh37.GATK.genome_index \
--readFilesIn fastq/${sample}_R1_001.fastq.gz fastq/${sample}_R2_001.fastq.gz \
--readFilesCommand zcat \
--outFileNamePrefix bam/"${sample}"

samtools sort -@ 12 bam/${sample}Aligned.out.bam -o bam/${sample}.bam
samtools index bam/${sample}.bam

isofox -sample $sample -functions TRANSCRIPT_COUNTS -bam_file bam/${sample}.bam -ref_genome reference/Homo_sapiens.GRCh37.GATK.illumina.fasta -ensembl_data_dir reference/hmf_references/common/ensembl_data -exp_gc_ratios_file reference/hmf_references/HMFtools-Resources_rna_pipeline_37_isofox_read_100_exp_gc_ratios.csv -output_dir counts -threads 12
```

But I encounter two problems:
1. How do I know which "exp_counts.csv" to use? There are two "read_151_exp_counts.csv" and "read_76_exp_counts.csv". I guess it depends on the fastq read length. But the fastq on Hartwig are either 2x75bp or 2x150bp. Do you know if there is any automatic way to determine the read length when processing a large batch of fastqs?
2. I still encountered "Java heap space" error. Here is the output of isofox:

> 10:13:05 - [INFO ] - Isofox version: 1.6.2
> 10:13:05 - [INFO ] - running function(s): TRANSCRIPT_COUNTS
> 10:13:11 - [INFO ] - loaded 210180 transcript expected GC ratios from file(/lustre/fs4/tavz_lab/scratch/wmei/reference/hmf_references/HMFtools-Resources_rna_pipeline_37_isofox_read_100_exp_gc_ratios.csv)
> 10:13:11 - [INFO ] - sample(CPCT02010276TII_AHTJKMBGX2_S2_L001) running RNA analysis
> 10:13:11 - [INFO ] - chr(22) processing 852 genes
> 10:13:11 - [INFO ] - chr(6) processing 1936 genes
> 10:13:11 - [INFO ] - chr(9) processing 1472 genes
> 10:13:11 - [INFO ] - chr(16) processing 1350 genes
> 10:13:11 - [INFO ] - chr(3) processing 2183 genes
> 10:13:11 - [INFO ] - chr(14) processing 1502 genes
> 10:13:11 - [INFO ] - chr(1) processing 3582 genes
> 10:13:11 - [INFO ] - chr(17) processing 1823 genes
> 10:13:11 - [INFO ] - chr(2) processing 2761 genes
> 10:13:11 - [INFO ] - chr(4) processing 1589 genes
> 10:13:11 - [INFO ] - chr(5) processing 1730 genes
> 10:13:11 - [INFO ] - chr(7) processing 1797 genes
> 10:22:14 - [INFO ] - chr(21) processing 502 genes
> 10:22:40 - [INFO ] - chr(Y) processing 417 genes

and many lines of "processing genes" info then

> 10:22:40 - [ERROR] - task execution error: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
> 10:22:40 - [INFO ] - chr(X) processing 1801 genes
> java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space

Thanks again

**Comment by charlesshale** [comment]
Isofox needs to be passed the correct read-length expected counts file, so you will need to know the read length for your samples.

For the out-of-memory issue, I would try passing it an argument to set the max heap-size higher, eg:
java -Xmx32G -jar isofox.jar etc

How much memory do you have on your server? Roughly how many reads are in your BAM?

Also did you run Sambamba MarkDuplicates on it first?

**Comment by onebeingmay** [comment]
1. Taking your advice, I marked duplicates using samtools and -Xmx32G indeed solved the out of memory issue. Now my program can run to the end but raised new error:
Running`
samtools collate bam/${sample}Aligned.out.bam bam/${sample}collate
samtools fixmate -m bam/${sample}collate.bam bam/${sample}fixmate.bam
samtools sort -@ 24 bam/${sample}fixmate.bam -o bam/${sample}sorted.bam
samtools markdup bam/${sample}sorted.bam bam/${sample}dupmarked.bam
samtools index bam/${sample}dupmarked.bam

isofox -Xmx32G -sample $sample -functions TRANSCRIPT_COUNTS -bam_file bam/${sample}dupmarked.bam -ref_genome reference/Homo_sapiens.GRCh37.GATK.illumina.fasta -ensembl_data_dir /reference/hmf_references/common/ensembl_data -exp_gc_ratios_file reference/hmf_references/HMFtools-Resources_rna_pipeline_37_isofox_read_100_exp_gc_ratios.csv -output_dir counts -threads 24`

Outputs

> 21:48:47 - [INFO ] - chr(Y) processed 100 of 417 genes
> 21:48:48 - [INFO ] - chr(Y) processed 200 of 417 genes
> 21:48:48 - [INFO ] - chr(Y) processed 300 of 417 genes
> 21:48:49 - [INFO ] - chr(Y) processed 400 of 417 genes
> 21:48:49 - [INFO ] - chr(Y) processing complete
> 21:48:49 - [INFO ] - read 16586552 total BAM records
> 21:48:49 - [INFO ] - applying GC adjustments and transcript re-fit
> 21:48:49 - [ERROR] - invalid expected(0) or actual(7277728) totals
> 21:48:49 - [ERROR] - task execution error: java.lang.NullPointerException
> java.lang.NullPointerException
> 	at com.hartwig.hmftools.isofox.ChromosomeTaskExecutor.applyGcAdjustToTranscriptAllocations(ChromosomeTaskExecutor.java:465)
> 	at com.hartwig.hmftools.isofox.ChromosomeTaskExecutor.call(ChromosomeTaskExecutor.java:152)
> 	at com.hartwig.hmftools.isofox.ChromosomeTaskExecutor.call(ChromosomeTaskExecutor.java:54)
> 	at com.hartwig.hmftools.common.utils.TaskExecutor.executeTasks(TaskExecutor.java:58)
> 	at com.hartwig.hmftools.isofox.Isofox.applyGcAdjustments(Isofox.java:341)
> 	at com.hartwig.hmftools.isofox.Isofox.processBamFragments(Isofox.java:261)
> 	at com.hartwig.hmftools.isofox.Isofox.allocateBamFragments(Isofox.java:219)
> 	at com.hartwig.hmftools.isofox.Isofox.runAnalysis(Isofox.java:150)
> 	at com.hartwig.hmftools.isofox.Isofox.main(Isofox.java:512)
> 21:49:00 - [INFO ] - Isofox complete, mins(13.011)

The problem seems to be from GC adjustment. If I removed the "-exp_gc_ratios_file" option the error disappeared.

2. Examining the isofox output the TPM of all genes is 0 (in CPCT02010276TII_AHTJKMBGX2_S2_L001.isf.gene_data.csv). Do you have an idea?

Thanks and Happy new year!

**Comment by charlesshale** [comment]
There is an inconsistency with the transcripts passes to Isofox and our generated expect counts and ratios files. We recommend running Isofox as part of our OncoAnalyser pipeline to ensure consistency of all reference data.
