### ISSUE TITLE
GC profile for Cobalt

### ISSUE THREAD

**Issue by ohofmann** [hartwigmedical/hmftools#5]
Hi,

I notice Cobalt requires a GC profile. Is this identical to the one generated via FREEC (http://bioinfo-out.curie.fr/projects/freec/tutorial.html#GCP) or an in-house profile? If the former, I assume window size is expected to match the window size for Cobalt?

Thanks, Oliver

**Comment by jonbaber** [comment]
Hi Oliver, 

1) Yes, we use the same format as FREEC
2) Correct, it should match the Cobalt window size.

We currently use a window size of 1000. Let me know if you would like me to make our GC profile available to you.

Cheers, Jon

**Comment by ohofmann** [comment]
Jon, yes please. We'll likely generate this in-house down the road, but to get started (and for comparisons) it would be easier to re-use the existing profile.

Cheers, Oliver

**Comment by jonbaber** [comment]
Great. You can access our pipe line dependencies [here](https://nc.hartwigmedicalfoundation.nl/index.php/s/a8lgLsUrZI5gndd?path=%2FHMF-Pipeline-Dependencies).

Jon
