### ISSUE TITLE
LILAC error: Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by LongpanUPC** [hartwigmedical/hmftools#501]
Hi hmftools team,
   firstly thank you for developing LILAC tool to detect HLA genotype and LOH. I try to deploy this tool in my series. According to the protocol, I successfully run it on normal sample only. However, when I added the tumor bam, somatic vcf file and copy-number file. The error shown above occured. Then I removed the parameter of copy-number, it run successfully. I think there is some problem with copy-number file, which was obtained from facets results.(I assigned the total copy number as minCopyNumber and minor allele CN as minMinorAlleleCopyNumber) 
   So I just tried the test sample provided by you from the website (hmf-public/DataAccessRequest-Resources >> somatic vcf and gene-level CNA profile; hmf-public/HMFtools-Resources/dna_pipeline/test_data/COLO_MINI/38 >> tumor/normal bam file). Again, it only works without copy-number file and presented the same error when add copy-number file.

script: 
$tooltojava -jar $maindir/Scripts/lilac_v1.5.2.jar \
   -sample COLO829T \
   -ref_genome $pathto_genomefile \
   -ref_genome_version V38 \
   -resource_dir $maindir/HLA_ref_data/ \
   -reference_bam $maindir/Realigned_BAM/HMFtools-Resources_dna_pipeline_test_data_COLO_MINI_38_COLO829R.bam \
   -tumor_bam $maindir/Realigned_BAM/HMFtools-Resources_dna_pipeline_test_data_COLO_MINI_38_COLO829T.bam \
   -somatic_vcf $maindir/Somatic_vcf/COLO829v003T.purple.somatic.vcf.gz \
   -gene_copy_number $maindir/CNA_gene_level/COLO829v003T.purple.cnv.gene.tsv \
   -output_dir $maindir/Output/COLO829T/ \
   -threads 4

Here is the CNA table I used with 18 columns.
![COLO829v003T purple cnv gene tsv](https://github.com/hartwigmedical/hmftools/assets/110898198/6e610203-8c86-42a8-a369-f3aaff89b923)

The detailed error info:
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
        at com.hartwig.hmftools.lilac.variant.CopyNumberAssignment.loadCopyNumberData(CopyNumberAssignment.java:60)
        at com.hartwig.hmftools.lilac.LilacApplication.extractTumorResults(LilacApplication.java:542)
        at com.hartwig.hmftools.lilac.LilacApplication.run(LilacApplication.java:474)
        at com.hartwig.hmftools.lilac.LilacApplication.main(LilacApplication.java:744)

So, is there something change about copy number file in the version 1.5.2 of LILAC? 
Thank you in advance.

Long

**Comment by LongpanUPC** [comment]
Hi I solved the problem. Some suggestions for other people whole also use CNA results from other tools. The file name of copy-number file should include the sample name and also it need to filter the missing value in column "minMinorAlleleCopyNumber" and "minCopyNumber" otherwise it will also give an error. Besides, keep the same column name and format as purple's output.
 
However, with the increasing understanding of LILAC method, **I have another question.** In the step of detecting HLA LOH, the pipeline said that _fragments of tumor samples are counted for each allele in the determined type. For each of HLA-A, HLA-B & HLA-C, the minor allele copy number from gene copy-number profile is assigned to the allele with the lowest ratio of supporting fragments for the allele in the tumor compared to the normal. The other allele for each is assigned the implied major allele copy number from the gene copy number file_. 
   Does it means that it will use the provided gene copy-number profile to determined the LOH of HLA alleles directly? How does LILAC deal with the following condition that in the whole chr6 region, the tumor sample is WT state with normal diploidy but it had a highly focal LOH only within HLA region. I think this is the problem of most of CNA tools and also was highlighted by the HLALOH cell2017 parper. Is it already solved by the Purple?
  The similar question also for HLA mutations. Does LILAC just only integrate the results from provided the vcf file?  Is it already solved by the SAGE?

  If LILAC detect the HLA genotype by itself and only integrate the HLA-LOH results from purple and mutations from SAGE, it means that using LILAC with gene copy-number file from other CNA tools (e.g. FACETS) and somatic vcf file from other vairant calling tool will produce inaccurate evaluation. I hope my understanding is wrong.
Looking forword to your relpy!
thank you!
Long

**Comment by p-priestley** [comment]
Hello.   

FYI - LILAC has been primarily developed to work with Hartwig tools (in this case PURPLE for copy number and SAGE for small variant calling).  Whilst you may be able to substitute with other similar tools, we have not tested.

Re your specific questions:

_Does it means that it will use the provided gene copy-number profile to determined the LOH of HLA alleles directly?_ 

Yes. That is correct.

_How does LILAC deal with the following condition that in the whole chr6 region, the tumor sample is WT state with normal diploidy but it had a highly focal LOH only within HLA region. I think this is the problem of most of CNA tools and also was highlighted by the HLALOH cell2017 parper. Is it already solved by the Purple?_

This is solved in PURPLE as PURPLE generates a copy number with single base resolution. 
We have a validation that this give sensible results for the HLA genes here: (https://www.nature.com/articles/s41588-023-01367-1/figures/9).

_The similar question also for HLA mutations. Does LILAC just only integrate the results from provided the vcf file?  Is it already solved by the SAGE?_

Yes.  LILAC will only look for evidence from variants identified in the provided SAGE VCF.   SAGE has specific logic for the HLA regions to help improve sensitivity.   LILAC will validate the call and evaluate which locus (A,B,C) and allele it is on.

**Comment by LongpanUPC** [comment]
Thank you for the detailed explanations.
