### ISSUE TITLE
question on Purple output

### ISSUE THREAD

**Issue by riccardobergamin** [hartwigmedical/hmftools#510]
I have a question regarding the output of PURPLE. I am not understanding if the tool returns somewhere the depth ratio per chromosome, or some quantity that allows to compute that. Thank you very much.

**Comment by p-priestley** [comment]
Can you explain what you mean exactly by 'depth ratio per chromosome'?

**Comment by riccardobergamin** [comment]
Hi, i mean the ratio between the number of reads covering a segment in the tumor and normal, normalized by gc content. Is that estimated and used in purple? It was not clear to me from the output. Thank you again for the help.

**Comment by p-priestley** [comment]
Yes.  This is available in the purple.segment.tsv file.

**Comment by riccardobergamin** [comment]
ok,but in the output i could find the following tsv files, did i missed someones, or is it just a different name?

tumor.driver.catalog.tsv
tumor.purple.cnv.gene.tsv
tumor.purple.cnv.germline.tsv
tumor.purple.cnv.somatic.tsv
tumor.purple.purity.range.tsv
tumor.purple.purity.tsv

**Comment by p-priestley** [comment]
it should be:   tumor.purple.segment.tsv

**Comment by riccardobergamin** [comment]
ok, i see. Thank you very much for the clarification.
