### ISSUE TITLE
cobalt targeted mode null pointer exception

### ISSUE THREAD

**Issue by briankegerreis** [hartwigmedical/hmftools#512]
Hello,

I tried to follow the instructions for targeted NGS [here](https://github.com/hartwigmedical/hmftools/blob/master/pipeline/README_TARGETED.md) using amber 3.9.1 and cobalt 1.15.2. Unfortunately I'm getting a null pointer exception from the Normalisation step with little explanation. Would appreciate help diagnosing the issue.

Command:
```
java -cp /hmftools/cobalt_v1.15.2.jar com.hartwig.hmftools.cobalt.norm.NormalisationFileBuilder -sample_id_file sample_ids.csv -cobalt_dir cobalt/ -amber_dir amber/ -ref_genome_version V38 -gc_profile GC_profile.1000bp.38.cnp -target_regions_bed targets.bed -output_file norm_file.tsv
```

Stderr:
```
17:11:14.100 [main] [INFO ] - loaded 8 samples from file
17:11:14.102 [main] [INFO ] - loading GC profile: GC_profile.1000bp.38.cnp
17:11:16.086 [main] [INFO ] - running Cobalt normalisation file generation from 8 samples
17:11:16.551 [main] [INFO ] - loaded 226228 target regions from file(targets.bed)
Exception in thread "main" java.lang.NullPointerException
        at com.hartwig.hmftools.cobalt.norm.GcProfileCache.findGcProfile(GcProfileCache.java:51)
        at com.hartwig.hmftools.cobalt.norm.NormalisationFileBuilder.setGcProfileData(NormalisationFileBuilder.java:138)
        at com.hartwig.hmftools.cobalt.norm.NormalisationFileBuilder.run(NormalisationFileBuilder.java:60)
        at com.hartwig.hmftools.cobalt.norm.NormalisationFileBuilder.main(NormalisationFileBuilder.java:177)
```

There is nothing special about my target BED:
```
chr1    12080   12251
chr1    12595   12802
chr1    13163   13658
chr1    14620   15015
chr1    15795   15914
chr1    16743   17098
chr1    17247   18121
chr1    18216   18411
chr1    18963   19169
chr1    24260   24532
```

**Comment by charlesshale** [comment]
Could you repeat this routine using the latest Cobalt and Amber versions:
https://github.com/hartwigmedical/hmftools/releases/tag/amber-v4.0
https://github.com/hartwigmedical/hmftools/releases/tag/cobalt-v1.16

and see if the issue persists. Thanks.

**Comment by briankegerreis** [comment]
I tried updating the tools but I'm still seeing the same error message. I also noticed -target_regions_bed has been added to the list of amber's options in the latest release and wasn't sure if that needed to be part of the process? But when I tried to pass it, it immediately failed:
10:28:29.569 [INFO ] Amber version 4.0
10:28:39.814 [ERROR] failed to load target regions file(): targets.bed

**Comment by serestech** [comment]
Hello, I was getting the same error here. I noticed that my bed file contained some ALT contigs (e.g., chr7_KI270803v1_alt), and removing those from the file solved the problem in my case. I don't know if ALT contigs are anyway ignored in analysis but in that case they should be handled. Though not sure if the original problem in the issue was this.

**Comment by charlesshale** [comment]
Yes that error is due to the presence of alt contigs. These need to be removed from the target panel definition BED.

Amber does uses this file.
