### ISSUE TITLE
Hotspots

### ISSUE THREAD

**Issue by mimifp** [hartwigmedical/hmftools#515]
Hello, I am a PhD student in molecular medicine. In my group we are interested in launching SAGE to do a variant-calling in human tumors. 

From what I see in the documentation, we need a file with the genome hotspots, and I have several doubts:
- Is the hotspot file relative to the reference genome or relative to the paired normal sample of tumors? 
- If it is for the reference genome, do you know where I can download the hotspot file for the GRCh38 genome?

Thank you very much in advance

**Comment by p-priestley** [comment]
Hi Miriam, 

The purpose of the hotspot file is to specify a set of known or likely pathogenic variants.  They are included in our refernce files: https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/dna_pipeline

Peter

**Comment by mimifp** [comment]
Thank you, Peter!
