### ISSUE TITLE
SAGE Germline files 

### ISSUE THREAD

**Issue by Indianhedgehog** [hartwigmedical/hmftools#519]
Do we use the same `ActionableCodingPanel.37.bed.gz` for SAGE germline and somatic mode?
Also the file  `CoverageCodingPanel.37.bed.gz `  stored in hmf/v5_34/ref/37/variants/ should be used for Germline mode i guess?

Because documentation has 'germline' at the end of the files.
`CoverageCodingPanel.germline.37.bed.gz `

**Comment by charlesshale** [comment]
Yes, use the same for both. I've updated the Sage read-me to remove 'germline' from the file names.

Thanks
