### ISSUE TITLE
Make breakend inferring optional

### ISSUE THREAD

**Issue by vladsaveliev** [hartwigmedical/hmftools#52]
Hi,

Wondering if there is a way to disable inferring of SVs from copy number transitions, or just prevent them getting into the circos plots? We find that for FFPE samples, PURPLE often infers too many events, e.g. for 400 manta good quality variants, there are 1000 inferred variants, which clutter the visualization. So we might wanna skip them or figure how to filter them additionally. One option is to run circos separately from PURPLE, but wanted to check with your first before going this route.

Vlad

**Comment by vladsaveliev** [comment]
Sorry, I'm probably reading the circos plot wrong - it looks like it has 400 variants, so no inferred events included. Can you confirm please that the inferred events don't get into circos plots?

**Comment by p-priestley** [comment]
The standard purple CIRCOS ouptut does not show inferred breakends, but will show copy number breaks.  We have not worked with FFPE, but there are some parameters which could improve the copy number smoothing.    If you are happy to share the segment.tsv file + the purple plots (please send to my hartwig address) I can offer some more specific advice.

**Comment by vladsaveliev** [comment]
Thanks Peter, I appreciate it so much. I emailed you the files.

**Comment by p-priestley** [comment]
The visualisation issue is not related to inferred variants.   Closing
