### ISSUE TITLE
mutect2 PURPLE Compatiblity

### ISSUE THREAD

**Issue by zhaowsong** [hartwigmedical/hmftools#521]
Hi authors,

I would like to inquire whether Purple is compatible with the results from Mutect2. Additionally, have you compared the differences between the results of Mutect2 and Sage?

Furthermore, I would also like to know if the HMF pipeline has a minimum requirement for sequencing depth, such as 30X?

**Comment by charlesshale** [comment]
Purple is not compatible with other variant callers and we recommend using Sage and Pave. We have primarily compared Sage with Strelka.

There is no minimum sequencing depth, but each tool has defaults which are based around 100x tumor / 30x normal. These can be adjusted with config parameters to work with other depths.
