### ISSUE TITLE
Latest version of PURPLE is not working with MultiQC

### ISSUE THREAD

**Issue by insilicool** [hartwigmedical/hmftools#524]
Please see the following MultiQC issue (https://github.com/MultiQC/MultiQC/issues/2363)

Essentially in version 4.0.1 of PURPLE the version information is not available for parsing in the purity file.  Is this a bug?

**Comment by charlesshale** [comment]
The version column has been removed from the Purple purity file. When Purple runs, it writes a purple.version file, as do all HMF tools.
