### ISSUE TITLE
mappability.hdr not found + stitching resource files

### ISSUE THREAD

**Issue by mich-chan** [hartwigmedical/hmftools#530]
Hello, I am trying to perform a test run on a pair of t-n samples with genome build 37, and found that mappability.hdr is not in the resources (I've tried looking through various versions from hmf-public, v5_28, 34, 33 for example)... Also secondly, do you foresee an issue with the fact that I've changed the paths for the INI file (hmf_noah_GRCh37.ini) using resources from various versions (because I couldn't find a version that had all of the necessary files)?

**Comment by charlesshale** [comment]
The mappability.hdr file is no longer use by our pipeline.

I would strongly recommend only use resources files that match a pipeline release. Our latest release is v5.34, and the details for this are now shown on the main HMF page - ie which tool versions are included, where to find the resource files.

We recommend running our pipeline using the NextFlow implementation, called OncoAnalyser.
