### ISSUE TITLE
i cannot find GermlineHetPon.37.vcf.gz in v5_34 resources

### ISSUE THREAD

**Issue by nan5895** [hartwigmedical/hmftools#532]
Hello, 

Thank you for the wonderful genomic analysis pipeline 

I found out that HMFTOOLS-Resources there are new version of resources. 

we were currently used v5_31, and now it seems v5_34 is available

What are there difference between two resources..?

`GermlineHetPon.37.vcf.gz` is missing in `v5_34/37/ref/copy_number/ `
i found `AmberGermlineSites.37.tsv.gz` instead ...
is that what we use for amber -loci argument input (which was previously `GermlineHetPon.37.vcf.gz`)?

Thank you 

Steve,

**Comment by charlesshale** [comment]
Yes that's correct - use AmberGermlineSites instead.

The other differences between the resource files are fairly minor, mostly updates to the driver gene panel.
