### ISSUE TITLE
Adjusted Allele Frequency is Sometimes Exactly Zero

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#54]
`PURPLE_AF` can be 0.0000 for a PASS variant in rare cases. For example,

```
chr13   58998732        .       C       G       .       PASS    AC=0;AF=0.00;AN=0;DP=142;MQ=51.85;MQ0=12;NT=ref;PURPLE_AF=0.0000;PURPLE_CN=4.10;PURPLE_GERMLINE=DIPLOID;PURPLE_MAP=0.027;PURPLE_PLOIDY=0.00;QSS=51;QSS_NT=51;ReadPosRankSum=-0.04;SGT=CC->CG;SNVSB=0;SOMATIC;SUBCL=1.00;SomaticEVS=9.01;TNC=GCT;TQSS=2;TQSS_NT=2;set=snvs  AD:AU:CU:DP:FDP:GU:SDP:SUBDP:TU 19,0:0,0:19,26:19:0:0,2:1:0:0,0 46,0:1,1:46,62:58:0:0,28:17:0:11,22
```

`GU` for reference sample is `0,2` and for disease sample is `0,28.` I would expect the allele frequency to be non-zero.

![image](https://user-images.githubusercontent.com/631218/66109151-6549b680-e607-11e9-9915-0fb5d2dabe2a.png)

Does PURPLE use Strelka's Tier 2 reads?

**Comment by p-priestley** [comment]
I believe we only use tier 1.    Are you using our script to add the AD field?   We could modify this to use tier 2 if it helps

**Comment by DarioS** [comment]
Yes, I'm using the script to add the AD field. It seems that Strelka uses [Tier 1 and Tier 2 to calculate PASS or not](https://github.com/Illumina/strelka/issues/87), although the explanation is not clear.

Another concern I have is adjusted allele frequencies such as 12.4487 and 24.6373. According to the [classical definition](https://en.wikipedia.org/wiki/Allele_frequency), the allele frequency could only be between 0 and 1.

**Comment by p-priestley** [comment]
From my notes tier1 = mapQ > 40 and tier2 = mapQ > 5.     By using tier1 we may indeed get AD=0 for regions with low mappability.  Let me know if you prefer to use tier 2 and I will look into it.

For the 2nd question, obviously VAF should be between 0.2 and 1.   However if you have a diploid tumor of purity 0.2 but you see an unadjusted VAF of 50%, then that is genuinely implying a purity adjusted VAF of greater than 1.   We could cap at 1 of course, but we prefer not to hide potential issues like this from downstream applications as they may indicate an issue.   One possibility which could lead to such a high adjusted VAF would be a germline variant  which has been called as somatic.   Another would be if a false positive variant is called in a very low copy number region (ie CN<<1).   It could also indicate a poor fit for the copy number in that region.

**Comment by DarioS** [comment]
I changed my mind. In a later part of that lengthy issue, Sangtae Kim writes

> We recommend to use only tier1 read counts to avoid unnecessary complications.

Also, I suppose it's important to see where the allele frequencies aren't realistic, rather than applying a ceiling.
