### ISSUE TITLE
SvPrep Depth Annotator missing VCF when no SVs detected

### ISSUE THREAD

**Issue by scwatts** [hartwigmedical/hmftools#540]
An oncoanalyser user has reported a pipeline failure where SvPrep Depth Annotator did not produce an output file. The provided logs show that upstream GRIDSS did not call any call SVs. The relevant issue:

- https://github.com/nf-core/oncoanalyser/issues/13 

I've confirmed with simulated data that SvPrep Depth Annotator does not produce an output file when given an empty input VCF. I expect this would also cause a failure in **[pipeline/scripts/run_pipeline](https://github.com/hartwigmedical/hmftools/blob/sv-prep-v1.2.3/pipeline/scripts/run_pipeline)**.

Can SvPrep Depth Annotator be adjusted to always create an output file for downstream processing even if it might be empty? Thanks!

/cc @PFRoux

**Comment by charlesshale** [comment]
Yes I will factor that in our next pipeline release.

From: Stephen Watts ***@***.***>
Date: Friday, 5 April 2024 at 9:32 am
To: hartwigmedical/hmftools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hartwigmedical/hmftools] SvPrep Depth Annotator missing VCF when no SVs detected (Issue #540)

An oncoanalyser user has reported a pipeline failure where SvPrep Depth Annotator did not produce an output file. The provided logs show that upstream GRIDSS did not call any call SVs. The relevant issue:

  *   nf-core/oncoanalyser#13<https://github.com/nf-core/oncoanalyser/issues/13>

I've confirmed with simulated data that SvPrep Depth Annotator does not produce an output file when given an empty input VCF. I expect this would also cause a failure in pipeline/scripts/run_pipeline<https://github.com/hartwigmedical/hmftools/blob/sv-prep-v1.2.3/pipeline/scripts/run_pipeline>.

Can SvPrep Depth Annotator be adjusted to always create an output file for downstream processing even if it might be empty? Thanks!

/cc @PFRoux<https://github.com/PFRoux>

**Comment by charlesshale** [comment]
Will be fixed in Esvee v1.0, due out in our next pipeline release (v6.0)
