### ISSUE TITLE
NullPointerException for SageApplication

### ISSUE THREAD

**Issue by Tina04021997** [hartwigmedical/hmftools#547]
Hi, 
Thank you all for the effort in developing and maintaining SAGE.
I happened to encounter an issue while using SageApplication and would love to know how I could modify it.

Error message:
Exception in thread "main" java.lang.NullPointerException
        at com.hartwig.hmftools.common.hla.HlaCommon.populateGeneData(HlaCommon.java:29)
        at com.hartwig.hmftools.sage.ReferenceData.<init>(ReferenceData.java:63)
        at com.hartwig.hmftools.sage.SageApplication.<init>(SageApplication.java:50)
        at com.hartwig.hmftools.sage.SageApplication.main(SageApplication.java:146)

Command used:
java -Xms4G -Xmx32G -cp $PATH/software/sage_v3.3.jar com.hartwig.hmftools.sage.SageApplication \
    -threads 8 \
    -reference PCGA-1080-BE-03_normal \
    -reference_bam$PATH/PCGA-1080-BE-03_normal_mkdp.bam \
    -tumor PCGA-1080-BE-03_tumor \
    -tumor_bam $PATH/PCGA-1080-BE-03_tumor_mkdp.bam \
    -ref_genome_version 38 \
    -ref_genome $PATH/GRCh38.d1.vd1/GRCh38.d1.vd1.fa \
    -hotspots $PATH/variants/KnownHotspots.somatic.38.vcf.gz \
    -panel_bed $PATH/variants/ActionableCodingPanel.38.bed.gz \
    -high_confidence_bed $PATH/variants/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed.gz \
    -ensembl_data_dir $PATH/Databases/VEP \
    -out $PATH/WGS_deep/SAGE/WGS60.sage.vcf.gz

Thank you so much for the help.

Best,
Tina

**Comment by charlesshale** [comment]
Did you feed in our v38 Ensemble data cache (ie the directory with the 5 Ensemble CSV files)? They are included in our pipeline resource files.

**Comment by Tina04021997** [comment]
Thank you so much. This solved the problem.
