### ISSUE TITLE
Isofox and Very Polymorphic Human Genes

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#549]
Like [T1K](https://genome.cshlp.org/content/33/6/923.long), can Isofox accurately infer HLA and KIR mRNA abundances given that hg38 poorly represents most people for such genes?

**Comment by p-priestley** [comment]
Hi Dario, 

We have developed LILAC for HLA typing (https://github.com/hartwigmedical/hmftools/tree/master/lilac and https://pubmed.ncbi.nlm.nih.gov/37165135/). This can be run on both RNA and DNA.

With respect to ISOFOX, we internally tested against both Salmon and RSEM during development on ~100 samples.   For HLA class 1 genes we found highly concordant abundance estimates with RSEM, but Salmon often differed quite markedly from both RSEM and ISOFOX.  

Peter

**Comment by DarioS** [comment]
Can Isofox somehow take as input LILAC-inferred HLA alleles and quantify those instead of gene-level quantification?

**Comment by p-priestley** [comment]
I think it will be similar.  Do you have an example where it goes wrong?

**Comment by DarioS** [comment]
No just wondering conceptually if instead of

```
        Sample A Samples B
HLA-A       10      0
HLA-B       20      30
```

something like

```
              Sample A   Sample B
HLA-A A*01:02     5         0
HLA-A A*02:01     5         0
HLA-B B*01:01     20        15 
HLA-B B*02:01     0         15
```

is possible for quantification. I am wondering about allele-specific expression (A.S.E.) of polymorphic genes.

**Comment by p-priestley** [comment]
This is very similar to what LILAC outputs.   Here is the picture from our paper: (https://www.nature.com/articles/s41588-023-01367-1/figures/1)

<img width="1091" alt="image" src="https://github.com/hartwigmedical/hmftools/assets/18154939/9c7e1dec-e753-4ce8-b685-a067ff5d4992">

**Comment by DarioS** [comment]
Indeed, it does.

> **RNA ‘expression’ of alleles**
> LILAC also optionally accepts a RNA bam. As per the fragments in the bam are counted for each allele in the determined type. This can be interpreted as a proxy for allele specific expression.
