### ISSUE TITLE
Replication Timing in the .linx.svs files

### ISSUE THREAD

**Issue by tillyRigby555** [hartwigmedical/hmftools#550]
Hello,

I see that in the replicationTimingStart and replicationTimingEnd columns in the .linx.svs files, the replication timing is all between 0 and 1. I was hoping for some additional insight into how the Replication Timing was calculated and if it was normalized. What does a replication timing value of 0 mean?

Thanks!

**Comment by p-priestley** [comment]
We have not looked at those annotations for a long while, but the replication timing is a relative scale with 0 being the latest and 1 being the earliest.   The numbers were originally sourced from the Encode Repliseq data.   I don't have too many more details sorry.
