### ISSUE TITLE
raw copy numbers

### ISSUE THREAD

**Issue by Pranav-Garg** [hartwigmedical/hmftools#555]
For some of my samples, purity estimation fails. In such cases, the copy number track from purple has a lot of noise, likely because it is being scaled up by (1/purity). I want to be able to use the copy number prior to such scaling so I looked at `purple.segment.tsv`. Could you please document which column(s) carry this information (see also #321)?

Another case where I found myself needing to examine the raw copy number was where the input.png file had a clear jump in copy number but it was lost in the smoothing step. In this case purity is not an issue but I want to diagnose why a real (verified via microscopy) deletion variant was initially detected but then excluded.
![del5q input crop png](https://github.com/hartwigmedical/hmftools/assets/5372292/f344d8e4-32fe-437d-b793-7398361f13ee)
![del5q circos crop png](https://github.com/hartwigmedical/hmftools/assets/5372292/18d73a48-e437-474e-a7bd-f493ab91b57e)

**Comment by p-priestley** [comment]
The segment file represents the consolidation by PURPLE of amber, cobalt and structural variant input.   The blue and green dots on the input.png file correspond to the observedTumorRatio and observedNormalRatio for this file.   only regions with germlineStatus = 'diploid' are shown in the input.png file and only these regions contribute to the somatic fit.   

In your 2nd case, the smoothing indeed looks too aggressive.   Not sure if you provide structural variants to the fit, but if you do these should prevent smoothing through bona fide breakpoints.

**Comment by Pranav-Garg** [comment]
Hmm regarding the second sample, I have indeed been supplying SVs. I found that the corresponding deletion SV was PASS in gridss but filtered by minQual after gripss, and wasn't rescued by purple despite the copy number jump. I don't feel equipped to figure out why it was lost, and I'll give up on trying to fix that sample.

Regarding `purple.segment.tsv`, if I understand correctly I can get pre-scaling and pre-smoothing copy numbers by looking at observedTumorRatio subject to germlineStatus = diploid. Or do I need to divide by observedNormalRatio? i.e is copyNumber in `purple.cnv.somatic.tsv` derived from the observedTumorRatio or is it derived from the division observedTumorRatio / observedNormalRatio?

**Comment by p-priestley** [comment]
In the second sample, it must be below detection threshold in that case then

In the segment.tsv the blue series in the input.png is the observedTumorRatio and the green series is the observedNormalRatio.   The copy number in purple is based on the observedTumorRatio, but the normal ratio affects smoothing.   I would suggest to use the observedTumorRatio as the raw copy number

**Comment by Pranav-Garg** [comment]
Thank you, I will do this.
I'd also like to consider using the copy number which is smoothed but was not corrected for purity. Is there a formula I can apply to undo the purity scaling?

**Comment by HenriettaHolze** [comment]
Hi, I work with experimental data (PDX data) and would also like to skip purity correction for any tool. Is that possible?

**Comment by p-priestley** [comment]
You will need to subtract the mouse reads prior to putting it through the pipeline.

If you don't want to do a purity adjustment, you can force purtiy to a fixed value (eg 100% and ploidy 2) by setting min_purity, max_purity, min_ploidy and max_ploidy. Please see here: https://github.com/hartwigmedical/hmftools/tree/master/purple#optional-fitting-arguments
