### ISSUE TITLE
CNV results from purple

### ISSUE THREAD

**Issue by zhaowsong** [hartwigmedical/hmftools#557]
Hi author,

I obtained some results analyzed using the hmf pipeline from other sources, mainly the SNV/indel results annotated by pave and the CNV results from purple. 

Since I only received the .purple.cnv.gene.tsv files, I would like to know if it is possible to estimate TP53 deletion status from the copy number provided by purple. I see that in other places, you mentioned that the definition of homozygous deletion is CN < 0.5, where CN refers to the minCopyNumber, right? For LOH, the definition is minorAlleleCopyNumber < 0.5. Does this definition only consider the minorAlleleCopyNumber?

https://github.com/hartwigmedical/hmftools/issues/88

Here are the TP53 copy number results for each sample that I merged. Can the ones circled in red be considered as LOH?
<img width="1073" alt="image" src="https://github.com/hartwigmedical/hmftools/assets/116059475/4cf6def4-d25b-42a3-82b1-40b74bffbe52">

Additionally, I ran my own WGS data using this pipeline, and for the following sample, minCopyNumber =0.0634，the result given by driver.catalog.somatic.tsv is TP53 del.
<img width="905" alt="image" src="https://github.com/hartwigmedical/hmftools/assets/116059475/65090208-5e80-40c6-89f2-24613f74ad77">

**Comment by p-priestley** [comment]
For quesiton 1, the answer is yes we always use minor allele copy number < 0.5 as the rule for identifying LOH.  The example you have got highlighted looks unsual though as the max copy number is very high which is strange for TP53 and seems to indicate some complex rearrangement.   You can visualise the structural variation using LINX.

For the 2nd point, I am not sure what the question is but perhaps you are wondering about why the copy number is not an integer?   This is because we don't round any of our calculations in PURPLE.    In this case the copy number is very likely = 0 so it is a homozgous deletion.

**Comment by zhaowsong** [comment]
Thank you for your explanation. These samples are from osteosarcoma, where TP53 often occurs rearrangement. In the first sample, a rearrangement has indeed occurred.

Regarding the definition of LOH, I would like to further inquire.

For the second sample, the TP53 minCopyNumber is 0.0634, and the minorAlleleCopyNumber is 0, indicating a TP53 deletion.

So, does the definition of LOH require simultaneously satisfying the conditions: minCopyNumber > 0.5 and minorAlleleCopyNumber < 0.5?

**Comment by p-priestley** [comment]
First we check if AlleleCN < 0.5 and then mark that as a homozgous deletion.    If not, we check if minorAlleleCN < 0.5 and mark that as LOH.  So I would say yes to your question.  I hope that is clear

A homozygous deletion arises first from an LOH, and then a second delete event on the other parental chromosome

**Comment by p-priestley** [comment]
LOH events are not added to the driver catalog, sorry

The LINX SV list may be smaller as it does not annotate "inferred" breakpoints created by PURPLE.   I guess this is likely the main difference in your numbers. There is also some additional filtering:   https://github.com/hartwigmedical/hmftools/tree/master/linx#artefact-filtering

**Comment by zhaowsong** [comment]
Thanks !
