### ISSUE TITLE
Kataegis Regions Tabular Output

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#56]
It would be convenient if kataegis regions were output into a tab-separated text file / BED file, like many other results already are. It's not easy to compare and contrast how many regions there are and their widths between groups of patients based on the plots alone.

**Comment by jonbaber** [comment]
Hi Dario,

The plot is generated from kataegis data in the VCF. Please check and let me know if the information available is sufficient for you needs. 

Regards, Jon

**Comment by DarioS** [comment]
That is sufficient to define the region boundaries with.
