### ISSUE TITLE
Length neoepitopes

### ISSUE THREAD

**Issue by p-levy** [hartwigmedical/hmftools#568]
Hi Charles and Peter, 

Is it possible to specify the length of the epitopes in the output from Neo? By default it is 31 for missense variants (15 aa upstream + 1 novel + 15 aa downstream). I'd like to get 40-mers for a specific project (19 upstream + 1 novel + 20 downstream). 

Thanks!
Pierre

**Comment by charlesshale** [comment]
Hi Pierre,

set this config option:
-req_amino_acids 20

when running the NeoEpitopeFinder.

**Comment by p-levy** [comment]
Awesome, thanks!
