### ISSUE TITLE
Separating out the read-back phasing functionality for MNVs

### ISSUE THREAD

**Issue by tinyheero** [hartwigmedical/hmftools#57]
I am quite interested in the [strelka-post-process](https://github.com/hartwigmedical/hmftools/tree/master/strelka-post-process) method for predicting MNVs that is used in https://www.biorxiv.org/content/10.1101/415133v4. If I understand it correctly, it is doing read-backed phasing of proximal SNVs and then grouping them into a single MNV. 

Currently, the method uses output from Strelka. However, I am interested in using SNV calls from another variant caller. It would seem that the key functionality is read-backed phasing. Is there any a way to separate out that functionality into a separate tool/script? This way it could more readily use variant calls from another caller. 

Kind regards

**Comment by p-priestley** [comment]
Thanks for your interest. 

The strelka-post-process is a legacy internal tool for us and not something we support externally.   We are instead working on building out our own full genome somatic point mutation caller (https://github.com/hartwigmedical/hmftools/tree/master/sage) which will handle MNVs natively, and which will be released in the coming weeks.

The tool does not have a specific strelka dependency, but does use some of the vcf fields that are populated by Srelka.   You are welcome to try to adapt either the tool or the vcf if you like.
