### ISSUE TITLE
Advice needed in regards to the `gridss_blacklist` within `hmf_dna_pipeline_resources.38_v5.34.tar.gz`

### ISSUE THREAD

**Issue by Teezi** [hartwigmedical/hmftools#573]
Hi,

As `gridss` recommended that I use ENCFF356LFX.bed file for hg38 (UCSC chr notation) as the blacklist (exclude_list).

Upon opening the hmf_dna_pipeline_resources.38_v5.34.tar.gz (which was downloaded from HMFTools-Resources in the Hartwig Medical Foundation's GCP bucket) I noticed another 2 blacklists: gridss_blacklist.38.bed.gz and sv_prep_blacklist.38.bed. Should I be using one of these lists instead of the `ENCFF356LFX.bed` and if so, which of the 2 files should I be using?

**Comment by charlesshale** [comment]
For Gridss use the grid's_blacklist BED file.
If you're running SvPrep first (as we recommend), use the sv_prep_blacklist BED for that too.

**Comment by Teezi** [comment]
Thanks for your response. 

Just to confirm, should I use `ENCFF356LFX.bed` or `gridss_blacklist.38.bed.gz` for `gridss`?

**Comment by charlesshale** [comment]
I recall they are the same file, but if not use the gridss_blacklist one

**Comment by Teezi** [comment]
> I recall they are the same file, but if not use the gridss_blacklist one

Thanks! I will use the `gridss_blacklist`

They are very different.

```
$ cat ENCFF356LFX.bed | head -n10
chr1	628903	635104
chr1	5850087	5850571
chr1	8909610	8910014
chr1	9574580	9574997
chr1	32043823	32044203
chr1	33818964	33819344
chr1	38674335	38674715
chr1	50017081	50017546
chr1	52996949	52997329
chr1	55372488	55372869
```

```
zcat gridss_blacklist.38.bed.gz | head -n10
chr1	629069	634991	High_Mappability_island	1000	.
chr1	788756	791663	Satellite_repeat	1000	.
chr1	889626	889735	BSR/Beta	1000	.
chr1	2651895	2702781	Low_mappability_island	1000	.
chr1	4303004	4303182	(CATTC)n	1000	.
chr1	5665806	5676591	Low_mappability_island	1000	.
chr1	16513428	16514901	Low_mappability_island	1000	.
chr1	37611746	37611748	Low_mappability_island	1000	.
chr1	37611748	37611751	Low_mappability_island	1000	.
chr1	91387228	91387590	LSU-rRNA_Hsa	1000	.
```

**Comment by Teezi** [comment]
> If you're running SvPrep first (as we recommend), use the sv_prep_blacklist BED for that too.

Thanks so much for bring that!!  I'm still learning the ropes with `gridss` and `gripss`,  I have a naive question, is there anything going wrong if `SvPrep` doesn't run?
