### ISSUE TITLE
Unable to run COBALT in tumor only mode 

### ISSUE THREAD

**Issue by Chunkz616** [hartwigmedical/hmftools#581]
Thanks great tool ! Just in tumor only mode I am having issues with it recognising the commands

# Set variables
TUMOR="PD59703a"
TUMOR_BAM="/lustre/scratch126/casm/team274sb/ah39/DNA_data/sim_links/scLeuk_3.7.24/PD57224a.sample.dupmarked.bam"
OUTPUT_DIR="/lustre/scratch126/casm/team274sb/ah39/DNA_data/purple/cobalt_output/${TUMOR}"
GC_PROFILE="/lustre/scratch126/casm/team274sb/ah39/DNA_data/sim_links/scLeuk_3.7.24/GC_profile.1000bp.38.cnp"
DIPLOID_BED="/lustre/scratch126/casm/team274sb/ah39/DNA_data/sim_links/scLeuk_3.7.24/DiploidRegions.38.bed.gz"
THREADS=2
COBALT_JAR="/lustre/scratch125/casm/team274sb/ah39/code_packages/cobalt-1.9.jar"

# Run COBALT in tumor-only mode
java -Xmx28G -jar $COBALT_JAR \
  -tumor $TUMOR \
  -tumor_bam $TUMOR_BAM \
  -output_dir $OUTPUT_DIR \
  -threads $THREADS \
  -gc_profile $GC_PROFILE \
  -tumor_only_diploid_bed $DIPLOID_BED
  
  is giving me 
  
  15:49:03 - org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -tumor_only_diploid_bed
usage: CountBamLinesApplication
 -gc_profile <arg>              Location of GC Profile
 -input_dir <arg>               Input directory (used for migration only)
 -min_quality <arg>             Min quality [10]
 -output_dir <arg>              Output directory
 -ref_genome <arg>              Path to reference genome fasta file if
                                using CRAM files
 -reference <arg>               Name of reference sample
 -reference_bam <arg>           Path to reference bam file
 -threads <arg>                 Number of threads [4]
 -tumor <arg>                   Name of tumor sample
 -tumor_bam <arg>               Path to tumor bam file
 -validation_stringency <arg>   SAM validation strategy: STRICT, SILENT,
                                LENIENT [STRICT]
(base) ah39@farm22-head1:~/Bash_scripts$ 

Tried a few different work arounds but seems like it is not expecting   -tumor_only_diploid_bed $DIPLOID_BED input. Is there anything I am missing

**Comment by Chunkz616** [comment]
Apologies, was running in older version - pre-tumor only mode. my bad

**Comment by edceeyuchen** [comment]
Hello! 
 I cant download DiploidRegions.38.bed.gz, could you help me to know how to download? 
Thank you!
