### ISSUE TITLE
Somatic CNV calling in case of pre-existing CNVs

### ISSUE THREAD

**Issue by HenriettaHolze** [hartwigmedical/hmftools#585]
Hi, could you explain how the pipeline handles somatic CNV calling in case of "germline" CNVs?  
We sequenced a cancer cell line before and after engraftment into mice. CNVkit suggests that a locus already has 5 copies at baseline. We are interested in additional CNVs that happened during engraftment, i.e. further amplification or loss.  
The results of CNVkit and purple are quite different: CNVkit estimates a somatic CN change of 1.38 but the CN estimated by purple is 2.03.  
Is this too far from the intended purpose of the tools?  
Thanks!

**Comment by p-priestley** [comment]
So do I understand correctly, that you are using the tumor cell line as the reference here and the PDX as the tumor?  This will not work well for PURPLE as there is a strong assumption that the reference will be diploid.  Upstream, AMBER will also likely give give poor results.

If that is your use case I would recommend running both samples through PURPLE in tumor only mode and then comparing the output to analyse differences.

**Comment by HenriettaHolze** [comment]
Thanks a lot, this is very helpful. Yes, cell line as reference and PDX (mouse reads removed) as tumor. Apart from CNV calling, do you think this approach is problematic for "somatic" SNV or SV calling?

**Comment by p-priestley** [comment]
For SNV/SV it should be fine with our software I think.

**Comment by HenriettaHolze** [comment]
Thanks again. Could you clarify if the VAF of SNVs or SVs is adjusted for purity at any step? Thanks.
