### ISSUE TITLE
Representing unmatched PURPLE copy number

### ISSUE THREAD

**Issue by Chunkz616** [hartwigmedical/hmftools#587]
### PURPLE unmatched copy number 

HI brilliant tool thank you. Apologies if this is a bit of a basic question, I am new to this area. I have run purple umatched and am happy with the COBALT and AMBER outputs for my tumour samples 

I am using the latest version with these inputs:
    # Run PURPLE for current patient ID
    java -jar $PURPLE_JAR \
      -tumor $TUMOR \
      -amber $AMBER_DIR \
      -cobalt $COBALT_DIR \
      -gc_profile $GC_PROFILE \
      -ref_genome_version $REF_GENOME_VERSION \
      -ref_genome $REF_GENOME \
      -ensembl_data_dir $ENSEMBL_DATA_DIR \
      -output_dir $OUTPUT_DIR \
      -circos $CIRCOS_BIN

You can see attached a visualiation of the outputs. For the final copy number outputs I can see overall it is correct but I am struggling to deal with the variation and noise. E..g segements with a baf count of 0. Is there something I could modify to improve this, or is there an accepted way of improving this? 

Additionally I know the copy number call to be wrong for some genes - e.g. PAX5 being homozygously deleted, but it is called as diploid. Is this a known issue? I did not provide the GRIDDS unmatched output in the above example but that didn't help either. 

![PD59703a_customplots (3)](https://github.com/user-attachments/assets/26f0c5f5-305d-49a5-9f1b-547bda522269)

**Comment by p-priestley** [comment]
Could you tell me what version of PURPLE, AMBER and COBALT you ran please?   Also, is your final plot just charting the purple.cnv.somatic.tsv?  It would be helpful if you could also attach the input.png and circos.png outputs for PURPLE if you don't mind so I can see the segmentation.

**Comment by Chunkz616** [comment]
Thank you for the quick response, apologies for not providing - I am using 
purple_v3.8.4.jar
cobalt-1.14.1.jar - with these inputs below 
    java -Xmx28G -jar $COBALT_JAR \
        -tumor $TUMOR \
        -tumor_bam $TUMOR_BAM \
        -output_dir $OUTPUT_DIR \
        -threads $THREADS \
        -gc_profile $GC_PROFILE \
        -tumor_only_diploid_bed $DIPLOID_BED
  amber-3.9.jar
  java -Xmx32G -cp $AMBER_JAR com.hartwig.hmftools.amber.AmberApplication \
      -tumor $TUMOR \
      -tumor_bam $TUMOR_BAM \
      -output_dir $OUTPUT_DIR \
      -threads $THREADS \
      -loci $LOCI \
      -ref_genome_version $REF_GENOME_VERSION

Final plot is the purple.cnv.gene.tsv I have attached both circos, but also put in the .cnv.somatic.tsv plot 
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/23e0fce2-08a9-4bd0-ae6d-33500a5856ad">

![PD59703a input_noGRIDDS (1)](https://github.com/user-attachments/assets/36d01714-1b98-4f1c-9bb6-222722884ecc)


      
    
![PD59703a circos_noGRIDDS (2)](https://github.com/user-attachments/assets/a11a149b-8612-498b-a5d4-9f2fdbdf5949)

**Comment by p-priestley** [comment]
I am not sure I can fully solve your problems here, but some hints which may be helpful:

- The fit itself appears to look correct to me based on the copy number pattern

- The main issue in the final CIRCOS appears to be that many localised LOH have been called (inner orange ring of CIRCOS).  I think this stems from the amber points being noisy than we typically see in our samples.  I am not really sure why this is might be.  Are you using FFPE or relatively low depth?   

- I don't know of any specific reason why a PAX5 homozgous deletion would be missed.  There is no LOH at all called around this region, so it would be strange to miss 2 events.      However, in tumor only mode we do exclude regions with common germline regions and also frequently noisy regions in the DIPLOID_BED file.  I noticed that there are some regions overlapping sections of PAX5.  If you are sure there is a deletion there and know the co-ordinates then you could check if that is overlapped specifically in the bed file.

**Comment by Chunkz616** [comment]
Many thanks again for your response - it was 65X and from a BM sample 

Thank you yes I agree it seems to really stem from regions of noise from AMBER
- do you think any of the optional arguments may help alleviate this?
e.g. setting 
amber --tumor_only_min_vaf 0.1 --tumor_only_min_support 5
Or do you think this won't really be the issue?

**Comment by p-priestley** [comment]
This is hard for me to advise on without seeing the data.   Perhaps you could look at the depth profile of some of the noisy points in the BAF output.  If they are typically low depth BAF points then adjusting those settings may help
