### ISSUE TITLE
help to run GRIDSS as a PURPLE input

### ISSUE THREAD

**Issue by a00101** [hartwigmedical/hmftools#59]
Dear developers.

GRIDSS manual says 'not supported somatic'.
Can you tell me command line of GRIDSS or step-by-step for using PURPLE as input?

Thanks in advance.

**Comment by p-priestley** [comment]
Sorry for the delayed reply

We have extensive documentation at this location: 

https://github.com/hartwigmedical/gridss-purple-linx
