### ISSUE TITLE
Different Calculation of PURPLE_AF

### ISSUE THREAD

**Issue by Se-Jung-LEE** [hartwigmedical/hmftools#592]
Hello, Thank you for developing such a great tool.

I tried to confirm the PURPLE_AF of my analyzed data based on the response provided in issue #394. 
However, my calculated result is different, so I wanted to ask if there is any part I might be missing.

For my data:
purity = 0.19 (from PURPLE purity.tsv)
VAF = 0.622 (from a specific variant's AF in PURPLE.germline.vcf.gz)
CN = 1.29 (from PURPLE_CN, calculated based on the information provided in issue #394)

Using these values, I calculated PURPLE_AF to be 4.73, but the PURPLE_AF recorded in the vcf file is 1.4276. Could you please let me know if there is anything I am missing?

I have attached the relevant data for your reference. 
Thank you.

<INFO>
BIALLELIC;CLNSIG=Pathogenic;GND_FREQ=0.065;IMPACT=ZFHX3,ENST00000268489,inframe_deletion,MISSENSE,false,c.10554_10556delCGG,p.Gly3519del,,MISSENSE,1;MAPPABILITY=1.00;MED=72;MH=CCG;PATH=PATHOGENIC;PAVE_TI=ENSG00000140836|ZFHX3|ENST00000268489|inframe_deletion|false|c.10554_10556delCGG|p.Gly3519del,ENSG00000140836|ZFHX3|ENST00000397992|inframe_deletion|false|c.7812_7814delCGG|p.Gly2605del,ENSG00000140836|ZFHX3|ENST00000641206|inframe_deletion|false|c.10554_10556delCGG|p.Gly3519del;PURPLE_AF=1.4276;PURPLE_CN=1.29;PURPLE_MACN=0.024;PURPLE_VCN=1.85;RC=CCACCGCCGCCGCCGCCACTG;RC_IDX=2;RC_LF=GCCGCCGCCG;RC_MH=CCG;RC_NM=1;RC_REPC=4;RC_REPS=CCG;RC_RF=CCACCGCCGC;REP_C=5;REP_S=CCG;TIER=PANEL;TNC=CAC

GT:ABQ:AD:AF:AMQ:ANM:DP:RABQ:RAD:RC_CNT:RC_IPC:RC_JIT:RC_QUAL:RDP:RSB:SB
Tumor
./.:35:16,28:0.622:60,60:0.800,1.30:45:973,960:27,28:21,7,0,0,0,16,45:0:1,14,7:498,103,0,0,0,378,1002:55:0.429,0.875:0.500,0.563
Blood
0/1:35:11,12:0.522:59,58:0.900,1.60:23:505,369:15,11:9,2,0,1,0,11,23:0:0,8,4:207,48,0,17,0,252,524:27:0.455,0.727:0.364,0.455

**Comment by p-priestley** [comment]
#394 was a question about calcualtion of adjusted AF for somatic variants.  Your query relates to a heterozygous germline  variant.  So you need to change the equation to assume 1 / 2 copies in the impure part of the tumor.

**Comment by Se-Jung-LEE** [comment]
Thank you for the quick response.

I missed the fact that it pertains to a germline variant. 
Although I understand the general idea of 'assuming 1/2 copies in the impure part of the tumor,' 
I am having difficulty understanding how exactly the formula should be adjusted. 

If you could kindly provide any reference materials or detailed explanations, 
I would greatly appreciate it and make every effort to understand them.

**Comment by p-priestley** [comment]
I think the formula linking observed VAF and adjusted VAF  for a germline heterozgous variant should be:

observed VAF = [PURPLE_AF* PURPLE_CN*Purity + 1*(1-Purity)] / [ PURPLE_CN*Purity + 2*(1-purity)]

The numerator in the equation here is the average number of copies containing the allele and the denominatior is the average depth.

**Comment by Se-Jung-LEE** [comment]
Thank you for explaining in detail.
Now I understand the calculation.
