### ISSUE TITLE
Feature Request: Joint CNV Calling

### ISSUE THREAD

**Issue by seedgeorge** [hartwigmedical/hmftools#593]
Hi there,
I see that [SAGE](https://github.com/hartwigmedical/hmftools/tree/master/sage) has support for joint-calling multiple tumour samples at the same time - any chance PURPLE will get the same treatment, to improve sensitivity and accuracy of segmentation? [Perhaps similar to... ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8317109/)

Kind regards,
George

**Comment by p-priestley** [comment]
Thanks for the suggestion.    we don't have any plans to develop this sorry.  My view on this is that every copy number change should be supported by a structural variant and in practice we find an SV to explain >95% of copy number regions in our cohort.   see: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02423-x/figures/3    

For this reason I feel that joint calling of CN segments is unlikely to yield much, and is not really worth the extra complexity.
