### ISSUE TITLE
Difference between IMPACT and PAVE_TI in PURPLE vcf file

### ISSUE THREAD

**Issue by HenriettaHolze** [hartwigmedical/hmftools#594]
Hi,  
Could you please explain what the difference between the IMPACT and the PAVE_TI column in the PURPLE somatic snv vcf file is ( `TUMOR.purple.somatic.vcf.gz`)?

I would like to plot an overview of number and effect of mutations. But I don't know how to handle mutations that have no gene in the IMPACT field but genes in the PAVE_TI field (example below). 

```
IMPACT=,,,NONE,false,,,,NONE,1;MAPPABILITY=1.00;MED=69;PAVE_TI=ENSG00000184677|ZBTB40|ENST00000650433|intron_variant|false|c.-70+14811C>G|;PURPLE_AF=0.2571;PURPLE_CN=2.15;PURPLE_GERMLINE=DIPLOID;PURPLE_MACN=1.000;PURPLE_VCN=0.553;RC=ATGTT;RC_IDX=2;RC_LF=GGAATTTGGT;RC_NM=1;RC_RF=ATTGCTACAG;REP_C=2;REP_S=T;SUBCL=0.887;TIER=HIGH_CONFIDENCE;TNC=TCT
```

Furthermore, can I annotate all mutations that do not have an IMPACT field as intergenic? 

I haven't found an answer in the [PAVE documentation](https://github.com/hartwigmedical/hmftools/tree/master/pave). 

Thanks!

**Comment by p-priestley** [comment]
IMPACT refers to the canonical transcript
