### ISSUE TITLE
ENSEMBL Login Failing via LINX

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#60]
I am using the same credentials as for the ENSEMBL website for LINX's paramters `-ensembl_user` and `-ensembl_pass` but I get an error

> 15:47:52 - [ERROR] - failed to connect to DB: java.sql.SQLException: Access denied for user 'dario.strbenac@sydney.edu.au'@'hh-bigip-ve3905.ebi.ac.uk' (using password: YES)
15:47:52 - [INFO ] - invalid Ensembl DAO

![image](https://user-images.githubusercontent.com/631218/68269306-6c079580-00ad-11ea-94b6-8aa86149bdf6.png)

Is there much of a delay between registration and being able to connect to the database perhaps? I also specified `-ensembl_user dario.strbenac@sydney.edu.au`

**Comment by charlesshale** [comment]
Hi Dario,

I've only connected using the anonymous user and a blank password, ie:

-ensembl_db "mysql://ensembldb.ensembl.org:3337/homo_sapiens_core_89_37" -ensembl_user "anonymous" -ensembl_pass ""

does that work for you?

thanks,

Charles

**Comment by DarioS** [comment]
That example works. Perhaps there should be a link in the user guide to [Public MySQL Server](https://asia.ensembl.org/info/data/mysql.html) for details about the connection. Also, the user guide mentions

> mysql://ensembldb.ensembl.org:3337/homo_sapiens_core_92_38

but this doesn't work, although the hg19 database does `09:55:48 - [ERROR] - failed to connect to DB: java.sql.SQLSyntaxErrorException: Unknown database 'homo_sapiens_core_92_38'`.

**Comment by DarioS** [comment]
Works using updated instructions published today.
