### ISSUE TITLE
Can't access common resources public for CUPPA pre-trained classifier

### ISSUE THREAD

**Issue by weewus** [hartwigmedical/hmftools#603]
Hi there,

I would like to use your CUPPA classifier. I'm unable to access your common-resources-public, however.
https://source.cloud.google.com/hmf-pipeline-development/common-resources-public/+/master:cuppa/

**Comment by luan-n-nguyen** [comment]
Sorry about this. I've changed the URL in the readme to link to here: https://console.cloud.google.com/storage/browser/hmf-public/HMFtools-Resources/cuppa

Please let me know if this still doesn't work!

Luan

**Comment by weewus** [comment]
Cheers Luan, it works and is all good now :)
