### ISSUE TITLE
Invalid reference data error

### ISSUE THREAD

**Issue by rmapbut** [hartwigmedical/hmftools#604]
Hi, 

I would be very grateful for your help with this. I am trying to run purple on a set of paired tumour/normal samples. I ran cobalt and amber without issue. However I get this error message when trying to run purple. I have tried using different versions of the reference fasta file (all version 37) but I still get this message. Is there a way of seeing in more detail what is causing the reference data to fail the isValid check?

13:31:09.914 [INFO ] Purple version: 3.8.4
13:31:10.524 [INFO ] output directory: /purple/output/example1234/
13:31:10.526 [INFO ] reference(example1234b) tumor(example1234a) 
13:31:29.235 [INFO ] using ref genome: V37
13:31:29.605 [ERROR] invalid reference data, exiting

The submission script is below:
java -jar B/purple/software/purple_v3.8.4.jar \
   -reference example1234b \
   -tumor example1234a \
   -amber /purple/output \
   -cobalt /purple/output \
   -gc_profile /purple/reference/GC_profile.1000bp.37.cnp \
   -ref_genome_version 37 \
   -ref_genome /Hsapiens/GRCh37/seq/GRCh37.fa \
   -ensembl_data_dir /purple/reference/homo_sapiens_merged/112_GRCh37/ \
   -somatic_vcf /vcf/example1234a-ensemble.vcf.gz \
   -threads 2 \
   -output_dir /purple/output/example1234/

**Comment by charlesshale** [comment]
I suspect that there is something unexpected in the Ensembl data you're running. I would recommend using the Ensembl data in our public resource files. Later versions of Purple (v4.0) should report more information about invalid reference data.
