### ISSUE TITLE
How to find the known_fusion_db_file files 

### ISSUE THREAD

**Issue by DanielNaro** [hartwigmedical/hmftools#606]
Hi,
Within the main file GenerateFusionFiles, there is a file referred to as known_fusion_db_file, which I do not find in the references (if not something in Orange's subdirectory, but which looks too short). The exact line using this is the following one:

https://github.com/hartwigmedical/hmftools/blob/f16936b9c57328353308e298c16faf82e74498b2/gene-utils/src/main/java/com/hartwig/hmftools/geneutils/fusion/GenerateFusionFiles.java#L50

Where can I find this input file, or is there a way to generate it?
Thank you

**Comment by charlesshale** [comment]
This is an internal Hartwig file used to generate the fusion files which are included in our public resources. 

Line and Isofox use the generated files:
- known_fusion_data.3x.csv
- known_fusions.3x.bedpe

so there should be no need to run this routine. If you need to modify the fusion files used by those tools it is fine to manually modidy them.
