### ISSUE TITLE
Building Cuppa

### ISSUE THREAD

**Issue by weewus** [hartwigmedical/hmftools#608]
Hi there,

I'm trying to build the feature extractor for cuppa from the source code provided from https://github.com/hartwigmedical/hmftools/releases/

I'm getting loads of errors that I think relate to dependencies on other packages e.g. 'org.jetbrains.annotations' or 'htsjdk.variant.variantcontext' or 'com.google.common.annotations'.

At the moment I'm just running the following: 
javac hmftools-teal-v1.3.1/cuppa/src/main/java/com/hartwig/hmftools/cup/prep/CuppaDataPrep.java
or
javac hmftools-teal-v1.3.1/cuppa/src/main/java/com/hartwig/hmftools/cup/\*/\*.java

I appreciate this might be naive, I'm not much of a java officianado.
I'd greatly appreciate any guidance.

Thanks,
Andreas

**Comment by luan-n-nguyen** [comment]
Hi Andreas, i think you'll need to build the entire project with Maven:
```
cd /path/to/hmftools/
mvn clean install -pl 'cuppa,hmf-common'
```

If that doesn't work, build the entire project:
```
mvn clean install
```

**Comment by weewus** [comment]
Great, thank you Luan!
