### ISSUE TITLE
SAGE configuration for whole-exome data

### ISSUE THREAD

**Issue by ypradat** [hartwigmedical/hmftools#616]
Dear HMF team,

Thank you for the awesome work. I am keen on running SAGE on WES data (depth 100-150X) but cannot figure out from the documentation what would be optimal filtering parameters.

The README of sage https://github.com/hartwigmedical/hmftools/tree/master/sage#readme redirects to this readme https://github.com/hartwigmedical/hmftools/blob/master/pipeline/README_TARGETED.md for higher depth targeted data.
In this README, I can see the recommended options

```
-high_depth_mode
-map_qual_ratio_factor 2.5
-fixed_qual_penalty -15
-hard_min_tumor_vaf 0.002
```

but `high_depth_mode` and `map_qual_ratio_factor` options do not seem to exist anymore in SAGE latest version (3.3) and the value of `hard_min_tumor_vaf` is identical to the one recommended for WGS data. 

Can you please advise on appropriate configurations for my WES data at 150X in tumor and 100X in normal?

Best regards,
Y. Pradat

**Comment by ypradat** [comment]
Running SAGE v4.0 (beta) made me realize that `high_depth_mode` and `map_qual_ratio_factor` are actually correct options in the latest version.
I got confused from the README https://github.com/hartwigmedical/hmftools/tree/master/sage#readme which suggests that the latest version of SAGE is v3.3.

Best regards,
Y. Pradat

**Comment by charlesshale** [comment]
These parameters will change in v4.0, due out for release shortly with pipeline v6.0. 

If you exome is 100-150X depth then you do not need to specify any additional Sage parameters. The 'high_depth_mode' argument is more about targeted panels and is likely of limited benefit for that depth over an exome, but might be test to experiment calling with and without it.

**Comment by thomasgarrety** [comment]
Apologies for the confusion here - the latest (non-beta) version of Sage is v3.4, and the Readme (including the recommended options you mentioned) are based on this version. However, the download links currently stop at v3.3. We will add v3.4 to this list.

As Charles mentioned, we will soon be releasing Sage v4.0, which will result in further changes to these parameters. When this occurs, we will update the Readme documentation as applicable, and add this version to the download links.
