### ISSUE TITLE
Missing R package 'copynumber' when running amber and cobalt:

### ISSUE THREAD

**Issue by AndreasSandJespersen** [hartwigmedical/hmftools#621]
Hi there,

I'm having some issues running amber and cobalt.
This is an issue with my java installation. Although I have a copynumber available in my version of R, java is not using this version of R it seems. It is however loading some version as it is able to load the dplyr package.
To be clear I'm working on an HPC where I load these tools individually, so there's not much reason to think that my version of R has much to do with my version of java.
I've tried looking online for help with this, but haven't had much success. I understand this isn't really an issue with either of your tools, but I was wondering if you could point me in the right direction.
The java version I'm using is jdk/21.0.1.

Thanks,
Andreas

**Comment by hongwingl** [comment]
Amber and Cobalt uses `RScript` on the `PATH` to run R. Are you able to make sure the correct `RScript` is on the `PATH` variable?

**Comment by AndreasSandJespersen** [comment]
It is

I have now somehow managed to get it to work. This was the path variable for an unsuccessful run:

```
/services/tools/circos/0.69-6/bin:/services/tools/gridss/2.13.2/bin:/services/tools/gridss/2.13.2/sbin:/services/tools/perl/5.20.1/bin:/services/tools/R/4.4.0/bin:/services/tools/intel/perflibs/2020_update4/compilers_and_libraries/linux/mpi/intel64/bin:/services/tools/intel/perflibs/2020_update4/compilers_and_libraries/linux/bin/intel64:/services/tools/gcc/9.4.0/bin:/services/tools/jdk/21.0.1/bin:/services/tools/anaconda3/2021.11/condabin:/ngc/projects/gm/utils/ac_help:/services/tools/anaconda3/2021.11/bin:/ngc/people/andjes/.local/bin:/ngc/people/andjes/bin:/usr/local/bin:/cm/local/apps/environment-modules/4.2.1//bin:/opt/moab/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/4.2.1/bin
Error in library("copynumber") : there is no package called ‘copynumber’
```

And this was the path variable when it worked:
```
/services/tools/circos/0.69-6/bin:/services/tools/perl/5.20.1/bin:/services/tools/R/4.4.0/bin:/services/tools/intel/perflibs/2020_update4/compilers_and_libraries/linux/mpi/intel64/bin:/services/tools/intel/perflibs/2020_update4/compilers_and_libraries/linux/bin/intel64:/services/tools/gcc/9.4.0/bin:/services/tools/jdk/21.0.1/bin:/services/tools/gridss/2.13.2/bin:/services/tools/gridss/2.13.2/sbin:/services/tools/anaconda3/2021.11/bin:/services/tools/anaconda3/2021.11/condabin:/ngc/projects/gm/utils/ac_help:/ngc/people/andjes/.local/bin:/ngc/people/andjes/bin:/usr/local/bin:/cm/local/apps/environment-modules/4.2.1//bin:/opt/moab/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/4.2.1/bin
Loading required package: BiocGenerics
```

I think I will have to look into this a bit more and get back to you. The only difference I can see is the order of some of these modules, namely gridss being loaded before or after R (appreciate it doesn't need to be loaded to run amber, I had just set up one big script for testing purposes):

modules 1:12 loaded in first failure case:
['/services/tools/gridss/2.13.2/bin',
 '/services/tools/gridss/2.13.2/sbin',
 '/services/tools/perl/5.20.1/bin',
 '/services/tools/R/4.4.0/bin',
 '/services/tools/intel/perflibs/2020_update4/compilers_and_libraries/linux/mpi/intel64/bin',
 '/services/tools/intel/perflibs/2020_update4/compilers_and_libraries/linux/bin/intel64',
 '/services/tools/gcc/9.4.0/bin',
 '/services/tools/jdk/21.0.1/bin',
 '/services/tools/anaconda3/2021.11/condabin',
 '/ngc/projects/gm/utils/ac_help',
 '/services/tools/anaconda3/2021.11/bin']

modules 1:11 loaded in second success case:

['/services/tools/perl/5.20.1/bin',
 '/services/tools/R/4.4.0/bin',
 '/services/tools/intel/perflibs/2020_update4/compilers_and_libraries/linux/mpi/intel64/bin',
 '/services/tools/intel/perflibs/2020_update4/compilers_and_libraries/linux/bin/intel64',
 '/services/tools/gcc/9.4.0/bin',
 '/services/tools/jdk/21.0.1/bin',
 '/services/tools/gridss/2.13.2/bin',
 '/services/tools/gridss/2.13.2/sbin',
 '/services/tools/anaconda3/2021.11/bin',
 '/services/tools/anaconda3/2021.11/condabin',
 '/ngc/projects/gm/utils/ac_help']
