### ISSUE TITLE
Tumor-only GRIPSS not working

### ISSUE THREAD

**Issue by micoli98** [hartwigmedical/hmftools#622]
Hi,
I'm using HMF tools for SV and CNV calling in tumor-normal matched and tumor-only mode and I've been running some test for samples for which I have the matched normal in both modes to compare the results. The problem appears when I'm running gripss (v2.3.4) since for some samples it calls much more SVs that in tumor-normal matched (it makes sense since there is no filtering of the germline variants), while for others it gives empty vcf so it hard-filters out all variants.
After some trials, I discovered that relaxation of the hard filter hard_max_normal_relative_support to 1 gives some results. Shouldn't these arguments be deactivated since there isn't the normal support?

I report here the code with parameters for both gridss and gripss:
```
/gridss-2.13.2/gridss \
    -r path/to/ref_genome \
    -j  /gridss-2.13.2/gridss-2.13.2-gridss-jar-with-dependencies.jar \
    -o sample_calls.vcf \
    -b merged_blacklist.bed \ #mix of hartwig and in-house balcklist
    --skipsoftcliprealignment \
    sample.bam

  java -jar /path/gripss_v2.3.4.jar \
        -sample  sample_name \
        -ref_genome path/to/ref_genome \
        -pon_sgl_file gridss_pon_single_breakend.bed \ #from previous gridss.GeneratePonBedpe with our cohort normals
        -pon_sv_file gridss_pon_breakpoint.bedpe \
        -vcf sample_calls.vcf \
        -ref_genome_version 38 \
        -output_dir .
```

gripss outcome when it filters all variants:
```
14:33:22.496 [INFO ] loaded 3102729 germline SV PON records from file(/SCNA_Purple/results/240617/gridss_pon_breakpoint.bedpe)
14:33:23.145 [INFO ] loaded 1520513 germline SGL PON records from file(/SCNA_Purple/results/240617/gridss_pon_single_breakend.bed)
14:33:23.197 [INFO ] sample(X_DNA1) processing VCF(/SCNA_Purple/results/tumorOnly_trial/X_DNA1_calls.vcf)
14:33:23.199 [INFO ] tumor genotype info(0: X_DNA1)
14:33:26.030 [DEBUG] sample(X_DNA1) processed 100000 variants
14:33:27.951 [DEBUG] sample(X_DNA1) processed 200000 variants
14:33:30.132 [DEBUG] sample(X_DNA1) processed 300000 variants
14:33:30.269 [INFO ] read VCF: breakends(308096) unmatched(0) complete(0) hardFiltered(195833)
14:33:30.269 [INFO ] writing output VCF files to /SCNA_Purple/results/tumorOnly_trial/
14:33:30.366 [INFO ] writing empty VCF
14:33:30.391 [INFO ] Gripss run complete
```

Are there suggested parameter values in tumor-only mode to have a comparable number of SVs?
Thank you in advance.

**Comment by charlesshale** [comment]
Gripss has been replaced by Esvee so would suggest moving to that instead, thanks
