### ISSUE TITLE
GRIPSS v2.4 : Missing sample names error 

### ISSUE THREAD

**Issue by AndreasSandJespersen** [hartwigmedical/hmftools#625]
Hi there,
I've seen a similar issue has been answered before in #523 and #441
I've run gridss v2.13.2, followed by gripss v2.4.

My error for gripss is as follows:
```
[INFO ] sample(<tumor_ID>) processing VCF(<workdir>/gridss/<tumorsample>.gridss.vcf.gz)
[ERROR] missing sample names in VCF: [<germsample>, <tumorsample>]
```

The #CHROM POS ... line of the vcf <tumorsample>.gridss.vcf.gz has both names present though:

`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  <germsample>        <tumorsample>
`
I'm not using the ´--labels´ option in gridss, should I be?
Should I just try using gripss v2.2?

**Comment by charlesshale** [comment]
Gripss has been replaced by Esvee so would suggest moving to that instead, thanks

**Comment by AndreasSandJespersen** [comment]
Okay! The link for ESVEE version 1 is currently dead however.
