### ISSUE TITLE
no output in the purple.cnv.gene.tsv file

### ISSUE THREAD

**Issue by yu-wei21** [hartwigmedical/hmftools#628]
Hi authors,

Thank you for developing this great tool for CNV analysis. I am using it to analyze cancer WGS data, but I encountered a problem.

when perforing purple analysis using the code below, **I got the results in the purple.cnv.somatic.tsv file but no data in the purple.cnv.gene.tsv file.** 

**This is my code script:** 
purple=/home/software/purple_v3.8.4.jar
java -jar ${purple} \
   -reference ${normal}.bqsr \
   -tumor ${tumor}.bqsr \
   -amber purple/amber/${tumor} \
   -cobalt purple/cobalt/${tumor} \
   -gc_profile ensemble_GRCh38.p14.release.112/v6_0/ref/38/copy_number/GC_profile.1000bp.38.cnp \
   -ref_genome ${ref} \
   -ref_genome_version 38 \
   -ensembl_data_dir ensemble_GRCh38.p14.release.112/v6_0/ref/38/common/ensembl_data \
   -output_dir purple/purple/${tumor}

**This is the results in the purple.cnv.somatic.tsv file:**
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/c67a57b8-cb9f-4fe5-b69b-b9b504e1d732">

But the purple.cnv.gene.tsv file is blank.

The purple version is 3.8.4.

Thank you for your time and help.

**Comment by seoldh** [comment]
I'm having the same issue. How did you solve it?

**Comment by yu-wei21** [comment]
yes, the issue is due to the "chr" in the reference genome. I used ensembl reference genome which have no "chr".

**Comment by charlesshale** [comment]
The Hartwig resources include the Ensembl data cache - would strongly recommending only using those for all HMF tools.

**Comment by seoldh** [comment]
I initially mapped reads to reference (V38) that did not contain 'chr' prefix.
Both cobalt and amber were done with 'chr' removed from the files provided by hmftools in version 38.
ex) 'GC_profile.1000bp.38_nochr.cnp', 'AmberGermlineSites.38_nochr.tsv.gz'

I was hoping that this would work for purple as well, but I am unable to resolve the following error with (-ref_genome_version 37).
![image](https://github.com/user-attachments/assets/0145edd0-b241-4661-b5ca-b4b8396ec75a)


with (-ref_genome_version 38), purple.cnv.gene.tsv is missing.

Is there a shortcut to resolve this?
