### ISSUE TITLE
r and cobalt/amber comment

### ISSUE THREAD

**Issue by sisterdot** [hartwigmedical/hmftools#63]
Hey!

first time user of cobalt/amber/purple and its a beauty :-)

small initial glitch with an R error in cobalt/amber that looks like

```
Warning: pcf is not run for sample 1 on chromosome arm  because all observations are missing. NA is returned.
Error in data.frame(rep(sampleid[i], nSeg), seg.chrom, seg.arm, pos.start,  : 
  arguments imply differing number of rows: 1, 0
Calls: pcf -> data.frame
In addition: Warning message:
In numericChrom(chrom) : NAs introduced by coercion
```

the cause was the setting options(stringsAsFactors=FALSE) in my Rprofile

more specifically cobalt/amber are removing the chromosomePrefix by determining it with something like `chromosomeLevels = levels(ratio$chromosome)`, which will fail with stringsAsFactors=FALSE

THANKS a lot for the great tools, easy usage and clear documentation!

**Comment by jonbaber** [comment]
Thanks for the very clear diagnosis! It makes it a lot easier when someone does all the hard work for me :)

I have added an explicit `stringsAsFactors = T` to the read.table call.

Glad you are finding the tools useful.

Jon

**Comment by sisterdot** [comment]
its not only useful- but its also so mega easy and the output super pretty -
i am loving it !!!!

also the cytoscape files are so clearly documented that its easy to mix and match tracks of input and purple output ! 

i am honestly impressed!

**Comment by jonbaber** [comment]
Thank you for your very kind comments. You have made my day :)

**Comment by jonbaber** [comment]
I have released new versions of AMBER and COBALT if you would like to try them.

**Comment by jonbaber** [comment]
https://github.com/hartwigmedical/hmftools/releases/tag/cobalt-v1.8
https://github.com/hartwigmedical/hmftools/releases/tag/amber-v3.1
