### ISSUE TITLE
Misformatted sgl_pon.38.bed.gz  and sv_pon.38.bedpe.gz in v5.34 resources

### ISSUE THREAD

**Issue by toddajohnson** [hartwigmedical/hmftools#637]
In the v5.34 resource, the sql_pon and sv_pon files appear to be misformatted.  For instance, chromStart is equal to chromEnd in sql.pon.34 for 1362734 rows, and chromStart is greater than chromEnd for 1364264 rows, while zero rows of the v5.32 bed file had chromStart equal to or greater than chromEnd. As far as I understand, the BED format should have starts less than or equal to end, but never greater, so the inconsistency with the previous files would suggest a bug during processing the newer dataset.  The sv_pon bedpe has similar inconsistencies for start and end columns encoding the two breakpoints.  This misformatting may not be caught as incorrect by GRIPSS, but an issue was filed on GRIDSS' Github issues where gridss_somatic_filter had errors when a couple of users upgraded to the v5.34 resource.

**Comment by charlesshale** [comment]
Esvee checks that the BED file is ordered correctly and the resource files sgl_pon.37/8.bed.gz and sv_pon.37/8.bedpe.gz are valid for pipeline v6.0 resources.
