### ISSUE TITLE
Amber config file

### ISSUE THREAD

**Issue by SophieS9** [hartwigmedical/hmftools#647]
Hi Team,

I've download amber v4.0.1 https://github.com/hartwigmedical/hmftools/releases/tag/amber-v4.0.1 as the latest release. I'm running as follows:

```
java -jar ~/amber_v4.0.1.jar \
    -tumor BC2001 \
    -tumor_bam ../Alignments/BC2001.sort.aligned.bam \
    -output_dir /BC2001/ \
    -threads 10 \
    -loci ~/v6_0/ref/38/AmberGermlineSites.38.vcf.gz
```

When trying to run I'm getting the error message:
```
13:51:47.802 [ERROR] invalid path for config: loci = /home/c.medss21/v6_0/ref/38/AmberGermlineSites.38.vcf.gz
```

I've tried changing this to the following as per the instructions:
```
java -jar ~/amber_v4.0.1.jar com.hartwig.hmftools.amber.AmberApplication \
    -tumor BC2001 \
    -tumor_bam ../Alignments/BC2001.sort.aligned.bam \
    -output_dir /BC2001/ \
    -threads 10 \
    -loci ~/v6_0/ref/38/AmberGermlineSites.38.vcf.gz
```

But then get the error:
```
13:55:05.519 [ERROR] expecting config name but encountered invalid argument: com.hartwig.hmftools.amber.AmberApplication
```

Where can I get this config file?

**Comment by hongwingl** [comment]
Hi,
Config we mean command line arguments. You need to remove the java class name.

**Comment by SophieS9** [comment]
Thanks @hongwingl. Might be good to update https://github.com/hartwigmedical/hmftools/tree/amber-v4.0.1/amber to make it clear that the java class name isn't needed,
