### ISSUE TITLE
Expand `known_fusion_data` with `FusionPDB`

### ISSUE THREAD

**Issue by bounlu** [hartwigmedical/hmftools#649]
Several tools like `esvee`, `linx`, `isofox` are using `known_fusion_data` as a reference, so it's crucial to have a comprehensive list of known fusion events. I would suggest to expand the current list with the available data from [FusionPDB](https://compbio.uth.edu/FusionPDB/) publicly available to [download](https://compbio.uth.edu/FusionPDB/download.html).

**Comment by charlesshale** [comment]
The known fusion files in the Hartwig public resources have been curated for use in clinical diagnostics. Users are able to provide a custom or expanded set of files as required.
