### ISSUE TITLE
Feature Request: COBALT Picard Options

### ISSUE THREAD

**Issue by lkhilton** [hartwigmedical/hmftools#65]
I'm working with some old bam files generated with BWA 0.7.5 that don't conform to current SAM specifications, specifically with regard to the mapping quality of unmapped reads. I'm working through the gridss-purple-linx.sh pipeline and have been able to add `VALIDATION_STRINGENCY=LENIENT` as an option to all the tools that precede COBALT, but it seems that COBALT doesn't accept this option so I run into the error 
```
Exception in thread "main" java.util.concurrent.ExecutionException: htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 69019581, Read name HS18_34:2:2106:5690:79340, MAPQ should be 0 for unmapped read.
```

Is it possible to add this option to all the tools in the gridss-purple-linx pipeline?

I've also raised this issue at the gridss-purple-linx github page. https://github.com/hartwigmedical/gridss-purple-linx/issues/6

**Comment by jonbaber** [comment]
I have added `validation_stringency` option to both AMBER and COBALT. Valid values are STRICT (default), LENIENT and SILENT.

**Comment by lkhilton** [comment]
Thanks for addressing this so quickly.

**Comment by jonbaber** [comment]
My pleasure. 

I have released new versions of AMBER and COBALT if you would like to try them.

**Comment by jonbaber** [comment]
https://github.com/hartwigmedical/hmftools/releases/tag/cobalt-v1.8
https://github.com/hartwigmedical/hmftools/releases/tag/amber-v3.1

**Comment by Kdreval** [comment]
Don't see a reason to open a new issue since my error is exactly the same:
```
Exception in thread "main" java.util.concurrent.ExecutionException: htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::INVALID_MAPPING_QUALITY:Record 4521, Read name HS18_34:2:2106:5690:79340, MAPQ should be 0 for unmapped read.
```
while running SAGE on bam files generated with the same version of BWA. Is it possible to add a similar option for validation stringency to SAGE?

**Comment by jonbaber** [comment]
Hi, yes that is fine. I will do that shortly and it will be in the next release.

**Comment by Kdreval** [comment]
Thank you for the new release and provided support!

**Comment by jonbaber** [comment]
No problem. I don't actually have a bam suitable to test the feature so please let me know if you have any issues.

**Comment by Kdreval** [comment]
I had 79 bams that were failing due to MAPQ in unaligned reads, and they all were completed using the updated 2.6 version. Many thanks!
