### ISSUE TITLE
`bam-tools` summary metrics in targeted mode

### ISSUE THREAD

**Issue by bounlu** [hartwigmedical/hmftools#652]
`bam-tools` calculates the BAM coverage summary metrics based on the input reference genome fasta file, no matter whether it was run on targeted mode. This might be confusing as one would expect the summary statistics calculated based on the target regions in the targeted mode if an input bed file is provided. Can this feature be added to the tool?

**Comment by charlesshale** [comment]
You can specify a BED file with the '-regions_file' argument.
Then BamMetrics can optionally ignore all other regions with the 'only_target' flag.
