### ISSUE TITLE
`redux` jitter analysis fails

### ISSUE THREAD

**Issue by bounlu** [hartwigmedical/hmftools#653]
`redux` failed for 1/15 samples with the below error:

`09:35:32.637 [main] [INFO ] analysing microsatellite jitter
09:37:15.202 [main] [ERROR] failed to write output of jitter analysis: org.apache.commons.math3.exception.MathIllegalArgumentException: not enough data (2 rows) for this many predictors (2 predictors)`

Is there a way to prevent this?

**Comment by charlesshale** [comment]
You could omit the MSI sites input file and it will then skip this MSI jitter routine. However Sage expects these files to have been produced (unless it is run with the option 'skip_msi_jitter').

Might be better to understand why this is occurring.
