### ISSUE TITLE
Feature request: Export CNVs from `purple` in `VCF`

### ISSUE THREAD

**Issue by bounlu** [hartwigmedical/hmftools#654]
Currently `purple` exports the [output files](https://github.com/hartwigmedical/hmftools/tree/master/purple#files) in TSV or plain text format only. To make it easier to work with some downstream tools which only accept VCF, I recommend to add a feature to `purple` to export CNV calls in VCF format also.

**Comment by charlesshale** [comment]
Thanks for the suggestion but I recommend using or developing another utility to do this.
