### ISSUE TITLE
Can PURPLE support WES?

### ISSUE THREAD

**Issue by ShixiangWang** [hartwigmedical/hmftools#66]
Dear developer,

Can PURPLE support WES? I cannot find any description in the README of PURPLE. 

Best,
Shixiang

**Comment by jonbaber** [comment]
Hi Shixiang, 

We have been considering this for a while and will look into it shortly (probably within the next 2-3 weeks). I will keep this ticket open for the moment and will update it once we decide either to go ahead with it or not.

Regards, Jonathan

**Comment by Xiaohuaniu0032** [comment]
@jonbaber Can PURPLE now  support WES or target sequencing data?

**Comment by p-priestley** [comment]
Not yet.   We have a use case for this internally now, so we intend to add  in the next 4-6 weeks.   

CNVKit may be a useful alternative for you in the meantime.

**Comment by milenastanojevic** [comment]
Is there any update on this issue? Are there any recommendations regarding parameters for running Purple-Linx on WES data? Thanks!

**Comment by p-priestley** [comment]
We have moved away for now from the idea of extending PURPLE to WES, so will close this for now.   We may look at this again later on.   

apologies
