### ISSUE TITLE
Questions for PURPLE pipeline

### ISSUE THREAD

**Issue by pdiakumis** [hartwigmedical/hmftools#7]
Hi folks,

First up - thanks for these very nice tools.

After a bit of a long hiatus due to computing issues we've started running PURPLE/AMBER/COBALT on a few tumor/normal samples. 

- I have a very basic question for starters: what is the general runtime that you have noticed for the above pipeline? The main bottleneck for us had been the sambamba mpileup step for AMBER, and the COBALT step, each taking at least 2.5-3hrs on ~30 cores, ~60-80G mem, on Unimelb's Spartan cluster. However today I ran the pipeline on NCI's Raijin and noticed ~10min runtime for each of those steps. Tumor/normal BAMs were 90/50 GB. And I used the latest jar releases. 
Is this more like the usual runtime from your experience?

- Second question: are there any plans to set up conda packages for these tools? Not sure how feasible that is, but it would make it a lot easier for us (and others) to grab via something like bioconda.

- Third question: when providing PURPLE with a SV VCF with the `structural_vcf` option, I've noticed that all the files in the `purple` directory change a tiny bit (e.g. BAF values), while the `purple/<sample-tumor>.purple.cnv` file's segments get chopped up a bit more and their copy number mostly stays the same (e.g. look at one of our samples here https://github.com/umccr/colo829/issues/1#issuecomment-403706191). Am I missing anything else?

Many thanks - Peter

**Comment by jonbaber** [comment]
Hi Peter,

1. Yes, we typically get 15 min runtimes for amber pileup and cobalt.
2. Not as yet, but appreciate the feedback and it is something we can look into down the track.
3. This is expected behaviour. When you provide an SV VCF, PURPLE will enforce a copy number segment at every SV break point. This provides much more accurate copy number segments. However, this can cause a problem when there are many SVs clustered together. If these clusters are smaller than the 1000 base cobalt window resolution then we are unable to determine what the copy number is inside these segments. However, if the SV VCF includes an Allelic Frequency, then we infer what the copy number is but anticipating the change in copy number from one side of the SV to the other. We have a tool ([BPI](https://github.com/hartwigmedical/hmftools/tree/master/break-point-inspector)) which improves upon the Manta logic and appends the AF to the output. Daniel Cameron has also added the same functionality to [GRIDSS](https://github.com/PapenfussLab/gridss) (I would have to check if this has been released yet).

Let me know if there is anything else I can do to help.

Cheers, Jon

**Comment by pdiakumis** [comment]
Awesome stuff, thanks for the quick response Jon!

1. That's great to hear about the runtime. We think Spartan generally has some IO issues, which explains why it takes that long.
2. Not too fussed about condarising stuff; the jars work perfectly fine. It's just that we've got snakemake pipelines going hand in hand with bioconda :-)
3. Cool, I was only really wondering if I was missing out on any other changes. We _are_ using BPI to further annotate Manta calls via [bcbio](https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/structural/manta.py#L42), so I'm guessing PURPLE automatically takes the `INFO/BPI_AF` field into account (let me know if that's not the case).

Cheers - Peter

**Comment by p-priestley** [comment]
Missed this comment earlier.

PURPLE will work fine with no SV at all, so filtering further is a good idea if you think it improves the SV calls overall.

**Comment by pdiakumis** [comment]
Apologies for re-opening this issue. 

We've been testing PURPLE internally and through [bcbio](https://github.com/bcbio/bcbio-nextgen) and were wondering what effect the provided `somatic_vcf` and `structural_vcf` options have on the CNV calls. Currently, we provide a Manta VCF (annotated with Break-Point-Inspector) for the SV option and a filtered ensemble VCF for the SNV/Indel option.

After testing ~40 samples with (i)both SV+SNV, (ii)only SV, and (iii)only SNVs as input to PURPLE, we get somewhat different results for some of the samples, with SNVs having quite an impact on the CNV calls for some of the samples. 

To be honest, I was under the impression that the SNVs were only optionally provided exclusively for plotting in the circos plot. To take this a step further, what impact would the filters we apply on the SNV calls have on the CNV calls?

Many thanks - Peter

**Comment by p-priestley** [comment]
Peter,

Apologies that this is not super transparent at this moment, but somatic SNV  do indeed affect the fit.   We will make a more detailed description of PURPLE functionality shortly.

Right now, there are 2 impacts of including SNVs:

1. If we find a candidate solution which is >95% diploid and we have a significant uncertainty in it's fitting range we use a dedicated SOMATIC mode.   In this mode we look at the VAF peaks in the somatic variants, and search for the best fit which produces consistent integer ploidies.   .  If we are in SOMATIC mode, there are not more than N (default 300) SNVs with greater than  10% VAF then we keep the original fit and mark as 'NO_TUMOR'.

2. We recently added a SOMATIC_DEVIATION_PENALTY which also affects all fit decisions if SNVs are provided.   A description below:

A somatic deviation penalty has been added to penalise fits which lead to somatic variants with higher ploidies than the major allele ploidy.   The 99.9% upper cutoff for binomial distribution from the major allele ploidy is used as a cutoff to mark variants as inconsistent.   1000 somatic variants are sampled per tumor, with the somatic penalty equal to the sum of the deviations over the 99.9% cutoff divided by the number of somatic variants sampled.


We find these features greatly improve fitting in some corner cases.   Please let me know if you see specific problems.   If you can provide examples to us directly via email then that would be good.

Peter

**Comment by ohofmann** [comment]
Peter,

don't think we've seen any issues, just edge cases where the addition of somatic SNVs made the calls much better -- in particular for FFPE samples it resolved a lot of the fragmentation we've seen with other callers that do not use the somatic calls. 

Oliver

**Comment by p-priestley** [comment]
Ok.  We have not tested ourselves on FFPE samples, so good to know.

**Comment by tea-kostic** [comment]
Hi!

I was wondering where can we find BPI tool to process Manta output for use in Purple? 
I know you guys aren't maintaining it anymore, but it would be of great value to us if we could get it somewhere somehow.

Thanks in advance!
Tea

**Comment by jonbaber** [comment]
I have updated the last [release](https://github.com/hartwigmedical/hmftools/releases/tag/bpi-v1.7) of BPI to include a jar.

Gridss now also supports a targeted mode that can take an existing SV VCF and then run only on those regions. We recommend using this instead.

**Comment by tea-kostic** [comment]
Thanks for the quick reply! It's really great news that Gridss has that feature now, since we are already using the HMF  Gridss/Purple/Linx pipeline(cwl version). Can you point us to some documentation on how to run Gridss in this targeted mode?

Thanks again!
Tea

**Comment by p-priestley** [comment]
Please see gridss_extract_overlapping_fragments.sh script now included in GRIDSS releases.
