### ISSUE TITLE
Circos hg38 karyotype

### ISSUE THREAD

**Issue by pdiakumis** [hartwigmedical/hmftools#71]
Is it possible to parameterise the circos karyotype file based on the human genome assembly detected/specified? The `data/karyotype` directory in the circos installation contains both hg19 & hg38 versions:

```
$ ls -1 data/karyotype/*human*
data/karyotype/karyotype.human.hg16.txt
data/karyotype/karyotype.human.hg17.txt
data/karyotype/karyotype.human.hg18.txt
data/karyotype/karyotype.human.hg19.txt
data/karyotype/karyotype.human.hg38.txt
data/karyotype/karyotype.human.txt
```
 
Based on https://github.com/hartwigmedical/hmftools/blob/master/purity-ploidy-estimator/src/main/resources/circos/circos.template#L35, I think the hg19 one is used by default (`karyotype.human.txt` is the same as `karyotype.human.hg19.txt`), even if the BAMs are aligned to hg38. I noticed I was getting some warnings about `data points extending past end of ideogram` in my logs when setting up a custom config.

Thanks for your awesome tools and support!
Peter

**Comment by jonbaber** [comment]
Good pickup. 

I have released [2.39](https://github.com/hartwigmedical/hmftools/releases/tag/purple-v2.39) for you. If you do upgrade please note that [2.38](https://github.com/hartwigmedical/hmftools/releases/tag/purple-v2.38) requires a database patch.

Glad I could help.

Cheers, Jon

**Comment by pdiakumis** [comment]
Sorry, just noticed I forgot to link to the [input template](https://github.com/hartwigmedical/hmftools/blob/master/purity-ploidy-estimator/src/main/resources/circos/input.template#L40) as well - is it too much trouble adjusting in the same way? Think it only needs KARYOTYPE in there, then [writeConfig](https://github.com/hartwigmedical/hmftools/blob/master/purity-ploidy-estimator/src/main/java/com/hartwig/hmftools/purple/plot/CircosCharts.java#L137) should handle it?
Thank you

**Comment by jonbaber** [comment]
Silly oversight. Thanks for pointing that out. Will be fixed in next release.
