### ISSUE TITLE
How to deal with genomes that result in FAIL_SEGMENT

### ISSUE THREAD

**Issue by rdmorin** [hartwigmedical/hmftools#72]
We have a few tumour/normal genome pairs that have very high ploidy estimates and an unrealistic number of segments. These genomes tend to also have QCStatus	FAIL_SEGMENT set by Purple. We have been able to obtain reasonable copy number from these genomes using other pipelines. Is there a way around this issue (e.g. parameters we can modify etc)?

**Comment by p-priestley** [comment]
FAIL_SEGMENT is a test that we use to look for excessive copy number noise in the sample.   We see this in about 1.5% of our samples.   It is most frequently caused by very high megabase scale GC bias in the sample that we think is associated with degradation of the sample (eg. we have shown that we can generate such damage by storing samples at room temperatures temporarily)

PURPLE may indeed not be well tuned to fitting the noise and will likely tend to overfit the noise and hence overestimate the ploidy.    

There are a few options you have around parameterisation, but I would like to understand the problem better first.   Would you be able to share the plots for 1 sample with me?    If you don't want to share here, you could share privately at p.priestley@hartwigmedicalfoundation.nl

**Comment by p-priestley** [comment]
I just checked quickly in our own cohort and we do seem to overestimate the ploidy of samples with FAIL_SEGMENT.   In the chart below you can see that the WGD peak is much bigger for these samples relative to the ploidy 2 peak.    

We will think about a way to structurally address this.   Please let me know if you want help with a work around as per above.

![image](https://user-images.githubusercontent.com/18154939/73411828-da7d8c00-435a-11ea-8c62-f1eb11be195d.png)

**Comment by rdmorin** [comment]
Thanks in advance for looking into this. I've attached the plots from one example.

[plots.zip](https://github.com/hartwigmedical/hmftools/files/4131928/plots.zip)

**Comment by p-priestley** [comment]
I just a took a look.   There indeed seems to be extensive large scale GC Bias and copy number noise in the tumor sample.   

The noise you can see in blue dots on the input png which show the initial segmentation of the tumor in cobalt.  Normally this would look like a set of thin blue lines following the somatic copy number with occasional segments lower or higher which are related to germline events.   

The large scale negative GC bias is most evident on the chr 1P arm (which together with chr19 and 22 has the highest GC content of any chromosome).   You can see that the copy number here is both very noisy and relatively low.    From an interpretation perspective this is quite risky as it can mean you can call homozygous deletions incorrectly.    

Cobalt does correct for 1kb level GC bias, and broad scale bias in the reference sample but correcting for large scale GC bias in the tumor is dangerous as we may be liable to fit out real copy number change.    

To me it is not completely clear in this case that the fit is wrong.   I assume that you believe in this case that the ploidy is much lower - close to diploid - but what purity do you get?      Some chromosomes such as chr 8 and 19 would be difficult to explain with a lower ploidy (they could have subclonal loss), and the somatic variant ploidies look like they could lend weight to a WGD thesis.

If you believe you know the correct purity then you can simply specify the min and max purity range to that level.  See  https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#optional-fitting-arguments 

There is also the possibility of setting a tight min-max ploidy I believe, but will need to look it up.  Let me know what you think first and if you need more details

**Comment by rdmorin** [comment]
[00306_genome_view.pdf](https://github.com/hartwigmedical/hmftools/files/4132112/00306_genome_view.pdf)
I've attached the result from running Sequenza on this case. The optimal fit from Sequenza estimates the purity at 0.4 and ploidy at 2.4. Based on the BAF I do suspect this tumour has higher ploidy. The next-best fit is purity ~0.1 and ploidy ~3.4. It doesn't sound like an underlying high ploidy is the cause of this issue though and since PURPLE is probably estimating a reasonable purity and ploidy, it's not clear to me if limiting the search range will help. I'm happy to try anything you suggest.

**Comment by p-priestley** [comment]
I think the sequenza plot is from a different sample as the copy number profile does not match.

Could you clarify what is it you want to achieve with this sample?

**Comment by rdmorin** [comment]
You're right. I don't know if we have Sequenza results yet for this case. I'll check on this and get back to you.

**Comment by rdmorin** [comment]
Sequenza calls this case close to diploid (see below). The segmentation is definitely noisier than usual for this case, though. 

[00036_genome_view.pdf](https://github.com/hartwigmedical/hmftools/files/4149959/00036_genome_view.pdf)

**Comment by p-priestley** [comment]
Sequenza shows large sections of the genome particularly on chr 1, 10 and 19 to be homozgously deleted.      In high quality samples we rarely find large segments of chromosomes deleted as there are generally essential genes scattered round the chromosomes.  Hence I would think this is biologically implausible.     PURPLE actively penalises fits with large amounts of homozygous deletions

In this case it may be that Sequenza fit is right, but the residual large scale GC bias leads Sequenza to call regions of high GC content with 0 copy number.      

I saw that a tool 'dryclean' was created recently to deal with some of this large scale bias: https://www.biorxiv.org/content/10.1101/847681v1   I have not tried myself, but perhaps it is helpful.
