### ISSUE TITLE
how to plot second circos plot showing structural variant?

### ISSUE THREAD

**Issue by a00101** [hartwigmedical/hmftools#74]
I don't know how to plot second circos plot, which is showing structural variant.
I got a result from PURPLE pipeline including 'testsample.circos.png' but It is not shown structural variant relationship such as translocation etc.
Is it possible when structural variant vcf is provided with GRIDSS?

Thanks.

**Comment by DarioS** [comment]
Please provide an example of the PURPLE command line you used. Also, how many structural variants are left in your VCF file after GRIDSS somatic fitlering?

**Comment by jonbaber** [comment]
As Dario suggested, could you please provide your command line arguments and a count of how many passing structural variants you are supplying to PURPLE.

Thanks.

**Comment by a00101** [comment]
Thank you for your replies.
I left a output file from GRIDSS inadvertently.
Sorry.
