### ISSUE TITLE
LINX Visualisation Required Arguments

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#75]
`sv_vcf` is "Full path and filename for the SV VCF" and `purple_dir` is "Directory with sample data for structural variant VCF". Doesn't the full path specified to sv_vcf make purple_dir redundant? Or is there something slightly different about them? Also, for LINX visualisation, couldn't Path to segment file, Path to link file, Path to protein domain file, Path to fusion file, Path to copy number alteration file, Path to exon file be inferred if a directory and sample ID were input since all files use the same prefix? Also, do any of these parameters depend on any parameter other than `-write_vis_data` during the previous LINX computation? I didn't specify any annotations such as fragile sites, replication timing, etc. and I am getting an error `Exception in thread "main" java.lang.NumberFormatException: For input string: "chainId"`.

**Comment by jonbaber** [comment]
> Also, for LINX visualisation, couldn't Path to segment file, Path to link file, Path to protein domain file, Path to fusion file, Path to copy number alteration file, Path to exon file be inferred if a directory and sample ID were input since all files use the same prefix

Yes they could be, but I prefer to explicitly state dependencies as it offers more flexibility. Our typical use cases are run as scripts so after the initial setup it is no extra work to specify all the files. 

I'll ask @charlesshale to answer your remaining questions. We will see what he says first but we might need to get your input files into the visualiser to diagnose why you are getting that exception.

**Comment by charlesshale** [comment]
Regarding this question:
 _Also, do any of these parameters depend on any parameter other than -write_vis_data during the previous LINX computation?_

the config option -'write_vis_data' is all you need to specify.

**Comment by charlesshale** [comment]
For that number format exception, could you send me the full command and arguments you're running? chainId isn't an argument, so it implies that one of the input files has invalid data in the chainId field.

**Comment by DarioS** [comment]
I figured out the cause. I was specifying `-link /tmp/LS13.linx.links.tsv` because I thought the file with link in its name would be the link file. However, I notice from the example `-link ~/linx/COLO829T.linx.vis_sv_data.tsv` that the link file is a different file containing vis_sv_data in its name. The error doesn't happen if I specify the correct input file. People not familiar with the software could naively assume that "Path to link file" would refer to the file with link in its file name, so I think that part of the documentation could be more explicit to avoid end-user mistakes.

**Comment by charlesshale** [comment]
Ok sure. I'll update the documentation to make that clear, thanks.
