### ISSUE TITLE
LINX R Script Error

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#78]
I used

```
java -cp linx.jar com.hartwig.hmftools.linx.visualiser.SvVisualiser -sample LS13 -plot_out /tmp -data_out /tmp -segment /tmp/LS13.linx.vis_segments.tsv -link /tmp/LS13.linx.vis_sv_data.tsv -exon /tmp/LS13.linx.vis_gene_exon.tsv -cna /tmp/LS13.linx.vis_copy_number.tsv -exon /tmp/LS13.linx.vis_gene_exon.tsv -protein_domain /tmp/LS13.linx.vis_protein_domain.tsv -fusion /tmp/LS13.linx.vis_fusion.tsv -circos /usr/local/circos/0.69-3/bin/circos
```

and an error happened

```r
Warning message:
In max(length) : no non-missing arguments to max; returning -Inf
Warning message:
In max(tmp$row) : no non-missing arguments to max; returning -Inf
Warning messages:
1: In max(rowLength) : no non-missing arguments to max; returning -Inf
2: In max(row) : no non-missing arguments to max; returning -Inf
3: In max(row) : no non-missing arguments to max; returning -Inf
Warning message:
In max(chromosomeLengths$row) :
  no non-missing arguments to max; returning -Inf
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
  invalid 'width' or 'height'
Calls: png
Execution halted
```

**Comment by jonbaber** [comment]
Could you please provide the TSV files that you used as input. Thanks.

**Comment by DarioS** [comment]
An archive of the tables is provided [LINXtest.zip](https://github.com/hartwigmedical/hmftools/files/4284165/LINXtest.zip) Many of them seem to be empty, containing only column headings, because I did not provide particular annotations to LINX such as fragile sites, replication timing, etc. because I haven't lifted them over to hg38 which my analysis is in reference to (hoping they'll appear for download soon on the resources webpage, otherwise I'll lift-over from hg19 myself) and was just trying a minimal run with minimal parameters.

**Comment by jonbaber** [comment]
I haven't forgotten about this, but unlikely to get to it this week. Let me know if this is blocking you and I will try to get to it sooner.

**Comment by DarioS** [comment]
No, next week suits me.

**Comment by jonbaber** [comment]
Thanks for you patience. 

The fix will be in the next released version which should be done sometime tonight.
