### ISSUE TITLE
SAGE 2 whole genome mode

### ISSUE THREAD

**Issue by vladsaveliev** [hartwigmedical/hmftools#79]
Hi!

Thanks so much for developing SAGE 2. Tiered variant calling is a really great approach. Something that is used by [varlociraptor](https://varlociraptor.github.io/docs/filtering/), but with more sensible tiers.

Just wanted to ask if the usage has changed compared to SAGE 1? I tried running the latest release sage-2.1.jar the same why I did run SAGE 1.0:

```
java -jar sage-2.1.jar \
-tumor SEQC-II_Tumor_50pc \
-tumor_bam SEQC-II_Tumor_50pc-ready.bam \
-reference SEQC-II_Normal \
-reference_bam SEQC-II_Normal-ready.bam \
-known_hotspots <(bcftools query -f "%CHROM\t%POS\t%REF\t%ALT\n" hotspots.vcf.gz) \
-coding_regions coding_regions.bed \
-ref_genome hg38.fa \
-out SEQC-II-50pc-sage2.vcf.gz
```

But it calls variants only in hotspots. How can I enable the whole genome mode?

Vlad

**Comment by jonbaber** [comment]
Hi Vlad, 

We have literally only put Sage 2.0 into our pipeline this week in parallel with Strelka to see how it compares. I'm glad you are so keen to try it out but I suggest you might want to wait another week or two to give us a chance to iron out any issues we encounter. We are also currently adding features such as multiple normal support to enable RNA or donor matching.

Once I am a bit more confident it is ready for prime time I will notify you on this ticket and update the documentation to include usage instructions. 

Cheers, Jon

**Comment by vladsaveliev** [comment]
Huh, sure, no worries at all! It sounded exciting so was eager to try :) Once it’s ready, we’ll compare it against the bcbio mutect2/vardict/strelka2 ensemble pipeline, as well as the Illumina Dragen variant caller.

**Comment by ohofmann** [comment]
@jonbaber Do you feel more confident about SAGE 2.0 at this point? Keen to give it another try.

**Comment by jonbaber** [comment]
Hi Oliver, 

I think it is pretty much functionally complete. I know it has been a long time coming but we have made a number of improvements and added new features such as:

- Realignment of inframe indels
- Improved MNV deduplication
- Detection of phased inframe indels
- Base Quality Recalibration
- Improved sensitivity in high depth regions
- Tumor only support
- Mitochondria support
- Multiple tumor support
- Multiple reference (or RNA) support
- Removed explicit RNA support (can use additional reference instead)
- Performance and memory improvements

Right now I am just working on reducing it's memory requirements down from 60-70Gb to 30Gb  to make it a bit more hardware friendly. 

Hopefully we will have something for you soon!

Jon

**Comment by ohofmann** [comment]
Intriguing! Thanks for the summary, looking forward to it :)

**Comment by p-priestley** [comment]
Sage 2.2 is fully validated and available for use.   

Please see documentation at:   https://github.com/hartwigmedical/hmftools/tree/master/sage

Let us know if you spot any issues.
