### ISSUE TITLE
Amber heterozygous locations

### ISSUE THREAD

**Issue by jaesvi** [hartwigmedical/hmftools#8]
Hi,
Quick question. How do you usually determine the heterozygous locations (_/path/to/bed/HeterozygousLocations.bed_) required as input for Amber? 

Thanks,
Jose

**Comment by kduyvesteyn** [comment]
We use the ~750k positions used by the CytoScan HD array (https://assets.thermofisher.com/TFS-Assets/LSG/manuals/cytoscan_hdarray_insert.pdf), but amber itself is not sensitive to the exact bed file. You could also pass every dbsnp position, or even the entire ref genome. Amber will filter only truly heterozygous positions from the positions in the bed file anyways

**Comment by jaesvi** [comment]
Thanks, it is clear now.
