### ISSUE TITLE
Unable to complete segmentation

### ISSUE THREAD

**Issue by Xiaohuaniu0032** [hartwigmedical/hmftools#80]
Hi, 
 I am runing AMBER to calculate the BAF in the tumor_only mode, but i get an error: `R execution failed. Unable to complete segmentation.` I checked the output file `*.amber.baf.tsv` and find this file is empty. I guess the segmentation error is caused by the empty file. But i do not why this happened.

**Comment by Xiaohuaniu0032** [comment]
the `bafSegmentation.R2885448677315039735.error` file's error msg is: `Error: input in data column 2 (posistions) must be numeric`

**Comment by Xiaohuaniu0032** [comment]
my command is `java -Xmx10G -jar amber-3.2.jar -tumor_only -tumor Z19W05700T -tumor_bam $tbam -output_dir $PWD -loci GermlineHetPon.hg19.vcf.gz`, my bam is target sequencing data. I do not know why  *.amber.baf.tsv file is empty.

**Comment by Xiaohuaniu0032** [comment]
19:04:53 - AMBER version: 3.2
19:04:53 - Loading vcf file /db/amber3/GermlineHetPon.hg19.vcf.gz
19:04:55 - Processing 1344545 heterozygous sites in tumor bam /aln/Z19W05700-B1TA/Z19W05700-B1TA.cons.bam
19:05:07 -   [####################] 100% complete
19:05:14 -   [####################] 100% complete
19:05:14 -   [####################] 100% complete
19:05:19 -   [####################] 100% complete
19:05:21 -   [####################] 100% complete
19:05:24 -   [####################] 100% complete
19:05:24 -   [####################] 100% complete
19:05:25 -   [####################] 100% complete
19:05:25 -   [####################] 100% complete
19:05:26 -   [####################] 100% complete
19:05:31 -   [####################] 100% complete
19:05:32 -   [####################] 100% complete
19:05:33 -   [####################] 100% complete
19:05:33 -   [####################] 100% complete
19:05:37 -   [####################] 100% complete
19:05:42 -   [####################] 100% complete
19:05:45 -   [####################] 100% complete
19:05:50 -   [####################] 100% complete
19:05:52 -   [####################] 100% complete
19:05:53 -   [####################] 100% complete
19:05:54 -   [####################] 100% complete
19:05:56 -   [####################] 100% complete
19:05:57 -   [####################] 100% complete
19:05:57 - Median tumor depth at potential contamination sites is 0 reads
19:05:57 - No evidence of contamination.
19:05:57 - Writing 0 BAF records to Z19W05700T.amber.baf.vcf.gz
19:05:57 - Applying pcf segmentation
19:05:57 - Executing R script via command: Rscript /tmp/script3021952164697556259.R Z19W05700T.amber.baf.tsv Z19W05700T.amber.baf.pcf
19:06:05 - Error executing R script. Examine error file /tmp/bafSegmentation.R1004458596889332636.error for details.
19:06:05 - Complete

**Comment by jonbaber** [comment]
The supplied AMBER loci are designed for WGS data. From the log files I would guess that none of the locations are present and heterozygous in your bam. You can confirm this if you like by using GermlineHetPon.hg19.vcf.gz to slice the bam file and examining it manually.

You can change the locations that AMBER looks at by providing a different set of loci but this will be of little use downstream as PURPLE does not currently support non-WGS data.

**Comment by Xiaohuaniu0032** [comment]
@jonbaber thank you very much
