### ISSUE TITLE
where to download the complied jar file

### ISSUE THREAD

**Issue by Xiaohuaniu0032** [hartwigmedical/hmftools#81]
Hi,
I want to download the complied jar file of AMBER, but i can not find the download link

**Comment by Xiaohuaniu0032** [comment]
I can only find AMBER by conda, is there any other ways to get the jar file?

**Comment by jonbaber** [comment]
You can find download links from the bottom of the [readme](https://github.com/hartwigmedical/hmftools/tree/master/amber) page. The current version is available [here](https://github.com/hartwigmedical/hmftools/releases/tag/amber-v3.2).
