### ISSUE TITLE
where to download the patient-report complied jar file

### ISSUE THREAD

**Issue by senzhaocode** [hartwigmedical/hmftools#82]
Hi,

Not sure whether patient-report binary jar file is available now? I could not find a link to download it. 

Best

Sen

**Comment by kduyvesteyn** [comment]
Hi Sen,

Apologies for slow reply. 

The patient reporter is not well-designed for sharing (no documentation available) and does not do much on top of the other algorithms. In essence it just puts the key mutations found in a single PDF. 

If you are interested in running it nonetheless, please send me a mail on k.duyvesteyn@hartwigmedicalfoundation.nl and I'll help you set it up.
