### ISSUE TITLE
Specify Which Somatic SNV VCF Variants Used

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#86]
PURPLE allows the specification of `-somatic_vcf`. Which variants inside the file does it use? One convention is all PASS and another is all within the file, depending on the software. I ask because we have cutaneous carcinoma (sun-exposed skin) data which has a somatic mutation burden of about 300 mutation per megabase. The variant caller MuTect2 often has `clustered_events` in the FILTER column. It does not PASS a variant if it's close to another one (without bothering to even define what "close" is - I'm sure SAGE 2 is better than this). One such example is the TERT promoter; CGs are relatively rare in the genome and clustered together into islands and the most frequently affected by sun damage. Will PURPLE retain such variants? Can it be written in the user guide?

**Comment by jonbaber** [comment]
Thanks for the feedback. 

We use PASSing or unfiltered variants for the somatic fitting, but we annotate and write ALL variants in the output. 

I have updated the readme to reflect this.
