### ISSUE TITLE
PURPLE Driver Analysis Reporting Only Copy Number Events

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#88]
I used `-driver_catalog` and `-hotspots KnownHotspots.hg38.liftover.vcf` but I found only copy number events for all patients. I have seen using Variant Effect Predictor that about 80% of patients have a missense or a nonsense variant in TP53, so there are at least some variants I would expect to see. Is there some basic unit test I can perform to ensure the software would output a SNV if it was present?

**Comment by p-priestley** [comment]
PURPLE requires the vcf to have snpeff annotation to be able to call the driver.   We do not support VEP sorry.    You can run snpeff on your vcf before running PURPLE if you would like to try it.    

I have added a note to the documentation:

Note that generating the driver catalog for SNVs assumes that the VCF has been annotated with SNPEFF.

**Comment by TnakaNY** [comment]
Just for clarification.
Does PURPLE need "-somatic_vcf" to provide "driver.catalog.tsv"?

My understanding was just set the option and providing below;
driver_catalog
hotspots
driver_gene_panel

My "driver.catalog.tsv" file only contained header. CNV output contained many and looked fine.

**Comment by jonbaber** [comment]
PURPLE doesn't strictly need the somatic vcf but then will only be able to output copy number drivers, ie, amplifications where copy number > 3 * ploidy or deletions where copy number < 0.5. 

When a (snp-eff enriched) somatic vcf is supplied PURPLE is also able to determine drivers from the somatic variants.

**Comment by TnakaNY** [comment]
Thank you for comments. Let me ask you two more questions.

1.How do I change the criteria for reporting in Driver.gene.catalog? Ex, reporting CNV > 2*ploidy.

2.For discovery cohort, I would like to use comprehensive gene panel for reporting rather than predefined gene panel (HMF gene panel). How do I make own gene panel?

**Comment by TnakaNY** [comment]
According to DriverGenePanel.hg38.tsv, I added all gene names (from "tumor.purple.cnv.gene.tsv" file) to this file and make all field "true" or "ONCO" so that PURPLE report all event.
But, I got a error below. How do I make whole gene?

Exception in thread "main" java.lang.IllegalArgumentException: dNdS not available for ONCO gene DDX11L1 in driver gene panel
        at com.hartwig.hmftools.common.drivercatalog.panel.DriverGenePanelFactory.create(DriverGenePanelFactory.java:35)
        at com.hartwig.hmftools.purple.config.DriverCatalogConfig.createConfig(DriverCatalogConfig.java:71)
        at com.hartwig.hmftools.purple.config.ConfigSupplier.<init>(ConfigSupplier.java:132)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:126)
        at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:103)

**Comment by jonbaber** [comment]
To be able to calculate a driver likelihood of a variant (ie after setting reportMissense to true) the gene must exist in https://github.com/hartwigmedical/hmftools/blob/master/hmf-common/src/main/resources/dnds/DndsDriverLikelihoodOnco.tsv

**Comment by jonbaber** [comment]
To answer your other question, currently there is no ability to change the driver catalog CNA criteria. You can always just load the data into a database and query the table yourself.

**Comment by TnakaNY** [comment]
Thank you for prompt reply. 
So, as long as I use only gene from DndsDriverLikelihoodOnco.tsv/DndsDriverLikelihoodTsg.tsv for UserDefinedGenePanel.tsv, it should work, right?

**Comment by jonbaber** [comment]
Yes. That constraint doesn't apply if you are only interested in CNA drivers however (reportAmplifications and reportDeletions).

**Comment by TnakaNY** [comment]
I am using WGS, human cancer data, and try to find SV event. Then, gridss, purple, linx is nice for discovery, annotation and vis.
After getting drivergeneoutput (no longer definite "driver"), I am thinking of running LINX to add additional info to the genes such as DUP, INV (to see which/what SVs affected genes status).

**Comment by TnakaNY** [comment]
By the way, for discovery usage, is it possible to make option for turning off calculation function of driver likelifood in future version?
dnds file has around 19600 genes, human gene is around 25000. So, 20% of gene is ignored even though I use self-made genepanel.

**Comment by jonbaber** [comment]
You already can disable it for a gene by setting reportMissense, reportNonsense and reportSplice to false.

**Comment by TnakaNY** [comment]
I see. Please let me try it! Thanks!

**Comment by TnakaNY** [comment]
I setted reportMissense, reportNonsense and reportSplice to false, but I still have a same error.
[ComprehensiveGenePanel.hg38.txt](https://github.com/hartwigmedical/hmftools/files/5705143/ComprehensiveGenePanel.hg38.txt)

I attached my gene panel, here (.tsv changed to txt to attach here). Could you check it? I edited original .tsv file by opening Windows excel and added all gene names, saved as .tsv file.

**Comment by TnakaNY** [comment]
I have a question about Driver catalog deletion criteria.
It looks a bit too strict to list all possible gene deletion. Usually, deletion is defined around under 1~1.5 copy number for each gene (using minCopyNumber of purple.cnv.gene.tsv file). So, i am try to list genes with AMP, del, LOH manually from purple output.

I am thinking of using below criteria to loosen the criteria.
AMP: minCopyNumber >=6
DEL: minCopyNumber <=1.0 or 1.5
copy number neutral LOH:  (1.0 or 1.5 < minCopyNumber < 6) & (minMinorallele copy number <= 0.5)  

I am not sure whether this criteria is acceptable for del, LOH detection.

Do you have any suggestions? Any help is great for me.

Thanks.

**Comment by DarioS** [comment]
You need different rules, depending on if the sample is whole genome duplicated or not. I based my analysis on the [TCGA rule of COSMIC CNV](https://cancer.sanger.ac.uk/cosmic/help/cnv/overview). You also need special rules for X and Y chromosomes for males and females. After all, you don't want a copy number of 0 for a Y chromosome gene for a female to be identified as a deletion.

```r
autosomes <- paste("chr", 1:22, sep = '')
copyTable <- do.call(base::rbind, lapply(sampleIDs, function(sampleID)
{
  geneCopyNumbers <- read.delim(file.path("/verona/HeadNeck/copyNumber", paste(sampleID, "purple.cnv.gene.tsv", sep = '.')))
  samplePurityPloidy <- read.delim(file.path("/verona/HeadNeck/copyNumber", paste(sampleID, "purple.purity.tsv", sep = '.')))
  sampleOverallPloidy <- round(samplePurityPloidy[["ploidy"]])
  sampleCopyTable <- data.frame(geneCopyNumbers[, "chromosome"], geneCopyNumbers[, "gene"], sampleID,
                                geneCopyNumbers[, "maxCopyNumber"], stringsAsFactors = FALSE)
  sampleCopyTable[, 4] <- round(sampleCopyTable[, 4])

  copyGroups <- NA
  if(samplePurityPloidy[, "gender"] == "FEMALE")
  {
      if(sampleOverallPloidy <= 2) # Diploid
      {
        copyGroups[sampleCopyTable[, 4] == 0 & (sampleCopyTable[, 1] %in% c(autosomes, "chrX"))] <- "Deletion" # No copies left.
        copyGroups[sampleCopyTable[, 4] >= 5 & sampleCopyTable[, 1] %in% c(autosomes, "chrX")] <- "Amplification"
      } else { # Genome doubling
        copyGroups[sampleOverallPloidy - sampleCopyTable[, 4] >= 2 & (sampleCopyTable[, 1] %in% c(autosomes, "chrX"))] <- "Deletion"
        copyGroups[sampleCopyTable[, 4] >= 8 & (sampleCopyTable[, 1] %in% c(autosomes, "chrX"))] <- "Amplification"
      }        
  } else { # Male
      if(sampleOverallPloidy <= 2) # Diploid
      {	  
        copyGroups[sampleCopyTable[, 4] == 0] <- "Deletion" # No copies left.
        copyGroups[sampleCopyTable[, 4] >= 2 & (sampleCopyTable[, 1] %in% c("chrX", "chrY"))] <- "Amplification"
        copyGroups[sampleCopyTable[, 4] >= 5 & (sampleCopyTable[, 1] %in% autosomes)] <- "Amplification"
      } else { # Genome doubling
        copyGroups[sampleOverallPloidy - sampleCopyTable[, 4] >= 3 & (sampleCopyTable[, 1] %in% autosomes)] <- "Deletion"
        copyGroups[(sampleOverallPloidy / 2) - sampleCopyTable[, 4] >= 1 & (sampleCopyTable[, 1] %in% c("chrX", "chrY"))] <- "Deletion"
        copyGroups[sampleCopyTable[, 4] >= 8 & (sampleCopyTable[, 1] %in% autosomes)] <- "Amplification"
        copyGroups[sampleCopyTable[, 4] >= 3 & (sampleCopyTable[, 1] %in% c("chrX", "chrY"))] <- "Amplification"
      }
  }
    
  sampleCopyTable[, 4] <- copyGroups
  sampleCopyTable <- sampleCopyTable[!is.na(sampleCopyTable[, 4]), ]
  sampleCopyTable[, 2:4]
}))
```

It would be convenient if PURPLE automatically output such a gene-level summary, though.

**Comment by TnakaNY** [comment]
Thank you very much for suggestion. Will try your script.
Please let me ask one more question.
How about LOH decision criteria from PURPLE output?

**Comment by p-priestley** [comment]
We have chosen only to call homozygous deletion in PURPLE as drivers (ie. CN<0.5)

For LOH we use minorAlleleCopyNumber<0.5.

**Comment by TnakaNY** [comment]
I see. Thanks!
