### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by renny817** [hartwigmedical/hmftools#9]
Hello,

I have been trying to run cobalt for some time now but I keep running into the following error:

09:06:14 - Thread Count: 4, Window Size: 10000, Min Quality 10
09:06:14 - Reading GC Profile
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
        at com.hartwig.hmftools.common.gc.GCProfileFactory.fromLine(GCProfileFactory.java:49)
        at com.hartwig.hmftools.common.gc.GCProfileFactory.loadGCContent(GCProfileFactory.java:33)
        at com.hartwig.hmftools.common.gc.GCProfileFactory.loadGCContent(GCProfileFactory.java:26)
        at com.hartwig.hmftools.cobalt.CountBamLinesApplication.<init>(CountBamLinesApplication.java:106)
        at com.hartwig.hmftools.cobalt.CountBamLinesApplication.main(CountBamLinesApplication.java:52)

This is what I'm running:

java -Xmx32g -jar cobalt-1.4.jar \
-reference G53.control \
-reference_bam $NORMAL_BAM \
-tumor G52.primary \
-tumor_bam $TUMOR_BAM \
-output_dir $OUTPUT \
-gc_profile $GC \
-window_size 10000

I've read that sometimes this could be a memory issue so I tried that, I've tried using different versions of java, I've made sure the gc profile has the same window size. The gc profile looks normal with the first few lines of:

1       0       -1      0
1       10000   0.5923  1
1       20000   0.5174  1
1       30000   0.4712  1
1       40000   0.3561  1
1       50000   0.3654  1

Any idea where I've gone wrong? I'm still learning the ropes of these programs so apologies if this is something simple. Thanks very much!

**Comment by jonbaber** [comment]
Hi Renny,

The gc profile requires a 5th column for mappability percentage. Note that a window must have a mappability >= 0.85 to be considered mappable. 

I have updated the [cobalt readme](https://github.com/hartwigmedical/hmftools/tree/master/count-bam-lines) to make this much clearer. 

I hope this helps.

Jon

**Comment by jonbaber** [comment]
Hi Renny, 

Just a heads up that we have only ever used a window size of 1000. I have just gone through the code and discovered a number of places where we have this value hardcoded. I will fix them shortly and release new versions of cobalt and purple for you.

In the meantime you might like to try with a window size of 1000. You can use our GCProfile available to download [here](https://nc.hartwigmedicalfoundation.nl/index.php/s/a8lgLsUrZI5gndd?path=%2FHMF-Pipeline-Resources). 

Regards, Jon

**Comment by renny817** [comment]
Hi Jon,

Thanks for getting bad to me so quickly. This is my mistake, I did see the window size of 1000 in multiple places but thought I could override it using the window size option. I used the GCProfile you provided and everything is running smoothly. Thank you for your help!

**Comment by jonbaber** [comment]
No problem. 

I am working on making it properly configurable now. Next version should have much better support.

Cheers, Jon

**Comment by jonbaber** [comment]
Hi Renny, 

Sorry to keep spamming you with messages :)

It turns out that having proper window support is actually too large a task for me to tackle right now. I am going to remove the window parameter from cobalt until I have the chance to fix it properly.

Regards, Jonathan

**Comment by renny817** [comment]
Hi Jon I should have mentioned in my previous message not to worry about changing it. I arbitrarily chose 10,000 without putting too much thought into it as it was the window size I used to create the GCProfile so no worries, 1000 is totally fine!

**Comment by renny817** [comment]
Hi Jon, would you mind if I contacted you via email? Cheers

**Comment by jonbaber** [comment]
Sure. Email is: j.baber@hartwigmedicalfoundation.nl
