### ISSUE TITLE
Y Chromosome Genes Have Estimated Ploidy of 1 for Females

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#90]
I used PURPLE version 2.41 and noticed that the values in the Gene Copy Number file are all above 0.5 - typically about 1 - for genes on the Y chromosome for females.

**Comment by jonbaber** [comment]
Hi Dario, 

Can you give me an example of this please. I ran the following query on our database of 5000+ samples and nothing came up:

```
select * from purity p, geneCopyNumber cn where gender = 'FEMALE' and p.sampleId = cn.sampleId and chromosome = 'Y' limit 1;
```

I have explicit logic to not include the Y chromosome for FEMALES so this should not occur.

Thanks, Jonathan

**Comment by DarioS** [comment]
One example is attached. Minimum and maximum copy number for SRY are 1.02. Note the IGV graph shows no reads across SRY. For the other genes, they each have minimum -0.0253 and maximum 1.0699. Conversely, I also see some males with maximum copy number of 0 for many genes on Y chromosome (e.g. CSCC_0001-M1 in files package). Unlike the females with Y chromosome, I don't know if this is biological or artefactual. It could be either. [testCase.zip](https://github.com/hartwigmedical/hmftools/files/4889076/testCase.zip)

So, when we put the samples together, the most frequently amplified or deleted samples are on the Y chromosome. Such genes typically have Y somewhere in their gene symbol (e.g. AMEL**Y**, FAM197**Y**2).

![image](https://user-images.githubusercontent.com/631218/86890119-2faa9e80-c140-11ea-8bfc-3c03366d07b3.png)

**Comment by jonbaber** [comment]
Thanks Dario, 

I have found the problem. It only affects HG38 which is why I couldn't see it in our cohort. Will be fixed in next version.

Jon

**Comment by DarioS** [comment]
Does the problem affect estimates on any autosomes? Is the Y chromosome zero for males converse issue also checked?

**Comment by jonbaber** [comment]
We don't use any sex chromosomes for fitting so the estimates won't change. The expected copy number of male X and Y chromosomes is already compatible with HG38.
