### ISSUE TITLE
Update Bioconda recipe for linx

### ISSUE THREAD

**Issue by lkhilton** [hartwigmedical/hmftools#92]
I'm not sure if you are maintaining the Bioconda recipes for hmftools, but I noticed that all the recipes have been updated with the latest packages except for linx. Would you be willing to update the recipe?

**Comment by lkhilton** [comment]
I also noticed the latest [gridss-purple-linx](https://github.com/hartwigmedical/gridss-purple-linx/releases) hasn't been updated to use linx v1.8.

**Comment by lkhilton** [comment]
Any chance this could be implemented soon? Maybe when you release version 1.10 of SV-Linx?

**Comment by cbrueffer** [comment]
I've opened https://github.com/bioconda/bioconda-recipes/pull/23323 which updates the recipe to version 1.10, should be merged today or tomorrow.

**Comment by lkhilton** [comment]
Thanks so much, I've successfully installed `hmftools-linx=1.10` from bioconda.
