### ISSUE TITLE
AnnotateStrelkaWithAllelicDepth error

### ISSUE THREAD

**Issue by alhafidzhamdan** [hartwigmedical/hmftools#94]
I am trying to annotate my strelka vcf files with the allelic depth field using AnnotateStrelkaWithAllelicDepth.java.

Here's my path definitions:

> 
> PURPLE_JAR=/exports/igmm/eddie/scripts/hmftools-purple-v2.43/purple-2.43.jar
> 
> PURPLE_ANNOTATE_STRELKA_AD=/exports/igmm/eddie/scripts/hmftools-purple-v2.43/purity-ploidy-estimator/src/main/java/com/hartwig/hmftools/purple/tools/AnnotateStrelkaWithAllelicDepth
> 
> WORK_DIR=$BCBIO_WORK/$PATIENT_ID
> JVM_OPTS="-Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Xms16g -Xmx16g"
> JVM_TMP_DIR="-Djava.io.tmpdir=$WORK_DIR/bcbiotx"
> 

Command:

> java $JVM_OPTS $JVM_TMP_DIR -jar $PURPLE_JAR $PURPLE_ANNOTATE_STRELKA_AD \
>     -in $S2_VARIANTS_PASSED/${PATIENT_ID}-strelka2.normalised.passed.filtered.vcf.gz \
>     -out $S2_VARIANTS_PASSED/${PATIENT_ID}-strelka2.AD.annotated.normalised.passed.filtered.vcf.gz
> 

Here's the error log:

> 
> 13:43:02 - PURPLE version: 2.43
> 13:43:02 - org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -in
> usage: PurityPloidyEstimateApplication
> 

I realise that this may point to the flag "-in" being incorrect but this is what's being used in the example.

Any thoughts?
A

**Comment by jonbaber** [comment]
Hi, 

When you run "java -jar" you actually run the default application of the jar file. In this case PURPLE. 

Instead you need to run with the command:
java -Xmx4G -cp purple.jar com.hartwig.hmftools.purple.tools.AnnotateStrelkaWithAllelicDepth -in xxx -out xxx

Regards, Jonathan

**Comment by alhafidzhamdan** [comment]
Perfect! It is now working.
