### ISSUE TITLE
Unusual Value of PURPLE normFactor

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#95]
Applied to a set of TCGA whole genome sequencing patients, I noticed one had a normFactor of 1.2000 and sample ploidy of 1.6003 and purity 0.9100. What is the valid range of normFactor values? I couldn't find a mathematical formula definition in the user guide, but I thought it would be between 0 and 1. AMBER and PURPLE QC both passed.

**Comment by p-priestley** [comment]
Normalisation factor is an internally used calculation for conversion by purity and ploidy only.   It does not have to be between 0 and 1
