### ISSUE TITLE
Low Purity Sample Passes All QC

### ISSUE THREAD

**Issue by DarioS** [hartwigmedical/hmftools#96]
I have previously described low purity samples that spuriously get a purity of 1.00 and ploidy of 2 but now I also notice low purity cancer samples that pass quality checks but they have a suspicious-looking CIRCOS plot. This is TCGA-CR-7391.

![TCGA-CR-7391-T circos](https://user-images.githubusercontent.com/631218/85240384-564bb280-b47b-11ea-834a-fa7366404fc8.png)

This sample has about 10 times less somatic SNV than all the other samples of the same cancer type I analysed. AD values of the normal sample look something like 43,0 and the cancer 56,4. All quality controls pass and the purity file contains status SOMATIC, purity 0.22 and normFactor 1.0000. The purity was probably too low to efficiently call all SNVs which are in the cancer, resulting in the 10-fold SNV difference to other samples and the generally low number of supporting reads in the cancer sample.

**Comment by p-priestley** [comment]
The somatic fit mode selects a purity for highly diploid samples that best explains the SNV distribution.    It is difficult to distinguish between low level false positives and tumors with low SNV TMB.     In this case it does look like the purity may be lower.   If depth is only 60x then Strelka will generally call variants with minimum 5-6 support, so it will be difficult to fit below around 20%.   

Not sure what you are requesting here?

**Comment by DarioS** [comment]
I was thinking that perhaps the software could automatically flag such samples as failures because of them being too low purity. I suppose if it was just low mutation burden, it might have just as few SNVs but the AD of the alternative allele would be quite higher than typically four or five reads, which seems to be about the minimum the software will call a variant by.

**Comment by p-priestley** [comment]
We do have a parameter for this:   somatic_min_total & somatic_min_peak

Described here:  https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator#optional-somatic-fit-arguments

These numbers are set quite low, but you could set these numbers higher if you are confident that your samples will always have at least n somatic variants if they have sufficient purity..   The effect will be to flag this sample as NO_TUMOR.
