### ISSUE TITLE
Cohort analysis with Gridss-Purple-Linx

### ISSUE THREAD

**Issue by milenastanojevic** [hartwigmedical/hmftools#98]
We are currently trying to use GRIDSS-PURPLE-LINX pipeline to analyze a number of WGS tumor samples coming from the same patient. For each patient, we have a control sample derived from blood available and multiple samples of primary  and recurrent tumors. Control samples are sequenced at the lower coverage than tumor samples.

What would be the best strategy to run GRIDSS-PURPLE-LINX pipeline? We ran the pipeline separately for  each tumor sample, but we assume that there could be a way for cohort analysis?

Thanks!

**Comment by p-priestley** [comment]
Hi Milena - just to be clear, you would like to run multiple tumors together with a single control sample?

For GRIDSS it is possible to jointly run on multiple samples (please refer to the GRIDSS github if you want to do this).   Jointly calling may improve detection of subclonal SV.  

However, PURPLE requires a single tumor and control sample (and require a somatic SV vcf specific for that tumor sample).   LINX depends on the PURPLE output.   I am not aware of any benefit of running these tools in a joint calling mode and we don't currently have intention to add this functionality.    In our database we have many patients with multiple tumor biopsies and always run the full pipeline independently.

Please let me know if I misunderstand your question.

**Comment by milenastanojevic** [comment]
Yes, that was my question. You understood it correctly. Thank you!
